### PR TITLE
Load the system-config configuration for inside security-agent

### PR DESCRIPTION
**Pull request by jinroh**
### What does this PR do?

Add loading of `system-probe.yaml` configuration file inside the `security-agent start` command to have working DI of sysprobeconfig.

### Motivation

Having access to the system-probe socket path that may be configured as part of the `system-probe.yaml` configuration file. Actual access is not part of this PR which only pave the way for system-probe configuration loading.

### Describe how to test/QA your changes

- Check the actual loading of the system-probe configuration using security-agent start command.
- Check that the `--system-probe` flag is actually taken into account as system-probe configuration path / dir.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by 0intro — APPROVED** [review]

**Comment by paulcacheux** [comment]
Maybe you need to edit the multiple entrypoints no ? Like https://github.com/DataDog/datadog-agent/blob/47422c7eeda64b61f97a817786b7468ac898b39a/Dockerfiles/agent/entrypoint.d/security-agent#L4 (but maybe there are others)

**Review by lebauce — APPROVED** [review]

**Comment by jinroh** [comment]
> @paulcacheux  Maybe you need to edit the multiple entrypoints no ?

indeed: 34b01082f4865627a213f044d0d262978138f53e

**Review by paulcacheux — APPROVED** [review]

**Comment by jinroh** [comment]
@L3n41c totally agree, however we need to access parameters that are already in-place and documented as part of the `system-probe` configuration file.

Hence this PR mostly following what `core-agent` and `process-agent` are already doing mostly for consistency and compatibility sake (ie. not introducing configuration changes for users).

**Review by L3n41c — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]
LGTM for files owned by Agent-platform

**Pull request merged**
