### PR TITLE
refactor(buildimages): Move and rename `get-gitlab-config-image-tag`

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
- Move the `get-gitlab-config-image-tag` from `pipelines.py` to `buildimages.py`
- Rename in `get-image-tag`
- Replace occurrences of `GitlabYamlLoader` by `ReferenceTag`

### Motivation
Refactoring

### Describe how to test/QA your changes
Invoke unit tests + manually ran the new task

### Additional Notes
Based on #30365

### CODE REVIEW

**Review by KevinFairise2 — APPROVED** [review]

**Review by pducolin — APPROVED** [review]
Thank you!

**Review by gjulianm — APPROVED** [review]

**Review by CelianR — APPROVED** [review]
Thanks !

**Review by spencergilbert — APPROVED** [review]

**Review by dustmop — APPROVED** [review]
LGTM for ASC-owned files

**Pull request merged**
