### PR TITLE
leaner livenessprobe

### LINKED ISSUE #1697: Datadog Agent Forwarder fails liveness probe when new spot instance joins cluster, causing multiple restarts
**Output of the info page (if this is a bug)**
```

==============
Agent (v6.0.0)
==============

  Status date: 2018-05-15 17:28:44.007680 UTC
  Pid: 326
  Python Version: 2.7.14
  Logs:
  Check Runners: 1
  Log Level: WARN

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    System UTC time: 2018-05-15 17:28:44.007680 UTC

  Host Info
  =========
    bootTime: 2018-05-15 17:21:48.000000 UTC
    kernelVersion: 4.4.115-k8s
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 9.3
    procs: 72
    uptime: 414
    virtualizationRole: guest
    virtualizationSystem: xen

  Hostnames
  =========
    ec2-hostname: ip-172-31-99-8.us-west-2.compute.internal
    hostname: i-0820f63f3cb2ffdc0
    instance-id: i-0820f63f3cb2ffdc0
    socket-fqdn: cluster-datadog-w2pc6
    socket-hostname: cluster-datadog-w2pc6

=========
Collector
=========

  Running Checks
  ==============
    No checks have run yet

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  IntakeV1: 1
  RetryQueueSize: 0
  Success: 1

  API Keys status
  ===============
    https://6-0-0-app.agent.datadoghq.com,*************************4d886: API Key valid

==========
Logs-agent
==========

  logs-agent is not running

=========
DogStatsD
=========

  Event: 1

```
**kubectl describe pod output**
```
  Normal   Pulled                 3m               kubelet, ip-172-31-99-8.us-west-2.compute.internal  Successfully pulled image "datadog/agent:6.0.0"
  Warning  Unhealthy              2m               kubelet, ip-172-31-99-8.us-west-2.compute.internal  Liveness probe failed: Agent health: FAIL
=== 1 healthy components ===
healthcheck
=== 13 unhealthy components ===
ad-autoconfig, ad-configresolver, ad-kubeletlistener, aggregator, collector-queue, dockerutil-event-dispatch, dogstatsd-main, forwarder, metadata-agent_checks, metadata-host, metadata-resources, tagger, tagger-docker
Error: found 13 unhealthy components
  Normal   Created    2m (x3 over 3m)  kubelet, ip-172-31-99-8.us-west-2.compute.internal  Created container
  Warning  Unhealthy  2m (x4 over 2m)  kubelet, ip-172-31-99-8.us-west-2.compute.internal  Liveness probe failed: Agent health: FAIL
=== 13 healthy components ===
ad-autoconfig, ad-configresolver, ad-kubeletlistener, aggregator, collector-queue, dockerutil-event-dispatch, dogstatsd-main, healthcheck, metadata-agent_checks, metadata-host, metadata-resources, tagger, tagger-docker
=== 1 unhealthy components ===
forwarder
Error: found 1 unhealthy components
  Normal  Killing  2m (x2 over 2m)  kubelet, ip-172-31-99-8.us-west-2.compute.internal  Killing container with id docker://datadog:Container failed liveness probe.. Container will be killed and recreated.
  Normal  Pulled   2m (x2 over 2m)  kubelet, ip-172-31-99-8.us-west-2.compute.internal  Container image "datadog/agent:6.0.0" already present on machine
  Normal  Started  2m (x3 over 3m)  kubelet, ip-172-31-99-8.us-west-2.compute.internal  Started container
```

**Describe what happened:**
We are running our cluster in AWS using with master nodes as on-demand instances, and worker nodes as spot instances. When we lose a spot node, and a new one rejoins, datadog frequently restarts on the node, about 6 times, until it runs normally again. The reason datadog is restarting is that the liveness probe fails, due to the forwarder being unhealthy. 

**Describe what you expected:**
The forwarder to be healthy when deployed on the fresh node. 

**Steps to reproduce the issue:**
On a kubernetes cluster running 1.8.7, with worker nodes on spot, and an autoscale group for the worker nodes, delete a worker node, and wait for a new node to join the cluster. Once the new node has joined the cluster, monitor the datadog pod scheduled on the node.

**Additional environment details (Operating System, Cloud provider, etc):**
Cloud Provider: AWS
Kubernetes Version: 1.8.7
Datadog Version: 6.0.0

### PR DESCRIPTION
**Pull request by nikopen**
Fixes #1697

### CODE REVIEW

**Comment by albertvaka** [comment]
Thanks for your contribution Niko! Looks good to me but let me quickly confirm with the containers team :)

**Review by albertvaka — APPROVED** [review]

**Comment by albertvaka** [comment]
I've approved this, although we will wait until next week to merge it. The master branch is frozen for the upcoming release.

**Comment by hkaj** [comment]
Hey @nikopen 
Thanks for the PR. We're open to merging it, and can also update the in-app instructions to reflect it, but I'm not sure this is necessary. Can you tell us which component fails to pass the health check in your case, and give us more info about memory usage vs limit, as well as the same info for CPU? I suspect this slowness to pass healthcheck might be due to the agent being throttled rather than a normal slowness.

30 seconds seem rather long compared to what we have observed. However if this is legit we'll merge your PR and work on bringing the init time down.

Thanks again.

**Comment by nikopen** [comment]
This was hit on 6.9.0 in my case

Do what you will with the PR, it's clearly indicative based on real events

**Comment by hkaj** [comment]
I'm not saying this didn't happen, I'm suggesting this may be due to CPU/MEM limits being too low for the load your agent is bearing, which depends on what options it's configured with.

If that's the case, tolerating a slow start doesn't fix the problem, and the agent likely runs in a degraded state because it's starved on mem and gets throttled on CPU cycles. If you could open a support ticket, or tell us about memory/cpu pressure that would allow us to investigate the root cause of this slow start.  

If we can't identify a configuration issue and the agent is just slow to start we'll merge this PR and investigate how to make it start faster.

**Comment by nikopen** [comment]
I don't think it was due to resource constraints.

There is no troubleshooting to be done. Obviously the agent couldn't start in 15 seconds. 
As I said, do as you will - it's an upstream indicative manifest anyway and people can just change it anytime - i.e. trivial change.

**Comment by hkaj** [comment]
@nikopen `failureThreshold` is at 3, and the retry period is 15s. It means we're actually talking about 1min before the first restart (1m15s with your change). This is suspiciously long, and does suggest that there's an error to troubleshoot.

It's not expected that the agent takes that long to start, and we haven't observed this anywhere unless in some cases of misconfiguration (low resource limits applied to agents with many checks enabled/heavy tracing usage for instance), so we won't be merging this PR.

As you said this is easily configurable anyway, so it shouldn't cause any issue. If you experience difficulties, or slowness with the agent starting, please [send us a flare](https://docs.datadoghq.com/agent/troubleshooting/?tab=agentv6#send-a-flare) and we'll investigate.

Thanks again.

**Comment by nikopen** [comment]
Ok!

**Pull request closed without merging**
