### PR TITLE
Move some Agent Core owned packages to `internal` folders

### PR DESCRIPTION
**Pull request by mx-psi**
### What does this PR do?

Move the following folders to internal:

```
github.com/DataDog/datadog-agent/pkg/aggregator/tags    -> github.com/DataDog/datadog-agent/pkg/aggregator/internal/tags
github.com/DataDog/datadog-agent/pkg/dogstatsd/mapper   -> github.com/DataDog/datadog-agent/pkg/dogstatsd/internal/mapper
github.com/DataDog/datadog-agent/pkg/serializer/stream  -> github.com/DataDog/datadog-agent/pkg/serializer/internal/stream
github.com/DataDog/datadog-agent/pkg/util/hostname/file -> github.com/DataDog/datadog-agent/pkg/util/hostname/internal/file
github.com/DataDog/datadog-agent/pkg/metadata/gohai     -> github.com/DataDog/datadog-agent/pkg/metadata/internal/gohai
github.com/DataDog/datadog-agent/pkg/metadata/resources -> github.com/DataDog/datadog-agent/pkg/metadata/internal/resources
```

### Motivation

Reduce public API surface to make it easier to modularize Datadog Agent codebase. See [here](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit) for explanation of `internal` packages.

### Additional Notes

No-op, detected by this [WIP tool](https://github.com/mx-psi/internalizer).

### Possible Drawbacks / Trade-offs

None: it can be reverted if needed. However, if you know that you want any of these packages to be part of the public API of your folder, maybe it doesn't make sense to merge (all of) this.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
Looks fine to me, but flagging a few more people to check:

* github.com/DataDog/datadog-agent/pkg/aggregator/tags - @vickenty
* github.com/DataDog/datadog-agent/pkg/dogstatsd/mapper - maybe @ogaca-dd ?
* github.com/DataDog/datadog-agent/pkg/serializer/stream - @ogaca-dd 
* github.com/DataDog/datadog-agent/pkg/util/hostname/file - @sgnn7 
* github.com/DataDog/datadog-agent/pkg/metadata/gohai - @truthbk 
* github.com/DataDog/datadog-agent/pkg/metadata/resources - @ogaca-dd ?

**Review by sgnn7 — APPROVED** [review]
I guess it's just a bit strange to see a single particular provider (`hostname/file`) be isolated into the internal package out of a big group but LGTM as it does move us closer to better-isolated packages.

**Comment by mx-psi** [comment]
> I guess it's just a bit strange to see a single particular provider (`hostname/file`) be isolated into the internal package out of a big group but LGTM as it does move us closer to better-isolated packages.

That's fair. I think it ultimately depends on if you think providers should be internal to the `hostname` package or not? If they 'should' be internal, then I agree this is a step in the right direction.

**Comment by sgnn7** [comment]
> I think it ultimately depends on if you think providers should be internal to the hostname package or not? If they 'should' be internal, then I agree this is a step in the right direction.

That's my thought here - I would expect that all of the specific hostname providers to eventually be opaque in the `internal` package so it's definitely a step forward IMO 👍

**Review by vickenty — APPROVED** [review]
LGTM

**Comment by ogaca-dd** [comment]
@mx-psi : LGTM sorry for my late answer.

**Pull request merged**
