### PR TITLE
[networks] Improve heartbeat URL sanitization

### PR DESCRIPTION
**Pull request by p-lambert**
### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details you may have to test your PR.

### CODE REVIEW

**Review by shang-wang — COMMENTED** [review]
I'm not a huge fan of using regex to parse URL, I think the golang's "net/url" package has some nicer way to extract host name for example, so you might get away of not using regex in my opinion.

**Comment by p-lambert** [comment]
> I'm not a huge fan of using regex to parse URL, I think the golang's "net/url" package has some nicer way to extract host name for example, so you might get away of not using regex in my opinion.

@shang-wang would you mind elaborating?
The only thing I think I could leverage from the `net/url` package would be calling [Hostname\(\)](https://golang.org/pkg/net/url/#URL.Hostname), but I would still have to resort to some sort of string manipulation.

**Comment by shang-wang** [comment]
I'm not suggesting not using string manipulation, I'm suggesting not using regex to parse URL. For example, your case would fail if we ever have to use `http` instead of `https` as protocol(hypothetically). I think as simple as using `Hostname()` would avoid this from happening, you could probably do
```
processIdx := string.Index(url.Hostname(), "process")
if processIdx != -1 {
    hostname = url.Hostname()[processIdx + len("process"):]
}
```
Or use regex on `Hostname()`.

**Comment by p-lambert** [comment]
@shang-wang let me know if it looks okay now.
FYI `url.Parse()` doesn't work well with URLs without a scheme: https://play.golang.org/p/j6L3sB4jGC5

**Review by shang-wang — APPROVED** [review]
Looks good. Sorry to bring this up and have you change it.

**Pull request merged**
