### PR TITLE
[e2e]: pass --no-refresh to zypper install commands to reduce step-by-step test flakiness

### PR DESCRIPTION
**Pull request by spencergilbert**
### What does this PR do?

Prevent flakey failures due to autorefresh failing. Global options for zypper can be found [here](https://en.opensuse.org/SDB:Zypper_manual#GLOBAL_OPTIONS).

### Motivation

[BARX-312](https://datadoghq.atlassian.net/browse/BARX-312) resolve flakey test.

### Additional Notes

[Reused change implemented in the install script](https://github.com/DataDog/agent-linux-install-script/pull/176).

### Describe how to test/QA your changes

[BARX-312]: https://datadoghq.atlassian.net/browse/BARX-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by chouquette — APPROVED** [review]
makes a lot of sense given we already refreshed the repo explicitly on the previous line

**Comment by spencergilbert** [comment]
> makes a lot of sense given we already refreshed the repo explicitly on the previous line

I believe we're only refreshing the newly configured `datadog` repo, and not anything else - however we shouldn't need any other packages (particularly for these tests).

**Comment by chouquette** [comment]
> > makes a lot of sense given we already refreshed the repo explicitly on the previous line
> 
> I believe we're only refreshing the newly configured `datadog` repo, and not anything else - however we shouldn't need any other packages (particularly for these tests).

Yeah but isn't that the repo we install from? However even if it isn't, as long as the test pass then the repos are refreshed enough :)

**Review by pducolin — APPROVED** [review]

**Pull request merged**
