### PR TITLE
[invoke] Add macOS M1 Agent build support

### PR DESCRIPTION
**Pull request by KSerrania**
### What does this PR do?

Upgrades the version of `github.com/DataDog/gopsutil` to `v1.2.0` to include https://github.com/DataDog/gopsutil/pull/40.

Removes the logic in `inv agent.build` that forces an IoT Agent build on macOS M1.

### Motivation

Fixes the main Agent build on macOS M1. Also possibly fixes the other Agent builds (but I haven't tested).

### Possible Drawbacks / Trade-offs

We're not 100% sure that our `gopsutil` fork works perfectly on macOS M1, but this should be enough to allow developers to build the Agent locally for testing.

### Describe how to test/QA your changes

Run `inv -e agent.build`, `inv -e process-agent.build`, `inv -e trace-agent.build` and `inv -e security-agent.build` on macOS M1, check that they succeed, and that the resulting binaries run well.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by vickenty — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]
🎉 🦾

**Review by paulcacheux — APPROVED** [review]

**Comment by paulcacheux** [comment]
```
>> inv -e agent.build --exclude-rtloader --build-exclude=python
>> inv -e security-agent.build
>> inv -e process-agent.build
>> inv -e trace-agent.build
```
all build successfully on M1

**Comment by nammn** [comment]
Builds for me!
But as I was trying it out it panicked
```
2022-07-15 16:46:29 CEST | PROCESS | INFO | (api/server.go:41 in StartServer) | API server listening on localhost:6162
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/DataDog/gopsutil/cpu.Info()
        /Users/namnguyen/go/pkg/mod/github.com/!data!dog/gopsutil@v1.2.0/cpu/cpu_darwin.go:99 +0x378
github.com/DataDog/datadog-agent/pkg/process/checks.CollectSystemInfo(0x14000b1f7a0)
        /Users/namnguyen/go/src/github.com/DataDog/datadog-agent/pkg/process/checks/system_info.go:28 +0x44
main.NewCollector(0x14000b1f7a0, {0x14000bb20a0, 0x2, 0x2})
```

**Comment by KSerrania** [comment]
> Builds for me!
> But as I was trying it out it panicked
> ```2022-07-15 16:46:29 CEST | PROCESS | INFO | (api/server.go:41 in StartServer) | API server listening on localhost:6162
> panic: runtime error: index out of range [1] with length 0
> 
> goroutine 1 [running]:
> github.com/DataDog/gopsutil/cpu.Info()
>         /Users/namnguyen/go/pkg/mod/github.com/!data!dog/gopsutil@v1.2.0/cpu/cpu_darwin.go:99 +0x378
> github.com/DataDog/datadog-agent/pkg/process/checks.CollectSystemInfo(0x14000b1f7a0)
>         /Users/namnguyen/go/src/github.com/DataDog/datadog-agent/pkg/process/checks/system_info.go:28 +0x44
> main.NewCollector(0x14000b1f7a0, {0x14000bb20a0, 0x2, 0x2})

Yes, I have been able to reproduce the same issue. This PR: https://github.com/DataDog/gopsutil/pull/43 should partially fix this.

**Pull request merged**
