### PR TITLE
[windows] remove pip2 declaration to reduce pip version confusion

### PR DESCRIPTION
**Pull request by derekwbrown**
### What does this PR do?

removes the pip2 definition dependency, so that we don't have multiple pip installs

### CODE REVIEW

**Review by ofek — CHANGES_REQUESTED** [review]
Let's instead change https://github.com/DataDog/datadog-agent/blob/9bb9158b5edb74f7b5b5327907aab00c9bf4e0bc/omnibus/config/software/datadog-agent-integrations-py2.rb#L91-L92 to

```ruby
    python = "#{windows_safe_path(python_2_embedded)}\\python.exe"
    pip = "#{python} -m pip"
```

**Comment by olivielpeau** [comment]
On Windows, is it required (or more generally, what are the reasons) to ship `pip` with python directly, instead of installing it separately from python?

Asking because installing it separately is what's done on Linux/macOS and makes things more flexible, as it makes it easy to upgrade pip (which is quite frequent) separately from python upgrades (which are less frequent).

**Comment by derekwbrown** [comment]
After 6.13, we will repackage python such that it no longer includes pip itself.  Then the installed pip will become the correct, only version

**Comment by derekwbrown** [comment]
Superseded by https://github.com/DataDog/datadog-agent/pull/3924

**Pull request closed without merging**
