### PR TITLE
Decrease the default log verbosity of the JMX command

### PR DESCRIPTION
**Pull request by ofek**
### What does this PR do?

Matches the check command:

https://github.com/DataDog/datadog-agent/blob/66817d7ab85253da0d360151462545de8a62f7b2/cmd/agent/app/check.go#L99-L101

### Motivation

It's way too noisy

### CODE REVIEW

**Review by therve — DISMISSED** [review]

**Review by prognant — COMMENTED** [review]
I guess `debug` is really a bad default setting, but maybe `warn` or `critical` may still be a good idea ?

**Comment by ofek** [comment]
Errors still come though with `off`, they look like this:

Capture

**Comment by ofek** [comment]
Capture

Capture

**Review by prognant — COMMENTED** [review]
I'm confused about the `off` log level not being properly honoured, it does feel suspicious. But in the jmx case the log level is passed to jmxfetch as-is so `off` will disable all jmxfetch logging, I'm not sure that's what we want.

**Review by prognant — APPROVED** [review]
Thanks ! 👍

**Comment by olivielpeau** [comment]
The issue of the `off` log level not being honored by JMXFetch should be fixed by this PR I just opened: https://github.com/DataDog/datadog-agent/pull/5255, so I don't think the present PR is needed.

**Pull request closed without merging**
