### PR TITLE
Update `go.opentelemetry.io/collector`  to v0.50.0

### PR DESCRIPTION
**Pull request by amenasria**
### What does this PR do?

This PR updates the following packages to `v0.50.0`:

- `go.opentelemetry.io/collector`
- `go.opentelemetry.io/collector/model`
- `go.opentelemetry.io/collector/pdata`
- `go.opentelemetry.io/collector/model/semconv`
- `github.com/open-telemetry/opentelemetry-collector-contrib/pkg/resourcetotelemetry`

### Motivation

Keep the dependancies updated.

### Describe how to test/QA your changes

First, check that every deprecation in the [v.0.50.0 release note](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.50.0) is wiped from the code.

Second, run the tests of the modified module/packages:
- OTLP Package: `invoke test --targets=./pkg/otlp --skip-linters`
- `pkg/otlp/model` module: `invoke test --module=pkg/otlp/model --skip-linters`
- `pkg/trace` module: `invoke test --module=pkg/trace --skip-linters`

Finally, build the agent and check that it's running fine with the modified features on:

`./bin/agent/agent run -c config.yaml` where `config.yaml` have `otlp` turned on:

```
api_key: your_api_key

otlp_config:
  receiver:
    protocols:
      grpc:
```

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by mx-psi** [comment]
I think you need to run `inv -e tidy-all`

**Comment by mx-psi** [comment]
As part of this PR we should remove https://github.com/DataDog/datadog-agent/blob/81ba6231cc0576a7e74e8600f3d28dd2aacc2097/cmd/trace-agent/test/testsuite/otlp_test.go#L21

**Review by gbbr — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]
🚀

**Review by apigirl — APPROVED** [review]
👍 for docs

**Comment by paulcacheux** [comment]
Maybe you can do https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.51.0 directly ? It was just released

**Comment by mx-psi** [comment]
> Maybe you can do https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.51.0 directly ? It was just released

We can do that in a second PR if we find the time before the freeze, it can be difficult to bump it since the API is not yet stable (plus, dependency hell problems sometimes :( )

**Pull request merged**
