### PR TITLE
Add technical docs

### PR DESCRIPTION
**Pull request by masci**
### What does this PR do?

Reorganise existing docs into a more comprehensive set of markdown files

### Motivation

Ease contributors onboarding

### CODE REVIEW

**Review by jeremy-lq — APPROVED** [review]
Other than one 404, LGTM from an open source/CLA perspective. @kent may have additional feedback from a docs POV. Well done!

**Review by truthbk — COMMENTED** [review]
Added some feedback :)

**Review by olivielpeau — COMMENTED** [review]
Went through `docs/dev/agent_dev_env.md`, left a few comments

**Review by kmshultz — APPROVED** [review]
Left a few more comments, but looks good to me!

**Pull request merged**
