### PR TITLE
chore: disable remote agent registry support by default

### PR DESCRIPTION
**Pull request by tobz**
### What does this PR do?

This PR disables support for the "remote agent registry" by default through the introduction of a new configuration setting, `remote_agent_registry.enabled`, which controls whether or not the registry is enabled (duh).

When the registry is disabled, remote agents will receive an error when attempting to register themselves that indicates that RAR is not enabled.

### Motivation

We want to gate this behavior somewhat while we flesh out its long-term design and security posture.

### Describe how to test/QA your changes

```shell
# Build the Agent and the `remote-agent` tool:
inv agent.build
inv agent.build-remote-agent

# In another shell, run the Agent.
# 
# We override `cmd_port` in our configuration to `6001` to avoid conflicts with
# any local Datadog Agent that's running, which will matter for running the
# commands further down.
bin/agent/agent -c bin/agent/dist run

# Check the Agent's status output, and observe that there's no `Remote Agents` section
# since RAR is now disabled by default:
bin/agent/agent -c bin/agent/dist status

# Run the `remote-agent` binary, pretending to be a remote agent.
#
# With the default Agent configuration, RAR is disabled, and so the client should
# an error that states "remote agent registry not enabled", like so:
# 
# ... failed to register remote agent: ... remote agent registry not enabled
bin/remote-agent -agent-id remote-agent-1 -display-name="Remote Agent #1" \
                 -listen-addr 127.0.0.1:13580 \
                 -agent-ipc-address localhost:6001 \
                 -agent-auth-token-file bin/agent/dist/auth_token

# Update your Agent configuration to set `remote_agent_registry.enabled` to `true`,
# and restart the Agent. Check its status again, and observe that there's now a
# `Remote Agents` section which indicates no remote agents are registered:
bin/agent/agent -c bin/agent/dist status

# We'll also now try to register the remote again (using the same `bin/remote-agent`
# command from before) which should end up showing something along these lines:
# 
# ... Registered with Core Agent. Recommended refresh interval of 10 seconds.

# Finally, check the Agent's status one last time, and observe that now there is an
# entry in the `Remote Agents` section for our local remote agent, Remote Agent #1:
bin/agent/agent -c bin/agent/dist status
```

### Possible Drawbacks / Trade-offs

N/A

### Additional Notes

N/A

### CODE REVIEW

**Review by GustavoCaso — APPROVED** [review]

**Review by GustavoCaso — CHANGES_REQUESTED** [review]
I believe we need to add the config bindings for `remote_agent_registry.enabled`. Have we added on another PR? 

Also, what would be the default value?

**Comment by tobz** [comment]
> I believe we need to add the config bindings for `remote_agent_registry.enabled`. Have we added on another PR?

@GustavoCaso We added the binding in this PR, or are you referring to something else?

**Comment by GustavoCaso** [comment]
> We added the binding in this PR, or are you referring to something else?

My bad I missed the last file change 🤦

**Review by GustavoCaso — APPROVED** [review]

**Pull request merged**
