### PR TITLE
ebpf: move system-probe jobs to k8s runners

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

Now that:
- the system probe build image is entrypoint free (https://github.com/DataDog/datadog-agent-buildimages/pull/292)
- the `golangci-lint` invoke task is able to fix the concurrency (https://github.com/DataDog/datadog-agent/pull/15722)

The jobs running on the system probe build images are fully ready to migrate to k8s runners.

### Motivation

Normal runners are susceptible to more infrastructure failures (no basic auth, arm64 fail to start etc). The whole CI is planned to move to k8s runners, and those jobs are some of the easier to migrate

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by brycekahle — APPROVED** [review]

**Comment by clarkb7** [comment]
> The whole CI is planned to move to k8s runners, and those jobs are some of the easier to migrate

Do we need to make changes to the Windows build images?

**Comment by paulcacheux** [comment]
@clarkb7 this PR only changes jobs running on the linux system probe build image. Nothing from the windows agent team to do here. Your review is only requested because of the changes to the `deps.yaml` file of which you are a CODEOWNERS. 

Regarding the move to the k8s runners this is a (very?) long term goal from the agent platform team, because this is the only way of fixing some infrastructure failures in job runs we see some times to times, since the system probe jobs based are some of the easier ones in the pipeline (no docker build for example) this can serve as good learning examples for a potential larger scale migration.

**Review by clarkb7 — APPROVED** [review]
not windows related

**Review by KSerrania — APPROVED** [review]
LGTM, Windows and Docker build errors are unrelated to this PR.

The run time of the system-probe jobs hasn't changed (~7 minutes for `tests_ebpf` jobs, ~8 minutes for `prepare_ebpf_functional_tests` jobs, ~4 minutes for `build_system-probe` jobs, before and after that change).

**Pull request merged**
