### PR TITLE
Use custom port for process expvar tests

### PR DESCRIPTION
**Pull request by robertjli**
### What does this PR do?

Update the tests in the `/comp/process/expvars` component to use a non-default port, so that it doesn't conflict with the agent installed on the CI runner.

### Motivation

This is required to upgrade to the faster Gitlab macOS runners for CI.

### Additional Notes

Unit tests pass locally:

```
datadog@2a682a41e360:/workspaces/datadog-agent$ deva test --targets=./comp/process/expvars/expvarsimpl
--- Setting rtloader paths to lib:/workspaces/datadog-agent/dev/lib | header:/workspaces/datadog-agent/dev/include | common headers:
--- Flavor base: unit tests
-----  Module '/workspaces/datadog-agent'
✓  comp/process/expvars/expvarsimpl (cached)

DONE 2 tests in 0.458s
All tests passed
Tests final status (including re-runs): ALL TESTS PASSED
```

### Describe how to test/QA your changes

N/A, only test code was changed

### CODE REVIEW

**Review by wiyu — APPROVED** [review]

**Review by amenasria — APPROVED** [review]
**👏 praise:** ‏Thanks for this !

**Pull request merged**
