### PR TITLE
ci(notify): Simplify requirements.txt file and remove option

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
- Simplify requirements.txt file for jobs using notifier image
- Remove broken option, similar to https://github.com/DataDog/datadog-agent/pull/31070

### Motivation
Tech debt

### CODE REVIEW

**Review by pducolin — APPROVED** [review]

**Review by CelianR — APPROVED** [review]

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
