### PR TITLE
AppSec Preview - Intake Reverse Proxy

### PR DESCRIPTION
**Pull request by Julio-Guerra**
Re-merge that was reverted due to the `main` branch code freeze: https://github.com/DataDog/datadog-agent/pull/8359

### CODE REVIEW

**Review by albertvaka — APPROVED** [review]

**Review by gbbr — COMMENTED** [review]
Can you please re-open the PR using exactly the reverted commit so that it is 100% clear that it is the same change and the commit message stays exactly the same?

**Comment by gbbr** [comment]
Specifically https://github.com/DataDog/datadog-agent/commit/c294b3a6dd9720baa478f2e805e2a8ca10fa154c

**Comment by Julio-Guerra** [comment]
> Can you please re-open the PR using exactly the reverted commit so that it is 100% clear that it is the same change and the commit message stays exactly the same?

Done @gbbr, but note that GitHub doesn't allow me to re-open the PR unless the commit ID changed. It otherwise thinks it was already merged because the commit ID of the merge is already in the main branch. So I cherry-picked it and applied it to the latest `main` branch commit.

**Review by gbbr — APPROVED** [review]
(Deleted)

**Pull request merged**
