### PR TITLE
[ON HOLD][OTEL-1724] Convert pkg/trace/stats to a Go module

### PR DESCRIPTION
**Pull request by songy23**
### What does this PR do?

Convert pkg/trace/stats to a Go module

### Motivation

[RFC](https://docs.google.com/document/d/1uKWa9rMNm0U-euEzEJ69KW7Id5u1E4GfYHyzC1SzYoI/edit#heading=h.wnkz5u7vx1fb)

This is also related to the ongoing APM stats refactor & improvement effort.

### Describe how to test/QA your changes

1. Send traces to Agent and make sure APM stats are generated properly.
2. Make sure `github.com/DataDog/datadog-agent/pkg/trace/stats` is import-able in other Go binaries

### CODE REVIEW

**Review by dineshg13 — APPROVED** [review]

**Review by spencergilbert — APPROVED** [review]

**Review by knusbaum — CHANGES_REQUESTED** [review]
I'd like clarification on what issues this solves. `pkg/trace` is already an independent module used in the collector. I'm not sure a separately-versioned `pkg/trace/stats` is a good idea.

**Comment by songy23** [comment]
@knusbaum  In the collector - you're right we have to import the full trace agent. In Agent OTel components though, we may want to import the trace stats module without importing the full trace agent. This is related to [OTEL-1712](https://datadoghq.atlassian.net/browse/OTEL-1712) & OTel sampling work in Agent.

**Comment by knusbaum** [comment]
> In Agent OTel components though, we may want to import the trace stats module without importing the full trace agent. 

Do we have a case where we want to do this? I would prefer not to increase the number of modules.

The only benefit that this potentially has is that a few indirect dependencies could be dropped.
Stats is already usable as part of `pkg/trace`, and so this can be done later if we decide it's worth it.

**Comment by songy23** [comment]
> Do we have a case where we want to do this? 

Currently the OTLP trace pipeline in Agent does not support OTel native sampling. We may want to add an Agent-specific OTel processor to do sampling as well as pre-sampled APM stats calculation on the OTLP traces, and that processor will be in core Agent and in its own module. In that processor we only need to import the trace stats module rather than the whole trace agent.

(This is in ideation phase, actual implementation may differ)

> so this can be done later if we decide it's worth it.

I agree with you it doesn't have to be done now. We can revisit it when it comes to the OTel sampling processor in Agent. I'll convert this PR to draft for now.

**Pull request closed without merging**
