### PR TITLE
Datadog Cluster Agent: Doesn't validate if metric is valid

### LINKED ISSUE #5282: Datadog Cluster Agent: Doesn't validate if metric is valid.
**Describe what happened:**
If HPA is configured incorrectly, then all HPAs that use external metrics from datadog are broken.

Example: if HPA is invalid:
```
  - external:
      metric:
        name: truth_service.http_requests_total
        selector:
          matchLabels:
            kube_cluster: '"pod19"' # <- our tooling inserted extra quotes.
            kube_project: truth-service
```

Resulting request contained 

`avg:truth_service.http_requests_total{kube_cluster:"pod19",kube_project:truth-service}.rollup(30)`
among other HPA. The whole request failed.

**Describe what you expected:**
Only HPA that has incorrect metrics configuration should fail.

**Steps to reproduce the issue:**
1. Create HPA that uses valid metric value.
1. Create HPA that uses invalid metric value.

MEtrics for HPA with valid metric will not be retrieved.

**Additional environment details (Operating System, Cloud provider, etc):**

Either client should validate before submitting or server should ignore bad metrics and return results for good metrics.

Logs from DCA:
```
datadog-cluster-agent-7b749f864f-dgl6w datadog-cluster-agent 2020-04-05 00:49:46 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/datadogexternal.go:84 in queryDatadogExternal) | Error while executing metric query XXX: : API returned error: Error parsing query:
```

### PR DESCRIPTION
**Pull request by eatwithforks**
### What does this PR do?

To fix https://github.com/DataDog/datadog-agent/issues/5282

we got the unit test to pass but we don't know how to do an integration test to make sure everything is working. Please advice if there's anything that needs to be updated/changed.

### CODE REVIEW

**Comment by eatwithforks** [comment]
@CharlyF could you take a look to see if logic makes sense when you have a chance? thanks!

**Comment by CharlyF** [comment]
Hey @eatwithforks - Sorry about the delay here.
We are going to release a new version of the Cluster Agent this week and I would like your change to be included.
I took a look at your change and with this logic we would be running a regex on all metrics every 30s (everytime we run queryExternalMetrics really). But as it is a hot path, and metrics are not supposed to change once collected from the HPA. I think there could be a solution that would introduce less overhead. 

What would you think about rejecting the metric from the HPA altogether (and thus the HPA) when we first parse and Ispect the HPA object here https://github.com/DataDog/datadog-agent/blob/master/pkg/util/kubernetes/autoscalers/autoscalers.go#L31.
That way, we only run the regex one, and the metric will not be included in the overall batch.
I would consider reformatting the metric and accepting the HPA (as long as we strip the `'\)` and are sure the metric will not invalidate everything) so that it solves the initial case but otherwise throw an error in the logs.

Best,
.C

**Comment by mifish79** [comment]
Instead of just checking for quotes, can this be modified to check against a regex pattern based off of the DataDog documentation? [Naming Custom Metrics](https://docs.datadoghq.com/developers/metrics/#naming-custom-metrics)

**Comment by mifish79** [comment]
Can the regex pattern be updated based on the [DataDog Custom Metrics Naming](https://docs.datadoghq.com/developers/metrics/#naming-custom-metrics) constraints?

**Comment by robertjli** [comment]
Closed in favor of https://github.com/DataDog/datadog-agent/pull/7537

**Pull request closed without merging**
