### PR TITLE
Don't build containers based on debian packages

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

Instead of relying on the debian package only to extract it, we can use the unpackaged build artifact and extract it directly.

### Motivation

This makes the container based jobs (and their dependencies) start about 3.5 minutes earlier, which is a nice little improvement.

### CODE REVIEW

**Comment by chouquette** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by vboulineau** [comment]
Were you able to do a filesystem diff between new and old image to make sure nothing got lost?

**Review by spencergilbert — APPROVED** [review]

**Comment by chouquette** [comment]
Here's the diff of files for the container based on the commit ancestor and the container generated by this PR:
(file lists generated with `docker run registry.ddbuild.io/ci/datadog-agent/agent:$version find / -type f > output.txt`)
```
--- /tmp/oldfiles.txt	2024-11-21 09:37:21.763598420 +0100
+++ /tmp/newfiles.txt	2024-11-21 09:34:15.339627716 +0100
@@ -56,10 +56,6 @@
 /etc/logrotate.d/alternatives
 /etc/logrotate.d/apt
 /etc/init.d/procps
-/etc/init.d/datadog-agent-security
-/etc/init.d/datadog-agent-process
-/etc/init.d/datadog-agent-trace
-/etc/init.d/datadog-agent
 /etc/hosts
 /etc/ld.so.conf.d/libc.conf
 /etc/ld.so.conf.d/x86_64-linux-gnu.conf
@@ -57745,6 +57741,7 @@
 /opt/datadog-agent/embedded/etc/dbus-1/session.conf
 /opt/datadog-agent/embedded/etc/xattr.conf
 /opt/datadog-agent/embedded/etc/README.md
+/opt/datadog-agent/embedded/etc/.gitkeep
 /opt/datadog-agent/embedded/share/system-probe/ebpf/tracer-debug.o
 /opt/datadog-agent/embedded/share/system-probe/ebpf/runtime-security-syscall-wrapper.o
 /opt/datadog-agent/embedded/share/system-probe/ebpf/tracer.o
@@ -58220,6 +58217,7 @@
 /opt/datadog-agent/embedded/bin/db_hotbackup
 /opt/datadog-agent/embedded/bin/curl
 /opt/datadog-agent/embedded/bin/python3.12
+/opt/datadog-agent/embedded/bin/.gitkeep
 /opt/datadog-agent/embedded/bin/kinit
 /opt/datadog-agent/embedded/bin/eu-elflint
 /opt/datadog-agent/embedded/bin/process-agent
@@ -78918,6 +78916,7 @@
 /opt/datadog-agent/embedded/lib/python3.12/posixpath.py
 /opt/datadog-agent/embedded/lib/libmagic.so.1.0.0
 /opt/datadog-agent/embedded/lib/librpmsign.so.9.4.0
+/opt/datadog-agent/embedded/lib/.gitkeep
 /opt/datadog-agent/embedded/lib/libzstd.so.1.5.5
 /opt/datadog-agent/embedded/lib/ossl-modules/legacy.so
 /opt/datadog-agent/embedded/lib/libverto.so.0.0
@@ -79917,6 +79916,7 @@
 /opt/datadog-agent/bin/agent/dist/checks/prometheus_check/__init__.py
 /opt/datadog-agent/bin/agent/dist/checks/winwmi_check.py
 /opt/datadog-agent/bin/agent/dist/config.py
+/opt/datadog-agent/bin/.gitkeep
 /opt/datadog-agent/final_constraints-py3.txt
 /opt/datadog-agent/LICENSE
 /opt/datadog-agent/LICENSES/gstatus-GPL-3.0
@@ -79953,6 +79953,7 @@
 /opt/datadog-agent/LICENSES/rpm-COPYING
 /opt/datadog-agent/LICENSES/xmlsec-Copyright
 /opt/datadog-agent/LICENSES/libsqlite3-Public-Domain
+/opt/datadog-agent/LICENSES/.gitkeep
 /opt/datadog-agent/LICENSES/curl-COPYING
 /opt/datadog-agent/LICENSES/libyaml-LICENSE
 /opt/datadog-agent/LICENSES/freetds-COPYING
@@ -79984,6 +79985,24 @@
 /readsecret.py
 /root/.bashrc
 /root/.profile
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/prerm-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/postrm
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/postrm-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/posttrans
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/preinst
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/postinst
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/posttrans-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/preinst-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/postinst-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-rpm/prerm
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/prerm-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/postrm
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/postrm-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/preinst
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/postinst
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/preinst-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/postinst-dbg
+/go/src/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent-deb/prerm
 /usr/share/keyrings/ubuntu-cloudimage-removed-keys.gpg
 /usr/share/keyrings/ubuntu-cloudimage-keyring.gpg
 /usr/share/keyrings/ubuntu-master-keyring.gpg
```

**Comment by chouquette** [comment]
I removed the package scripts that have no use here. I suppose the .gitkeep files should also be removed, but I'm not entirely sure why they are not currently included.
Regarding the missing `init.d` files, I'm fairly sure they are irrelevant in a container, but would rather have a confirmation from your end

**Comment by chouquette** [comment]
`.gitkeep` files are explicitly skipped in omnibus' `deb` and `rpm` packagers, but not in the `xz` one that we introduced when splitting build & packaging.
That being said, I don't see a reason to create a gitkeep file as part of the build process, so I added a new commit to stop generating those.

**Comment by spencergilbert** [comment]
> Regarding the missing init.d files, I'm fairly sure they are irrelevant in a container, but would rather have a confirmation from your end

`init.d` shouldn't impact the containerized agent either, all of the "init/service" scripts should be handled by s6 (added in the dockerfile directly).

**Review by vboulineau — APPROVED** [review]
`init` is indeed useless and `gitkeep` as well I believe.

**Pull request merged**
