### PR TITLE
Conntrack Support core

### PR DESCRIPTION
**Pull request by LeiZhang-Hunter**
Conntrack Support core,This is my first submission, I will actively revise if there are any problems, criticisms and corrections are welcome.

### CODE REVIEW

**Comment by LeiZhang-Hunter** [comment]
Why the ci run fails

**Comment by LeiZhang-Hunter** [comment]
What should I do about these errors in ci? It feels like an administrator needs to operate

**Comment by brycekahle** [comment]
@LeiZhang-Hunter Thanks for your contribution. We will have an update really soon that will make it clearer how to write CO-RE code in a way that is source-compatible with our prebuilt and runtime-compilation build methods. That way we don't need multiple copies of shared code.

**Comment by LeiZhang-Hunter** [comment]
> Thanks for your contribution. We will have an update really soon that will make it clearer how to write CO-RE code in a way that is source-compatible with our prebuilt and runtime-compilation build methods. That way we don't need multiple copies of shared code.

thank you

**Pull request closed without merging**
