### PR TITLE
[ASCII-2228] Use params for dsd server

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?
This PR adds a mandatory parameter to the dogstatsd server `Module()` in order to replace
```go		
fx.Supply(server.Params{
			Serverless: false,
		}),
dogstatsd.Bundle(),
```
by
```go
dogstatsd.Bundle(server.Params{Serverless: false}),	
```

### Motivation
By adding the parameter to the `Module` function, a user of dogstatsd server doesn't have to guess that `dogstastd.Params` is mandatory

### Describe how to test/QA your changes
QA done by running unit tests and E2E tests.

### CODE REVIEW

**Comment by ogaca-dd** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by carlosroman — APPROVED** [review]

**Review by louis-cqrl — APPROVED** [review]

**Comment by ogaca-dd** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
