### PR TITLE
Remove aliases for env package

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

The changes were generated by `gopatch`. The only real change are locate in `pkg/config/aliases.go`.

### Describe how to test/QA your changes

No code change so running the test should be enough.

### CODE REVIEW

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by gjulianm — APPROVED** [review]

**Review by vickenty — APPROVED** [review]

**Review by guyarb — APPROVED** [review]

**Review by hmahmood — APPROVED** [review]

**Review by paulcacheux — APPROVED** [review]
LGTM for agent-security and agent-cspm owned files

**Review by mfpierre — APPROVED** [review]

**Review by dkirov-dd — APPROVED** [review]

**Review by iliakur — APPROVED** [review]

**Review by GustavoCaso — APPROVED** [review]
Wonderful 🎉

**Review by truthbk — APPROVED** [review]

**Review by ichinaski — APPROVED** [review]

**Review by daniel-taf — APPROVED** [review]

**Review by sblumenthal — APPROVED** [review]

**Review by NouemanKHAL — APPROVED** [review]

**Pull request merged**
