### PR TITLE
[ASCII-1098] Update Go version to 1.21.9

### PR DESCRIPTION
**Pull request by louis-cqrl**
### What does this PR do?

Update the version of Go used to build the agent to 1.21.9.

### Describe how to test/QA your changes

Done with usual dashboard monitoring.

### CODE REVIEW

**Review by pgimalac — APPROVED** [review]

**Review by amenasria — APPROVED** [review]
LGTM for Agent CI Experience owned files !

**Review by songy23 — COMMENTED** [review]
LGTM for OTel

cc @mx-psi

**Review by songy23 — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]
LGTM for ADT owned files

**Review by moth-a — APPROVED** [review]

**Review by jmw51798 — APPROVED** [review]

**Review by wdhif — APPROVED** [review]
LGTM on our files

**Review by kangyili — APPROVED** [review]

**Review by buraizu — APPROVED** [review]

**Review by carlosroman — APPROVED** [review]

**Review by ahmed-mez — APPROVED** [review]

**Review by gh123man — APPROVED** [review]

**Review by jennchenn — APPROVED** [review]

**Review by chouquette — APPROVED** [review]
LGTM for build & release file

**Review by clarkb7 — APPROVED** [review]

**Review by kkhor-datadog — APPROVED** [review]

**Pull request merged**
