### PR TITLE
DOCS-2215 Add @env variables to datadog.yaml

### PR DESCRIPTION
**Pull request by ruthnaebeck**
### What does this PR do?

Add `@env` variables to datadog.yaml:

```
DD_AUTOCONF_TEMPLATE_DIR
DD_AUTOCONFIG_EXCLUDE_FEATURES
DD_AUTOCONFIG_INCLUDE_FEATURES
DD_CLOUD_FOUNDRY_BBS_ENV_EXCLUDE
DD_CLOUD_FOUNDRY_BBS_ENV_INCLUDE
DD_CLOUD_FOUNDRY_CC_URL
DD_CLOUD_FOUNDRY_CC_CLIENT_ID
DD_CLOUD_FOUNDRY_CC_CLIENT_SECRET
DD_CLOUD_FOUNDRY_CC_SKIP_SSL_VALIDATION
DD_CLOUD_FOUNDRY_CC_POLL_INTERVAL
DD_CLOUD_FOUNDRY_CC_APPS_BATCH_SIZE
DD_CLOUD_FOUNDRY_GARDEN_LISTEN_ADDRESS
DD_CLOUD_FOUNDRY_GARDEN_LISTEN_NETWORK
DD_DISABLE_CLUSTER_NAME_TAG_KEY
DD_ECS_METADATA_TIMEOUT
DD_ECS_RESOURCE_TAGS_REPLACE_COLON
DD_KUBERNETES_APISERVER_CA_PATH
DD_KUBERNETES_APISERVER_TLS_VERIFY
DD_KUBERNETES_NAMESPACE_LABELS_AS_TAGS
DD_SNMP_TRAPS_CONFIG_PORT
DD_SNMP_TRAPS_CONFIG_COMMUNITY_STRINGS
DD_SNMP_TRAPS_CONFIG_BIND_HOST
DD_SNMP_TRAPS_CONFIG_STOP_TIMEOUT
DD_SNMP_TRAPS_ENABLED
```

### Motivation

- Documentation OKR
- [RFC](https://github.com/DataDog/architecture/blob/master/rfcs/agent-env-var-docs/rfc.md)

### Additional Notes

Variables will be added in small batches.

### Describe how to test your changes

N/A

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by jtappa — APPROVED** [review]

**Review by sgnn7 — APPROVED** [review]

**Comment by ruthnaebeck** [comment]
Holding for code freeze

**Review by clamoriniere — APPROVED** [review]
Ok for #container-integrations

**Review by AlexandreYang — APPROVED** [review]

**Comment by sgnn7** [comment]
@ruthnaebeck This PR will need rebasing before merge. Since it's freeze day for 7.38, should we move the milestone on this to 7.39?

**Comment by hestonhoffman** [comment]
Hi! Since so much time has elapsed since this PR was opened, I'm going to close it and do a little investigation to see if these changes are still necessary. [I have a ticket for this work here](https://datadoghq.atlassian.net/browse/DOCS-4683). I'll open a fresh PR once I've taken a look.

**Comment by hestonhoffman** [comment]
After getting some more context on this one, I decided to reopen and fix the merge conflict so we don't have to ask everyone for reviews again

**Pull request merged**
