### PR TITLE
Migrate the `copyrights` hook to `invoke`

### PR DESCRIPTION
**Pull request by FlorentClarret**
### What does this PR do?

Migrate the copyrights hooks to invoke

### Motivation

Remove code duplication

### Additional Notes

https://datadoghq.atlassian.net/browse/ADXT-308

### CODE REVIEW

**Review by amenasria — APPROVED** [review]
LGTM !

**Review by KevinFairise2 — APPROVED** [review]
Just want to point out that it slightly modify the behavior of the hook.  It will now fail if files that are not going to be commited (not staged yet) have missing copyright.
I do no think this is a big issue

**Comment by FlorentClarret** [comment]
> Just want to point out that it slightly modify the behavior of the hook. It will now fail if files that are not going to be commited (not staged yet) have missing copyright. I do no think this is a big issue

That's correct. I modified the code!

**Review by KevinFairise2 — APPROVED** [review]

**Pull request merged**
