### PR TITLE
fix(mypy): Rename `unit-tests` folder

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
Rename `unit-tests` in `unit_tests` to stick to python naming convention and 

### Motivation
technical debt

### CODE REVIEW

**Review by pgimalac — APPROVED** [review]

**Review by CelianR — COMMENTED** [review]
When I run `grep -rn 'unit-tests'` some files contains a path to `unit-tests` and have not been changed, can you update them as well ? (for example `./test/kitchen/tasks/unit-tests/kitchen_unit_tests.py:12`)

**Review by CelianR — APPROVED** [review]
Approved if `pyproject.toml` and `CODEOWNERS` are updated 👍

**Review by pducolin — APPROVED** [review]

**Review by f4usto — APPROVED** [review]
reviewed for omnibus path change

**Pull request merged**
