### PR TITLE
Honor more config options in Windows network tracer

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

There were several configuration options that were not being applied to the windows tracer. This fixes that.

### Motivation

Consistency between Linux and Windows.

### Describe how to test your changes

Using any of the non-default values of the following config options on Windows, should now work:

- `CollectTCPConns`
- `CollectUDPConns`
- `CollectIPv6Conns`
- `CollectLocalDNS`
- `ExcludedSourceConnections`
- `ExcludedDestinationConnections`

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.

### CODE REVIEW

**Review by derekwbrown — APPROVED** [review]

**Review by derekwbrown — CHANGES_REQUESTED** [review]
I put this in slack, but it probably bears repeating here

We need to think about our process here.

My general flow would be to 
a) make changes to driver
b) make a datadog-agent branch to test those changes
c) get the driver signed
b) update release.json on that branch prior to merging.

(this PR has (a) and (b) so far)

The idea would be that master never points to testsigned, because there's some risk of shipping the testsigned drivers.

Now, this flow has some other fairly obvious flaws... so I'm not saying we have to stick to that.  But we should agree on something, and that something (IMO) should be centered around making sure we don't accidentally ship an unsigned driver.

**Review by hush-hush — APPROVED** [review]
Only looking at the release.json.

**Review by albertvaka — APPROVED** [review]
✅ changes to release.json

**Comment by brycekahle** [comment]
> get the driver signed

How long does this normally take?

**Review by nplanel — APPROVED** [review]

**Review by sgnn7 — APPROVED** [review]

**Review by derekwbrown — APPROVED** [review]

**Pull request merged**
