### PR TITLE
pkg/trace/watchdog: remove LogOnPanic

### PR DESCRIPTION
**Pull request by gbbr**
This change removes LogOnPanic for the following reasons:

* Not useful: we have no occurrences in the past period, nor reports of panics.
* Defer is slow.
* Code is ugly.
* We have logs and flares to find panics if and when they occur.

### CODE REVIEW

**Review by LotharSee — APPROVED** [review]
LGTM.

Can you share here what a panic would look like now in the Agent logs? Or how to exactly get it in a flare?

**Review by AlexJF — COMMENTED** [review]
Not sure this should be removed. 

* Defers are slow yes but here we're only calling them during 
"bootstrapping" not on a hotpath so removing them should have 0-impact.
* Besides adding a small log message, `LogOnPanic` also makes sure any pending logs are flushed and a metric is posted to datadog. We might not have recently used this but I think this is a nice thing to have when we actually need it. Debugging issues surrounding a panic is not fun when you can't even be sure you have all the logs around the time of the panic occurrence. Unless something else triggers this flushing already?

**Comment by gbbr** [comment]
We've discussed this before with Benjamin and concluded it wasn't needed.

But the question is very valid and I'm looking into how this would end up in the logs in case of a panic before considering merging. I will report back here with the findings.

**Comment by LotharSee** [comment]
Yup my thoughts were that the Agent already had something like a `LogOnPanic` so we didn't need to keep our watchdog. 
If not, that the task is to see how the whole Agent handles panic and have something similar used everywhere.

**Comment by AlexJF** [comment]
Oh yeah that definitely makes sense 😄

**Comment by gbbr** [comment]
I've done some research and it seems like most big projects do the same as we do, as does the [standard library](https://github.com/golang/go/blob/master/src/net/http/server.go#L1766-L1771). We'll have to keep it.

I was operating under the wrong assumption that somehow our logging library would capture this output (which goes to `os.Stderr` too).

Thank you for questioning!

**Pull request closed without merging**
