### PR TITLE
Revert "Revert "update ECS fargate collector to use v4 endpoint""

### PR DESCRIPTION
**Pull request by kangyili**
Reverts DataDog/datadog-agent#24914

The original PR broke CI on main so it was reverted. It is because I accidentally deleted the code initialising ecs clients during refactoring, this PR adds it back...

### CODE REVIEW

**Comment by kangyili** [comment]
Nothing is changed but adding the code to initialise clients 9f17b62a5a2a10ae444aac617b4d78ab7daa3bd5

**Review by adel121 — APPROVED** [review]

**Comment by kangyili** [comment]
It's hard to have an e2e test for an internal component as it doesn't send data directly. 
I will open another PR to add an e2e test for the check `orchestrator_ecs` that uses workload-meta store.

**Comment by kangyili** [comment]
\merge

**Pull request merged**
