### PR TITLE
[OASIS-12] Fix OTel dependencies

### PR DESCRIPTION
**Pull request by songy23**
### What does this PR do?

Update all `go.opentelemetry.io/collector/*` dependencies to the same version (v0.100.0) and run `inv tidy-all`

Previously there are a mix of v0.97.0, v0.98.0,  v0.99.0,  v0.100.0 versions of `go.opentelemetry.io/collector/*` all over the place.

### CODE REVIEW

**Review by dineshg13 — APPROVED** [review]

**Review by amenasria — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]
LGTM for files owned by ASC

**Review by dineshg13 — APPROVED** [review]

**Review by remeh — APPROVED** [review]
All good for files owned by APR.

**Review by ajgajg1134 — APPROVED** [review]

**Review by guyarb — APPROVED** [review]

**Comment by songy23** [comment]
On hold waiting for https://github.com/DataDog/datadog-agent/pull/25733. Context: #incident-27503

**Pull request merged**
