### PR TITLE
[invoke] Add more linting tasks

### PR DESCRIPTION
**Pull request by hkaj**
### What does this PR do?

Add gocyclo, misspell, and ineffassign tasks in invoke

### Motivation

They're nice.

### Additional Notes

Leaving them out of the CI for now so we can first play with them manually.

### CODE REVIEW

**Comment by mfpierre** [comment]
IMHO `ineffassign` & `misspell` could be added to `inv test`

**Review by masci — APPROVED** [review]
🍰

**Comment by xvello** [comment]
Should we investigate https://github.com/alecthomas/gometalinter ?
As our CI runners have several CPUs, that could shorten the run time

**Comment by hkaj** [comment]
@xvello yeah we can look into it. Let's add that to the backlog though as I don't have time to pursue this idea now.

**Comment by hkaj** [comment]
@mfpierre I'm down for that, but adding them now would block the CI as they raise issues.
I'll add them in another PR.

**Pull request merged**
