### PR TITLE
Remove unnecessary uses of fmt.Sprintf

### PR DESCRIPTION
**Pull request by testwill**
### What does this PR do?
remove unnecessary use of fmt.Sprintf 

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by pgimalac — CHANGES_REQUESTED** [review]
Thank you for the contribution ! Just a small fix needed

**Review by pgimalac — APPROVED** [review]
LGTM, thanks for the contribution

**Review by paulcacheux — APPROVED** [review]

**Review by TCheruy — APPROVED** [review]

**Review by scottopell — APPROVED** [review]

**Review by kkhor-datadog — APPROVED** [review]

**Review by mfpierre — APPROVED** [review]

**Review by AlexandreYang — APPROVED** [review]

**Comment by pgimalac** [comment]
@testwill can you rebase your PR on main ?
We fixed a few issues with the CI, once the tests pass you can merge this PR.
(I'll trigger the tests again once you rebase)

**Comment by testwill** [comment]
ok

**Comment by pgimalac** [comment]
@testwill I'm sorry but we actually had another issue with our CI which was just fixed by https://github.com/DataDog/datadog-agent/pull/18280
Could you rebase or merge main one more time ?

**Comment by pgimalac** [comment]
Thank you for the PR !

**Pull request merged**
