### PR TITLE
Allow long values in submit_histogram_bucket

### PR DESCRIPTION
**Pull request by therve**
We're currently enforcing an integer, which obviously fails with bigger values.

Question: should it be `long long`?

### CODE REVIEW

**Review by olivielpeau — COMMENTED** [review]
indeed, it might be better to use `int64`/`C.longlong` on the go side, and `long long` on the C side, just to make sure we're consistently using 64-bit integers everywhere.

Other than that LGTM

**Comment by olivielpeau** [comment]
This should wait for https://github.com/DataDog/datadog-agent/pull/4887, it doesn't make sense to merge this before the bucket interpolation works better

**Comment by olivielpeau** [comment]
(also, needs a release note)

**Comment by hush-hush** [comment]
Moving this to 7.19 since we're waiting for #4887 

Should we dot the same for all other method (gauge, rate, ...) ?

**Comment by olivielpeau** [comment]
moving this back to 7.18.0 actually, since we'll actually want to merge the present PR as soon as #4932 is merged

**Review by olivielpeau — APPROVED** [review]

**Pull request merged**
