### PR TITLE
[SMP] Increase the DogStatsD default stringInterner size

### PR DESCRIPTION
**Pull request by blt**
### What does this PR do?

This commit increases the default DogStatsD string interner size from 4096 keys to 20_480 keys. Per #19852 we believe that this will benefit Agent memory consumption, allocation pressure while nominally increasing DogStatsD throughput. Details [in this comment](https://github.com/DataDog/datadog-agent/pull/19852#issuecomment-1741843960).

### Additional Notes

We will know if this change is specific to a single scenario or more generally applicable after the Regression Detector runs. I will comment with an analysis on this PR once that happens.

### Possible Drawbacks / Trade-offs

Given the allocation pressure already present in this portion of the codebase I am unaware of any. The string interner does not pre-allocate its storage -- although https://github.com/DataDog/datadog-agent/pull/19179 suggests that would be an interesting follow-up -- so smaller target deploys will not see higher baseline memory consumption. 

### Motivation

[See this page for details](https://datadoghq.atlassian.net/wiki/spaces/SMP/pages/3191537984/Agent+in+1GiB+of+RAM)

REF SMPTNG-12

### CODE REVIEW

**Comment by blt** [comment]
Observations from the Regression Detector:

* change is throughput neutral
* presence of distribution metrics drowns out all other effects
* even in [`_nodist_100MiB`](https://app.datadoghq.com/dashboard/t3q-y5d-i7u/smp-regression-detector-capture-data?refresh_mode=paused&tpl_var_experiment%5B0%5D=uds_dogstatsd_to_api_nodist_100mib&tpl_var_run-id%5B0%5D=9b4c5823-9410-427c-830d-f58034ae756f&from_ts=1696269682398&to_ts=1696270244392&live=false) the CPU percentage drop is notable, -50% utilization

We now have [profiles](https://app.datadoghq.com/profiling/search?query=account%3Asingle-machine-performance%20runtime%3Ago%20client_team%3Aagent%20version%3A%28_7_49_0_rc.1_git.1.4c90311_4c90311_%20OR%20_7_49_0_rc.1_git.2.c428892_c428892_%29&my_code=disabled&viz=flame_graph&start=1696268888216&end=1696272488216&paused=true) for this run. Results, `main` vs this PR:

| Experiment | CPU time | Lifetime Allocations | Heap Live Size | Mutex Time | 
| ------------ | --------- | ------------------- | --------------- | ------------ |
| `uds_dogstatsd_to_api_nodist_100MiB` | -27 sec | ~ -52 M | -63Mb | ~ -3 sec |
| `uds_dogstatsd_to_api_nodist_200MiB` | -25 sec | ~ -65 M | -85Mb | ~ -3 sec | 
| `uds_dogstatsd_to_api_nodist_nomulti_100MiB` | -32 sec | ~ -53 M | +21Mb | ~ -1 sec | 
| `uds_dogstatsd_to_api_nodist_nomulti_200MiB` | -25 sec | ~ -64 M | -85Mb | +12 sec |

Consider [`_nodist_nomulti_100MiB`](https://app.datadoghq.com/profiling/comparison?query=account%3Asingle-machine-performance%20runtime%3Ago%20client_team%3Aagent%20version%3A%28_7_49_0_rc.1_git.1.4c90311_4c90311_%20OR%20_7_49_0_rc.1_git.2.c428892_c428892_%29&compare_end_A=1696272318360&compare_query_A=account%3Asingle-machine-performance%20runtime%3Ago%20client_team%3Aagent%20version%3A_7_49_0_rc.1_git.1.4c90311_4c90311_%20%20%20experiment%3Auds_dogstatsd_to_api_nodist_nomulti_100mib&compare_query_B=account%3Asingle-machine-performance%20runtime%3Ago%20client_team%3Aagent%20version%3A_7_49_0_rc.1_git.2.c428892_c428892_%20%20%20%20experiment%3Auds_dogstatsd_to_api_nodist_nomulti_100mib&compare_start_A=1696267922663&compare_start_B=1696268379973&compareValuesMode=absolute&my_code=disabled&profile_type=heap-live-size&viz=flame_graph&start=1696268599355&end=1696272199355&paused=false). Added live heap appears to be present in both this and the `_200MiB` variant in [`sendEvents`](https://github.com/DataDog/datadog-agent/blob/4c90311cb95a6037308a4ee6a63afb5e450f8cfc/pkg/aggregator/aggregator.go#L646). This is consistent with the increase in throughput in these experiment, below the Regression Detector threshold in relative terms but worth [~5MiB/sec](https://app.datadoghq.com/dashboard/t3q-y5d-i7u/smp-regression-detector-capture-data?refresh_mode=paused&tpl_var_experiment%5B0%5D=uds_dogstatsd_to_api_nodist_nomulti_200mib&tpl_var_run-id%5B0%5D=9b4c5823-9410-427c-830d-f58034ae756f&from_ts=1696269682398&to_ts=1696270244392&live=false) in absolute terms.

In general I consider this change a desirable one.

**Comment by blt** [comment]
Some noted concerns, questions:

* @scottopell : Will this increase memory consumption in low-throughput scenarios? 
* @GeorgeHahn : Does this work because it is not populating the string intern cache?

Apologies if I muddled the paraphrase. To the first, I think we could introduce a new variant experiment in this PR that does, say, 100KiB/sec throughput, all other settings being the same. It's certainly something we can probe. To the second, we can collect the interner's self-telemetry, I just need to wire that in.

**Review by pgimalac — APPROVED** [review]

**Comment by scottopell** [comment]
I'm trying to establish an intuition for what factors play into this, I don't think its as simple as "high bytes per second vs low bytes per second".

The string interner is really about the number of unique strings that are processed (ie, components of a dogstatsd message).
So in a high-churn environment where new metric names and tags are constantly seen, this is nearly useless. We'll just continue to flush the cache and we get no real benefit.

But "every metric is unique" is not the case for the Agent. We see many tags and metric names repeated, which brings us back to the idea of a metric context.

In a scenario where we have a _high_ number of metric contexts, we correspondingly have a high number of unique strings, we want to re-use existing allocations for all of them, so increasing `dogstatsd_string_interner_size` is useful.

In a scenario where we have a _low_ number of metric contexts, if the `dogstatsd_string_interner_size` is too big, then we end up wasting space holding onto strings we may have only seen once and will never see again.

I'm leaning towards leaving this default alone and maybe updating [our docs](https://docs.datadoghq.com/developers/dogstatsd/high_throughput/) for high throughput dogstatsd to mention this as a good thing to tune.

Longer/medium term it would be great to improve the tunables here as its rather hard to say what a good size would be for a given workload. Or make it automatic so nobody ever has to tune this (though I have no idea how we'd do that).


Sorry for the big wall of text, but I lean towards a docs change vs a default change.

**Comment by blt** [comment]
Fundamentally, I do not believe that our customers should need to be domain expert in the internals of our Agent to get acceptable performance. I believe that documenting toggles is a _kinder_ way of pushing demand for expertise on customers, but it's still pushing that demand. If a DogStatsD heavy customer is not using distribution metrics, this is the bottleneck and memory allocation center they'll hit even for a moderate number of contexts, see below.

> I'm trying to establish an intuition for what factors play into this, I don't think its as simple as "high bytes per second vs low bytes per second".

It's not, no. It's also not as simple as contexts per second. If we consider the distribution problem, Agent performance is clearly contingent on throughput, distribution of input through time -- smooth, spikey etc -- and also contingent on factors that impact the internals of a component (contexts, here). That pattern is repeated here. I strongly believe that optimizing Agent to remove allocations / second is the major heuristic available to us today, [these results](https://github.com/DataDog/datadog-agent/pull/19882#issuecomment-1743602854) are driven entirely by following that heuristic. Allocating and then freeing memory is not cheap.

> The string interner is really about the number of unique strings that are processed (ie, components of a dogstatsd message). So in a high-churn environment where new metric names and tags are constantly seen, this is nearly useless. We'll just continue to flush the cache and we get no real benefit.
> 
> But "every metric is unique" is not the case for the Agent. We see many tags and metric names repeated, which brings us back to the idea of a metric context.

These experiments are not exercising unique metric names. The maximum number of contexts is 10k. The minimum is 1,000. I do agree that we lack -- as a project -- the notion of what a reasonable number of contexts for a single agent to handle is as of this writing to frame 'reasonable' here. 

> In a scenario where we have a _high_ number of metric contexts, we correspondingly have a high number of unique strings, we want to re-use existing allocations for all of them, so increasing `dogstatsd_string_interner_size` is useful.
> 
> In a scenario where we have a _low_ number of metric contexts, if the `dogstatsd_string_interner_size` is too big, then we end up wasting space holding onto strings we may have only seen once and will never see again.

This is not correct. If we have a low number of input contexts through the lifetime of the Agent the interner will size up proportionally to that size. We are not pre-allocating storage. The worse behavior here is what happens when we overwhelm the cache. As of this PR we continue to dump the whole storage, reallocate it and then restart the cache. It is true that we do not clear the cache without dumping the whole thing.

I have added experiments to this PR to experiment with low-throughput, same context situations. I've re-triggered it with a rebase from `main` so we can speak from more up to date data. If you would like to see other parameters changed do let me know.

> I'm leaning towards leaving this default alone and maybe updating [our docs](https://docs.datadoghq.com/developers/dogstatsd/high_throughput/) for high throughput dogstatsd to mention this as a good thing to tune.
> 
> Longer/medium term it would be great to improve the tunables here as its rather hard to say what a good size would be for a given workload. Or make it automatic so nobody ever has to tune this (though I have no idea how we'd do that).

That is this work. I believe a non-trivial improvement is possible here in the near term. As mentioned, I believe we might also profitably explore re-introduction of https://github.com/DataDog/datadog-agent/pull/19179 as a follow-up but more importantly we _really_ should not be invaliding the whole cache in one shot when it's full. We could explore lumping more work into this PR, if our follow-up discussion from new data still leaves some concerns.

> Sorry for the big wall of text, but I lean towards a docs change vs a default change.

**Comment by scottopell** [comment]
> Fundamentally, I do not believe that our customers should need to be domain expert in the internals of our Agent to get acceptable performance. I believe that documenting toggles is a kinder way of pushing demand for expertise on customers, but it's still pushing that demand.

I agree, this is a great goal. I'll pick one nit which is that we're talking about getting acceptable performance _under an abnormally high workload_.

> This is not correct. If we have a low number of input contexts through the lifetime of the Agent the interner will size up proportionally to that size. We are not pre-allocating storage. The worse behavior here is what happens when we overwhelm the cache. As of this PR we continue to dump the whole storage, reallocate it and then restart the cache. It is true that we do not clear the cache without dumping the whole thing.

I understand that we don't pre-allocate, when I say "we end up wasting space and holding onto strings that we may have only seen once and will never see again", I'm referring to a scenario where there is some application and/or codepath that is hit early in the agent's lifecycle which emits some large strings as part of a dogstatsd payload.
Those metrics never get sent again, and therefore the space they occupy in the string interner cache is wasted, and because they're in the interner, they never get GC'd.

This risk is always present with low-context workloads, but the risk is _higher_ with a larger cache size, which is why I don't support this as a new default value.

> That is this work. I believe a non-trivial improvement is possible here in the near term. As mentioned, I believe we might also profitably explore re-introduction of https://github.com/DataDog/datadog-agent/pull/19179 as a follow-up but more importantly we really should not be invaliding the whole cache in one shot when it's full. We could explore lumping more work into this PR, if our follow-up discussion from new data still leaves concerns.

I think this was poor phrasing on my part, when I say:
> Longer/medium term it would be great to improve the tunables here
I'm referring to what "tunable"/"variable" is available to be changed. Right now we only have a variable that says "size of string cache", but as this discussion highlights, its hard to reason about the impact of changing this.

If we want to improve the string interner for high-context/throughput workloads, we should be making changes to the way the string interner works, not just bumping up the default.

**Comment by blt** [comment]
It doesn't look like the pr-commenter ran. `0b810c87-3bd9-4b9a-b4e1-aad012cd9639` is the most recent job-id. CI results: [here](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/343827061).

Results: https://app.datadoghq.com/notebook/6635384/datadog-agent-string-interner-optimization?range=575458&tpl_var_experiment%5B0%5D=uds_dogstatsd_to_api_nodist_nomulti_100mib&tpl_var_experiment%5B1%5D=uds_dogstatsd_to_api_nodist_nomulti_1kib&tpl_var_experiment%5B2%5D=uds_dogstatsd_to_api_nodist_nomulti_200mib&tpl_var_run_id=0b810c87-3bd9-4b9a-b4e1-aad012cd9639&view=view-mode&start=1696607177068&live=false

> > Fundamentally, I do not believe that our customers should need to be domain expert in the internals of our Agent to get acceptable performance. I believe that documenting toggles is a kinder way of pushing demand for expertise on customers, but it's still pushing that demand.
> 
> I agree, this is a great goal. I'll pick one nit which is that we're talking about getting acceptable performance _under an abnormally high workload_.

For context, the Workload Checks experiment `app_server` targets 32MiB/s and demonstrates a similar bottleneck, once the distribution issue is removed. We could run an exact copy of that experiment to reconfirm if you'd like but I'd argue the setup here is less abnormal than it might seem. That said, I agree with the concern of not wanting to pessimize low-throughput use cases and see that as important.

> > This is not correct. If we have a low number of input contexts through the lifetime of the Agent the interner will size up proportionally to that size. We are not pre-allocating storage. The worse behavior here is what happens when we overwhelm the cache. As of this PR we continue to dump the whole storage, reallocate it and then restart the cache. It is true that we do not clear the cache without dumping the whole thing.
> 
> I understand that we don't pre-allocate, when I say "we end up wasting space and holding onto strings that we may have only seen once and will never see again", I'm referring to a scenario where there is some application and/or codepath that is hit early in the agent's lifecycle which emits some large strings as part of a dogstatsd payload. Those metrics never get sent again, and therefore the space they occupy in the string interner cache is wasted, and because they're in the interner, they never get GC'd.

Understood, but that problem is not addressed with the project's existing default either. 

Consider also that the memory consumption under discussion is [small](https://app.datadoghq.com/notebook/6635384/datadog-agent-string-interner-optimization?fullscreen_end_ts=1696607752526&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_start_ts=1696607177068&fullscreen_widget=58zhd4rt&range=575458&tpl_var_experiment%5B0%5D=uds_dogstatsd_to_api_nodist_nomulti_100mib&tpl_var_experiment%5B1%5D=uds_dogstatsd_to_api_nodist_nomulti_1kib&tpl_var_experiment%5B2%5D=uds_dogstatsd_to_api_nodist_nomulti_200mib&tpl_var_run_id=0b810c87-3bd9-4b9a-b4e1-aad012cd9639&view=view-mode&start=1696607177068&live=false), on the order of 2.6MiB in the high-end throughput experiments.  The existing default _does_ indicate an allocation led throughput bottleneck across a range of throughputs. My argument for raising the default is that we end up in a no-worse state, set ourselves up for further improvements _and_ address an existing bottleneck for very little effort.

I certainly think that eviction of the cache needs to be revisited. I also think that the cache is far too small by default.

> This risk is always present with low-context workloads, but the risk is _higher_ with a larger cache size, which is why I don't support this as a new default value.

I think we should be clear about what constitutes low/high contexts, else we might be thinking about numbers that are way, way off. [Context data](https://app.datadoghq.com/notebook/6635384/datadog-agent-string-interner-optimization?fullscreen_end_ts=1696607752526&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_start_ts=1696607177068&fullscreen_widget=bhmlivtt&range=575458&tpl_var_experiment%5B0%5D=uds_dogstatsd_to_api_nodist_nomulti_100mib&tpl_var_experiment%5B1%5D=uds_dogstatsd_to_api_nodist_nomulti_1kib&tpl_var_experiment%5B2%5D=uds_dogstatsd_to_api_nodist_nomulti_200mib&tpl_var_run_id=0b810c87-3bd9-4b9a-b4e1-aad012cd9639&view=view-mode&start=1696607177068&live=false) from the experiments. (Note this indicates the context filter in lading is buggy, or potentially surprising if throughput is low. Something to investigate.)

Some thoughts on the risk being higher, noting the experimental numbers above:

* In the 1KiB case we see no difference in the bytes held in the interner between baseline and comparison.
* In 100MiB and 200MiB cases we see most replicates thrash around 0.6MiB with two replicates holding steady at 2.62MiB. 
* Even with the higher default we spend [a lot](https://app.datadoghq.com/notebook/6635384/datadog-agent-string-interner-optimization?fullscreen_end_ts=1696607752526&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_start_ts=1696607177068&fullscreen_widget=kaqld92e&range=575458&tpl_var_experiment%5B0%5D=uds_dogstatsd_to_api_nodist_nomulti_100mib&tpl_var_experiment%5B1%5D=uds_dogstatsd_to_api_nodist_nomulti_1kib&tpl_var_experiment%5B2%5D=uds_dogstatsd_to_api_nodist_nomulti_200mib&tpl_var_run_id=0b810c87-3bd9-4b9a-b4e1-aad012cd9639&view=view-mode&start=1696607177068&live=false) of time resetting the cache.

It seems to me that:

* The amount of memory under discussion worst-case is small relative to the total amount consumed by Agent at runtime, 
* the behavior of low-throuhgput users is not pessimized compared to baseline,
* the proposed default improves the behavior of higher-throughput users and
* the reset counter for 100MiB/200MiB cases suggests that resets happen multiple times per second as-is.

This suggests to me that the proposed risk in cases where it does happen in practice:

* exists in `main` today,
* is a rounding error amount of memory and
* will not happen in practice for high-throughput clients which demonstrably reset the cache frequently.

Further, correctly setting the tunable flag requires:

* a detailed understanding of Agent internals, one's workload,
* potentially access to a profiled view of the live Agent. 

> > That is this work. I believe a non-trivial improvement is possible here in the near term. As mentioned, I believe we might also profitably explore re-introduction of #19179 as a follow-up but more importantly we really should not be invaliding the whole cache in one shot when it's full. We could explore lumping more work into this PR, if our follow-up discussion from new data still leaves concerns.
> 
> I think this was poor phrasing on my part, when I say:
> 
> > Longer/medium term it would be great to improve the tunables here
> > I'm referring to what "tunable"/"variable" is available to be changed. Right now we only have a variable that says "size of string cache", but as this discussion highlights, its hard to reason about the impact of changing this.
> 
> If we want to improve the string interner for high-context/throughput workloads, we should be making changes to the way the string interner works, not just bumping up the default.

To be clear, I would like to follow this work up with:

* a PR to pre-allocate the storage for the cache (potentially undesirable for reasons discussed above)
* a PR to introduce FIFO eviction to the cache to avoid flushing the whole thing, since resetting is such a frequent operation.

This work is a good, cheap win -- is my argument -- and we can follow-up with improvements on the low-end of things too.

**Comment by scottopell** [comment]
https://github.com/DataDog/datadog-agent/pull/19990 related

**Comment by blt** [comment]
See https://github.com/DataDog/datadog-agent/pull/19990#issuecomment-1758131870

**Comment by blt** [comment]
Supplanted by https://github.com/DataDog/datadog-agent/pull/20943

**Pull request closed without merging**
