### PR TITLE
telemetry: do not set the namespace, the configuration check will take care of it

### PR DESCRIPTION
**Pull request by remeh**
### What does this PR do?

Do not deal with the namespace of the metrics in the pkg, the configuration of the check will take care of it.

### CODE REVIEW

**Review by ahmed-mez — DISMISSED** [review]
thanks 👍

**Review by olivielpeau — CHANGES_REQUESTED** [review]
This feels clunky: we're relying on a build tag that we know is only included in the cluster agent build today, but this may not be true in the future, so I don't think we should rely on it: it adds what I would consider an unexpected side effect of the `clusterchecks` build tag.

I think it's OK to add an `Init(namespace string)` method on the `telemetry` package, called at startup by each agent. It feels more explicit and only adds a bit more verbosity. What do you think?

_EDIT_: we have other places in the codebase where we have to deal with such small naming differences between the cluster agent and the agent. See for example the startup telemetry in the aggregator (that sends a `datadog.agent.started` metric at startup for the agent vs `datadog.cluster_agent.started` for the cluster agent): https://github.com/DataDog/datadog-agent/blob/master/cmd/agent/app/run.go#L257-L258

**Comment by remeh** [comment]
@olivielpeau There is an issue: we declare the metrics in `init()` methods of the different pkg.
Because the order of execution of `init()` methods is undefined, we can't use one to set it in different agents. Also we can't properly add a func in Agents to later change the namespace, because it would run after the vars declaration.

**Review by olivielpeau — APPROVED** [review]
✅

**Review by ahmed-mez — APPROVED** [review]

**Pull request merged**
