### PR TITLE
upgrade(installer): Report and store policies metadata

### PR DESCRIPTION
**Pull request by BaptisteFoy**
### What does this PR do?
Reports policies applied and add boilerplate to add more metadata.
The policies metadata is reported through Remote Config Updater state. To permanently have it for stable / experiment versions it is stored in a file next to configuration. It is encoded in protobuf to lower footprint on customer host. The file can only be read (not written) by dd-agent & root. It is written by root only.

### Describe how to test/QA your changes
QA-ed manually, E2E test

### CODE REVIEW

**Review by arbll — APPROVED** [review]
📦

**Review by KevinFairise2 — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Pull request merged**
