### PR TITLE
logs/sds: delete existing scanners when an update with 0 configuration is received through RC

### PR DESCRIPTION
**Pull request by remeh**
APR-94

### What does this PR do?

When an Agent isn't targeted _anymore_, it is receiving an update with no configuration.
In this scenario for the SDS "agent config" configurations, we have to make sure existing scanners are dropped.

### Motivation

Fix the behaviour when an Agent isn't targeted anymore.

### Describe how to test/QA your changes

* In an org with RC & SDS enabled
* Configure a scanning group for your agent to receive a configuration through the UI
* Make sure it is reconfiguring itself
* Change the scanning group to not target this agent anymore
* Make sure the Agent is reconfiguring itself (destroying its scanners)

### CODE REVIEW

**Review by gh123man — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Are there any tests that could be updated for this?

**Review by songy23 — APPROVED** [review]
LGTM for OTel

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
