### PR TITLE
Fix trace agent to properly locate windows core agent with changes for

### PR DESCRIPTION
**Pull request by derekwbrown**
`six

### CODE REVIEW

**Review by gbbr — APPROVED** [review]

**Comment by olivielpeau** [comment]
@derekwbrown This isn't the only location where something expects the path of the agent binary on Windows to be `<PROGRAM_DATA>\\embedded\\agent.exe`. Off the top of my head, I can think of:

* the process agent (https://github.com/DataDog/datadog-agent/blob/1fdb5e1746f9834d627f8fa1611d3753c1f9db10/pkg/process/config/config_windows.go#L24)
* a lot of docs (both in the present repo, for example for `secrets`, and on the public website)
* in the Chef cookbook, for the `integration` command support (still unreleased for the moment): https://github.com/DataDog/chef-datadog/blob/master/resources/integration.rb#L53

More generally, changing the Agent's binary could be regarded as a breaking change, some users may be relying on it to remain stable across minor releases. Is there a way we could either:

* keep the binary where it was in 6.11, or
* somehow (with a link for example?) make the older path (`embedded\\agent.exe`) still work, even though the binary is now in `bin\\agent.exe`?

(also asking because I don't know what were the reasons to move it to `bin\\agent.exe` in the first place)

**Comment by derekwbrown** [comment]
I could put it back.  The reason moved it is because at the moment, there isn't going to be an `embedded` directory at all. (embedded2 for py2, embedded3 for py3).   I could put it back, and then the only thing in `embedded` will be the agent binary, which will look a bit weird, but there won't be anything wrong with it.

**Comment by olivielpeau** [comment]
To be honest I prefer the new path `bin\agent.exe` 😄
Is is possible to remain compatible with external scripts still using `embedded\agent.exe` with a link of some kind?

**Comment by derekwbrown** [comment]
We could do a link in embedded; we may have to add some other links to make it work.  It's still going to look a bit odd, imo, because we'll have embedded, embedded2, and embedded3; and embedded is just going to have a link to bin.

also, symlinks only exist on NTFS... I can't imagine anyone still running on FAT, but as soon as I say that...

**Comment by olivielpeau** [comment]
> we may have to add some other links to make it work

Would that list of additional links grow/change over time? (asking because if this becomes a maintenance burden, having links is probably not a good idea)

> It's still going to look a bit odd, imo, because we'll have embedded, embedded2, and embedded3; and embedded is just going to have a link to bin.

I'm OK if the main cost is that we end up with an odd directory structure :)

> also, symlinks only exist on NTFS... I can't imagine anyone still running on FAT, but as soon as I say that...

Can we add symlinks only if we're on NTFS, and not create them otherwise, but not fail in any case?

**Comment by derekwbrown** [comment]
> > we may have to add some other links to make it work
> 
> Would that list of additional links grow/change over time? (asking because if this becomes a maintenance burden, having links is probably not a good idea)

Probably not.  Mostly C-runtime for 2k8 (so it would shrink over time).
> 
> > It's still going to look a bit odd, imo, because we'll have embedded, embedded2, and embedded3; and embedded is just going to have a link to bin.
> 
> I'm OK if the main cost is that we end up with an odd directory structure :)
>
yeah, I guess.
> > also, symlinks only exist on NTFS... I can't imagine anyone still running on FAT, but as soon as I say that...
> 
> Can we add symlinks only if we're on NTFS, and not create them otherwise, but not fail in any case?

We can always ignore failures ;)

**Pull request merged**
