### PR TITLE
Add fips agent flavor e2e installer tests

### PR DESCRIPTION
**Pull request by jeremy-hanna**
### What does this PR do?

* Add the fips packages to the e2e_testing_deploy tasks so they are available as flavors for installation with the e2e framework
* Add installer tests around the new agent flavor artifacts

### CODE REVIEW

**Comment by jeremy-hanna** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by jeremy-hanna** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by jeremy-hanna** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by amenasria — APPROVED** [review]
LGTM for Agent DevX Infra owned files !

**Comment by jeremy-hanna** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by chouquette — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Review by khewonc — APPROVED** [review]

**Pull request merged**
