### PR TITLE
[docker] Update network detection logic

### PR DESCRIPTION
**Pull request by conorbranagan**
### What does this PR do?

Check the NetworkMode in the HostConfig first to determine if a container is in host mode, no-network mode or depends on a separate container id to provide the network namespace.

If we're in the last case we will also resolve these cases to their respective network namespace after we've gathered all container networks.

Tests are added around all of these cases.

### Motivation

Fixes some buggy network detection cases that we saw around Kubernetes and others in earlier versions of the process-agent.

### CODE REVIEW

**Review by xvello — CHANGES_REQUESTED** [review]
Host networking will manifest differently in the netsettings, but the most reliable way to detect it should be to look at [Container.HostConfig.NetworkMode](https://godoc.org/github.com/moby/moby/api/types#Container)

Fallbacking to host mode with that LGTM, but I'd also test that value at the very beginning of the method and return without event a debugf as that's to be expected.

**Comment by hkaj** [comment]
+1 we should check for NetworkMode here. For example in k8s: 
```
"NetworkMode": "container:a379060c7cb72064220a3fc4759c27573ff9efdbe773623593e79853e79fb16e",
```
and 
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
```
no network doesn't always mean host mode.

**Comment by xvello** [comment]
Indeed, that could also mean `--net=none`

**Comment by conorbranagan** [comment]
I can look into these changes. All of this behavior is basically replicated from dockerutil as it is now: https://github.com/DataDog/dd-agent/blob/master/utils/dockerutil.py#L620 which doesn't seem to look at `NetworkMode` at all, afaict. Is this somewhere else in the Agent 5 code or are we extending the behavior in Agent 6?

**Comment by xvello** [comment]
That agent5 logic was written during my first week on the project, I know Docker better now ;)

**Review by xvello — APPROVED** [review]
LGTM!
We'll need to discuss about a longer-term solution for handling pod networking though, but that replicates what we do in agent5

**Pull request merged**
