### PR TITLE
Bump `github.com/golang/protobuf` from 1.3.2 to 1.5.2

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

It seems `etcd` made some progress on grpc/proto dependencies. This mean this bump is at least possible. Please note that even though this PR seems simple and straightforward, the protobuf dependency migrated everything and reimplemented everything in terms of v2. This needs some serious QA/review that everything is still working as expected.

### Describe how to test/QA your changes

The "on the wire" payload should absolutely be the same, the QA should then just be to check that everything is till working as expected.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by truthbk — APPROVED** [review]
Looks good! 📦

**Review by bkabrda — APPROVED** [review]

**Comment by mx-psi** [comment]
@paulcacheux what should Agent Platform test for this PR's QA?

**Comment by paulcacheux** [comment]
This is kind of hard, basically there should be no visible change. But protobuf is a nasty piece since it can affect performance (as can be seen by the fact that we pin exact protobuf versions in agent-payload). I added the label `major change` so that if people start seeing strange stuff, they can directly see that this was bumped and can be a possible explanation

**Comment by mx-psi** [comment]
Okay. We tested the OTLP bits that use protobuf for a different QA card, so I think from our side there is not much more to test. Thanks for clarifying!

**Pull request merged**
