### PR TITLE
Omnibus rework

### PR DESCRIPTION
**Pull request by masci**
### What does this PR do?

Global review and partial refactoring of the Omnibus packaging process.

### Motivation

The project was ported from the old agent without too much reworking, thus checking in stuff that we either don't need or want to do better.

### Additional Notes

A non exhaustive list of the changes:

 * make the use of Omnibus a little more idiomatic
 * add specific docs
 * make Omnibus GOPATH-aware when building go software
 * no need to run the Omnibus build from the GOPATH anymore
 * in general, clean up code and make it more consistent

**NOTE**: Windows support will come with a dedicated PR.

### CODE REVIEW

**Review by gmmeyer — COMMENTED** [review]
I added three comments on this. Is there anything specific you think I should know about the PR? I read through most of it and it all seems sensible to me. As long as it works in our containers I don't have too big of a worry about it. I'm gonna read through it again, but I think it's likely good to go.

**Review by gmmeyer — COMMENTED** [review]
adding a few more comments

**Review by olivielpeau — COMMENTED** [review]
Made a few comments, overall this looks good!

I think you also need to rename the directory `omnibus/package-scripts/datadog-agent6/` to `omnibus/package-scripts/agent/` (IIRC omnibus uses the project name to determine the correct path).

**Review by olivielpeau — COMMENTED** [review]
a few inline comments + a few general comments:
- `pkg/config/config_nix.go` still defines paths to `/etc/dd-agent`, we need to update those
- nit: could you fix the `FIXME` in the postrm script? (i.e. uncommenting the lines that remove the dd-agent user/group and remaining files during a `purge` of the deb pkg).

**Pull request merged**
