### PR TITLE
Remove all source `/root/.bashrc` using the honor entrypoint FF

### PR DESCRIPTION
**Pull request by KevinFairise2**
Reverts DataDog/datadog-agent#29004 and fix the issue.
I ran a full pipeline to make sure it does not break tests

### CODE REVIEW

**Comment by KevinFairise2** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by KevinFairise2** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by amenasria — APPROVED** [review]
LGTM ! Thanks for this banger

**Review by paulcacheux — APPROVED** [review]

**Review by FlorentClarret — APPROVED** [review]

**Comment by KevinFairise2** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by Pythyu — APPROVED** [review]

**Review by NouemanKHAL — APPROVED** [review]

**Review by L3n41c — APPROVED** [review]

**Review by duncanista — APPROVED** [review]

**Pull request merged**
