### PR TITLE
Add docker check

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

Adding a first and basic version of the docker check based on the one from integration-core. The main difference is that we heavily rely on the internal `tagger` and docker util package within the agent.

### Additional Notes

This is based on #585 and #586, you can skip the `pkg/util` and `pkg/tagger` folders from your review.

### CODE REVIEW

**Review by xvello — CHANGES_REQUESTED** [review]
Exiting times! Some improvement suggestions

**Review by xvello — DISMISSED** [review]
LGTM 🐳

**Review by xvello — DISMISSED** [review]
🐋 Here's another whale for you!

**Review by masci — APPROVED** [review]
👍

**Pull request merged**
