### PR TITLE
Update copyright to 2021

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Update copyright to 2021.

### Motivation

We’re in 2021 now !

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details that should be tested during the QA.

### CODE REVIEW

**Review by juliogreff — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by gbbr — APPROVED** [review]
🥳 Happy New Year

**Review by mfpierre — APPROVED** [review]

**Review by zippolyte — APPROVED** [review]
FWIW, we're using `Copyright 2019-Present Datadog, Inc.` in our libraries to avoid these kind of PR every year.
Not sure if that's applicable to you, just FYI 🙂

**Review by leeavital — APPROVED** [review]

**Comment by jeremy-lq** [comment]
> -Present

This format can be used across Datadog repos.

**Comment by ofek** [comment]
> > -Present
> This format can be used across Datadog repos.

That's what we did https://github.com/DataDog/integrations-core/pull/5384

**Comment by L3n41c** [comment]
Following the suggestion, I’ve replaced the `-2021` by `-present` in the copyright.

**Review by sgnn7 — APPROVED** [review]

**Review by jeremy-lq — APPROVED** [review]

**Review by ofek — APPROVED** [review]

**Pull request merged**
