### PR TITLE
[system-probe] Re-build conntrack cache on each call to getConnections

### PR DESCRIPTION
**Pull request by leeavital**
### What does this PR do?

cached_conntrack.go uses an LRU cache of netlink sockets. This means that we hold onto the last 128 (hardcoded) netlink sockets, even if the namespace is no longer being used. This causes problems with some CNIs that do not recognize the interface associated with the namespace as "free" to re-assign.

The fix is to have a new cached_conntrack between on each call to
/connections. This has a disadvantage of creating a new netlink
socket per namespace on run of /connections, but has the advantage of
releasing netlink sockets as soon as possible.

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details you may have to test your PR.

### CODE REVIEW

**Review by mbakht — APPROVED** [review]
- Is there a way to quickly add a test for this change?
- Is there any performance concern with creating a new netlink
socket per namespace on run of /connection?

**Comment by leeavital** [comment]
> Is there a way to quickly add a test for this change

`tracer_test.go` will exercise the code path that this touches, but I don't see a good place to add/assert that a new conntrack table is getting created.  I'm open to ideas.

I also ran the istio test scenario on one of our test clusters, and connections resolve as expected.

> Is there any performance concern with creating a new netlink socket per namespace on run of /connection?

I am a bit concerned, and the ultimate solution will be to move all this code to eBPF. For testing I ran the usual high load scenario we run and we were within the usual expected CPU/memory use. I also tried creating 20 replicas of a single deployment to test CPU use with a higher number of namespaces, and didn't see a noticable change in CPU use. 

the number of netlink connections should be low, since there should be one namespace per container, and the number of containers at any given time is usually in the mid 10s.

**Comment by lbernail** [comment]
Thanks a lot for fixing this quickly!

Note that the problem is likely to impact all CNI plugins but impacts will differ depending on the CNI handles delete calls:
- CNI Delete frees IP and removes interface: only problem is network namespace leak (no real impact except maybe under very high churn? I don't know what kernel limits are wrt number of nsids)
- CNI Delete frees IP and doesn't remove interface: netns + interface leak. Similar issue as above but we the number of interfaces managed by the kernel can also get very high
- CNI Delete does not free IP / remove interface (it relies on the namespace deletion for gc): this is the problem we had with our CNI plugin in chinook/general1. Depending on the plugin this can lead to failures to create new pods (because an IP considered free by CNI is considered in use by the kernel) or worse conflicting IPs in different namespaces, routing issues

Creating and deleting a new socket every time is definitely much safer

A few other ideas:
- could we have a toggle to enable/disable namespaced conntrack collection (if I understand correctly this is only valuable for istio)?
- we could also listen for net namespace deletion events and drop the associated netlink connection (probably more complex)

**Comment by leeavital** [comment]
@lbernail istio is a big motivator. The code is not written to treat the root namespace "specially" , so I'm hesitant to try to bolt that into this release. 

As you noted, hooking into netns delete events is harder (we'd have to look for the right events/system-calls to subscribe to and do thorough testing)

**Review by truthbk — APPROVED** [review]
Issue with the kitchen tests is unrelated to this PR. I am uneducated for the code changes but do approve we merge this into `master` and backport to `7.25.x` if everyone else is good with the changes. 🙇

**Pull request merged**
