### PR TITLE
usm: Remove enable_http_stats_by_status_code configuration

### PR DESCRIPTION
**Pull request by guyarb**
### What does this PR do?

Removing the configuration flag to simplify USM.
The removal does not change the behavior of USM which will continue to report status code granularity for HTTP requests

### Motivation

The configuration was enabled by default in 7.51 and became the default behavior for USM.
USM will continue to report status codes granularity for the HTTP transactions.

We want to remove unneeded configuration options and make USM simple.

### CODE REVIEW

**Review by gjulianm — APPROVED** [review]
LGTM for ebpf-platform files

**Review by emiliot — APPROVED** [review]

**Comment by GustavoCaso** [comment]
Looking at the codebase, I think there are few more place that reference `EnableHTTPStatsByStatusCode`

```
git grep EnableHTTPStatsByStatusCode

pkg/network/config/config.go:   // EnableHTTPStatsByStatusCode specifies if the HTTP stats should be aggregated by the actual status code
pkg/network/config/config.go:   EnableHTTPStatsByStatusCode bool
pkg/network/config/config.go:       EnableHTTPStatsByStatusCode: cfg.GetBool(join(smNS, "enable_http_stats_by_status_code")),
pkg/network/config/config_test.go:func TestEnableHTTPStatsByStatusCode(t *testing.T) {
pkg/network/config/config_test.go:      assert.True(t, cfg.EnableHTTPStatsByStatusCode)
pkg/network/config/config_test.go:      assert.True(t, cfg.EnableHTTPStatsByStatusCode)
pkg/network/protocols/http/statkeeper.go:       enableStatusCodeAggregation: c.EnableHTTPStatsByStatusCode,
pkg/network/usm/monitor_test.go:            cfg.EnableHTTPStatsByStatusCode = tt.aggregateByStatusCode
pkg/network/usm/monitor_tls_test.go:    cfg.EnableHTTPStatsByStatusCode = true
pkg/network/usm/monitor_tls_test.go:    cfg.EnableHTTPStatsByStatusCode = true
```

I think the ones in `pkg/network/usm/monitor_test.go` and `pkg/network/usm/monitor_tls_test.go` needs to be remove as well 😄

**Review by GustavoCaso — APPROVED** [review]
Looks great 🎉 

Still there are a few test failing in CI. 

For example, we need to remove this check https://github.com/DataDog/datadog-agent/blob/main/comp/metadata/inventoryagent/inventoryagentimpl/inventoryagent_test.go#L496

**Review by hestonhoffman — APPROVED** [review]

**Comment by hmahmood** [comment]
I am little wary of just deleting configs like this. No warning for users who have actually set this not to the default? Or was that really not supported/realistic in the past?

**Comment by guyarb** [comment]
> I am little wary of just deleting configs like this. No warning for users who have actually set this not to the default? Or was that really not supported/realistic in the past?

That's a good question - the reason why I'm immediately deleting without deprecation are that we can traverse the operation in the backend without any impact on the user.
Even today, users have the option to use `status_code` (i.e 203) and `status_class` (i.e 200). so no real impact on the experience of the user

**Review by hmahmood — APPROVED** [review]

**Pull request merged**
