### PR TITLE
Ensure AD subscription happens before scheduling

### PR DESCRIPTION
**Pull request by djmitche**
Without this change, on a heavily-loaded system, the ADListener might
not call sch.Register(..) before AD has gotten to the point of
scheduling configs -- leading to logs-agent missing configs.

This patch is temporary for 7.36, and makes some assumptions which are
true in that version:
 * ADListener is only ever instantiated once (for pkg/logs/schedulers/ad)
 * ADListener is instantiated before AD (this is the source of the bug)

### Additional Notes

I added panic() here to verify some assumptions that I'm _pretty sure_ are true in 7.36.  I'd like failures of those assumptions to be very obvious.  This won't be forward-ported to 7.37, so the panic's wont' stick around.

### Describe how to test/QA your changes

Start up an agent with a file config for logs, and verify that it tails the logfile.

Run `agent check load` and verify it doesn't panic.

Start up an agent in a container environment (k8s or docker) with DD_LOGS_AGENT_CONTAINER_COLLECT_ALL=true and start a container (`docker run -ti --rm bash`) and see that it gets logged (via `agent status`).

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by djmitche** [comment]
@vickenty confirmed that this works properly in a place where, due to small instances and high load, the logs-agent had previously been losing the race to register before configs were scheduled.

**Comment by djmitche** [comment]
And lo, the assumptions are _not_ true for the iot agent!

**Comment by djmitche** [comment]
(in fact, `agent check` fails even for the core agent)

**Review by gh123man — APPROVED** [review]

**Comment by djmitche** [comment]
(note that https://github.com/DataDog/datadog-agent/pull/11813 covers `main`, so this will not be forward-ported)

**Pull request merged**
