### PR TITLE
Start reworking container_collect_all

### PR DESCRIPTION
**Pull request by mnshdw**
### What does this PR do?

Remove container_collect_all from the config, start moving it to scanners.
Properly init and use dynamic sources in the agent status.

### CODE REVIEW

**Review by ajacquemot — COMMENTED** [review]
I left one comment, don't you think we should keep a check when starting the agent that asserts that there is at least one config set to start collection logs ?
e.g: `ENV_VARS > 0 || SOURCES > 0` ?

**Comment by mnshdw** [comment]
Yes we need to keep one.

**Comment by tmichelet** [comment]
is it expected that this has been merged despite the CI failing?

**Comment by tmichelet** [comment]
Ah sorry didn't realize it was not merged on master!

**Pull request merged**
