### PR TITLE
Pin k8s.io/klog@release-1.x

### PR DESCRIPTION
**Pull request by albertvaka**
### What does this PR do?

Pin k8s.io/klog@release-1.x to include https://github.com/kubernetes/klog/commit/4ad0115ba9e45c096d06a31d8dfb0e5bd945ec5f

### Motivation

Fix Windows Nano image.

### CODE REVIEW

**Comment by vboulineau** [comment]
Shouldn't it be a replace? (just asking)

**Comment by mx-psi** [comment]
I think you should merge master to update the Gitlab pipeline to see if the tests pass then. I have re-tried the failing jobs but they keep failing (seemingly from reasons unrelated to this PR changes)

**Review by mx-psi — APPROVED** [review]

**Comment by vboulineau** [comment]
@albertvaka Should we also try `nano` again for 7.21?

**Comment by albertvaka** [comment]
There's another blocker :( psutils isn't compatible with Windows Nano and we are waiting on this PR: https://github.com/giampaolo/psutil/pull/1768

**Pull request merged**
