### PR TITLE
Bump `golang.org/x/...` dependencies

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?
Bump `golang.org/x/...` dependencies.

### Motivation
Benefit from bugfixes.

### Additional Notes

Generated with the following command:
```sh
inv -e modules.for-each "go get golang.org/x/arch golang.org/x/crypto golang.org/x/lint golang.org/x/mod golang.org/x/net golang.org/x/sync golang.org/x/sys golang.org/x/term golang.org/x/text golang.org/x/time golang.org/x/xerrors golang.org/x/tools golang.org/x/exp"
inv tidy
```

### CODE REVIEW

**Review by davidor — APPROVED** [review]

**Review by vickenty — APPROVED** [review]

**Review by amenasria — APPROVED** [review]
LGTM as long as the CI passes

**Review by jszwedko — APPROVED** [review]
Approving @DataDog/agent-processing-and-routing owned files.

**Review by pducolin — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]
LGTM

**Review by jennchenn — APPROVED** [review]

**Review by kkhor-datadog — APPROVED** [review]

**Review by robertjli — APPROVED** [review]

**Review by moth-a — APPROVED** [review]
RC files LGTM

**Review by ichinaski — APPROVED** [review]

**Review by YoannGh — APPROVED** [review]

**Pull request merged**
