### PR TITLE
Nomad namespace

### PR DESCRIPTION
**Pull request by kung-foo**
### What does this PR do?

Adds Nomad namespace and datacenter tag extraction from Docker container environmental variables

### Motivation

I need the Normad namespace tag

### CODE REVIEW

**Comment by kung-foo** [comment]
I just found out you can also extract tags via the config var `docker_env_as_tags`, however, I think this PR still is valid since the other orchestrators have similar tags extracted (`swarm_namespace`, `rancher_stack`, etc).

**Review by vboulineau — APPROVED** [review]

**Review by ahmed-mez — COMMENTED** [review]
@kung-foo could you please rebase your PR?

**Comment by kung-foo** [comment]
> @kung-foo could you please rebase your PR?

done

**Comment by L3n41c** [comment]
Hello @kung-foo,
I’d like to apologise for the time it took to take your contribution into account.
Unfortunately, this PR has one more time conflicts to resolve. In order to not bother you with yet another rebase, I took the liberty to rebase your patch myself. I opened #9847 as I cannot update your PR.

**Comment by L3n41c** [comment]
This change was merged by #9847 in https://github.com/DataDog/datadog-agent/commit/5408d53227522c8199e728df52d6d08746805b41

**Comment by kung-foo** [comment]
@L3n41c no worries. I had actually forgotten about this PR :)

**Pull request closed without merging**
