### PR TITLE
[NDM][NDMII-2634]change the snmp_listener config name to autodiscovery

### PR DESCRIPTION
**Pull request by jedupau**
### What does this PR do?

Following [this PR]( https://github.com/DataDog/datadog-agent/pull/24644 ) we rename the snmp_listener name config to autodiscovery
This is not a breaking change because `network_devices.snmp_listener` was not released

### CODE REVIEW

**Review by FlorianVeaux — APPROVED** [review]
Let's make it clear in the PR description that this is not a breaking change because `network_devices.snmp_listener` was never released

**Review by AlexandreYang — APPROVED** [review]

**Review by TCheruy — APPROVED** [review]

**Review by Kaderinho — APPROVED** [review]
**❓ question:** ‏I don't know `snmp_listeners` and `autodiscovery` well but they seemed like completely different features to me. So is there any difference between these ?

**Review by cswatt — APPROVED** [review]
Docs-approved

**Pull request merged**
