### PR TITLE
Convert snmp subcommand to an app

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Converts the `agent snmp` command to an Fx App.

### Motivation

Top-down approach to componentization.

### Additional Notes

This PR is against a base branch containing #13699 and #13662.  Once those are merged, I'll change the base of this PR to `main` and rebase, but it can be reviewed in the interim.

### Describe how to test/QA your changes

Compare the output of the following commands before and after the changes in https://github.com/DataDog/datadog-agent/pull/13463 and https://github.com/DataDog/datadog-agent/pull/13716 to ensure no significant changes have occurred.

* `agent snmp`
* `agent snmp walk`
* `snmp walk 127.0.0.1 .1.3.6.1.2.1.1.5.0 -v 2 -C public -l noAuthNoPriv`
* `agent snmp walk 127.0.0.1 .1.3.6.1.2.1.25.1.4.0 -C public` (or equivalent working command-line; this works for a local snmpd install on Ubuntu)
* `agent snmp walk 127.0.0.1 .1.3.6.1.2.1.1.5.0 -u testy -a SHA-512 -A myauthphrase -x AES -X myprivphrase -v 3` (with `createUser testy SHA-512 myauthphrase AES myprivphrase` and `rouser testy authpriv -V systemonly` in the config files) 

Please also test the following flags to verify that they are interpreted correctly and not just applying defaults.

```
  -N, --context string            Set context name
  -r, --retries int               Set the number of retries (default 3)
  -t, --timeout int               Set the request timeout (in seconds) (default 10)
```

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by hush-hush — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]

**Comment by djmitche** [comment]
@pducolin asked me to hold off merging this until #13779 lands, at which point they will resolve the conflicts in this PR.

**Comment by djmitche** [comment]
Merge conflicts resolved (I had to do so anyway to rebase my topic branch).  @pducolin would you like to review now?

**Review by pducolin — APPROVED** [review]
Thank you for taking care of the rebase !

**Comment by djmitche** [comment]
@AlexandreYang I see you self-assigned this for review a week ago -- did you want to have a look?

**Review by AlexandreYang — APPROVED** [review]
LGTM, thanks for the refactoring.

**Pull request merged**
