### PR TITLE
[docs] adding agent memory troubleshooting 101 guide

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

Adds a basic 101 guide for agent memory behavior/leak troubleshooting.

### Motivation

Better developer docs when dealing with memory issues. 

### Other

[Rendered](https://github.com/DataDog/datadog-agent/blob/jaime/dev-memguide/docs/dev/agent_memory.md)

### CODE REVIEW

**Review by ofek — DISMISSED** [review]
The Python section matches what we discussed and is very thorough. 👍 from me

Excellent job here!

**Comment by l0k0ms** [comment]
Do you think it could be useful to move this to the documentation repository as a Guide in the Agent section ? It will benefit from the documentation website visibility and design.

**Review by olivielpeau — DISMISSED** [review]
Nice, thanks for putting this together!

just a nit to improve the page's visibility: could you add a link to this doc from https://github.com/DataDog/datadog-agent/blob/master/docs/dev/README.md ?

**Comment by sarina-dd** [comment]
Did a mass edit to fit within editorial guidelines (header retitling, tone, removal of emojis, etc.) Feel free to review again and I can do one final batch of edits before merge. 👍

**Review by olivielpeau — APPROVED** [review]

**Pull request merged**
