### PR TITLE
Apply go1.17 gofmt to all files

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Adds `//go:build`-formatted build directives where only `// +build` directives existed before.

### Motivation

These are otherwise appearing in PRs such as [this one](https://github.com/DataDog/datadog-agent/pull/10600#pullrequestreview-857281429).

### Additional Notes

I ran go1.17's `gofmt` over the entire codebase.  This appears to have triggered `govet` to have a second look at some `tests/` files, which apparently haven't been changed in a while.  If CI complains, then I'll make the necessary changes to keep govet happy, but otherwise I'd prefer to keep this PR focused.

### Possible Drawbacks / Trade-offs

None.  We'll be upgrading to go1.17 soon, so this doesn't hurt anyway.   This is also easy to rebase if I don't manage to merge it first when the freeze lifts :)

### Describe how to test/QA your changes

Tested by CI.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by brycekahle** [comment]
The files in `pkg/ebpf/bytecode/runtime` are generated, and thus would lose your changes the next time they are generated with `go generate`.

**Comment by djmitche** [comment]
> The files in `pkg/ebpf/bytecode/runtime` are generated, and thus would lose your changes the next time they are generated with `go generate`.

Ah, good point.  Those will get updated when they're generated from go1.17, then.

**Review by brycekahle — APPROVED** [review]

**Review by albertvaka — APPROVED** [review]
Github hangs trying to show the 885 modified files 💥 😂

**Review by clamoriniere — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by nammn — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]

**Review by ppknap — APPROVED** [review]

**Comment by djmitche** [comment]
(rebased onto latest main, with the first commit regenerated)

**Review by albertvaka — APPROVED** [review]

**Pull request merged**
