### PR TITLE
[E2E] Mark TestKindSuite as flaky

### PR DESCRIPTION
**Pull request by Pythyu**
### What does this PR do?

Mark TestKindSuite as flaky

### CODE REVIEW

**Review by pducolin — APPROVED** [review]

**Review by clamoriniere — COMMENTED** [review]
have we identified the PR that have introduced the flakiness?
if yes can we revert it instead of flagging this test as flaky?

**Comment by Pythyu** [comment]
Force merging because of the failure rate is increasing 7 out of 10 last pipelines

**Pull request merged**
