### PR TITLE
Stop double scrubbing json payloads

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Stop double scrubbing the input in the `ScrubJSON` Scrubber method.

### Motivation

It uses CPU and memory, and shouldn't improve security.

### Describe how to test/QA your changes

It's tricky to be sure nothing can break from this change, I added unit tests to increase confidence.

### CODE REVIEW

**Review by hush-hush — APPROVED** [review]

**Comment by pgimalac** [comment]
Merge queue failed due to codecov timeout, retrying

**Pull request merged**
