### PR TITLE
[ASCII-1628] Make the api component a go module

### PR DESCRIPTION
**Pull request by jeremy-hanna**
### What does this PR do?

This PR relates to the work of moving the registration of api endpoints to the relevant components:
* https://github.com/DataDog/datadog-agent/pull/24045
* https://github.com/DataDog/datadog-agent/pull/24872
* https://github.com/DataDog/datadog-agent/pull/25234
* https://github.com/DataDog/datadog-agent/pull/25336

The remaining api endpoints are from components that are go modules and require the api component to also be a module to import the types. This PR does just that, by removing the final import of the StartServer argument we can make the component interface and EndpointProvider types + constructor a go module for the remaining components to import and use.

### Describe how to test/QA your changes
* we have e2e tests for the api component routes so that is covered
* This touches the jmx build and should be tested separately

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
👍 for @DataDog/agent-processing-and-routing files.

**Review by davidor — APPROVED** [review]
:+1: For container-platform files (the diff is just some imports)

**Review by vickenty — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]
LGTM

**Review by alopezz — APPROVED** [review]

**Review by purple4reina — APPROVED** [review]

**Review by chouetz — APPROVED** [review]

**Review by FlorentClarret — APPROVED** [review]

**Pull request merged**
