### PR TITLE
remove gopacket import in agent/process-agent

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

Reorganizes the NDM traceroute code to not import `github.com/google/gopacket` into a binary, unless it is needed.

### Motivation

The `github.com/google/gopacket` dependency has several large fixed allocations that can take up memory, even if not used. This is part of a larger effort to reduce the RSS and binary size of the agent processes.

### Describe how to test/QA your changes

Code was only reorganized not functionally changed, so existing automated tests is sufficient.

### CODE REVIEW

**Comment by akarpz** [comment]
looks like this may not be working on windows?

**Review by jmw51798 — APPROVED** [review]

**Comment by scottopell** [comment]
Clear win here, thanks for the contribution
image

**Comment by brycekahle** [comment]
> looks like this may not be working on windows?

Unrelated. One known flake and the other two failing jobs are also failing on `main`.

**Review by akarpz — APPROVED** [review]

**Pull request merged**
