### PR TITLE
[serverless] serverless cold start perf: enlarge sample & print

### PR DESCRIPTION
**Pull request by goxberry**
### What does this PR do?

Given the importance of cold start latency to Serverless Agent performance, gathering a larger data set would enable us to better estimate quantile statistics, as well as estimate the accuracy of those estimates (e.g., using a confidence interval).

This pull request increases the iteration count of the cold start container loop from 10 to 301 so that:

- this test still runs in an hour or less (hopefully)

- we can plot a histogram of the raw data to better understand the distribution of cold start times

- the data set is large enough to use bootstrapping methods to construct confidence intervals on the median

In addition, this pull request should print the raw cold start data in a ~~CSV-like~~ space-delimited format on a single line so it's easy to import into a `numpy` array for exploratory data analysis.

### Motivation

Improve understanding of how PRs affect cold starts in practice. Explore potentially incorporating uncertainty in the estimated median cold start time into the serverless cold start performance test.

### Additional Notes

Larger data sets (like 1,000+) would be better, resources permitting. Under some mild assumptions[^1], as the sample size approaches infinity, the distribution of the sample median approaches a normal distribution[^2], which can be used to compute confidence intervals[^3].

[^1]: Assuming the cold start latency could be modeled as an absolutely continuous random variable, and samples are independently and identically distributed.

[^2]: Google "asymptotic normality median", or see chapter 21 of A. W. van der Vaart, *Asymptotic Statistics*, Cambridge University Press, 1998.

[^3]: In practice, one would use bootstrapping to approximate the distribution of medians, which is sort of like computing a correction to this asymptotic result. T. Hesterberg, "What teachers should know about the bootstrap: resampling in the undergraduate statistics curriculum", [arXiv:1411.5279](https://arxiv.org/abs/1411.5279) is a nice introduction to why this approach is useful. Rigorous mathematical justification for this argument can be found in Chapter 3 of P. Hall, *The Bootstrap and Edgeworth Expansion*, Springer, 1992. The "correction" I allude to is the second (and sometimes third) term in an Edgeworth expansion about a normal distribution.

### Possible Drawbacks / Trade-offs

Increasing the sample size used to compute median cold start time means that the serverless perf test will run longer. Given that other functional tests (e.g., the regression detector tests) have an SLO of around an hour, I used that SLO as a guideline when increasing that sample size.

### Describe how to test/QA your changes

Look at the CI output for this test.

### CODE REVIEW

**Comment by goxberry** [comment]
Curious if there's additional precision in measuring startup times, given that other output in the CI logs lists timings in milliseconds to three decimal places.

**Comment by goxberry** [comment]
Gave up on separating elements of the raw data array by commas; a space-delimited string will work just as well, and printing the raw data to console in some format is better than not printing it at all.

An example job using 301 iterations took 55 minutes, 21 seconds, meeting the 1 hour target, and also had some interesting outliers on the high end.

**Review by duncanpharvey — APPROVED** [review]
LGTM! If we want to increase the iteration count beyond 301 I think we should explore methods to parallelize the invocations

**Pull request merged**
