### PR TITLE
[snmp] Suggest single quote for community string

### PR DESCRIPTION
**Pull request by AlexandreYang**
Related PR: https://github.com/DataDog/integrations-core/pull/9742

### What does this PR do?

- Use single quote in auto_conf.yaml
- Recommend using single quote for community_string

### Motivation

If community string contain special character the actual community string being use to reach the device might be wrong.

### Describe how to test your changes

- Check that `auto_conf.yaml` works as before (use snmp_listener config as described here https://docs.datadoghq.com/network_monitoring/devices/setup?tab=snmpv2)

### Checklist

- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

### CODE REVIEW

**Review by gmarabout — APPROVED** [review]
LGTM

**Review by djmitche — COMMENTED** [review]
Is a `'` character in the community string possible?

**Comment by AlexandreYang** [comment]
> Is a `'` character in the community string possible?

Yes, that's possible, in this case, user can escape using double single quote like this `''`:

```
instances:
  - ip_address: '1.2.3'
    community_string: 'abc''123'
```


Note: reverted the change to `cmd/agent/dist/conf.d/snmp.d/auto_conf.yaml`, it's not needed since we only have values like %%xxxx%% that doesn't contain any special char.

**Comment by djmitche** [comment]
Ah, I was reading the `%%..%%` strings as template tokens -- if those are just instructions for humans, then there's no issue.

**Review by jtappa — APPROVED** [review]
👍🏻 from docs team

**Comment by AlexandreYang** [comment]
> Ah, I was reading the %%..%% strings as template tokens -- if those are just instructions for humans, then there's no issue.

@djmitche They are actually template tokens, but AFAIK the interpolation is done one the value `%%host%%`, not the entire document. 

https://github.com/DataDog/datadog-agent/blob/be59410d2c6d6321289287d8563e2c17493f369f/pkg/autodiscovery/configresolver/configresolver.go#L35-L51

So, in the change made previously that changes double quote to single quote in `auto_conf.yaml` shouldn't have any effect (reverted https://github.com/DataDog/datadog-agent/pull/8659/commits/c45d80df6f7ed376af1b9be3e17f8916f0e1b6de).

**Comment by AlexandreYang** [comment]
> Ah, I was reading the `%%..%%` strings as template tokens -- if those are just instructions for humans, then there's no issue.

@djmitche They are actually template tokens, after some testing, it seems, we indeed have an issue with the use of quotes. I think this is the code responsible for that:
https://github.com/DataDog/datadog-agent/blob/be59410d2c6d6321289287d8563e2c17493f369f/pkg/autodiscovery/configresolver/configresolver.go#L35-L51
So, in the change made previously that changes double quote to single quote in `auto_conf.yaml` shouldn’t have any effect (reverted https://github.com/DataDog/datadog-agent/pull/8659/commits/c45d80df6f7ed376af1b9be3e17f8916f0e1b6de).

After some testing, it seems that AD template like this one

```
ad_identifiers:
  - snmp
init_config:
instances:
  -
    ## @param ip_address - string - optional
    ## The IP address of the device to monitor.
    #
    ip_address: "%%host%%"

    ## @param community_string - string - optional
    ## Only useful for SNMP v1 & v2.
    #
    community_string: "%%extra_community%%"
```

will lead to yaml syntax error, if `extra_community` contain double quote. I created II-448 ticket to investigate that.

**Review by djmitche — APPROVED** [review]
What remains on this PR looks fine (just comment changes)

**Pull request merged**
