### PR TITLE
WIP: Create a badger based context-resolver

### PR DESCRIPTION
**Pull request by iksaif**
The idea here is to use [badger](https://dgraph.io/docs/badger/) to store contexts.

It came from the idea of using a trie to keep contexts (because metrics usually share the same prefix, and tags usually share the same keys) and realising that getting the context out of the tree was probably not going to be much faster than a compression mechanism like snappy.

So instead the idea is to use a compressed kv store. This PR starts in diskless mode but we could eventually enable disk to reduce memory usage at the cost of disk and slightly increased latency (but there's a block cache ..)

Let's see what it can get us!

### CODE REVIEW

**Review by djmitche — COMMENTED** [review]
If I understand this correctly, it uses badger mainly as a more space-efficient, if slower in absolute terms, replacement for a map.

Paging to disk is an option in the future, but my concern there is that we are likely cycling through nearly the entire set of contexts a few times per minute -- there is no "hot set" that would let LSM's efficiency shine.  Even so, the possibility to page to disk instead of OOMing sounds attractive.

There are a number of proposals and PRs for this particular component of the agent right now.  I wonder if it would be good to get all of those written down in one place and see how they fit together.  We could talk about adding a few layers of abstraction, too (such as the interface added in this PR).

**Comment by iksaif** [comment]
> If I understand this correctly, it uses badger mainly as a more space-efficient, if slower in absolute terms, replacement for a map.

Yes
 
> Paging to disk is an option in the future, but my concern there is that we are likely cycling through nearly the entire set of contexts a few times per minute -- there is no "hot set" that would let LSM's efficiency shine. Even so, the possibility to page to disk instead of OOMing sounds attractive.

I'll try to summarise my thinking here: We get two kind of clients, the dumbs ones that are just sending metrics whenever (a), and the smart ones that have client side aggregation (b)

For (a) there is a hot set of metric, and it would be useful to keep a smaller in-memory non-compressed fixed-size LRU cached.
For (b) you are going to get all the contexts observed every 5 or 10sec, and you are not going to aggregate much so keeping the contexts across periods of 5/10sec is not really useful.

There are multiple techniques to compress the set, and I think we really want to compress it and only optionally page it out to disk, because it's going to be faster and likely use the same amount of memory / memory bandwidth / cpu anyway.  The simplest thing seems to just use a compressed embedded k/v store with optional page-out features (= that's how I came up with badger).

Now as you said, it's going to slow us down, but (a) have a hot set and (b) is going to cycle through all metrics each periods. In both cases having a smaller fixed size (50M?) LRU cache is going to be enough.


> There are a number of proposals and PRs for this particular component of the agent right now. I wonder if it would be good to get all of those written down in one place and see how they fit together. We could talk about adding a few layers of abstraction, too (such as the interface added in this PR).

Doing a first round of abstraction + writing an offline benchmark would be great to help us all explore options.

**Comment by iksaif** [comment]
Small addition to above: badger does have an uncompressed block cache, which maybe might be useful here (or maybe not 🤷 )

**Comment by djmitche** [comment]
> Doing a first round of abstraction + writing an offline benchmark would be great to help us all explore options.

I think writing a benchmark is getting pretty far ahead of things :)

The main point of contention I'm thinking about is that @vickenty and others have been working on de-duplicating storage of tagsets, using the hashes that must be computed anyway.  That seems a likely route to save a lot of RAM in the common case where bunches of metrics all have the same tags.  Even deduplication in pairs (e.g., metrics `foo.hot` and `foo.cold` have the same tags) is equivalent to 50% compression.  But, I think such deduplication would be incompatible with a k/v store like this.

We've also talked about (and I'm sure this list is incomplete):
* using tag hashes computed on the dogstatsd client
* caching un-parsed tag strings in the dogstatsd server, along with their hash
* pre-computing hashes for subsets of the final tag set, such as for DD_TAGS; and taking advantage of the fact that hash(tagsetA ∪ tagsetB) = hash(tagsetA) ⊕ hash(tagsetB) iff tagsetA and tagsetB are disjoint.

My thinking is, rather than making individual efforts and justifying each one with benchmarks, we should think about the overall effect from a more theoretical perspective, create a new design, and then optimize and measure the performance of its implementation.  We may even realize that we can adaptively switch implementations depending on the nature of the data we're handling (as we already do for deduplication of tags).

**Comment by iksaif** [comment]
> My thinking is, rather than making individual efforts and justifying each one with benchmarks, we should think about the overall effect from a more theoretical perspective, create a new design, and then optimize and measure the performance of its implementation. We may even realize that we can adaptively switch implementations depending on the nature of the data we're handling (as we already do for deduplication of tags).

I was thinking of having an offline benchmark that can work at a level abstract enough that it can allow us to test the various approaches. 

This PR was just a way to get some datapoints with brute force block compression instead of fine-tuned hand-crafted compression, the goal was certainly not to merge it :)

**Pull request closed without merging**
