### PR TITLE
[EBPF] Simplify suggested test command in KMT

### PR DESCRIPTION
**Pull request by gjulianm**
### What does this PR do?

Simplify the suggested `kmt.test` command so that if all children of a parent test failed, only that parent is included in the test command.

### CODE REVIEW

**Review by usamasaqib — APPROVED** [review]

**Comment by gjulianm** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
