### PR TITLE
pkg/ebpf: remove pointer from DataEvent usage

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

This PR removes one indirection in `DataEvent` usage, removing the need to allocate DataEvent separately to the channel already existing allocation.

[Example profile](https://app.datadoghq.com/profiling/explorer?query=service%3Asystem-probe%20version%3A_7_57_0_rc.3__259ed08_&agg_m=count&agg_m_source=base&agg_t=count&cols=timestamp%2Cservice%2C%40metrics.core_cpu_cores%2C%40metrics.core_alloc_bytes_per_sec%2Cversion%2Chost&event=AgAAAZGOPHeh71Lt1wAAAAAAAAAYAAAAAEFaR09QSGZLQUFEN0NEZ25ESmQ0WEFBQQAAACQAAAAAMDE5MThlNDAtZDgyMC00MThjLWI4NTctNzQ1YzQ3MzA2ZWQ4&my_code=disabled&profile_type=alloc-size&profileId=AZGOPHfKAAD7CDgnDJd4XAAA&refresh_mode=paused&stream_sort=%40metrics.core_alloc_bytes_per_sec%2Cdesc&viz=stream&from_ts=1724666694529&to_ts=1724670294529&live=false) where the huge amount of allocation is visible

### CODE REVIEW

**Comment by brycekahle** [comment]
Do you have a profile with your change? I would still expect an allocation since that is a buffered channel, and is essentially escaping to the heap.

**Comment by paulcacheux** [comment]
Here is a list of the profiles I collected deploying this on a small staging clusters. https://ddstaging.datadoghq.com/profiling/explorer?query=service%3Asystem-probe%20kube_cluster_name%3Astingchameleon%20version%3A_7_58_0_devel_git.117.2d69cd4_2d69cd4_%20&agg_m=count&agg_m_source=base&agg_t=count&cols=timestamp%2Cservice%2C%40metrics.core_cpu_cores%2C%40metrics.core_alloc_bytes_per_sec%2Cversion%2Chost%2C%40metrics.go_lifetime_heap_bytes&fromUser=true&my_code=disabled&refresh_mode=paused&stream_sort=timestamp%2Cdesc&viz=stream&from_ts=1724603078602&to_ts=1724689478602&live=false

I was not able to find one that showed the same behavior. My understanding is that this change will allow the `DataEvent` object to be directly copied from the stack to the channel buffer, without going through the heap at all

**Comment by brycekahle** [comment]
Do you have a direct A/B comparison under the same approximate workload so we can see the direct effect of this change? Even the load testing env would be OK. This is pretty fundamental, so trying to make sure there are no surprises.

**Comment by paulcacheux** [comment]
[Here is a compare profile](https://ddstaging.datadoghq.com/profiling/comparison?query=service%3Asystem-probe%20kube_cluster_name%3Astingchameleon%20host%3Ai-0c16b9de860776759%20&agg_m=count&agg_m_source=base&agg_t=count&cols=timestamp%2Cservice%2C%40metrics.core_cpu_cores%2C%40metrics.core_alloc_bytes_per_sec%2Cversion%2Chost%2C%40metrics.go_lifetime_heap_bytes&compare_end_A=1724842205398&compare_query_A=service%3Asystem-probe%20kube_cluster_name%3Astingchameleon%20host%3Ai-0c16b9de860776759%20version%3A_7_57_0_rc.1__fa72fd1_%20&compare_query_B=service%3Asystem-probe%20kube_cluster_name%3Astingchameleon%20host%3Ai-0c16b9de860776759%20version%3A_7_58_0_devel_git.237.e2c41e7_e2c41e7_%20&compare_start_A=1724827805398&compare_start_B=1724852850430.4832&compareValuesMode=absolute&fromUser=true&my_code=disabled&op_filter=recordhandler&profile_type=alloc-size&refresh_mode=paused&stream_sort=%40metrics.core_alloc_bytes_per_sec%2Cdesc&viz=flame_graph&from_ts=1724842205398&to_ts=1724856605398&live=false)

**Review by brycekahle — APPROVED** [review]

**Pull request merged**
