### PR TITLE
remove system-probe linux kitchen tests

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

- remove system-probe linux kitchen tests
- add Amazon Linux 2023 to KMT

### Motivation

system-probe **linux** testing with kitchen is now deprecated, with KMT taking its place.

### Additional Notes

system-probe **windows** testing remains

https://datadoghq.atlassian.net/browse/EBPF-479

### CODE REVIEW

**Review by chouetz — APPROVED** [review]

**Review by chouquette — APPROVED** [review]
LGTM for BaRX owned file

**Review by usamasaqib — APPROVED** [review]
Looks good. Just a few questions.
1) Do we want to remove entries from the platforms.json file used by kitchen?
2) Are there no distributions we want to continue testing in kitchen? Redhat?

**Comment by brycekahle** [comment]
> 1. Do we want to remove entries from the platforms.json file used by kitchen?

Some of them are in-use by other kitchen tests and it doesn't hurt to keep them there for now.

> 2. Are there no distributions we want to continue testing in kitchen? Redhat?

CentOS is equivalent from a kernel compatibility perspective.

**Pull request merged**
