### PR TITLE
use builtin min and max functions

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

use builtin `min` and `max` functions

### Motivation

Reduce duplicated code from builtin functions.

### Additional Notes

Available since Go 1.21.0

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
👍 for files owned by @DataDog/agent-processing-and-routing

**Review by guyarb — APPROVED** [review]
Reviewed USM only files

**Review by hush-hush — APPROVED** [review]
:ok_hand:

**Review by rayz — APPROVED** [review]

**Review by hmahmood — APPROVED** [review]

**Review by ichinaski — APPROVED** [review]

**Review by richl-dd — APPROVED** [review]

**Pull request merged**
