### PR TITLE
Reschedule file tailer on next pipeline channel

### PR DESCRIPTION
**Pull request by gh123man**
### What does this PR do?

When a log file rotates, it would land on the same logs pipeline instance as the rotated file. 
If the rate of logs from this source is at or near the agent limits, the agent might fail to catch up on the rotated file. 
This change schedules the next tailer on a different pipeline. If the agent has additional resources it will be able to more effectively catch up on the rotated file. As a result the agent can handle larger spikes of log load and higher peak rates. 

### Motivation

Performance optimization

### Describe how to test/QA your changes

There should be no functional change. But it's worth checking the benchmark environment: 
- On the RC build - assert that `datadog.agent.logs.bytes_missed` is zero
- Functionality is validated via SMP run on PR.

### CODE REVIEW

**Review by blt — APPROVED** [review]

**Review by vickenty — APPROVED** [review]
Nothing wrong with the change, but I wonder if this makes it more likely that the remainder of the rotated file will appear in mixed order with the messages from the newer file?

**Comment by gh123man** [comment]
@vickenty 

> Nothing wrong with the change, but I wonder if this makes it more likely that the remainder of the rotated file will appear in mixed order with the messages from the newer file?

Good callout. TBH I think this was possible before as well since two tailers (each with their own read goroutine) would be writing to the same channel - the logs could still become interlaced. So yes more likely that this will happen but only because we are able to process more logs. (I don't think the behavior regresses in any way)

**Pull request merged**
