### PR TITLE
Fix GCE hostname logic to pull in short name

### PR DESCRIPTION
**Pull request by dixonscottr**
### What does this PR do?

Updates the GCE `GetHostname()` function to pull in the short hostname to be consistent with the GCE hostname [logic of Agent 5](https://github.com/DataDog/dd-agent/blob/a7d1031b62301cd6e7c01cc50efbdf57b65c93ec/utils/cloud_metadata.py#L89)

### Motivation

Customer pointed out inconsistencies in GCE hostnames after upgrading to Agent 6

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by olivielpeau — CHANGES_REQUESTED** [review]
At first glance I don't think we should merge this.

The recommended behavior of Agent 5 since 5.5.0 is to use the full hostname provided by GCE to avoid hosts from different GCE projects from reporting with the same hostname. See https://github.com/DataDog/dd-agent/pull/1737, which introduced the `gce_updated_hostname` flag in the config with a recommended value of `true`.

If using the "short" hostname is still absolutely needed for some users, let's identify why and _maybe_ re-introduce a similar config flag which would by default report the "better" hostname, i.e. the full hostname; and could be disabled by users to report the short hostname.

I would love not having to re-introduce it though, since using the full hostname makes sense and it's therefore a breaking change that we have to do at some point.

**Comment by irabinovitch** [comment]
CC @DanielLanger for his thoughts. but I agree long host names make more sense. who short host names make sense as a host alias?

**Comment by andyshinn** [comment]
If there was a way to keep the long hostname as default but have it recognize previous Agent 5 hosts that were using the short alias (so that they end up as the same logical host in Datadog when upgrading) this would be fine. But this could also have ramifications if users already had separate hosts using long and short hostnames.

**Comment by olivielpeau** [comment]
@andyshinn: unfortunately it's not possible to alias hosts in the way you described: Agents sending 2 different hostnames create 2 different hosts on Datadog, and there's no way to "re-alias" them from the app. So, as you noticed, the "new" host does not have the historical data of the "old" host...

**Comment by olivielpeau** [comment]
Synced with @DanielLanger on this. Since we want the long GCE hostnames to be used in the long term, it makes sense to make the breaking change with Agent v6. #1472 adds docs to make this breaking change visible to users considering an upgrade to v6.

**Pull request closed without merging**
