### PR TITLE
[pipeline/build] fix android build

### PR DESCRIPTION
**Pull request by remeh**
### What does this PR do?

Fixes the android build.

  - gomobile must be run with go modules disabled, see https://go-review.googlesource.com/c/mobile/+/167659/
  - systemd has been enabled for all build but that's causing issue with the android port
  - part of the code from the system-probe / ebpf should not be built while building the android port

### CODE REVIEW

**Review by albertvaka — APPROVED** [review]
Neat and tidy PR, thanks a lot @remeh!

**Review by olivielpeau — APPROVED** [review]
Thanks!

What's the reason we only run the android build on triggered pipelines? Running it on every pipeline would likely make it easier/faster to catch build regressions.

**Comment by albertvaka** [comment]
@olivielpeau it's the opposite we have `skip_when_triggered` which means it runs always except on triggered pipelines, so it doesn't prevent a release pipeline from succeeding (since we don't release Android).

**Comment by olivielpeau** [comment]
oh, thanks for the correction @albertvaka, I was looking at the `gitlab-ci.yml` that was used when we upgraded to Go 1.13, but since then you merged https://github.com/DataDog/datadog-agent/pull/5250 indeed. All good, thanks!

**Review by leeavital — APPROVED** [review]

**Pull request merged**
