### PR TITLE
gitlab: use newer builders images

### PR DESCRIPTION
**Pull request by remeh**
APR-94

### What does this PR do?

Fixes `unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000` when using the `libsds_go.so` library on rpm-arm64.

### Describe how to test/QA your changes

* Validate that this warning doesn't appear in the `tests_rpm-arm64` anymore.

### CODE REVIEW

**Review by CelianR — APPROVED** [review]

**Comment by remeh** [comment]
Done by https://github.com/DataDog/datadog-agent/pull/26360 already.

**Pull request closed without merging**
