### PR TITLE
Download VM images using curl

### PR DESCRIPTION
**Pull request by usamasaqib**
### What does this PR do?
This PR pulls in [changes](https://github.com/DataDog/test-infra-definitions/pull/637) from test-infra-definitions to use curl to download VM images instead of aria2c.

### Motivation
Described in https://github.com/DataDog/test-infra-definitions/pull/637

### CODE REVIEW

**Comment by pducolin** [comment]
Including the testinfra changelog: https://github.com/DataDog/test-infra-definitions/compare/180d0c3c5d44...dba45dd5d1f1

I would like to automate this, in the meantime can you add the changelog on next bumps ? It helps investigations in case of issues

**Review by pducolin — APPROVED** [review]

**Comment by usamasaqib** [comment]
> Including the testinfra changelog: [DataDog/test-infra-definitions@180d0c3...dba45dd](https://github.com/DataDog/test-infra-definitions/compare/180d0c3c5d44...dba45dd5d1f1)
> 
> I would like to automate this, in the meantime can you add the changelog on next bumps ? It helps investigations in case of issues

I can add for this one as well. Is there an example PR on how to do this properly?

**Comment by pducolin** [comment]
Looks like container tests are broken by this bump, let me check

**Comment by pducolin** [comment]
> I can add for this one as well. Is there an example PR on how to do this properly?

What I usually do is I add manually the github compare, see `https://github.com/DataDog/test-infra-definitions/compare/180d0c3c5d44...dba45dd5d1f1`, where I use 

```
`https://github.com/DataDog/test-infra-definitions/compare/before_sha...after_sha`
```

**Comment by usamasaqib** [comment]
> ks like container tests are broken by this bump, let me check

Hey @pducolin any update on this?

**Comment by pducolin** [comment]
> Hey @pducolin any update on this?

It was a dependency temporarily broken, I missed updating here, we communicated on slack. I will re-run those jobs for you

**Comment by usamasaqib** [comment]
Closed because test-infra is being updated by https://github.com/DataDog/datadog-agent/pull/23336

**Pull request closed without merging**
