### PR TITLE
Enable secrets in Cluster Agent config

### PR DESCRIPTION
**Pull request by xornivore**
### What does this PR do?

Enable secrets management in config for Cluster Agent.

### Motivation

Users would like to use secrets in config for Cluster Agent via the `ENC[]` notation.

### CODE REVIEW

**Review by CharlyF — COMMENTED** [review]
Can you just add a released note (in the specific dca folder) ? This is good otherwise.

**Comment by clamoriniere** [comment]
I think this PR should also update the cluster-agent dockerfile in order to add the `secret-helper` script  https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/agent/secrets-helper like it is done for the `agent`: https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/amd64/Dockerfile#L124

**Review by clamoriniere — CHANGES_REQUESTED** [review]
I think this PR should also update the cluster-agent dockerfile in order to add the secret-helper script https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/agent/secrets-helper like it is done for the agent: https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/amd64/Dockerfile#L124

**Comment by xornivore** [comment]
👋 @clamoriniere @CharlyF this should be good for a second round of reviews - I've added the secrets helper in the DCA image.

**Comment by xornivore** [comment]
Closing in favor of #4639 which does not require pulling in the python dependency in the DCA image.

**Pull request closed without merging**
