### PR TITLE
Reduce uploads to dd-ci-artefacts-build-stable

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

Stop uploading deb & OCI packages to `dd-ci-artefacts-build-stable`

### Motivation

The OCI artifacts are never read from, which means we were uploading ≃800MB for no purpose in each pipeline.
The DEB packages are used when building containers, but always in the same pipeline, so we can simplify things by relying on gitlab artifacts, and reduce a bit the amount of S3 buckets we rely on.

BARX-612

### Possible Drawbacks / Trade-offs

:warning: This means that we won't be able to rebuild an image for a given pipeline by simply restarting the job.
For pipeline containers, that seems OK.
For RCs/releases, this might be problematic. We would need to introduce a fallback to download from `dd-release-artifacts` for such pipelines.

### CODE REVIEW

**Comment by chouquette** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by chouquette** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by alopezz — APPROVED** [review]
🆒 👍 Looks good let's hope the pipelines like it too :)

**Pull request merged**
