### PR TITLE
[invoke] Test task refactor - Part 1

### PR DESCRIPTION
**Pull request by KSerrania**
### What does this PR do?

Removes the `--flavors` (list) option of `inv test`, and replaces it with the `--flavor` (string) option, that only allows specifying one flavor.
Removes code to handle multiple flavors.
Simplifies test and lint results processing: we don't need a complex per-phase and per-flavor dictionary anymore, since each task only targets one flavor, and does either linting or testing, not both.

### Motivation

Simplify the `inv test` task. I believe there there are no uses of `inv test` with multiple flavors specified, so it is not worth keeping overly complex code for this feature.

### Additional Notes

n/a

### Possible Drawbacks / Trade-offs

n/a

### Describe how to test/QA your changes

Verify that all lint and test tasks in CI still work, and do test what they are expected to test.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Everything looked reasonable to me, did we leave the flag "deprecated" for long enough (if we have any sort of policy around that...)

**Comment by KSerrania** [comment]
> Everything looked reasonable to me, did we leave the flag "deprecated" for long enough (if we have any sort of policy around that...)

It has been here since November 2023. I'll merge this during the first week of February, so I think that was enough advance notice.

**Review by KevinFairise2 — APPROVED** [review]

**Comment by KSerrania** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Review by chouetz — APPROVED** [review]

**Pull request merged**
