### PR TITLE
DOCS-2215 Add @env variables to datadog.yaml

### PR DESCRIPTION
**Pull request by ruthnaebeck**
### What does this PR do?

- Add @env variables to datadog.yaml:

```
DD_APM_CONFIG_APM_DD_URL
DD_APM_CONFIG_APM_NON_LOCAL_TRAFFIC
DD_APM_CONFIG_ENABLED
DD_APM_CONFIG_ENV
DD_APM_CONFIG_EXTRA_SAMPLE_RATE
DD_APM_CONFIG_IGNORE_RESOURCES
DD_APM_CONFIG_LOG_FILE
DD_APM_CONFIG_LOG_THROTTLING
DD_APM_CONFIG_MAX_CPU_PERCENT
DD_APM_CONFIG_MAX_EVENTS_PER_SECOND
DD_APM_CONFIG_MAX_MEMORY
DD_APM_CONFIG_MAX_TRACES_PER_SECOND
DD_APM_CONFIG_RECEIVER_PORT
DD_APM_CONFIG_RECEIVER_SOCKET
DD_APM_CONFIG_REPLACE_TAGS
```
- Update a few docs links

### Motivation

- Documentation OKR
- [RFC](https://github.com/DataDog/architecture/blob/master/rfcs/agent-env-var-docs/rfc.md)

### Additional Notes

Variables will be added in small batches.

### Describe how to test your changes

N/A

### Checklist

- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

### CODE REVIEW

**Review by sgnn7 — APPROVED** [review]

**Review by kayayarai — APPROVED** [review]

**Comment by ogaca-dd** [comment]
I think we can add a test that failed when the env variable is not defined (or not correctly defined). Do you think it would be useful?

**Comment by ruthnaebeck** [comment]
> I think we can add a test that failed when the env variable is not defined (or not correctly defined). Do you think it would be useful?

Yep, probably after we get done adding them.

**Comment by gbbr** [comment]
I don't think it's a good idea to merge PRs regarding documentation without approval from engineers. All of those environment variables are wrong. It's `DD_APM_` not `DD_APM_CONFIG_`. The same for this PR: https://github.com/DataDog/documentation/pull/11684. Those env. vars. don't exist. Customers ended up creating tickets due to bad documentation.

Please _always_ ask for approval from engineers.

**Comment by sgnn7** [comment]
> I don't think it's a good idea to merge PRs regarding documentation without approval from engineers. 

Hey @gbbr, I approved the PR as the env var pattern matched up with the general pattern of `path_a`->`path_b`->`path_c` == `DD_PATH_A_PATH_B_PATH_C` mappings that most of the config file uses. If inconsistent configurations like this are likely to be hit, we're at somewhat of a limit that `CODEOWNERS` can do for us here since `dd/agent-all` is not very useful in those cases for a generic review and asking for specific owners of the env var groups may be something to consider for future PRs probably. @ogaca-dd's suggestion here about automating the env var tests also may be helpful to do before more are added.

**Comment by ruthnaebeck** [comment]
@gbbr - I did get approval from engineering. I don't think it even lets me merge without it. Sorry this turned out to be incorrect.

**Pull request merged**
