### PR TITLE
Autodiscover standard tags in ECS Fargate

### PR DESCRIPTION
**Pull request by xornivore**
### What does this PR do?

Extract tags from ECS container's labels:
- `com.datadoghq.ad.service`
- `com.datadoghq.ad.env`
- `com.datadoghq.ad.version`

### Motivation

Unify DD tagging

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by ahmed-mez — COMMENTED** [review]
looks great, could you add a test case in `ecs_fargate_extract_test.go` ?

**Review by ahmed-mez — APPROVED** [review]
:shipit:

**Comment by sveniu** [comment]
@xornivore Was "com.datadoghq.tags.**source**" not included on purpose? Would it be possible to include it, or does it not make sense – maybe it only has significance for logs? I see that it is set to ecsFargateCollectorName (with value "ecs_fargate"), but it would usually have values like "nginx" or "postgresql" as reference to which Datadog integration to use, but again this might only have an effect on log parsing? And Fargate logs would be propagated through FireLens/FluentBit anyway, which sets its own dd_source value.

**Comment by sveniu** [comment]
Ah wait, this should be alleviated by arbitrary tag support coming in #5779

**Pull request merged**
