### PR TITLE
Add configcheck command

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?

Add a `configcheck` command that helps investigating the current loaded/resolved configs for each config provider:

screen shot 2018-01-29 at 18 49 05

Additionnally with a `-v` option it can output debug info such as the warnings during resolve and the templates yet to be resolved:

screen shot 2018-01-30 at 11 02 11

The output of this commande (in debug mode) is added to the flare to a `config-check.log` file

### Motivation

The autodiscovery is a piece of the agent where a lot of components could go wrong (template, ad identifiers, discovery...) and that's why we need a tool to give an idea of the current state of a running agent for development & debugging purposes

### CODE REVIEW

**Review by hkaj — COMMENTED** [review]
Great stuff 💯 LGTM overall, just one issue: I tried adding a check config file with invalid yaml and it didn't show in the configcheck command output. We can see it in the logs of course, but it would be nice if  `configcheck` could outline the unmarshalling error. Here's the log output:
```
2018-02-04 12:42:22 UTC | INFO | (file.go:68 in Collect) | File Configuration Provider: searching for configuration files at: /etc/datadog-agent/conf.d
2018-02-04 12:42:22 UTC | WARN | (file.go:180 in collectEntry) | /etc/datadog-agent/conf.d/nginx.d/conf.yaml is not a valid config file: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `:foo:ba...` into []check.ConfigRawMap
```

**Comment by tmcarr** [comment]
https://github.com/DataDog/datadog-agent/issues/1159

**Review by hkaj — APPROVED** [review]
we need it now, let's merge as is and handle yaml errors in a follow-up PR.

**Comment by hkaj** [comment]
and thanks for the eyes @tmcarr, we'll fix it asap. Making troubleshooting easier is a high priority.

**Comment by mfpierre** [comment]
@hkaj static config errors added to the command output via https://github.com/DataDog/datadog-agent/pull/1189

**Pull request merged**
