### PR TITLE
Ship unixodbc with the Agent

### PR DESCRIPTION
**Pull request by nmuesch**
### What does this PR do?

Ships unixodbc with the agent

### Motivation

Adding sqlserver support for Linux requires adding the pyodbc dependency (done in integrations core) That wheel depends on unixodbc being present.

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by ofek — DISMISSED** [review]

**Review by olivielpeau — DISMISSED** [review]
✅ Feel free to merge if gitlab pipeline passes

**Review by derekwbrown — DISMISSED** [review]

**Comment by masci** [comment]
Suse build is failing on a missing library: `/usr/lib64/libltdl.so.7`

**Comment by olivielpeau** [comment]
indeed... Had a quick look at the debian pkg that's built and none of the odbc libs seem to dynamically depend on `libltdl.so.7` (it may be statically linked?), not sure why the odbc libs built on suse are different.

This warrants further investigation. If you want to unblock this PR now for 6.8 I'd advise to not include `unixodbc` on SUSE in 6.8. (here you could add a conditional like `unless suse?`)

**Comment by masci** [comment]
Build fixed in https://github.com/DataDog/omnibus-software/pull/274

**Comment by masci** [comment]
After fine tuning the `unixodbc` software definition on `omnibus-software` all the builds pass. Waiting for the last one after my last commit.

**Review by olivielpeau — APPROVED** [review]
Re-approving

**Pull request merged**
