### PR TITLE
Merge distribution & time samplers

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?

Merge the distribution sampler with the regular time sampler

### Motivation

* have a single time sampler for dsd
* preparation work to introduce sketchs in the check sampler

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by olivielpeau — COMMENTED** [review]
LGTM overall!

One note though: the main logic change that the PR introduces is that series (from dogstatsd) and sketches are now aggregated in a logic that shares one `contextResolver`. The old contexts tracked in the `contextResolver` are expired after every `flush`, so now that the `contextResolver` is shared its old contexts are expired by both the `flushSeries` and `flushSketches` methods.
If sketches and series aren't flushed at approximately the same times then this could lead to inconsistent states in the `contextResolver`. Example: if we were to call `flushSeries`, but _not_ `flushSketches`, for more than `defaultExpiry` (`300` seconds), the contexts of the distribution points would be expired and the next `flushSketches` call would fail (gracefully: `flushSketches` would return 0 sketches even if dist points were submitted in the timeframe).

It's extremely unlikely that this happens with the current code, since `flushSketches` and `flushSeries` are always called one after the other, by the aggregator. Still, IMO it's not great that this shared state can be updated by 2 independent parts of the code. Potential solutions: either have 2 separate `ContextResolver`s, or have one flush for both series and sketches and expire at the end of that.

Let me know what you think. I'm probably being overcautious, but I still feel this isn't great behavior.

**Comment by mfpierre** [comment]
@olivielpeau indeed nice catch, see 2d124bf35aef27f3041a5dba7e00b08141291f53 for having a single `flush` for both series & sketches

**Review by olivielpeau — DISMISSED** [review]
👍 LGTM overall

I'm not sure how this change helps to port the sketch aggregation logic to the `CheckSampler`, do you have more details on your plan after this PR is merged?

About memory usage: since in the scope of this package, a `context` is the set of `(metric name, tags, hostname)`, I would not expect "regular" metrics and distribution metrics to share the same `context` (the metric name should be different), so I wouldn't expect memory usage to improve: we basically end up with one map that has twice as many keys as each of the previous 2 maps. I'd assume that performance would be relatively similar. It'd be useful to have benchmarks and/or some perf comparisons of Agents with significant dogstatsd workloads before/after the changes.

**Comment by mfpierre** [comment]
We'll try to benchmark this during QA, it does not help top port the sketch logic per say, but I think having a single `sampler` makes things cleaner and as the `checkSampler` will also have to support both I wanted to give it a try on the `timeSampler` first + for consistency

**Review by olivielpeau — APPROVED** [review]
:shipit:

**Pull request merged**
