### PR TITLE
fix(go): Update to go 1.21.11

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
Update to go 1.21.11

### Motivation
Agent 6 release

### CODE REVIEW

**Review by brett0000FF — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]
LGTM for files owned by ASC

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
