### PR TITLE
[EBPF-293] Add OpenSUSE/SUSE images to KMT

### PR DESCRIPTION
**Pull request by gjulianm**
### What does this PR do?

Adds the following images to KMT:

* OpenSUSE 15.3 (ARM64, x64)
* OpenSUSE 15.5 (ARM64, x64)
* SUSE 12.5 (ARM64, x64)

### Motivation

Matching testing platforms in KMT for the security-agent to the ones in Kitchen.

https://datadoghq.atlassian.net/browse/EBPF-293

### Describe how to test/QA your changes

Tests in CI

### CODE REVIEW

**Comment by gjulianm** [comment]
/trigger-ci --variable RUN_KMT_TESTS=on

pls work

**Review by paulcacheux — APPROVED** [review]

**Review by usamasaqib — APPROVED** [review]

**Pull request merged**
