### PR TITLE
Add e2e test for container-meta payload

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?

Add e2e test for container-meta payload

### CODE REVIEW

**Review by devonboyer — COMMENTED** [review]
What are the challenges with adding a unit test for this feature similar to https://github.com/DataDog/datadog-agent/blob/master/pkg/util/docker/tags_test.go instead of an e2e test?

Now that the e2e framework is a lot easier to use, I think we should caution adding e2e tests when a unit test would achieve the same confidence.

Perhaps we should add both?

**Comment by mfpierre** [comment]
@devonboyer I'll add additional check to other metadata present in the payload that will justify the e2e test 👍

**Comment by mfpierre** [comment]
@devonboyer I feel adding a unit test with a fake client for the metadata would not be super useful, it would feel a lot like testing the fake client itself as there's almost no logic in https://github.com/DataDog/datadog-agent/blob/master/pkg/util/docker/metadata.go

Testing the whole metadata payload generation though, is a quite complex flow to test, and is IMHO worth an e2e test.

**Comment by devonboyer** [comment]
@mfpierre Alright, I can agree with that.

**Review by devonboyer — APPROVED** [review]

**Pull request merged**
