### PR TITLE
improve series payload JSON serialization

### PR DESCRIPTION
**Pull request by arbll**
### What does this PR do?

Make sure JSON generated with the series payload is sent to a reusable buffer during serialization instead of allocating a bunch of them.

Results vs master:
```
benchmark                         old ns/op       new ns/op       delta
BenchmarkJSONStream1-4            302767          196764          -35.01%
BenchmarkJSONStream10-4           302995          218605          -27.85%
BenchmarkJSONStream100-4          485625          325715          -32.93%
BenchmarkJSONStream1000-4         2928747         1999100         -31.74%
BenchmarkJSONStream10000-4        26948853        20529779        -23.82%
BenchmarkJSONStream100000-4       238035373       176771649       -25.74%
BenchmarkJSONStream1000000-4      2672207824      1670560816      -37.48%
BenchmarkJSONStream10000000-4     39562572955     18233628846     -53.91%

benchmark                         old allocs     new allocs     delta
BenchmarkJSONStream1-4            38             32             -15.79%
BenchmarkJSONStream10-4           102            32             -68.63%
BenchmarkJSONStream100-4          733            32             -95.63%
BenchmarkJSONStream1000-4         7035           32             -99.55%
BenchmarkJSONStream10000-4        70040          32             -99.95%
BenchmarkJSONStream100000-4       700043         33             -100.00%
BenchmarkJSONStream1000000-4      7000163        120            -100.00%
BenchmarkJSONStream10000000-4     70001122       806            -100.00%

benchmark                         old bytes      new bytes     delta
BenchmarkJSONStream1-4            823329         826973        +0.44%
BenchmarkJSONStream10-4           825283         827069        +0.22%
BenchmarkJSONStream100-4          858926         842190        -1.95%
BenchmarkJSONStream1000-4         1315889        1115124       -15.26%
BenchmarkJSONStream10000-4        5291411        3234203       -38.88%
BenchmarkJSONStream100000-4       29337641       7594088       -74.11%
BenchmarkJSONStream1000000-4      244979016      28711592      -88.28%
BenchmarkJSONStream10000000-4     2319457872     127689544     -94.49%
```

### Motivation

Reduce memory usage & pressure on the GC.

### CODE REVIEW

**Review by remeh — DISMISSED** [review]
Neat!
Small nit: I think the `jsonSeparator`, `jsonArrayStart` and `jsonArrayEnd` are not used anymore.

**Review by remeh — APPROVED** [review]
👌

**Comment by jd** [comment]
@arbll did you mean to merge this 16MB Mach-O executable named `serializer.test` in the root directory?

**Comment by arbll** [comment]
I did not, nice catch @jd

**Pull request merged**
