### PR TITLE
Clean up embedded python libs when Agent installation changes

### PR DESCRIPTION
**Pull request by remicalixte**
### What does this PR do?

Remove all custom python modules on upgrade

Tested on Ubuntu and Fedora

### CODE REVIEW

**Comment by arbll** [comment]
This is a pretty big change in behavior. Do we have a plan on how to make sure our customer are warned before upgrading ? 
cc @olivielpeau

**Comment by olivielpeau** [comment]
Agreed, before merging this we need to decide on a plan on:

* how to test this change thoroughly on the deb and rpm packages (fresh install, upgrade from v5, upgrade from earlier v6, downgrade)
* how to advertise the change to our users, since as you wrote it's a significant change in behavior

**Comment by remicalixte** [comment]
The current solution removes previous content of `lib/python2.7` before installation
- Works for upgrade
- Doesn't do anything for uninstallation: leave all the custom libs there
- On installation, first or after an uninstallation, clean the libs

It works but it could be better to remove libs when uninstalling

**Comment by remicalixte** [comment]
As an alternative, we can keep track of all the files we explicitly install somewhere and then remove all the other files.
Pros:
- Cleaner
- We would be able to remove all the custom libs on uninstallation
Cons:
- less simple than doing `rm -rf`
- Be careful of which list we use when we change the packages we ship

**Comment by olivielpeau** [comment]
Closing this in favor of https://github.com/DataDog/datadog-agent/pull/2161

**Pull request closed without merging**
