### PR TITLE
Move alternative otel collector implementations into new component layout

### PR DESCRIPTION
**Pull request by dustmop**
### What does this PR do?

Move the old pipeline implementation (used by core agent) into its own folder, to match the new collector implementation (used by otel-agent). This follows the guidelines for the new component layout.

### CODE REVIEW

**Review by ogaca-dd — APPROVED** [review]
LGTM

**Review by songy23 — COMMENTED** [review]
Linter failed https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/519741171

**Review by dineshg13 — APPROVED** [review]

**Comment by dustmop** [comment]
> Linter failed https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/519741171

Thanks for the heads up, @songy23. I pushed some commits that fix it.

**Review by purple4reina — APPROVED** [review]

**Pull request merged**
