### PR TITLE
refactor(tasks): split the go_test file in several pieces

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
- Split the go_test.py file in several subtask
- I refactored the tasks checking PR labels/milestone, and added more UT on these
- I moved one task, generate_config to agent.generate_config. The impact should be limited and I think it was justified

### Motivation
Technical debt

### Additional Notes
I changed the namespace of one task: `generate_config` was a "standalone" task and was added to the `agent` collection (as it generates the datadog.yaml configuration file I thought it would make sense)

### Describe how to test/QA your changes
As I just moved the tasks I just tested the generation of invoke list. TODO: run more tests
For the pr_checks tasks I reviewed and enriched the UT

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Assuming CI passes, I didn't see any concerns about the re-organization

**Review by paulcacheux — APPROVED** [review]

**Review by pgimalac — APPROVED** [review]
Nice, thanks for that

**Review by brycekahle — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]

**Review by ahmed-mez — APPROVED** [review]

**Review by kkhor-datadog — APPROVED** [review]

**Review by vboulineau — APPROVED** [review]

**Pull request merged**
