### PR TITLE
[ASCII-2075] Wait for providers to stop in metadata runner stop

### LINKED ISSUE #24171: [BUG] Datadog agent causing RPM database get corrupted
**Description**
Ok i'm not 100% confident that is a Datadog issue, but it's the only clue I have right now. Since  march 22th we see (10) servers with getting their RPM DB corrupted. The facts:
- This only happens when the agent upgraded to 7.52.0-1
- We only see it on machines with Datadog agent; the other 300 servers don't show this behaviour which all have the same base configuration but without DD agent.
- Different cloud providers (just to rule some storage out or something)

Fixing the DB corruption will not prevent it from happening again. We have servers which have had this corruption multiple times now.

**Agent Environment**
The agent is running 7.52.0-1 on RHEL 8.9

**Describe what happened:**
The RPM database get's corrupted and calling the rpm/dnf command shows:

```
error: rpmdb: BDB0113 Thread/process 2421732/140117948610432 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
```

**Describe what you expected:**
Database not getting corrupted

**Steps to reproduce the issue:**
Upgrading is enough, but don't know what triggers it.

**Additional environment details (Operating System, Cloud provider, etc):**

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Improve stopping mechanism of the metadata runner component.

The metadata runner currently stops running providers asynchronously to avoid blocking the agent stop.
This PR changes that to wait at most 30 seconds for providers to stop.
That way we can both limit risks of interrupting a provider, and avoid blocking the agent stop indefinitely.

### Motivation

Trying to fix https://github.com/DataDog/datadog-agent/issues/24171.
We suspect some metadata providers could be interrupted when the agent stops, while they are still running, causing a corruption. 

### Additional Notes

Providers should check the context so that they stop as early as possible when it's canceled, but most don't.
Follow-up work will improve that. 

This PR also fixes an issue with the use of the `WaitGroup` where it was incremented in the routine instead of before starting it, so when starting and stopping quickly in tests it could not wait for routines.

### Possible Drawbacks / Trade-offs

Could make the agent longer to stop, but stop is cleaner.

### Describe how to test/QA your changes

Added unit tests to ensure each case works as expected when we try to stop the runner while providers are running:
- runner stop timeout is shorter than provider duration: stop returns after timeout
- runner stop timeout is longer than provider duration: stop returns when provider ends

### CODE REVIEW

**Review by misteriaud — APPROVED** [review]
LGTM !

**Comment by pgimalac** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
