### PR TITLE
fix import: use testify instead of gotest.tools

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Replace import of `"gotest.tools/assert"` with `"github.com/stretchr/testify/assert"`

### Motivation

Seeing https://github.com/DataDog/datadog-agent/pull/17957 made us realize that the import was not the correct one. Most of the agent uses `testify` so we might as well do the same.

### Describe how to test/QA your changes

No QA as this only relates to tests.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by sgnn7 — APPROVED** [review]
@pgimalac LGTM but there are some build failures

**Comment by sgnn7** [comment]
@pgimalac This seems to be a subset change of https://github.com/DataDog/datadog-agent/pull/1795 - maybe we need to close this PR?

**Comment by pgimalac** [comment]
@sgnn7 The CI is currently quite broken so I'll wait for it to be fixed first, but I don't believe the fails are due to this change

When I saw the PR mentioned in the description I asked @hush-hush (who wrote that code) why we were using `gotest.tools` and he told me it was an error, and that I could change it if it was easy enough.
I just found it weird that we were using another testing framework in this specific file, but I don't really mind otherwise so if you think we should stick to `gotest.tools` I can just close this PR.

PS: I'm not sure you linked the good PR in your comment ?

**Review by hush-hush — APPROVED** [review]

**Comment by sgnn7** [comment]
@pgimalac Ah, the PR I linked is not the right one - here's the one I intended to post: https://github.com/DataDog/datadog-agent/pull/17957

**Pull request merged**
