### PR TITLE
To add for supporting Windows whose System Drive is not C Drive.

### PR DESCRIPTION
**Pull request by yamatoya**
Signed-off-by: Takahito Yamatoya <takahito.yamatoya@bitflyer.com>

### What does this PR do?

* To add support for Windows whose system drive is not C Drive (for example, Azure Cloud Service's System Drive is D drive).

### Motivation

I want to run on Azure Cloud Services.

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by yamatoya** [comment]
temporary close and fix it.

**Comment by yamatoya** [comment]
My friend fix for CI test error, so I reopen this.

**Comment by guitarrapc** [comment]
What is the status of this PR? I do also required this enhancement.

**Comment by guitarrapc** [comment]
This issue is already resolved with https://github.com/DataDog/datadog-agent/pull/2546 .

**Pull request closed without merging**
