### PR TITLE
Update buildimages

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

This bumps our build images

### Motivation

The only change is the debian-arm image that can now perform XZ compression on multiple threads. Other images are unchanged.
Link to associated PR: https://github.com/DataDog/datadog-agent-buildimages/pull/515/files

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by Pythyu — COMMENTED** [review]
Is there a reason we're removing the `v` prefix in front of versions ?
like from `v25937664-dd22a18f` to `26473479-2dfb49af`.
Otherwise LGTM

**Comment by chouquette** [comment]
> Is there a reason we're removing the `v` prefix in front of versions ? like from `v25937664-dd22a18f` to `26473479-2dfb49af`. Otherwise LGTM

Mostly because I can't copy paste properly. Thanks for noticing :facepalm:

**Review by Pythyu — APPROVED** [review]
🚀

**Pull request merged**
