### PR TITLE
[omnibus] Make system-probe binary builds use the GOMODCACHE env

### PR DESCRIPTION
**Pull request by KSerrania**
### What does this PR do?

Updates the `system-probe` binary build commands in the `datadog-agent.rb` software definition to pass the `env` hash.

This hash sets a number of environment variables (like `GOPATH`, `LDFLAGS`, `CGO_CFLAGS`, `CGO_LDFLAGS`, `GOMODCACHE`).

The `GOMODCACHE` one in particular is important, as it allows the command to reuse the go dependency cache that we prepare in the `go_deps` job. This helps avoid the total number of dependency downloads done from third-parties in the CI.

Since the `system-probe` binary build commands did not have this variable set, they were re-downloading their go dependencies. This sometimes caused download errors ([example](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/665024290)), making CI fail.

### Motivation

Avoid unnecessary dependency downloads in CI.

### Describe how to test/QA your changes

Full successful pipeline run.

### Possible Drawbacks / Trade-offs

I could have passed only the `GOMODCACHE` variable to the commands to be extra safe. However, since all other go build commands in the software definition already pass the full `env` hash, I prefer having a uniform way of running all of them.

### Additional Notes

n/a

### CODE REVIEW

**Comment by KSerrania** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by spencergilbert — APPROVED** [review]
**🥜 nitpick:** ‏ we seem to be using `:env => env` and `env: env` interchangeably here.

**Comment by alopezz** [comment]
> **🥜 nitpick:** ‏ we seem to be using `:env => env` and `env: env` interchangeably here.

My 2c: I think `env: env` is the better syntax here and the one we should prefer; but without any sort of linter enforcing it we have no way to ensure consistency.

**Pull request merged**
