### PR TITLE
Remove `aerospike` dependency definition

### PR DESCRIPTION
**Pull request by ofek**
### What does this PR do?

Revert most of https://github.com/DataDog/datadog-agent/pull/4933

### Motivation

No longer necessary since https://github.com/DataDog/integrations-core/pull/8044

### CODE REVIEW

**Review by ogaca-dd — APPROVED** [review]
LGTM.

Should we also remove lines like https://github.com/DataDog/datadog-agent/blob/b16b2270f19ead64b837e6ee5c3a3a457efe60a5/omnibus/config/software/datadog-agent-integrations-py2.rb#L100?

**Comment by ofek** [comment]
After I update Aerospike to support Python 3.9 I'll try enabling those again

**Comment by ofek** [comment]
(AppVeyor error is unrelated to this change)

**Review by hithwen — APPROVED** [review]

**Comment by KSerrania** [comment]
If I understand correctly, in the current state we install the `datadog-aerospike` integration, but not its dependency `aerospike` (because of the `blacklist_packages.push(/^aerospike==/)` lines: https://github.com/DataDog/datadog-agent/blob/491f5d299dcc2efc69a92ceb800669ce5877cc93/omnibus/config/software/datadog-agent-integrations-py2.rb#L76, https://github.com/DataDog/datadog-agent/blob/491f5d299dcc2efc69a92ceb800669ce5877cc93/omnibus/config/software/datadog-agent-integrations-py3.rb#L71), so we should expect the aerospike integration to not work?

**Comment by ofek** [comment]
Ah, I see. Fixed.

**Review by truthbk — APPROVED** [review]

**Pull request merged**
