### PR TITLE
[CWS] add ubuntu 22.04 to functional tests

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

This PR adds an `ubuntu-22-04` entry to CWS functional tests. Because ubuntu 22.04 ssh server doesn't accept `ssh-rsa` keys by default, this PR also removes the ssh key creation from kitchen setup and lets the different kitchen provider to manage those keys themselves (this is needed since just adding the platforms entry was failing with ssh failed error).

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by albertvaka — APPROVED** [review]
LGTM as long as all the kitchen tests pass.

**Comment by paulcacheux** [comment]
Looking at https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/7778576 all kitchen tests are passing except the windows ones, but with failure similar to the ones found on the main branch (for example https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/7777411)

**Comment by albertvaka** [comment]
Oh, wait, it seems this broke some things here: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/131913499

**Comment by albertvaka** [comment]
@paulcacheux I think you will have to revert 😓

**Pull request merged**
