### PR TITLE
[ASCII-2587] Migrating TraceAgent to use IPC cert

### PR DESCRIPTION
**Pull request by misteriaud**
### What does this PR do?
This PR migrates the Trace Agent Debug server to an HTTPS server, using the new Agent-wide IPC certificate. This change will allow Agents to identify this API as legitimate when they act as a client.

The certificate generation/retrieval implementation have been made in the following PR:
- #31838

### Motivation
This PR takes place in a plan of Agent security IPC improvement.   

### Describe how you validated your changes

The existing unit tests that cover the Debug server were updated with this PR as well.

### Possible Drawbacks / Trade-offs
Based on my understanding, the Trace Agent Debug endpoint is intended for internal use only. This means we can modify it without notifying customers. However, if any customer applications or other processes are using it, such communications will be interrupted.

### CODE REVIEW

**Review by ajgajg1134 — APPROVED** [review]
This looks good to me, I agree that I believe the debug endpoint is really only for internal uses (especially flare generation)

**Comment by misteriaud** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by jeremy-hanna — APPROVED** [review]
🔥 awesome work man!

**Pull request merged**
