### PR TITLE
Check docker access paths using podman paths, too

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Updates the access check for docker containers to look for the podman directory instead when `use_podman` is set.

### Motivation

Otherwise the tailer falls back to the docker API when using podman.

### Describe how to test/QA your changes

Same as for #9589.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by sgnn7 — COMMENTED** [review]
@djmitche Few tiny nits

**Comment by djmitche** [comment]
Once containers are built, I'll try this out on my podman VM

**Review by gh123man — APPROVED** [review]

**Review by sgnn7 — APPROVED** [review]
@djmitche CI unit test failures in `pkg/logs/input/docker` but outside of that LGTM.

**Comment by djmitche** [comment]
(confirmed on a VM that this now consumes logs via files)

**Pull request merged**
