### PR TITLE
[CWS] fix CentOS 7 kernel headers download

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

This PR:
- adds CentOS 7 kernel headers location to search algorithm
- fixes functional tests to extract Nikos into the docker container

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by lebauce — APPROVED** [review]

**Comment by brycekahle** [comment]
@paulcacheux We test against CentOS 7.6 already and don't have problems with it finding the kernel headers.

**Comment by paulcacheux** [comment]
Are you sure you're not falling back to precompiled during your tests ? Because I experimented a lot, and the previous kernel headers that used to be downloaded by Nikos did not contain `kconfig.h`, a very important header since it's basically included by everything (contains the `CONFIG_XX` macro

**Comment by brycekahle** [comment]
> Are you sure you're not falling back to precompiled during your tests

[Yes](https://github.com/DataDog/datadog-agent/blob/abc83517ab175085983521205c496bd67f9d4c84/pkg/network/tracer/tracer_test.go#L1625-L1628), but we are using headers [pre-installed by the package manager](https://github.com/DataDog/datadog-agent/blob/abc83517ab175085983521205c496bd67f9d4c84/test/kitchen/site-cookbooks/dd-system-probe-check/recipes/linux.rb#L14), rather than downloaded headers.

**Comment by paulcacheux** [comment]
Oh that makes sense, in a patch to Nikos I fixed the fact that we were downloading the wrong headers package (cf https://github.com/DataDog/nikos/commit/d052da838170acbc31a80d43eb9030c038ec3033).

**Comment by paulcacheux** [comment]
I will do more investigation and come back to you on this matter then

**Comment by paulcacheux** [comment]
@brycekahle looking at https://centos.pkgs.org/7/centos-x86_64/kernel-devel-3.10.0-1160.el7.x86_64.rpm.html (and checked with a `rpm -qlp` on the file downloaded by Nikos (`kernel-devel` package). It only contains files in `/usr/src/kernels/*`. I don't completely understand why it's working in your CI yet

**Comment by brycekahle** [comment]
@paulcacheux Is there a symlink added from `/lib/modules/$(uname -r)/{source,build}`? I'd have to turn on debug logging to see where the CI is finding the kernel headers.

**Comment by paulcacheux** [comment]
There is a script running at postinstall:
```
postinstall scriptlet (using /bin/sh):
if [ -f /etc/sysconfig/kernel ]
then
    . /etc/sysconfig/kernel || exit $?
fi
if [ "$HARDLINK" != "no" -a -x /usr/sbin/hardlink ]
then
    (cd /usr/src/kernels/3.10.0-1127.el7.x86_64 &&
     /usr/bin/find . -type f | while read f; do
       hardlink -c /usr/src/kernels/*.el7.*/$f $f
     done)
fi
```
But nothing I can see linking to /lib/modules

**Comment by paulcacheux** [comment]
Running `rpm -qf /lib/modules/3.10.0-1127.el7.x86_64/build` outputs `kernel-3.10.0-1127.el7.x86_64` so a third different package

**Comment by brycekahle** [comment]
From a CI run with debug logs turned on:
```
1645734434644883269 [Debug] found valid kernel headers at /lib/modules/3.10.0-957.27.2.el7.x86_64/build
1645734434644969669 [Debug] found valid kernel headers at /lib/modules/3.10.0-957.27.2.el7.x86_64/source
1645734434645011169 [Debug] found non-versioned kernel headers at /usr
1645734434645077770 [Debug] found kernel headers in /lib/modules/3.10.0-957.27.2.el7.x86_64/build,/lib/modules/3.10.0-957.27.2.el7.x86_64/source,/usr
```
🤷‍♂️

**Comment by paulcacheux** [comment]
I'm sorry but without this fix, I'm getting a `unable to find kernel headers: downloaded headers are not valid ` error. Since it's just adding a standard path, I think we should merge it

**Review by brycekahle — APPROVED** [review]
I'm going to approve this, since as you said, adding this directory is harmless. I do think we should get to the bottom of this but it isn't urgent.

**Comment by paulcacheux** [comment]
Thank you. I added a note in my todo list to do a deeper analysis on why it works/doesn't work depending on the source (downloaded or pre-installed)

**Pull request merged**
