### PR TITLE
Fix agent payload version check

### PR DESCRIPTION
**Pull request by mbakht**
### What does this PR do?

If we are making changes in `agent-payload`, we sometimes need to use a specific version of that module in the `agent-repo` based on a commit hash. That breaks the _version extraction_ code. 

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

```python
>>> import re
>>> line1 = "github.com/DataDog/agent-payload v4.40.0+incompatible"
>>> line2 = "github.com/DataDog/agent-payload v4.42.1-0.20200826134834-1ddcfb686e3f+incompatible"
>>> version_split = re.split(r'[ +]', line1)
>>> version = version_split[1].split("-")[0].strip()
>>> re.search(r"^v\d+(\.\d+){2}$", version)
<_sre.SRE_Match object at 0x1097904b0>
>>> version
'v4.40.0'
>>> version_split = re.split(r'[ +]', line2)
>>> version = version_split[1].split("-")[0].strip()
>>> re.search(r"^v\d+(\.\d+){2}$", version)
<_sre.SRE_Match object at 0x1097904b0>
>>> version
'v4.42.1'
```

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]
LGTM if CI is ✅

**Comment by mx-psi** [comment]
The `run_tests_windows-x86` is throwing a payload-related error, I don't think it is related to this change but could you have a look?

**Comment by mbakht** [comment]
> The `run_tests_windows-x86` is throwing a payload-related error, I don't think it is related to this change but could you have a look?

Sorry for the n00b question - but how do I look it up?   Usually for other tests, I use the `Details` link.

**Comment by mbakht** [comment]
> > The `run_tests_windows-x86` is throwing a payload-related error, I don't think it is related to this change but could you have a look?
> 
> Sorry for the n00b question - but how do I look it up? Usually for other tests, I use the `Details` link.

Never mind, I was able to find the link by going to Gitlab. After merging latest master, only the `macos` build test failed. The error seems unrelated:
```
Verification for liblzma failed due to a checksum mismatch:

    expected: 19d924e066b6fff0bc9d1981b4e53196
    actual:   afd33cb888461aae3bfd05b80c9e42a8
```
Ok to merge?

**Comment by mx-psi** [comment]
Sure, go ahead! 👍

**Pull request merged**
