### PR TITLE
Update collector version to 0.114.0

### PR DESCRIPTION
**Pull request by dineshg13**
### What does this PR do?

Updates the Collector modules version to 0.114.0. Fix the invoke task `collector.update` to handle all modules.

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Review by pgimalac — APPROVED** [review]

**Review by ajgajg1134 — APPROVED** [review]

**Review by chouetz — APPROVED** [review]
OK for agent-devxinfra side

**Comment by songy23** [comment]
Please resolve merge conflicts

**Review by jackgopack4 — APPROVED** [review]
thanks for addressing my concerns, looks good to me

**Review by jackgopack4 — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Pull request merged**
