### PR TITLE
Add `freetds ` linux dep

### PR DESCRIPTION
**Pull request by AlexandreYang**
Refactored in https://github.com/DataDog/datadog-agent/pull/5869

### What does this PR do?

- [x] Add `freetds` linux dep

Other required steps/PR:

See https://github.com/DataDog/integrations-core/pull/6636

### Motivation

Needed to run SQL Server integration in Docker Agent:

https://github.com/DataDog/integrations-core/issues/6591

### Additional Notes

- [ ] TODO: remove deps in e2e https://github.com/DataDog/integrations-core/blob/1bf1bcf5f4af4a54f16bf45ad76d55c4f364ce05/sqlserver/tests/common.py#L95 

### Describe your test plan

Write there any instructions and details you may have to test your PR.

### CODE REVIEW

**Comment by FlorianVeaux** [comment]
Can we have a look at the required dependencies for the various drivers?

FreedTDS seems to require unixodbc + tdsodbc indeed but is that enough for MSODBC driver?

**Comment by FlorianVeaux** [comment]
I have seen that test: https://github.com/DataDog/integrations-core/pull/6593
But this test still includes a custom `odbcinst.ini` file which defines the FreeTDS driver. The current agent container ships an empty `/opt/datadog-agent/embedded/etc/odbcinst.ini` so I don't think this is enough to make the sql integration work out of the box in containers at the moment.

**Comment by FlorianVeaux** [comment]
And you'll need to update omnibus-software as well before: something like this https://github.com/DataDog/omnibus-software/blob/master/config/software/unixodbc.rb

**Comment by AlexandreYang** [comment]
> I have seen that test: DataDog/integrations-core#6593
> But this test still includes a custom odbcinst.ini file which defines the FreeTDS driver. The current agent container ships an empty /opt/datadog-agent/embedded/etc/odbcinst.ini so I don't think this is enough to make the sql integration work out of the box in containers at the moment.

Make sense, if we intend to ship `tdsodbc`, it would make sense to ship also a valid `odbcinst.ini` to make it work OOTB.

**Comment by AlexandreYang** [comment]
> And you'll need to update omnibus-software as well before: something like this https://github.com/DataDog/omnibus-software/blob/master/config/software/unixodbc.rb

Related note: https://stackoverflow.com/a/51340351

```
wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.92.tar.gz
tar -xzf freetds-1.00.92.tar.gz
cd freetds-1.00.92
./configure --prefix=/usr/local --with-tdsver=7.3
sudo make
sudo make install
```

**Review by albertvaka — COMMENTED** [review]
The PR description mentions "Add valid odbcinst.ini" but I don't see it here. Is that missing?

Also, you can add omnibus recipes directly to this repo, they don't have to be in omnibus-software.

Do you need help with the omnibus part/is there any other blocker?

**Comment by AlexandreYang** [comment]
@albertvaka 

> The PR description mentions "Add valid odbcinst.ini" but I don't see it here. Is that missing?

It's still in WIP, but yes, `odbcinst.ini` should be provided. Not sure yet what's the best location though, any suggestion?

> Also, you can add omnibus recipes directly to this repo, they don't have to be in omnibus-software.

Sure 👍

> Do you need help with the omnibus part/is there any other blocker?

I will have a try, but will ask for help there is an issue. No other blocker for now.

**Comment by albertvaka** [comment]
`omnibus/config/templates` is the right place if you need it to be a template (eg: with paths coming from variables from the code). You can copy-paste how the files there are used form other recipes. If you don't need templates... I don't know where to put it actually, so use a template 😂

**Review by albertvaka — APPROVED** [review]

**Review by FlorianVeaux — APPROVED** [review]
Good for integrations-core (let's make sure it builds correctly).
I like the idea that we ship odbcinst.ini with the integration directly instead 👍

**Comment by AlexandreYang** [comment]
All linux builds passed.

**Pull request merged**
