### PR TITLE
[Config] allow the config path to be set by environment variable

### PR DESCRIPTION
**Pull request by gmmeyer**
### What does this PR do?

This lets the config file be set via an environment variable

### Motivation

I've run into a bunch of situations where this would be beneficial

### CODE REVIEW

**Review by derekwbrown — COMMENTED** [review]
IMO, this takes a very confusing part of our config and makes it worse.  With this code, if they have it in the environment and on the command line, both configs will be added.

If there's an environment variable that's just a path (i.e. no `yaml` extension), and there's a `datadog.yaml` on the environment path and default path, we'll read both.  What happens if the configs have conflicting options? Which takes precedence?

IMO, for an option like this, there should be explicit precedence.  If the env is set, we don't look in the default locations. Same with command line,  And, in the case of env & command line, need an explicit precedence so we're never merging conflicting configs.

**Comment by gmmeyer** [comment]
@derekwbrown if you add one on the cli it will add that to the list of places it already looks for the file. I believe it takes the options only from the first file it finds in the list.

**Comment by derekwbrown** [comment]
But which one does it find first?  If theres an ENV, a command line, and default location.  My point is that the notion of a "list of places" is suspect, and this PR adds to that list.

**Comment by olivielpeau** [comment]
Just to confirm: the library we use for config (`viper`) iterates through the paths in the order they were added and uses the first `datadog` config file it finds in these paths. No merge is made between multiple files.

I agree that when a config path is provided through the command line or through an env var, we should only add that path to `viper`: to me, if the user provided that path and we couldn't find a valid file there, the Agent should exit with an error. The precedence should be `command line` > `env var` > `default location`.

That said, there might be one use case where adding multiple paths to `viper` would make sense to me: when no path is explicitly provided, we may want to add the path to the "dev datadog.yaml" file first, so that in a dev env the Agent reads that file if it exists.

@gmmeyer @derekwbrown thoughts?

**Comment by gmmeyer** [comment]
I'll be clear about the specific use case I have in mind here. In Cloud Foundry the config isn't at the normal spot. So, when the agent is called from the process agent, it cannot find the config. And, the way the subprocess works, you can't just add the flag in the config file the process agent is reading. It just doesn't see it.

However, I've also encountered a few other situations where this would be useful, like in a dev environment. So I thought it was a good idea.

I agree with @olivielpeau's assessment of precedence here as well.

I also agree that we should attempt to fail over to the dev path if all else fails. I think that will make the agent much more resilient.

**Comment by gmmeyer** [comment]
In some especially borked systems, it might even be a good idea to have a copy of the default checks in the dev path, so that you continue to get metrics even if you can't read the other config location for some reason (but that's off topic).

**Comment by gmmeyer** [comment]
I'm gonna close this as it's been open for too long but I still think this is a good idea

**Pull request closed without merging**
