### PR TITLE
Bug fix for duplicate logs with docker

### PR DESCRIPTION
**Pull request by achntrl**
### What does this PR do?
Fix a bug where the docker tailer would send the last line of log several time when a container wasn't writing much logs (less than 1 log / 30 sec)

### Motivation
What inspired you to submit this pull request?

### CODE REVIEW

**Review by tmichelet — DISMISSED** [review]
Looks good. Could you remind me why `getLastSince` gets called several times when a container has no live logs?

**Review by ajacquemot — APPROVED** [review]
LGTM, thanks for fixing the bug

**Comment by redRolf** [comment]
Hi I am sorry to report this, but I have come across this exact issues after migrating our infrastructure to Fedora Core OS. 
The screenshot below shows this exact behaviour. 
Screenshot 2020-05-26 at 13 48 14

If I can help with more information or assist in any way, please let me know.

**Comment by olivielpeau** [comment]
@redRolf this issue shouldn't occur anymore with recent versions of the Agent.

Could you open a support case with our [support team](https://www.datadoghq.com/support/), send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare), and include the logs from the container where you're seeing this? (please make sure the logs don't contain any sensitive information)

**Pull request merged**
