### PR TITLE
separate python sender per check

### PR DESCRIPTION
**Pull request by gmmeyer**
### What does this PR do?

Each python check needs its own sender, otherwise python checks will stomp on each others rates.

I've created a sender pool in the aggregator. It does not expose this directly, instead just using the same GetSender function that we used before.

I then call this in `api.go`, with the check name from each check as the Check ID. (I have to do some type conversion in order to make this go smoothly.) Instead of using the check name, it might be better to use the Check ID itself. This would require a few extra steps and I think the current mechanism copies what happened in Agent5, where each check object got its own aggregator, pretty well.

I have tested this and the Python checks work and send metrics and such up to DataDog.

### Additional Notes

My C is a bit rusty, but I think this works fine

### CODE REVIEW

**Review by olivielpeau — COMMENTED** [review]
The approach is good overall I think.

Just one thing: the `name` of the check is not enough to identify check instances (the `name` is currently shared among all the check instances of the same class). Overall I'm not sure any of the current attributes of `AgentCheck` provide an identifier that's unique enough.

We could maybe set the `ID` we have in the `PythonCheck` class on an attribute of the python `AgentCheck` instances.

Alternatively, we could set the `name` to a unique identifier, but I'm a bit concerned about custom python checks overwriting the value of `name` for their own purposes.

**Review by olivielpeau — COMMENTED** [review]
LGTM! 👏 

The only part that's still missing is passing the ID to the python `AgentCheck` objects so that they can use the ID instead of the `name` when sending metrics/events/etc.

@masci Can you review this PR too? :)

**Review by masci — CHANGES_REQUESTED** [review]
Left few comments, I need to take another pass to better review the C part

**Review by masci — CHANGES_REQUESTED** [review]
Few nits but overall looks very good!

**Review by masci — APPROVED** [review]
Looks very good to me! Let's 🚢 it!

**Pull request merged**
