### PR TITLE
[go.mod] Bump go-systemd to v22.1.0

### PR DESCRIPTION
**Pull request by davidor**
### What does this PR do?

Updates `go-systemd` to `v22.1.0`.

### Motivation

This is a pre-requisite to have a workloadmeta collector for Podman because recent versions of the podman go client don't work with the current version of `go-systemd` that we're using.

I chose `v22.1.0` because it's the most recent version that seems to be compatible with the systemd libraries installed in the build images. For example, when I try the latest version of `go-systemd`, I get this error:
`/go/pkg/mod/github.com/coreos/go-systemd/v22@v22.3.2/sdjournal/journal.go:1158:29: could not determine kind of name for C.SD_ID128_STRING_MAX `

### Additional Notes

To the best of my knowledge this update does not break anything, but I might have missed something. Please let me know if I should test anything else. These are the things I tried:
- Verified that the `systemd` check reports the same metrics that it reported before this change.
- Configured the journald integration as documented here: https://docs.datadoghq.com/integrations/journald/?tab=containerized. Then, I launched a docker container with `--log-driver=journald` and verified that `agent stream-logs` shows the logs with `type=journald`.

### Describe how to test/QA your changes

See in the previous section what I tested.

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by djmitche — COMMENTED** [review]
> compatible with the systemd libraries installed in the build images

This has me pretty worried, substituting "customer systems" for "the build images".

Do you have more information on what's going on there?  I don't think we necessarily need to do something silly like trying this on every possible system before landing, but having some more context for why this error occurred and where/how it might happen for customers would be useful.  At least, that will feed into an "update go-systemd to latest" card for later.

**Comment by davidor** [comment]
@djmitche Thanks for taking a look.

My understanding is that `go-systemd` depends on the systemd library installed in the host. This is the part of the code that's responsible for that: https://github.com/coreos/go-systemd/blob/9b43fbe5552b6e9e247a1a513c41474bc29c63a4/sdjournal/functions.go

Starting from go-systemd v22.2.0, according to the error that I pasted in my original comment, it seems that the golang wrapper relies on a constant `SD_ID128_STRING_MAX` that's not defined in the systemd library used in our build images.

It seems that there was a similar problem in the past, and that's why the version that we're currently using does not work on some of the build images:
https://github.com/DataDog/datadog-agent/blob/c0f26578424078925494fc58a14163dd6f5c594a/.gitlab/source_test/linux.yml#L51

I agree that this seems a bit risky, that's why in my original comment I asked for ideas about what should be tested. I'm not sure if we should try on a specific set of distros/versions.

This is a change that can wait for the next release, so we can remove it from the milestone and take more time to evaluate it if needed.

**Comment by djmitche** [comment]
> This is a change that can wait for the next release, so we can remove it from the milestone and take more time to evaluate it if needed.

Let's do that, and evaluate the ramifications without time pressure.

**Comment by davidor** [comment]
This PR is no longer needed, because in the end we chose a different approach to implement the Podman collector.

**Pull request closed without merging**
