### PR TITLE
Update s6 overlay version

### PR DESCRIPTION
**Pull request by inductor**
### What does this PR do?

Update S6 overlay version

### Motivation

It's been a few months after its release now

### Additional Notes

N/A

### CODE REVIEW

**Comment by vboulineau** [comment]
Thank you for your contribution. We are currently working on the next agent release (7.17), so your PR will be merged for 7.18

**Comment by inductor** [comment]
@vboulineau hi, any updates?

**Comment by vboulineau** [comment]
> @vboulineau hi, any updates?

The 7.18 is coming and we should merge this PR before the cutoff. Could you please just add a release note (https://github.com/DataDog/datadog-agent/blob/master/docs/dev/contributing.md#reno), and I'll merge it.

**Comment by inductor** [comment]
@vboulineau done! 🙏

**Review by vboulineau — APPROVED** [review]

**Pull request merged**
