### PR TITLE
[pkg/otlp] Update opentelemetry-collector version to v0.41.0

### PR DESCRIPTION
**Pull request by KSerrania**
### What does this PR do?

Updates the `go.opentelemetry.io/collector` version used to `v0.41.0` in the main module & `pkg/otlp/model`, and resolves breaking changes:
- `service/parserprovider` -> `config/configmapprovider`
  - `parserprovider.MapProvider` -> `configmapprovider.Provider`
  -  all `parserprovider.XMapProvider` methods -> `configmapprovider.X` (eg. `parserprovider.NewMergeMapProvider` -> `configmapprovider.NewMap`)
  - `mapProvider` now implements `configmapprovider.Retrieved`
- changed config unmarshalling error strings in tests
- changed `cors` fields in receiver config tests
- changed tests to use the new `configmapprovider.Provider` interface (`provider.Retrieve` -> `retrieved` object -> `retrieved.Get` instead of `provider.Get`)
- changed collector tests to use the new `GetState` method instead of the `GetStateChannel`.

### Motivation

Stay up-to-date with upstream.

### Describe how to test/QA your changes

Updated & ran unit tests, OTLP E2E tests, and manually tested sending OTLP metrics to the Agent.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by KSerrania — COMMENTED** [review]
License updates missing, I'll add that

**Review by mx-psi — COMMENTED** [review]
This should have a release note since it has a breaking change (the `cors` settings). I think we can just say "bump to v0.41.0" of the OpenTelemetry Collector. (this is the changelog entry I wrote for the otlp receiver config https://github.com/DataDog/datadog-agent/blob/b4f03a75f5e5abf51b94a74e5c3fe345708439f8/releasenotes/notes/otlp-receiver-config-8383b827f910e935.yaml)

Otherwise (license-linting thingie aside) this LGTM

**Review by mx-psi — APPROVED** [review]

**Review by apigirl — COMMENTED** [review]
release note is 👍 from a content perspective

**Comment by KSerrania** [comment]
`Serverless Integration Tests` failure is unrelated, I'm going to merge.

**Pull request merged**
