### PR TITLE
make service_discovery disabled by default

### PR DESCRIPTION
**Pull request by rarguelloF**
### What does this PR do?

This PR makes the `service_discovery` corecheck (added in https://github.com/DataDog/datadog-agent/pull/24861) disabled by default.
#incident-28512
### Motivation

Since we need the changes from https://github.com/DataDog/datadog-agent/pull/26672 for the feature to be complete, we will leave it disabled until then.

### Describe how to test/QA your changes

The `service_discovery` check should not be enabled by default:

- Run `agent status collector`
- `service_discovery` should not show up.

If enabled, it should not crash the agent (it could produce error logs in the evp forwarder component in case of misconfigurations).

- Create `service_discovery` conf folder: `mkdir -p /etc/datadog-agent/conf.d/service_discovery.d`
- Create `service_discovery` default config: `echo "instances: [{}]" > /etc/datadog-agent/conf.d/service_discovery.d/conf.yaml.default`
- Check there is a load error if we don't change any config: `agent status collector`:

```
Could not configure check service_discovery: service discovery is disabled
```
- Re-run the agent using the `DD_SERVICE_DISCOVERY_ENABLED=true` env variable and check `service_discovery` is running OK in `agent status collector`
- Do the same test using updating `datadog.yaml` instead of the env variable:
```yaml
service_discovery:
  enabled: true
```

### CODE REVIEW

**Review by f4usto — APPROVED** [review]
lgtm for related agent delivery files

**Review by jeremy-hanna — APPROVED** [review]
LGTM

**Review by jonbodner — APPROVED** [review]

**Comment by chouetz** [comment]
The test failure on `new-e2e-aml` will be solved by #26753

**Pull request merged**
