### PR TITLE
Migrate win32_event_log check to component

### PR DESCRIPTION
**Pull request by clarkb7**
### What does this PR do?

Migrate the win32_event_log check to a component

### Motivation

Prepare to receive Logs Agent component
https://datadoghq.atlassian.net/browse/WINA-698

### Describe how to test/QA your changes

There are automated tests for the functionality of the check.
So QA is just to:
-  ensure agent check command still shows events
```PowerShell
& 'C:\Program Files\Datadog\Datadog Agent\bin\agent.exe' check win32_event_log --check-rate
```
- ensure agent service sends events to backend

example config
```yaml
init_config:
  legacy_mode: false

instances:
  - path: Application
    start: oldest
```

### CODE REVIEW

**Review by iglendd — APPROVED** [review]

**Review by lrbhatia — APPROVED** [review]
LGTM!

**Review by pgimalac — APPROVED** [review]
LGTM for ASC owned files

**Review by gh123man — APPROVED** [review]
AML owned files LGTM

**Pull request merged**
