### PR TITLE
[system-probe] make close channel size configurable

### PR DESCRIPTION
**Pull request by shang-wang**
### What does this PR do?

Currently we have some dropped connections because the buffer would get full. This PR increases the default to 500 and makes it configurable so we retain more connections. cc: @DataDog/burrito 

### Motivation

Less dropped events.

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by sfluor** [comment]
Can we add a test to make sure it's parsed / used correctly ?

**Comment by shang-wang** [comment]
@sfluor I added a test.

**Review by leeavital — APPROVED** [review]

**Comment by sunhay** [comment]
How was 500 chosen? What does this mean for memory?

**Comment by shang-wang** [comment]
Most of the dropped connection counts in prod is under 500 except some spikes, that why I pick the number. From what I can tell, closeChannel would hold ConnectionStats, which are roughly 80 bytes, 500 of them would be 40kb memory, I think we could afford it.

**Review by sfluor — APPROVED** [review]

**Pull request merged**
