### PR TITLE
Refactor configuration to be able to pass a different SSH key per cloud provider

### PR DESCRIPTION
**Pull request by KevinFairise2**
### What does this PR do?

Refactor configuration to allow using a different SSH key per cloud provider.

### CODE REVIEW

**Review by pducolin — APPROVED** [review]

**Comment by pducolin** [comment]
Wonder if we can recommend running `inv setup` from `test-infra` if keys are not found in the config, to update it

**Comment by KevinFairise2** [comment]
> Wonder if we can recommend running `inv setup` from `test-infra` if keys are not found in the config, to update it

Indeed, I'll do a PR on test-infra to update this. I think we just miss the local key configuration, I think the others are already created when running `inv setup`
I will also check the behavior when no keys are configured and print a message, indicating to run `inv setup` if it fails

**Pull request merged**
