### PR TITLE
Allow configuring check cancel timeout

### PR DESCRIPTION
**Pull request by vboulineau**
### What does this PR do?

This PR allows to configure cancel timeout. Stil default to previous value of `500ms`.
It may be required to increase the timeout in certain situation (mostly Python check that are not getting back the GIL or doing long operations).

It's a temporary solution as, ideally, it should be per-check (like `Interval`), and should not block Scheduling/Unscheduling operation if not necessary (e.g. not the same check).

### Describe how to test/QA your changes

An internal grep on `timeout while calling check.Cancel() on check ID` will show if TO has been take into consideration.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by sblumenthal — APPROVED** [review]

**Review by pgimalac — APPROVED** [review]

**Review by vickenty — COMMENTED** [review]
I may be missing some context, but wouldn't this just hide the error message? And as you mention, it can negatively affect scheduling of new checks. What sort of problem we are trying to fix here?

> An internal grep on

Can't this be tested in any other way?

**Comment by vboulineau** [comment]
> I may be missing some context, but wouldn't this just hide the error message? And as you mention, it can negatively affect scheduling of new checks. What sort of problem we are trying to fix here?
> 
> > An internal grep on
> 
> Can't this be tested in any other way?

It won't hide the error message. As-is it does not change anything to the current code.
The goal is allow operators to give more time to checks to perform their `Cancel` operation.

Why? Because on a `timeout` on `Cancel`, the check is kept while the `Unschedule` returns. It means that the same check ID cannot be re-scheduled again, because when it's scheduled again, it will be rejected with a `already running` error (while it's actually not already running).
It's critical for AD (and especially Cluster Checks), because a failed `Unscheduled` may trigger loss of monitoring and it may never recover and take a lot of time to recover (basically the check needs to be re-dispatched). If you have any critical monitor as a service check, it can trigger monitors without reason.
We do observe this for instance with DBM.

It does have an impact on scheduling, _only if there are such checks_, given the low number of `Schedule/Unschedule`, and the time some checks spend in `Configure` it's not really a big concern to me.

**Comment by vickenty** [comment]
Thank you for detailed explanation!

> It does have an impact on scheduling, only if there are such checks, given the low number of Schedule/Unschedule, and the time some checks spend in Configure it's not really a big concern to me.

Lack of negative impact something we should validate in QA as well, besides testing if the fix works.

**Comment by vboulineau** [comment]
> Lack of negative impact something we should validate in QA as well, besides testing if the fix works.

Yes but this PR does not change anything as the default setting is the same as today. And the negative impact will depend on the chosen value. We've already validated that `1s` (Agent) and `2s` (CLC) works fine in internal deployments.

**Review by vickenty — APPROVED** [review]

**Pull request merged**
