### PR TITLE
remove config from installer

### PR DESCRIPTION
**Pull request by raphaelgavache**
Remove agent config templates from installer as agent and installer are now distinct

### CODE REVIEW

**Review by BaptisteFoy — APPROVED** [review]

**Review by chouquette — APPROVED** [review]
The change LGTM, but isn't this premature until the install script generates the config at an earlier stage?

**Review by chouquette — APPROVED** [review]
The change LGTM, but isn't this premature until the install script generates the config at an earlier stage?

**Comment by raphaelgavache** [comment]
It's required to remove those to be installed in parallel with datadog-agent deb/rpm.
Yes it does change the behaviour of agent oci, but since we're not shipping it now to customers it's ok. We'll have to add config templates in it

**Pull request merged**
