### PR TITLE
Revert "Add types to KMT tasks (#23580)"

### PR DESCRIPTION
**Pull request by gjulianm**
This reverts commit 9387a5c1f0cda4bec2f4267477351a6ccd048e8c.

### What does this PR do?

Fix KMT jobs on main

### CODE REVIEW

**Comment by gjulianm** [comment]
>

**Comment by gjulianm** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Review by usamasaqib — APPROVED** [review]

**Review by usamasaqib — APPROVED** [review]

**Pull request merged**
