### PR TITLE
separate system-probe marshal and unmarshal code

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

Separates out the marshalling and unmarshalling code for system-probe into two separate packages.

### Motivation

The receiving side only needs to know about the protobuf format and unmarshalling code. Using separate packages means it doesn't import a whole bunch of types and packages it does not care about.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by hmahmood — APPROVED** [review]
How much of a reduction in binary size are we talking about here?

**Review by derekwbrown — APPROVED** [review]

**Review by guyarb — COMMENTED** [review]
What is the benefit of the change?

**Review by kkhor-datadog — APPROVED** [review]
This doesn't really affect processes functionality, only the connections check in the process agent

**Comment by brycekahle** [comment]
> What is the benefit of the change?

@guyarb This reduces the number of imports that the `agent` and `process-agent` have (see the [bot comment](https://github.com/DataDog/datadog-agent/pull/21334#issuecomment-1841752749)). This may have a size reduction (I'll post numbers in a bit), but it also has a semantic importance. There is no reason for the agent/process-agent to import `pkg/ebpf` and a lot of those `pkg/network` packages.

**Comment by guyarb** [comment]
> > What is the benefit of the change?
> 
> @guyarb This reduces the number of imports that the `agent` and `process-agent` have (see the [bot comment](https://github.com/DataDog/datadog-agent/pull/21334#issuecomment-1841752749)). This may have a size reduction (I'll post numbers in a bit), but it also has a semantic importance. There is no reason for the agent/process-agent to import `pkg/ebpf` and a lot of those `pkg/network` packages.

And on the other hand, it complicates the readability of our project furthermore and separates implementations for marshaling and unmarshaling

Unless it has a significant impact on the binary size i'd prefer to keep the already complicated project a little less complicated

**Comment by brycekahle** [comment]
> Unless it has a significant impact on the binary size i'd prefer to keep the already complicated project a little less complicated

It could long-term. See this [other PR](https://github.com/DataDog/datadog-agent/pull/20757#issuecomment-1841635209) which causes the `ebpf-manager` to be imported into process-agent. There was no way around it (both `linux` and `linux_bpf` build tags have separate problems). This PR would prevent that import.

**Comment by brycekahle** [comment]
> I get that we would like to avoid the indirect import of ebpf-manager

The problem is any new import in `pkg/ebpf` or a bunch of other packages ends up affecting the agent/process-agent.

**Comment by brycekahle** [comment]
The unmarshaller and marshaller don't share any code. The unmarshallers are simple outside of one function to deal with zero values. I don't see how this PR is adding any complexity, it was mostly moving files.

**Comment by brycekahle** [comment]
> The impact on the process-agent is less than 0.5%

That doesn't include the impact `ebpf-manager` and the other imports would have, since I compared against `main` just for this PR.

**Comment by brycekahle** [comment]
Another option is to leave the marshaller alone and move the unmarshaller out into a separate package. That would probably be less code churn.

**Comment by hmahmood** [comment]
My 2c: just reducing the number of imports in process-agent and agent reduces complexity. Anytime you can take out a few edge in the dependency graph that is a win in my book. The imports that were taken out also don't make a lot of sense to have been pulled in in the first place; its great those are gone, it makes more intuitive sense you just pull in what is needed.

**Review by guyarb — APPROVED** [review]

**Pull request merged**
