### PR TITLE
[CI] Remove milestone analysis workflow

### PR DESCRIPTION
**Pull request by amenasria**
### What does this PR do?

This PR removes the milestone Github workflow.

### Motivation

Thanks to #22567 the milestone is now automatically set after merge. This is hence not needed anymore.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by chouquette — APPROVED** [review]
LGTM!
2 related questions:
- Should the associated mention in the reviewer checklist also be removed
- Should we stop providing a milestone in automated PRs?

**Review by buraizu — APPROVED** [review]

**Comment by amenasria** [comment]
@chouquette thanks for the ✅ !
> Should the associated mention in the reviewer checklist also be removed
It will be in #22487, yes !
> Should we stop providing a milestone in automated PRs?
I think both keeping / removing it is fine, but let's remove it to be consistent ! Could you give me an example where we're doing this please ?

**Comment by amenasria** [comment]
Waiting for #22738 to be merged.

**Comment by amenasria** [comment]
@chouquette good point. Here are the PRs:
- omnibus-ruby: https://github.com/DataDog/omnibus-ruby/pull/181
- omnibus-software: https://github.com/DataDog/omnibus-software/pull/509

**Comment by amenasria** [comment]
The `Add milestone` workflow is working 🎉

image

**Review by chouetz — APPROVED** [review]

**Pull request merged**
