### PR TITLE
Remove useless header include in oomkill probe

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

This PR removes the useless
```
#include <linux/ptrace.h>
#include <linux/compiler.h>
```
in oom-kill and tcp queue length probes.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by brycekahle** [comment]
Does the TCP queue length check need this change as well?

**Comment by paulcacheux** [comment]
I think we can remove it on the tcp queue length check as well. I'm still checking if this fix the issue that was reported on bottlerocket

**Comment by brycekahle** [comment]
@paulcacheux Is this fixing a particular compilation error?

**Comment by paulcacheux** [comment]
Yes it fixes an issue on bottlerocket arm64 (Bottlerocket OS 1.5.1).

**Comment by brycekahle** [comment]
@paulcacheux Do we have CI testing of the TCPQ/OOM checks on both x86 and arm64?

**Comment by paulcacheux** [comment]
@brycekahle yes we have tests for all combinations of OS from the kitchen tests of system probe (usually used for the network related tests) and for both prebuilt and runtime compiled.

**Review by brycekahle — APPROVED** [review]

**Review by davidor — APPROVED** [review]

**Pull request merged**
