### PR TITLE
[process-agent] Start process agent on Windows when process discovery is enabled

### PR DESCRIPTION
**Pull request by xornivore**
### What does this PR do?

Starts the process agent service when the `process_config.process_discovery.enabled` flag is enabled.

### Motivation

Support for the process discovery feature in Windows.

### Describe how to test/QA your changes

On Windows, enable the setting in the configuration and make sure that the process agent service starts when the core agent service is started.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno)
  has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or
  [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml)
  has been updated.

### CODE REVIEW

**Review by sgnn7 — APPROVED** [review]

**Review by just-chillin — CHANGES_REQUESTED** [review]
Does this include the case where `process_discovery.enabled = true` but `process_config.enabled = disabled`?

Looking at [IsEnabled](https://sourcegraph.com/github.com/DataDog/datadog-agent@0a8424967bd9e065bf221ed479c545a27ac57777/-/blob/cmd/agent/app/dependent_services.go?L16:22) shows that it may enable the process agent anyway. The reason this is a problem is because if a customer specifies `process_config.enabled = disabled`, but omits the `process_discovery.enabled`, the process agent will turn on anyway since `process_discovery.enabled` defaults to `true`.

**Comment by xornivore** [comment]
> Does this include the case where `process_discovery.enabled = true` but `process_config.enabled = disabled`?
> 
> Looking at [IsEnabled](https://sourcegraph.com/github.com/DataDog/datadog-agent@0a8424967bd9e065bf221ed479c545a27ac57777/-/blob/cmd/agent/app/dependent_services.go?L16:22) shows that it may enable the process agent anyway. The reason this is a problem is because if a customer specifies `process_config.enabled = disabled`, but omits the `process_discovery.enabled`, the process agent will turn on anyway since `process_discovery.enabled` defaults to `true`.

Appreciate the feedback @just-chillin! Technically the case of `"disabled"` is covered by `IsEnabled` here because under the covers, `viper.GetBool` is using `spf13/cast` which [in turn uses](https://github.com/spf13/cast/blob/88075729b052bca4b8b6c31bf198db2fe6c9da93/caste.go#L95) `strconv.ParseBool`, and `"disabled"` results in `false`.

So this code does correctly start the process agent as a dependent service if `process_config.enabled = disabled`, however the agent will exit immediately because there is currently a bug [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/process/config/yaml_config.go#L319-L324). The bug is that we check for `process_config.enabled = false` instead of `process_config.enabled != true`. In the nutshell `process_discovery` cannot currently coexist with container collection. I can fix that in a separate PR.

**Review by just-chillin — APPROVED** [review]
Thanks for fixing that bug! Looks good now :)

**Comment by xornivore** [comment]
> Thanks for fixing that bug! Looks good now :)

Np, it's not really a but to be honest, more like an oversight.

**Pull request merged**
