### PR TITLE
docs: update readme to render sections clearer

### PR DESCRIPTION
**Pull request by miketheman**
### What does this PR do?

When reading the rendered README.md in a browser, the structure and
flow of the paragraphs and sub-bullets is not preserved, leading to
confusion on what options the reader can choose, when and why.

Using spacing and indentation to correct the structure leads to a
more legible rendered output.

### Motivation

I was reading the readme in the browser, and the flow of the items looked incorrect and broken compared to the intended source.

### Additional Notes

I like chocolate chip cookies.

### Describe your test plan

I used Markdown preview both locally and in GitHub to compare before and after.

Wasn't certain if this deserved a `reno`, added one just in case.

### CODE REVIEW

**Review by olivielpeau — CHANGES_REQUESTED** [review]
Thanks Mike! (and good to see you around here :) )

Could you remove the release note? We only use these for changes that affect the end user/the Agent artifacts.

**Review by apigirl — APPROVED** [review]
thanks for these fixes @miketheman!

**Comment by miketheman** [comment]
> Thanks Mike! (and good to see you around here :) )

Good to "see" you too!

> Could you remove the release note? We only use these for changes that affect the end user/the Agent artifacts.

Removed! This would be an excellent addition to the contributing guide near the `reno` details so as to make it clearer what the contributor should expect to add to the changelog.

**Review by mx-psi — APPROVED** [review]
LGTM 🍪

**Review by olivielpeau — APPROVED** [review]
Thanks! Merging

(and addressing your comment on the reno docs here: https://github.com/DataDog/datadog-agent/pull/7389)

**Pull request merged**
