### PR TITLE
Revert "Revert "Change Windows Containers to Windows Server Nano""

### PR DESCRIPTION
**Pull request by julien-lebot**
Reverts DataDog/datadog-agent#5589 since https://github.com/giampaolo/psutil/pull/1768 has been merged.

### CODE REVIEW

**Review by albertvaka — APPROVED** [review]
We need to bump the dependencies on psutils (I think they all are in integrations-core) to include the fixed version as well.

**Comment by tonyredondo** [comment]
Hi! ✋  do you know what is this PR missing to get merged? We are working in the CI/CD integration project and launching the agent in a windows pipeline take too long due the image size, we think this would help us a lot.

**Comment by mx-psi** [comment]
I believe we just have to bump psutils, let me open a PR for that.

**Comment by tonyredondo** [comment]
> I believe we just have to bump psutil, let me open a PR for that.

Great! and I've just saw that it got merged! 🎉

**Pull request merged**
