### PR TITLE
Copy datadog-trace-agent into repository

### PR DESCRIPTION
**Pull request by gbbr**
This PR merges the trace-agent repository into this repository.

* Main package goes into `cmd/trace-agent`
* All trace agent sub-packages go into `pkg/trace`

Current status:

* Build pipeline and CI passing.
* Omnibus builder for Agent 6 successful with new location.
* ❗️dd-agent-omnibus builder still in progress.

#### TODO:

- [x] Update `omnibus`
- [ ] Update [dd-agent-omnibus](https://github.com/DataDog/dd-agent-omnibus/) (https://github.com/DataDog/dd-agent-omnibus/pull/351)

### CODE REVIEW

**Comment by ajacquemot** [comment]
Can you open several PRs so that it ease reviews:
- a first containing the `mv` to `./pkg`
- a second containing the bridge in `./cmd`
- a third containing the change in `inv`
- ...
Many thanks

**Comment by gbbr** [comment]
I don’t think that’s a good idea. I think there should be one PR after
which everything works: the pipeline, omnibus, etc. No point to have
multiple broken PRs.

I will however try to make separate clean commits outlining the work.

**Comment by gbbr** [comment]
P.S. will let you know when it’s ready for review and there will be one
commit for each one of the bullet points in your list.

**Comment by ajacquemot** [comment]
This should work if they point to this branch, it's up to you.

**Review by derekwbrown — CHANGES_REQUESTED** [review]
there's also one file missing from `.gitignore`.  I can add it, and you can squash it, or ??  How would you like to do it?


also, pkg/trace/info/git_version.go is checked in, and gets modified every build, so it gets confused.  IMO that should be deleted from the repo and also added to .gitignore?

**Comment by gbbr** [comment]
> also, pkg/trace/info/git_version.go is checked in, and gets modified every build, so it gets confused. IMO that should be deleted from the repo and also added to .gitignore?

It's in `.gitignore`. I've left it in the repo to avoid people getting build time errors when trying to build the trace agent. I think that should be fine, no?

**Review by derekwbrown — DISMISSED** [review]
Looks good to me...

**Review by derekwbrown — APPROVED** [review]

**Review by gmmeyer — APPROVED** [review]
I think this looks great! congrats on merging it in

**Pull request merged**
