### PR TITLE
fix domain test logfile

### PR DESCRIPTION
**Pull request by clarkb7**
### What does this PR do?

Fix path of installer log file in domain tests

### Motivation

https://github.com/DataDog/datadog-agent/pull/23174 moved the `InstallMSI` call from base to the agent package so the default application of the `OutputDir` prefix was lost.

### Possible Drawbacks / Trade-offs

We could still have base add the `OutputDir` prefix if the logfile option is just a filename, but then passing `WithInstallLogFile` to `suite.InstallAgent` would have different behavior than  `windowsAgent.InstallAgent` and that seems confusing.

### CODE REVIEW

**Review by iglendd — APPROVED** [review]

**Review by richl-dd — APPROVED** [review]

**Comment by clarkb7** [comment]
rebase for fix for serverless size

**Pull request merged**
