### PR TITLE
[ASCII-2578] Remove seelog imports outside pkg/util/log

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?
Remove most direct uses of https://github.com/cihub/seelog outside of `pkg/util/log` (and enforce it with a linter).

It does so by creating aliases for constants (log levels), types (`LoggerInterface`), and functions (a few basic functions to create a logger) of seelog in `pkg/util/log`.

### Motivation
Avoid leaking the agent logging abstraction (no code should rely on `seelog` directly, only `pkg/util/log`).
This will make it much easier to replace `seelog` with another library.

### Describe how you validated your changes

There should be no functional change, only aliases, so CI is considered good enough.

Two tests called `seelog.ReplaceLogger` (on top of `log.SetupLogger`), which should not be needed, the PR removes these two calls, this should be the only change in behavior.
The two tests are in `comp/trace/config/config_test.go` and `pkg/util/kubernetes/apiserver/controllers/wpa_controller_test.go`.

### Additional Notes

https://github.com/cihub/seelog didn't get a single commit in 8 years, it is unmaintained, and we should probably not be using it anymore.

There are a few remaining uses of seelog outside of `pkg/util/log`:
- `cmd/agent/common/common_windows.go`: initialize the logger on Windows with a specific config
- `pkg/process/procutil/process_linux_test.go`: disable logging from `DataDog/gopsutil`
- `pkg/ebpf/ebpftest/log.go`: creating a custom logger for testing
- `pkg/ebpf/ebpftest/fail_log.go`: creating a custom logger for testing

### CODE REVIEW

**Comment by pgimalac** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by guyarb — APPROVED** [review]

**Review by akarpz — APPROVED** [review]

**Review by paulcacheux — APPROVED** [review]

**Review by ajgajg1134 — APPROVED** [review]
looks good for the trace-agent!! Thanks for taking on this work!

**Review by ogaca-dd — APPROVED** [review]

**Review by vickenty — APPROVED** [review]

**Review by clamoriniere — APPROVED** [review]

**Review by jesssu7 — APPROVED** [review]

**Review by zoedt — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]

**Review by L3n41c — APPROVED** [review]
👍🏻 LGTM for file owned by @DataDog/container-integrations.

**Review by TCheruy — APPROVED** [review]

**Review by kkhor-datadog — APPROVED** [review]

**Review by alexgallotta — APPROVED** [review]

**Review by hmahmood — APPROVED** [review]

**Review by aureleoules — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Review by brycekahle — APPROVED** [review]

**Pull request merged**
