### PR TITLE
Added task to generate a gitlab ci config subset

### PR DESCRIPTION
**Pull request by CelianR**
### What does this PR do?

> [!NOTE]
> I added an `experimental` decorator that prints a warning with details when running the task

Adds `gitlab.gen-config-subset` that is able to generate a subset of the config in order to run the target provided jobs without running the whole pipeline.
It adds only the provided jobs, the jobs that depend on them, the config attribute (`variables`...) and some jobs to keep (such as `cancel-prev-pipelines`).

[Example](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/38429098) with `inv gitlab.gen-config-subset tests_rpm-arm64-py3,tests_deb-arm64-py3`:

Screenshot 2024-07-05 at 12 26 50

Note that now it always adds the jobs within the `jobs_to_keep` variable

### CODE REVIEW

**Review by KevinFairise2 — APPROVED** [review]
I think that's very interesting to be able to run a subset of the pipeline for some specific use case.

I just have a little concern. With that we build the pipeline with explicit needs between jobs. However the implicit ones that are due to stage order are not shown in the generated smaller pipeline.
As an example if you create a pipeline that target `trigger_auto_staging` release job. You will get a pipeline with the `jobs_to_keep` and only the `trigger_auto_staging` job. Which will not work because the release job expect the build artifacts.

However I do not think this should prevent the birth of this feature and we could maybe just warn that it will not work if you target jobs with implicit dependencies

**Comment by CelianR** [comment]
> I think that's very interesting to be able to run a subset of the pipeline for some specific use case.
> 
> I just have a little concern. With that we build the pipeline with explicit needs between jobs. However the implicit ones that are due to stage order are not shown in the generated smaller pipeline. As an example if you create a pipeline that target `trigger_auto_staging` release job. You will get a pipeline with the `jobs_to_keep` and only the `trigger_auto_staging` job. Which will not work because the release job expect the build artifacts.
> 
> However I do not think this should prevent the birth of this feature and we could maybe just warn that it will not work if you target jobs with implicit dependencies

I added a warning on stderr to explain this, thanks for the information 👍

**Review by amenasria — APPROVED** [review]
LGTM !

**Pull request merged**
