### PR TITLE
Update github.com/spf13/cast to latest

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?
Update `github.com/spf13/cast` to the latest in each module, and explicitly replace with the fork where needed.

### Motivation
When running tests we use the version specified in each module, which is not the same as the one used to build the agent. Having the same version everywhere avoids this issue.
When using a go.work, go also uses the replaced version when running tests, and they actually fail, so this PR unblocks https://github.com/DataDog/datadog-agent/pull/31214.

### Describe how to test/QA your changes
Relying on CI to catch issues

### CODE REVIEW

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by hush-hush — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]

**Review by remeh — APPROVED** [review]
LGTM for files owned by APR

**Review by L3n41c — APPROVED** [review]
👍🏻 LGTM for files owned by @DataDog/container-integrations.

**Review by carlosroman — APPROVED** [review]

**Review by amenasria — APPROVED** [review]

**Review by mellon85 — APPROVED** [review]

**Review by dinooliva — APPROVED** [review]

**Pull request merged**
