### PR TITLE
[system-probe] Disable netlink OS thread lock when possible

### PR DESCRIPTION
**Pull request by p-lambert**
### What does this PR do?

Avoid locking an OS thread for netlink socket pooling when system-probe is already running on root network namespace.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by kevinconaway — APPROVED** [review]
Is the cause of the issues we saw in plain1?

**Comment by p-lambert** [comment]
> Is the cause of the issues we saw in plain1?

Not really, but it's low hanging fruit that might yield some performance gain. Worth a try!

**Comment by brycekahle** [comment]
It looks like if we upgrade the `mdlayher/netlink` library, this PR wouldn't be needed anymore: https://github.com/mdlayher/netlink/commit/26242dd2484ccabf0602351419eb0eaf8f18115b

> v1.2.0
...
[Performance] #171: netlink.Conn no longer requires a locked OS thread for the vast majority of operations, which should result in a significant speedup for highly concurrent callers. Thanks @ti-mo.

**Comment by ti-mo** [comment]
Hi, we've deprecated the `DisableNSLockThread` flag in 1.2.0 as the underlying behaviour that caused the performance impact has been removed. The library now only keeps the OS thread locked for the duration of `Dial()` in the given netns. Once the socket has been created, the thread is migrated back to its original netns and unlocked.

Simply upgrading the dependency should solve this for you. :slightly_smiling_face:

**Comment by p-lambert** [comment]
Thanks for the updates, folks. I'm closing this PR since this code is very outdated and the netlink code was completely refactored since then. 
We should definitely restrict the LockOSThread during the socket creation on root namespace as suggested by @ti-mo (this is actually we do already when we create the raw socket used for DNS traffic inspection 😄)

**Pull request closed without merging**
