### PR TITLE
[ASCII-2203] Add mandatory params to Eventplatform Module

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?
This PR adds a mandatory parameter to the Eventplatform `Module()` in order to replace
```go		
eventplatformimpl.Module(),
fx.Supply(eventplatformimpl.NewDefaultParams()),
```
by
```go
eventplatformimpl.Module(eventplatformimpl.NewDefaultParams()),		
```

### Motivation
By adding the parameter to the `Module` function, a user of Eventplatform doesn't have to guess that `Eventplatform.Params` is mandatory

### Describe how to test/QA your changes
QA done by running unit tests and E2E tests.

### CODE REVIEW

**Comment by ogaca-dd** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by NouemanKHAL — APPROVED** [review]

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by GustavoCaso — APPROVED** [review]
LGTM

**Review by daniel-taf — APPROVED** [review]

**Review by vickenty — APPROVED** [review]

**Review by jmw51798 — APPROVED** [review]

**Review by remeh — APPROVED** [review]

**Pull request merged**
