### PR TITLE
command line ipc client

### PR DESCRIPTION
**Pull request by derekwbrown**
Curl is not usable for the IPC on windows, as it doesn't support named pipes (the transport on windows).
This PR creates a command line program (all platforms) for testing/using the ipc mechanism.

### CODE REVIEW

**Review by hush-hush — COMMENTED** [review]
Added a couple of comment/questions. Also is it worth it to add unit test for commands (testing they connect to the right endpoint) or are we planning directly to do system tests ?

**Review by masci — CHANGES_REQUESTED** [review]
Why a new app and not adding more features to the main CLI interface in `cmd/agent`?

**Review by gmmeyer — CHANGES_REQUESTED** [review]
I have the same inquest as @masci, this feels like it should be merged into the main cli (unless there's a compelling reason otherwise).

I have one comment, small typo, otherwise this seem pretty good to me. :)

**Review by gmmeyer — APPROVED** [review]
I'm happy that the criticisms I made were addressed, I'll approve so as not to be a blocker

**Review by masci — APPROVED** [review]

**Pull request merged**
