### PR TITLE
Improve ecs_fargate tagging

### PR DESCRIPTION
**Pull request by xvello**
### What does this PR do?

- Honor the `docker_labels_as_tags` option to extract custom tags (factor code from the docker collector)
- Parse the arn out of the `cluster_name` tag
- Add the `short_image` and `container_id` tags
- Remove tag blacklist (handled by using `docker_labels_as_tags` whitelisting instead)
- Merge `pullMetadata` and `fetchMetadata` into a single method
- Remove custom `lastSeen` logic and use `taggerutil.Expire` instead
- Fix `Fetch` lifecycle issue: if several `Fetch` are triggered in rapid succession (first container list), we might end with empty tags for some containers, as they might be already seen by previous runs, but not imported in the store yet:
  - when `Fetch`ing, parse all containers, return the one we are looking for
  - when `Pull`ing, only parse unknown containers
- Add testing

This might increase `Fetch`'s CPU usage, but worst case scenario is once per container in the whole agent lifecycle

**Classic ECS has the same issue**, whall we fix it in the same PR?

Result:

### CODE REVIEW

**Comment by xvello** [comment]
@CharlyF would love some feedback on the lifecycle changes if you have some time

**Review by hkaj — COMMENTED** [review]
Sweet, tags look so much better 😎
Tests are failing on `TestParseMetadata`, could you look into it?
Also noticed a typo but looks good otherwise 🍪

**Review by hkaj — APPROVED** [review]
🎉

**Pull request merged**
