### PR TITLE
Add default values for boolean OTLP config options

### PR DESCRIPTION
**Pull request by liustanley**
### What does this PR do?
Adds default values (false) for boolean OTLP config options.

### Motivation
Fixes the following bug which was found in https://github.com/DataDog/datadog-agent/pull/30061 when upgrading dependencies:
```
2024-10-29 17:59:31 UTC | CORE | ERROR | (comp/otelcol/collector/impl-pipeline/pipeline.go:111 in func1) | Error running the OTLP ingest pipeline: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': error reading configuration for "serializer": decoding failed due to the following error(s):

error decoding '': decoding failed due to the following error(s):

'metrics.resource_attributes_as_tags' expected type 'bool', got unconvertible type 'string', value: 'true'
```

### CODE REVIEW

**Comment by jackgopack4** [comment]
do we need to have user-facing documentation or is this not something the user can configure, just us internally?

**Review by ogaca-dd — APPROVED** [review]
LGMT for files owned by ASC

**Comment by L3n41c** [comment]
I’ve temporarily marked the `TestOTLPIngest` otel e2e as flaky until this fix is merged.
Let’s not forget to unmark it by reverting this change in this PR: https://github.com/DataDog/datadog-agent/pull/30061/commits/44799265fbbfe0e1de675f2e26998c7ed8d38406

**Comment by jackgopack4** [comment]
@liustanley we don't need this anymore right?

**Comment by liustanley** [comment]
> @liustanley we don't need this anymore right?

Yes this can be closed, this issue was fixed in another PR

**Pull request closed without merging**
