### PR TITLE
[gitlab][gopkg] fix gopkg lock generation + android build

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

Because we’re having to resort to: `DEPPROJECTROOT="/src/github.com/DataDog/datadog-agent"` in the containers for `dep` to work properly due to the weird `GOPATH`, the `github.com/DataDog/datadog-agent` pkg is getting vendored too, which is weird. This doesn't appear to happen when you locally `inv deps` (and `DEPPROJECTROOT` is not set).

We maybe should update the `GOPATH` stuff in the builders, to avoid having it in `/`, but until then this manual cleanup allows for a successful build.

### Motivation
- Undefined builds (using vendored `datadog-agent` pkg 🙈)
- Broken android gitlab build.

### CODE REVIEW

**Review by olivielpeau — COMMENTED** [review]
`inv agent.omnibus-build` also runs the `deps` task which will itself run `dep ensure`, so we probably have to perform the same cleanup there

**Review by olivielpeau — COMMENTED** [review]
I was able to test a resulting debian package, where there was a related issue of the paths in `-X` ldflags not being taken into account properly (and as a result, `py.pythonHome` not being set correctly, which causes the system python to be loaded instead of the embedded one on the packaged Agent). I can confirm this issue has been fixed on the debian package, and that all vars set through the `-X` ldflags are set properly.

We should confirm this on all the other packaged Agents.

A couple of other comments:
* I see a _lot_ of changes on the revisions in `Gopkg.lock`. I understand these revision changes are allowed by our version constraints in `Gopkg.toml`, but I don't think these constraints are strict enough and we must have a plan to review and confirm all these version bumps won't introduce regressions
* I think the removal of the vendored datadog-agent should only be done in the logic of the `deps` task, unless there's a good reason to add it to .gitlab too

**Review by olivielpeau — DISMISSED** [review]
👍 let's merge as soon as gitlab is ✅ 

can you update the PR description?

**Comment by truthbk** [comment]
Gitlab is 💚 - merging!

**Pull request merged**
