### PR TITLE
Add a `only-modified-packages` option to the `linter.go` task

### PR DESCRIPTION
**Pull request by FlorentClarret**
### What does this PR do?

Add a `only-modified-packages` option to the `linter.go` task, so we can now run: 

```
❯ inv linter.go --only-modified-packages
```

This works exactly the same way `inv test --only-modified-packages` works

### Motivation

We would like to be able to run linters in a pre-commit hook, but there's no need to run linters on everything. This is the first step and we will add the hook once merged.

### CODE REVIEW

**Review by pducolin — APPROVED** [review]
<3

**Review by amenasria — APPROVED** [review]
LGTM ! Not a big fan of importing a task and use it as a function as it duplicates the task in the namespace where it's imported.

But since you're importing it in the function, it's not duplicated !
```
git checkout florentclarret/linter_modified_files
inv -l | grep "get-modified-packages"
```

**Comment by FlorentClarret** [comment]
> LGTM ! Not a big fan of importing a task and use it as a function as it duplicates the task in the namespace where it's imported.
> 
> But since you're importing it in the function, it's not duplicated !
> 
> ```
> git checkout florentclarret/linter_modified_files
> inv -l | grep "get-modified-packages"
> ```

Yup that's why I locally imported it. Happy to do it another way if you think there's a better alternative though!

**Comment by amenasria** [comment]
We talked about this back then with the team and the cleanest way we thought about was to create a `_my_task` function that you'll pass to the `my_task` invoke task function

**Comment by FlorentClarret** [comment]
> We talked about this back then with the team and the cleanest way we thought about was to create a `_my_task` function that you'll pass to the `my_task` invoke task function with the content of the task.

The main problem with this approach is that it add another layer of complexity in the code, which I don't think is a good idea. 

Having a local import is fine imo, it reduces code complexity in this case and in some cases is slightly more performant because we import only if needed (even though performance is not a problem in our case). I'll keep it that way for now if you don't mind

**Pull request merged**
