### PR TITLE
fix kitchen test

### PR DESCRIPTION
**Pull request by ian28223**
### What does this PR do?

Workaround the sleep hack in kitchen test

### Motivation

- AC-761

### Additional Notes

I've ran several rounds of kitchen tests and they seem to be working well. Link to pipelines below.
- (Datadog internal-only) https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/3895711
- (Datadog internal-only) https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/3907347

Some tests may have failed but are unrelated to the kitchen tests.

### CODE REVIEW

**Review by albertvaka — APPROVED** [review]
LGTM as a workaround, but would there be any way to move this logic to the Agent itself? Right now, any user trying to do something when the Agent starts (like we do for kitchen tests) needs to mimic this logic in their code.

**Comment by olivielpeau** [comment]
> LGTM as a workaround, but would there be any way to move this logic to the Agent itself? Right now, any user trying to do something when the Agent starts (like we do for kitchen tests) needs to mimic this logic in their code.

@albertvaka At a high level I think there are 2 ways to signal to the user or system that the Agent is actually ready:

1. through the service manager/init system: in this case the Agent service wouldn't be marked as running by the service manager until it's actually ready: 

  * on Linux this could be possible when systemd is used, by using `Type=notify` (see [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options)) and making the Agent notify systemd when it's "ready". This doesn't exist with `upstart` though. With sysvinit it could be implemented manually in the init scripts I guess if we wanted it.
  * on Windows the agent would only signal to the SCM that its service is running once it's "ready"
  * on containerized environments, the readiness probe fulfills this purpose.
2. with an agent command: I don't think an agent command could be much smarter/useful than "running `agent status` and checking whether it's successful" (basic check that agent is running) or the existing `agent health` command (thorough check that agent components are running, closer to liveness check on containerized envs).

We could explore doing `1.` for more systems (systemd and Windows), in which case we'd want to define what the "ready" state should actually guarantee on these systems, but I don't see a strong use case today. Our kitchen tests need to cover scenarios where the Agent is completely broken, but most users could rely on the return code of `agent status` or the output of `agent health` depending on the use case in their tests/automation.

WDYT?

**Comment by albertvaka** [comment]
I agree that doing only systemd and Windows would be enough. Given both platforms provide a way for services to signal they are ready, IMO we should be "good citizens" on those platforms by doing that. I agree with you that the use cases are rare so probably it's not a top priority, but on the other hand we have a use case ourselves, and any time we spend coding workarounds could be spent adding the feature.

**Comment by olivielpeau** [comment]
I agree with the general sentiment, but I think this is a case where the internal workaround is orders of magnitude simpler than defining and implementing the "correct" fix to cover systemd and Windows. Adding a card in backlog for this (see AC-822 internally), not sure if this should be owned by the platform or core team 🤔

**Pull request merged**
