### PR TITLE
Remove dependency from metrics to serializer

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?

Remove the dependency from `metrics` package to `serializer`. 
This PR moves the metrics serialization logic to the new package `metricsserializer`.

This is a big PR but there is no code change. Functions were moved from the `metrics` package to the  `metricsserializer` package. The content of the functions did not changed.
It is recommend to review commit by commit.

Note: The content of `metricsserializer` will be moved to `pkg/serializer/metrics` in a later PR.

### Motivation

`serializer` package must depend on `metrics` and not the opposite.
One of the drawback of having `metrics` depends on `serializer` is that is require to have many interfaces: https://github.com/DataDog/datadog-agent/blob/df965be7ee8bb02173efb0a6ae308bd304a4613b/pkg/serializer/marshaler/marshaler.go#L15-L53 Another PR will remove these interfaces.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The appropriate `team/..` label has been applied, if known.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
Nice!!

**Review by mx-psi — APPROVED** [review]
Changes in serializerexporter look good

**Review by sgnn7 — APPROVED** [review]
@ogaca-dd Nice improvement! 

PS: I re-triggered the failed `tests_macos` pipeline build stage since it looked like it might have been a flake so hopefully it passes this time.

**Comment by djmitche** [comment]
The macos needs a rebase, I think

**Pull request merged**
