### PR TITLE
Add `--service` to `stream-logs`

### PR DESCRIPTION
**Pull request by keisku**
### What does this PR do?

Add `--service` flag to `stream-logs` command.

### Motivation

Because I want to filter the logs in more detail.

### Describe how to test/QA your changes

1 ) Build the Agent at [this branch](https://github.com/keisku/datadog-agent/tree/add_service_steram-logs_filter) according to https://github.com/DataDog/datadog-agent#getting-started

2 ) Confirm the `Flags`

I can see `--service string   Filter by service`.

1  keisuke_umegaki_datadoghq_com@keisuke-vm-201 _gosrcgithub comkeiskudatadog-agent 2022-03-17 at 10 23 18 PM

3 ) Create the log config for test.

```bash
touch ~/test.log
```

Write the configuration in `/bin/agent/dist/conf.d/tttttest.d/conf.yaml`.

```yaml
logs:
 - type: file
   path: /home/keisuke_umegaki_datadoghq_com/test.log
   source: test_log
   service: test_log
```

4 ) Run the Agent

```bash
sudo ./bin/agent/agent run -c ./bin/agent/dist/datadog.yaml > /dev/null 2>&1 &
```

5 ) Write logs to `~/test.log`

```bash
while true; do echo "hello at $(date)" >> ~/test.log; sleep 2; done &
```

6 ) See streamed logs

```bash
sudo ./bin/agent/agent stream-logs --service=test_log -c ./bin/agent/dist/datadog.yaml
```

Screen Recording 2022-03-17 at 10 28 37 PM

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by djmitche — COMMENTED** [review]
Agreed with @gh123man.  QA steps would basically entail making sure the existing functionality (no --source) and new functionality both work.

**Comment by keisku** [comment]
@gh123man @djmitche 
Thank you for your review! I created the release note and QA steps in the PR description.

**Review by gh123man — APPROVED** [review]
Excellent QA steps 👌

**Review by urseberry — APPROVED** [review]

**Review by djmitche — APPROVED** [review]

**Comment by gh123man** [comment]
@keisku Sorry for the delay! I didn't realize you didn't have permission

**Pull request merged**
