### PR TITLE
Correct description about custom ntp.d config from ntp.yaml to conf.yaml

### PR DESCRIPTION
**Pull request by guitared**
### What does this PR do?
Correct the description for inline comment with official docs (https://docs.datadoghq.com/integrations/ntp/#configuration)

It said to edit the file called `ntp.d/conf.yaml` but in comment you said `ntp.d/ntp.yaml`.

### Motivation
I am confuse when I have to go through this custom configuration. Just to correct it.

### Additional Notes
n/a

### Possible Drawbacks / Trade-offs

none

### Describe how to test/QA your changes

just prove that my correction make sense.

### CODE REVIEW

**Review by hush-hush — APPROVED** [review]

**Comment by dustmop** [comment]
Thanks for the fix, @guitared! Your change has been approved and is going to be merged soon.

**Comment by guitared** [comment]
seems like the merge is timeout.
@dustmop @hush-hushcould you please help check the status again?
I want to clean up my local patch repo, many thanks.

**Pull request merged**
