### PR TITLE
Make endianness a compile time decision

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

Move the endianness determination to compile time based on architecture.

This results in a reduction of the instructions necessary for endian-related operations. The wall clock time difference for a single call is miniscule (picoseconds).

An example, with the `ByteOrder.Uint32` function:
Runtime instructions: https://godbolt.org/z/fPor6abqf
Buildtime instructions: https://godbolt.org/z/PnKa7z7G5

The function call on amd64 changes from:
```
MOVQ    "".NativeEndian(SB), CX
MOVQ    "".NativeEndian+8(SB), DX
MOVQ    32(CX), CX
MOVQ    "".~R0+40(SP), SI
SARQ    $31, SI
MOVQ    AX, BX
MOVL    $4, DI
MOVQ    DX, AX
MOVQ    CX, DX
MOVQ    DI, CX
PCDATA  $1, $1
CALL    DX
```
to
```
MOVQ    "".~R0+40(SP), CX
SARQ    $31, CX
MOVL    CX, (AX)
```
The difference on arm64 is equivalent, but uses different specific instructions.

The exact instructions are not important, but that this allows the optimizer to make better decisions and output better instructions.

### Motivation

Improve runtime performance.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by hmahmood — APPROVED** [review]

**Review by xornivore — COMMENTED** [review]
Looks great, mind adding some QA instructions? Is there any merit in adding some really basic tests in `pkg/util/native`?

**Review by hush-hush — APPROVED** [review]

**Comment by nplanel** [comment]
it's not replacing to XCHGL   AX, AX (it's a nop)   (gobolt confuse you with their color line matching)
the optimizer do a better job, probably because it give a pointer of the stack where the array has been loaded
        MOVUPS  X15, ""..autotmp_14+48(SP)

**Review by nplanel — CHANGES_REQUESTED** [review]
we would need to test from an indirect values (from an byte array pointer)

**Comment by brycekahle** [comment]
> Is there any merit in adding some really basic tests in `pkg/util/native`?

@xornivore I'm not sure what you would test?

**Comment by brycekahle** [comment]
> we would need to test from an indirect values (from an byte array pointer)

@nplanel Updated the test with non-constant values, and updated the comment.

**Comment by xornivore** [comment]
> > Is there any merit in adding some really basic tests in `pkg/util/native`?
> 
> @xornivore I'm not sure what you would test?
I meant the basics of byte order correctness but for all supported platforms? I guess the hope is it is indirectly tested outside of the package in various uses of it. A slight concern - it touches some platforms which may not be supported by `process-agent` `procutil` code (correct me if I am wrong), but then it's not the only place affected.

**Review by xornivore — APPROVED** [review]

**Review by nplanel — APPROVED** [review]

**Pull request merged**
