### PR TITLE
improve murmur3 perf

### PR DESCRIPTION
**Pull request by arbll**
### What does this PR do?

Speed up the generation of context keys.

### Motivation

Aggregator hot-path, any improvement there will speed up dogstatsd processing as a whole.

### Notes

- Sorting is the most expensive part of this operation
- Results should be even better with dogstatsd once we use `[]byte`s as the lib has a streaming mode for `[]byte` that does not require us to move everything to a temp `[]byte` buffer. We could adapt the library to deal with strings but it's probably not worth it for regular integration metrics.

### Results

```
benchmark                             old ns/op     new ns/op     delta
BenchmarkKeyGeneration/1-tags-4       128           31.5          -75.39%
BenchmarkKeyGeneration/2-tags-4       138           43.7          -68.33%
BenchmarkKeyGeneration/4-tags-4       211           84.9          -59.76%
BenchmarkKeyGeneration/8-tags-4       440           267           -39.32%
BenchmarkKeyGeneration/16-tags-4      1295          1006          -22.32%
BenchmarkKeyGeneration/32-tags-4      1859          1305          -29.80%
BenchmarkKeyGeneration/64-tags-4      4434          3455          -22.08%
BenchmarkKeyGeneration/128-tags-4     9737          7909          -18.77%

benchmark                             old allocs     new allocs     delta
BenchmarkKeyGeneration/1-tags-4       0              0              +0.00%
BenchmarkKeyGeneration/2-tags-4       0              0              +0.00%
BenchmarkKeyGeneration/4-tags-4       0              0              +0.00%
BenchmarkKeyGeneration/8-tags-4       0              0              +0.00%
BenchmarkKeyGeneration/16-tags-4      0              0              +0.00%
BenchmarkKeyGeneration/32-tags-4      1              1              +0.00%
BenchmarkKeyGeneration/64-tags-4      1              1              +0.00%
BenchmarkKeyGeneration/128-tags-4     1              1              +0.00%

benchmark                             old bytes     new bytes     delta
BenchmarkKeyGeneration/1-tags-4       0             0             +0.00%
BenchmarkKeyGeneration/2-tags-4       0             0             +0.00%
BenchmarkKeyGeneration/4-tags-4       0             0             +0.00%
BenchmarkKeyGeneration/8-tags-4       0             0             +0.00%
BenchmarkKeyGeneration/16-tags-4      0             0             +0.00%
BenchmarkKeyGeneration/32-tags-4      32            32            +0.00%
BenchmarkKeyGeneration/64-tags-4      32            32            +0.00%
BenchmarkKeyGeneration/128-tags-4     32            32            +0.00%
```

TODO:
- Confirm this lib is safe to use
- Check that thread safety is good

### CODE REVIEW

**Review by ogaca-dd — CHANGES_REQUESTED** [review]
Current code LGTM. Some tests failed.

**Comment by olivielpeau** [comment]
Haven't gone through your changes in details, but is the switch to the `twmb/murmur3` library an important part of the perf improvements?

Asking specifically because it looks like `twmb/murmur3` has a native assembly implementation on for amd64 processors, and the library the Agent currently uses (`DataDog/mmh3`) has an implementation that's also specific to amd64 processors (`Hash128x64` function) that we don't use at the moment. So I'm wondering:
* how much of the perf gains you noticed are related to the arch-specific code/implementation
* what the results look like on non-amd64 processors

**Comment by arbll** [comment]
vs `datadog/mmh3` with all the improvements in this PR
```
benchmark                             old ns/op     new ns/op     delta
BenchmarkKeyGeneration/1-tags-4       31.1          63.6          +104.50%
BenchmarkKeyGeneration/2-tags-4       42.7          90.4          +111.71%
BenchmarkKeyGeneration/4-tags-4       84.4          163           +93.13%
BenchmarkKeyGeneration/8-tags-4       256           389           +51.95%
BenchmarkKeyGeneration/16-tags-4      996           1260          +26.51%
BenchmarkKeyGeneration/32-tags-4      1274          1859          +45.92%
BenchmarkKeyGeneration/64-tags-4      3425          4523          +32.06%
BenchmarkKeyGeneration/128-tags-4     8238          10317         +25.24%
```

vs `datadog/mmh3` with all the improvements in this PR using `WriteHash128x64`
```
benchmark                             old ns/op     new ns/op     delta
BenchmarkKeyGeneration/1-tags-4       31.1          44.3          +42.44%
BenchmarkKeyGeneration/2-tags-4       42.7          53.2          +24.59%
BenchmarkKeyGeneration/4-tags-4       84.4          108           +27.96%
BenchmarkKeyGeneration/8-tags-4       256           293           +14.45%
BenchmarkKeyGeneration/16-tags-4      996           1082          +8.63%
BenchmarkKeyGeneration/32-tags-4      1274          1473          +15.62%
BenchmarkKeyGeneration/64-tags-4      3425          3902          +13.93%
BenchmarkKeyGeneration/128-tags-4     8238          8921          +8.29%
```

There is probably some error margin here but it seems that `twmb/murmur3` is a bit faster. The nice thing about it is that it automatically selects the correct implementation a build time. Even if the difference is small, this path gets very hot when we receive lots of samples.

I'll add more data once I have a chance to run this against our harness and on a few roles to get some real world usage.

**Review by olivielpeau — DISMISSED** [review]
LGTM, thanks for the additional details.

FWIW the `github.com/twmb/murmur3` lib appears to be well-tested internally as well (see https://github.com/twmb/murmur3#testing).

Approving, but FYI there are some conflicts on the Gopkg files that need to be solved.

**Comment by arbll** [comment]
Had to rework a bunch of testing code that was relying on sorting by context keys (endianness changed).

**Pull request merged**
