### PR TITLE
[JMX] Stop passing "confd_path" to JMX fetch

### PR DESCRIPTION
**Pull request by ISauve**
### What does this PR do?

Removes the "--conf_directory" parameter from our call to JMX fetch, because this option is only for sending a check via a named pipe (and thanks to https://github.com/DataDog/datadog-agent/pull/604, agent 6 exclusively uses the API and not named pipes).

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by ISauve** [comment]
[[jmx fetch] Address changed structure of the conf.d directory](https://trello.com/c/AbUN9V0l/458-jmx-fetch-address-changed-structure-of-the-confd-directory)

**Review by truthbk — APPROVED** [review]
Looks good but we shouldn't merge until a new JMXFetch version with the respective changes (see https://github.com/DataDog/jmxfetch/pull/161) is released or this will break the agent's interactions with JMX.

**Review by truthbk — DISMISSED** [review]
You'll have to update a few things:
https://github.com/DataDog/datadog-agent/blob/1979267b08a27bf07b3a1af42b7ba3ce20304ac6/omnibus/config/software/jmxfetch.rb#L8
https://github.com/DataDog/datadog-agent/blob/671b00bbc6a10d0b821f3d1d1c9b62aaf1aaabbd/pkg/collector/corechecks/embed/jmx.go#L30

So that they point to `0.18.1` - the new default

**Review by olivielpeau — APPROVED** [review]
LGTM

**Pull request merged**
