### PR TITLE
Recommend a third imports section for local imports, and add a one-time fix to do so

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Runs `goimports` to verify imports are correctly formatted, including putting local imports in a third section.

### Motivation

We've long had a style guide suggesting putting local imports in a third section, but with no enforcement we (mostly me) have gotten this wrong in 600+ files.

### Additional Notes

* This may be a bit slow -- maybe too slow to run in `inv test`?
* This will run in all of the unit-tests jobs.  Should it not do so, and instead run in a new `goimports` job so that it's clear when it fails what has gone wrong?
* This may be annoying for people whose editors are not configured with the `-local` option.  Is it safe to assume that such annoyance will lead to updating those editor settings?

### Possible Drawbacks / Trade-offs

This PR will ping EVERYONE.  It's automatic, so I don't think there's need for everyone to review the import changes, nor will I necessarily wait for everyone to approve.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by brycekahle — APPROVED** [review]

**Review by sgnn7 — APPROVED** [review]
👍 for @DataDog/agent-shared-components files

**Review by ofek — APPROVED** [review]
Hell yeah!

**Review by mx-psi — CHANGES_REQUESTED** [review]
We have moved to running all Go-related lints through golangci-lint. Since `goimports` is supported by golangci-lint, could we use it here too? It needs to be enabled and then can be configured here: https://golangci-lint.run/usage/linters/#goimports

If, for whatever reason, using golangci-lint doesn't work, we need to add this to [`internal/tools`](https://github.com/DataDog/datadog-agent/blob/c05deb9670078ddeb8a66d583b810a26330eb56b/internal/tools/go.mod#L5) to keep up to date and have a way for people to install the tool.

**Comment by djmitche** [comment]
@ofek's advice was a complete rewrite, so I've force-pushed.  Same effect, though!

**Review by mx-psi — APPROVED** [review]

**Review by paulcacheux — APPROVED** [review]
Running this through golangci-lint has the advantage of ignoring auto-generated files, which is a good thing. LGTM !

**Comment by djmitche** [comment]
Hm, `--fix` appears to have only fixed some of the issues.  Some of the missed files have tags, so _maybe_ it's tags-related?  But for example `pkg/flare/archive_test.go` does not have tags, yet --fix isn't reformatting it.  But `goimports -w -local .. ./pkg/flare` does fix it.  Ideas?

**Comment by mx-psi** [comment]
> Hm, `--fix` appears to have only fixed some of the issues. Some of the missed files have tags, so _maybe_ it's tags-related? But for example `pkg/flare/archive_test.go` does not have tags, yet --fix isn't reformatting it. But `goimports -w -local .. ./pkg/flare` does fix it. Ideas?

Build tags does seem to be part of the puzzle, but I don't understand either the `archive_test.go` case

**Comment by djmitche** [comment]
I can't even see how `--fix` works from looking at the [golangci_lint source](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/goimports.go).

**Comment by djmitche** [comment]
Ah, an upgrade of golangci-lint fixed things.

**Comment by djmitche** [comment]
..and then I realized I had a _very_ old version installed -- the version already specified in internal/tools is fine, once I ran `inv install-tools`

**Comment by djmitche** [comment]
Thanks -- I am looking at that right now.  If I can find a fix, I'll do it, otherwise I'll leave it to you.

**Comment by djmitche** [comment]
It looks like the issue is that all blank lines are removed after the template is rendered, putting all of the imports in one section.  `gofmt` sorts them, but does not separate them into sections.  I'll leave the fix to you.

**Comment by djmitche** [comment]
Hm, it also appears that `golangci-lint` only operates on some (random?) subset of files at once -- I keep getting new errors in CI.  I'll keep hacking away.

**Comment by djmitche** [comment]
I think `inv golangci-lint` locally is missing submodules, so I ran
```
for dir in $(git ls-files pkg cmd | grep 'go\.mod' |grep /| grep -v github | sed 's!/go.mod!!'); do
  (cd $dir && 
  golangci-lint run --fix --timeout 10m0s --build-tags 'process jetson etcd apm cri otlp systemd clusterchecks netcgo gce ec2 containerd python zlib zk jmx consul kubeapiserver podman fargateprocess secrets docker kubelet orchestrator' ./...
)
done
```

**Review by jtappa — APPROVED** [review]

**Review by hush-hush — APPROVED** [review]

**Comment by djmitche** [comment]
It looks like golangci-lint is very particular about build flags.  It has missed +linux, even running on a linux host.

I'm going to try automating this with `goimports` itself, but we'll see if that's effective and/or fast.

**Comment by djmitche** [comment]
It turns out that there's no efficient way to enforce this, so we're just going to not enforce it.  I've pushed commits which only
 * add docs recommending three sections and how to configure your editor to do so automatically
 * apply a one-time fix of all go source files

**Review by mfpierre — APPROVED** [review]

**Review by juliogreff — APPROVED** [review]

**Review by sgnn7 — APPROVED** [review]

**Pull request merged**
