### PR TITLE
[pkg/trace/api] Support stable HTTP semantic conventions

### PR DESCRIPTION
**Pull request by mx-psi**
### What does this PR do?

Supports stable semantic conventions for HTTP spans in the OTLP ingest.

### Motivation

Semantic conventions for HTTP spans were stabilized in v1.23.1.
This introduced some breaking changes. There was a transition period which has ended for some OpenTelemetry language libraries such as .NET.

### Additional Notes

I checked each convention on https://opentelemetry.io/docs/specs/semconv/http/migration-guide/

Old conventions are still honoured, provided that new conventions are not also present.

### Describe how to test/QA your changes

Report OTLP spans using the old and new semantic conventions check that the resource and the error message are set correctly on the following scenarios:

- [ ] When using new HTTP semantic conventions
- [ ] When using old HTTP semantic conventions
- [ ] When using both new and old HTTP semantic conventions (new takes precedence)

### CODE REVIEW

**Review by ancostas — APPROVED** [review]

**Review by mackjmr — CHANGES_REQUESTED** [review]
`http.status_code` and `http.method` are DD convention which are expected in Backend (see [here](https://datadoghq.atlassian.net/wiki/spaces/APM/pages/2357395856/Span+attributes#http.status_code)). These used to correspond to the OTel convention, so we could let the [loop here](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/api/otlp.go#L542-L551) set it for us. Now that the new conventions don't match the DD conventions, we need to make sure that the dd conventions get set in meta for the translation.

**Review by cswatt — APPROVED** [review]
relnotes look great!

**Comment by mx-psi** [comment]
> `http.status_code` and `http.method` are DD convention which are expected in Backend (see [here](https://datadoghq.atlassian.net/wiki/spaces/APM/pages/2357395856/Span+attributes#http.status_code)). These used to correspond to the OTel convention, so we could let the [loop here](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/api/otlp.go?rgh-link-date=2024-04-25T15%3A36%3A41Z#L542-L551) set it for us. Now that the new conventions don't match the DD conventions, we need to make sure that the dd conventions get set in meta for the translation.

Good catch! Can you take another look?

**Review by mackjmr — APPROVED** [review]

**Pull request merged**
