### PR TITLE
Drop the unattended-upgrades from the debian AMIs

### PR DESCRIPTION
**Pull request by FlorentClarret**
### What does this PR do?

Drop the unattended-upgrades from the debian AMIs.

### Motivation

We are facing issues because of the `unattended-upgrades` because of the apt lock. [We disabled it during the tests](https://github.com/DataDog/datadog-agent/pull/27613) but that's not enough because sometimes it's already running at that time. Disabling it in the AMI will fix the issue.

### Additional Notes

The AMIs that I did not update already had the unattended-upgrades disabled.

https://datadoghq.atlassian.net/browse/ADXT-500

### CODE REVIEW

**Review by pducolin — APPROVED** [review]

**Review by f4usto — APPROVED** [review]

**Review by chouquette — APPROVED** [review]
Thanks a lot for handling this!

**Comment by FlorentClarret** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by FlorentClarret** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by FlorentClarret** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
