### PR TITLE
Collect and submit systemd substates as tags

### PR DESCRIPTION
**Pull request by FlorianVeaux**
Ready for review, not QA-ed yet

### CODE REVIEW

**Review by florimondmanca — APPROVED** [review]
LGTM, close to what I envisioned back when I saw this FR in the Support board. :-)

If there are any instructions to QA this locally (eg. a reproduction example for the `active (exited)` setup) I'd love to give it a shot.

Adding `agent-core` as a reviewer too, not sure they were left out on purpose?

**Comment by FlorianVeaux** [comment]
I've been able to QA it by simply spinning up a debian VM, running `systemctl list-units`, that shows for each unit the `loaded`, `active` and `sub` states. That gave me a lot of examples like `active (exited)`, `active (running)`,  `active (abandoned)` ...

I just made sure that those substates were fetched correctly. Also you can pull an agent binary artifact directly from the gitlab pipelines.

**Comment by hush-hush** [comment]
Have we check the implication in the number of context this will have on the backend ? This might multiply the number of context by the number of state in systemd. Not sure a tag is the best way to collect this (it might change on a regular basis no ?).

**Comment by florimondmanca** [comment]
@hush-hush Agreed that there may be a lot of different sub-states for each state. For the life of me I haven't been able to find a list of all possible sub-states (apparently such a list doesn't exist?), but [some sources](https://manpages.debian.org/unstable/systemd/systemctl.1.en.html) indicate that sub-states depend on each unit, and there may be 100+ units in total.

So, possible options maybe:

- Limit the set of sub-states we're accounting for. Eg only submit substates for the `active` state. This should reduce the extra possible tags to maybe a dozen? (Not sure what all the possible sub-states for `active` are.)
- Submit a service check that accounts for the `active (<not 'running'>)`, eg. by submitting `WARNING` instead of `OK`. This would at least allow users to know that "hey look, your service is done running, if this ought to be a web server you might want to look into this", which I think was the initial use case for this.

**Comment by FlorianVeaux** [comment]
Context cardinality is mostly fine here, check out the tests to see that we don't need to assert more metrics.

Reason is:
- Metrics like `systemd.units_by_state` are the number of units containing a given tag, they are tagged by the `unit_state` and will additionally be tagged by the unit substate. This indeed increase the tag cardinality but at most (by expecting all substates to be unique strings) you can't have more timeseries than the total number of units on the system. 
- For more granular metrics like `systemd.unit.uptime`, they are already tagged by the unit name so adding an extra "substate" tag doesn't change the cardinality, there will still be one timeserie per unit.

I can remove the additional tag in the first category of metric, the most valuable addition is for the second category anyway. The tag was added in both places for consistency, but I don't see a use case for it.

>  Not sure a tag is the best way to collect this (it might change on a regular basis no ?).

The tag may change (when a unit starts/exits/fails...) and it may be valuable to have monitors based on that. We can't have separate metrics for this as that would generate an unbound number of metric (and we can't have metadata for those). I think a tag is the best option in that case but open to other suggestions.

**Comment by hush-hush** [comment]
@FlorianVeaux, the number of metrics will be the same but the number of context will not. We will multiply the number of context by the number of state of each service. Unless I'm mistaking, I think we should compute how big that increase will be and check with the backend team.

**Comment by truthbk** [comment]
My 2 cents are that a tag would indeed the right way to submit the substate, but I'm not convinced on whether or not it makes a good tag. Is the number of substates is going to be bounded in practice? Are the tags going to become arbitrary given lack of consistency across units? If the tag doesn't provide a true aggregation level across the metric, then we maybe should reconsider. On the other hand, if for the most part we're dealing with a fairly standard set of substates, then it's probably fine and the cardinality problem would not be _that_ bad. 

The systemd docs suggest the following:
> systemd provides a dependency system between various entities called "units" of 11 different types. Units encapsulate various objects that are relevant for system boot-up and maintenance. The majority of units are configured in unit configuration files, whose syntax and basic set of options is described in systemd.unit(5), however some are created automatically from other configuration, dynamically from system state or programmatically at runtime. Units may be "active" (meaning started, bound, plugged in, …, depending on the unit type, see below), or "inactive" (meaning stopped, unbound, unplugged, …), as well as in the process of being activated or deactivated, i.e. between the two states (these states are called "activating", "deactivating"). A special "failed" state is available as well, which is very similar to "inactive" and is entered when the service failed in some way (process returned error code on exit, or crashed, an operation timed out, or after too many restarts). If this state is entered, the cause will be logged, for later reference. Note that the various unit types may have a number of additional substates, which are mapped to the five generalized unit states described here.

Because substates are mapped to the five unit states described, does it add value to ship the substates? Or is it really just fluff? While I do feel that in practice the number of substates would likely not be arbitrarily large, and thus probably not a huge cardinality burden, I'm not convinced they provide a great aggregation context given how in theory these may differ from unit to unit.

**Comment by FlorianVeaux** [comment]
@hush-hush Had a talk with someone from the data-eng team. I was under the assumption that what impacts us is the number of live contexts (the way custom metrics are [billed](https://docs.datadoghq.com/account_management/billing/custom_metrics/?tab=countrategauge)) but they also have their own negative impact on some parts (mostly regarding churning). 

Regarding the size of the increase we can expect a given unit to go through less than a handful of substate during its lifetime. So worse case would be an 5x increase which would totally be handled easily by the backend. Today we send one metric per host and per *monitored* (explicitly configured) unit. The main risk would come from big bursts where all the context change at the same time, but we're able to handle much bigger bursts than than the worse case scenario here.

In any case,  we're postponing this PR to a latter date as it. It'll be hard to get it for 7.18 and it's really to help with the specific use case where the "State" doesn't reflect the correct status for the unit. And this may be more like an systemd configuration issue on the user side, so we'll look into that first.

**Comment by FlorianVeaux** [comment]
> On the other hand, if for the most part we're dealing with a fairly standard set of substates, then it's probably fine and the cardinality problem would not be that bad.

It's fairly standard (running, exited, failed ...), but there are some potential variations from unit to unit. 

The exact use case was the following:
- A specific unit was considered "active" but with an `exited` substate. It was not doable to get alerts from datadog on that situation. Adding it as as tag felt the natural option to have better queries.
- "active" with an `exited` substate is a specific state where your unit is considered to be a one-time script that exits upon completion. If the unit is configured as a "daemon" this combination of state should not happen.
- Adding all of this just to help with a use case where a service was not configured correctly as a daemon seems hacky and we'd rather not rush that for now.

**Pull request closed without merging**
