### PR TITLE
Modify the indents of conf.yaml.example in oracle.d

### PR DESCRIPTION
**Pull request by taromn**
### What does this PR do?

This PR modifies the indents of `oracle.d/conf.yaml`.

before
```
instances:
- server: <HOST> or server: <HOST>:<PORT>
```

↓

after
```
instances:
  - server: <HOST> or server: <HOST>:<PORT>
```

put two-space indents to all the lines after L35

### Motivation
To improve visibility

### CODE REVIEW

**Review by nenadnoveljic — APPROVED** [review]

**Comment by nihasave** [comment]
Can someone please suggest sampling interval I should have for 90 custom metrics?
  ## @param min_collection_interval - int - optional - default:10
  ## Active session sampling interval in seconds
  # min_collection_interval: <interval_in_seconds>

**Comment by taromn** [comment]
further information about Support portal:
https://docs.datadoghq.com/account_management/guide/access-your-support-ticket/

**Pull request merged**
