### PR TITLE
remoteconfig: replace FEATURES product by ASM_FEATURES

### PR DESCRIPTION
**Pull request by Hellzy**
### What does this PR do?
Replace the FEATURES product in remote configuration by the ASM_FEATURES product.

### Motivation
The decision has been made to create a specific product for ASM remote config activation, which was originally
made through FEATURES but will now use a dedicated product, ASM_FEATURES.

#### Why replace FEATURES, not add ASM_FEATURES?

FEATURES was only holding ASM enablement related configuration and would end up being an empty config now
that ASM_FEATURES is there. It can easily be added back once there is a need for some more configuration specific to this product.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by Hellzy** [comment]
Not sure about the milestone so I'll default this to triage.

**Comment by Hellzy** [comment]
@ameske If you could give this a look when you have time 🙏

**Review by ameske — APPROVED** [review]
We don't really expose "remote config" concepts like the product names to users of the agent, so this change won't impact any interaction they might have with the agent. Given that, I think we should probably omit any release note about this change. I added the `changelog/no-changelog` label so CI will still pass once it's removed.

**Comment by Hellzy** [comment]
Got it, removing the notes 👍

**Review by alai97 — APPROVED** [review]
No docs review needed.

**Pull request merged**
