### PR TITLE
remove unused build tags from system-probe build

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

This PR cleans up the list of build tags used to build the system-probe binary. It moves from a "take the agent build tags and remove some known ones" to a "include just what we need" model.

Doing so it removes the following build tags:
```
apm
consul
containerd
cri
crio
docker
etcd
jetson
jmx
kubeapiserver
kubelet
oracle
orchestrator
otlp
podman
```

saving between 30 and 40MiB of binary size (around 25%).

### CODE REVIEW

**Comment by paulcacheux** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by paulcacheux** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by paulcacheux** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by pgimalac — APPROVED** [review]
Yay -40MB ! 🥳

**Review by chouetz — APPROVED** [review]

**Pull request merged**
