### PR TITLE
Optimize dd_bkgrnd.png

### PR DESCRIPTION
**Pull request by blt**
### What does this PR do?

This commit optimizes the background png bundled into the Agent for use in its gui, running oxipng 9.1.2 on its max setting. Image size is reduced by half.

### Motivation

Shrink a piece of data that is present in core-agent rodata, saving some memory.

### Possible Drawbacks / Trade-offs

None known.

### Additional Notes

Observation by @brycekahle.

Run by me as `oxipng --opt max PATH_TO_PNG`.

### CODE REVIEW

**Review by sgnn7 — APPROVED** [review]

**Comment by pgimalac** [comment]
@blt could you add on the PR description the `oxipng` command you ran ? (so that we can reproduce if we ever need)

**Review by jeremy-hanna — APPROVED** [review]

**Comment by blt** [comment]
> @blt could you add on the PR description the `oxipng` command you ran ? (so that we can reproduce if we ever need)

Glad to. I'm on PTO but I can do so this coming Monday.

**Comment by blt** [comment]
> > @blt could you add on the PR description the `oxipng` command you ran ? (so that we can reproduce if we ever need)
> 
> Glad to. I'm on PTO but I can do so this coming Monday.

Done.

**Pull request merged**
