### PR TITLE
Added a fallback for the alias in case /instance/name returns an error

### PR DESCRIPTION
**Pull request by Simwar**
### What does this PR do?

A customer has an issue with the endpoint `/instance/name` on their GKE cluster: the request results into a 404.
This makes the agent not getting any aliases with the latest image which creates a mismatch between the agent and the gce crawler (double host in the infralist as no match can be done with aliases).

I added a fallback to use the old way used to get the alias (<6.11) in case getting this endpoint results into an error.

### Motivation

A customer reached out that this was not working for them and we could not understand why this endpoint was not working for them. I decided to go ahead and add a fallback in case this happens for other customers.

### CODE REVIEW

**Comment by prognant** [comment]
Are we sure that if `/instance/name` is not working then may work `/instance/hostname` ?
As per https://cloud.google.com/compute/docs/storing-retrieving-metadata#default both should be available.

**Comment by Simwar** [comment]
@prognant good question.
It does work for one client though and I don't know why.
Maybe it would be worth it to go to the bottom of this before pushing this change?

**Comment by prognant** [comment]
@Simwar I think that would be a good idea to spend a little time on that. Best case scenario we can reproduce it or at least understand why this is happening. Worst case scenario we move forward with your change as-is. WDYT ?

**Comment by Simwar** [comment]
Agreed, will try to get some help from the cloud team. Thanks

**Comment by prognant** [comment]
@simwar I shifted the PR to 7.20

**Comment by prognant** [comment]
Hi there, any update on this @Simwar ?

**Comment by Simwar** [comment]
Sorry, got no news.
We are still unsure why this happens :(

**Comment by Simwar** [comment]
@prognant we got some news from the support side.
They managed to replicate with workload identity setup.

Having this PR would work-around workload identity and setup the correct hostname.


Connor Callahan
2 days ago

Hey Simon Guerrier - hoping to sync on the status of this. I was able to replicate the same results in gke with and without workload identity enabled:

w/workload-identity

```
root@wlidtest-datadog-ddzl7:/# curl http://169.254.169.254/computeMetadata/v1/instance -H 'Metadata-Flavor: Google'<a href="/computeMetadata/v1/instance/">Moved Permanently</a>.
root@wlidtest-datadog-ddzl7:/# curl http://169.254.169.254/computeMetadata/v1/instance/hostname -H 'Metadata-Flavor: Google'gke-connor-c-cluster-default-pool-4790f04d-shzz.c.datadog-sandbox.internalroot@wlidtest-datadog-ddzl7:/#
root@wlidtest-datadog-ddzl7:/# curl http://169.254.169.254/computeMetadata/v1/instance/name -H 'Metadata-Flavor: Google'Not Found
```

w/out workload-identity

```
root@wlidtest-datadog-4j2xj:/# curl http://169.254.169.254/computeMetadata/v1/instance -H 'Metadata-Flavor: Google'/computeMetadata/v1/instance/
root@wlidtest-datadog-4j2xj:/# curl http://169.254.169.254/computeMetadata/v1/instance/hostname -H 'Metadata-Flavor: Google'gke-connor-c-cluster-default-pool-48e87dda-bm8w.c.datadog-sandbox.internalroot@wlidtest-datadog-4j2xj:/#
root@wlidtest-datadog-4j2xj:/# curl http://169.254.169.254/computeMetadata/v1/instance/name -H 'Metadata-Flavor: Google'gke-connor-c-cluster-default-pool-48e87dda-bm8wroot@wlidtest-datadog-4j2xj:/#
```

I hope it helps!

**Comment by prognant** [comment]
Possible explanation, when running under the identity workload metadata are served by the GKE metadata server (running as a daemonset) while without the identity workload metadata are served by the GCE metadata server. I think this could explain the difference, by digging a little bit more I think it may be because of some podsecuritypolicy applied to the daemonset (a possible workaround may be to ), if we can confirm this theory the PR bring a simple solution.

**Review by prognant — CHANGES_REQUESTED** [review]
Now we have the complete picture the change is OK, could you please add a release note saying that it aims to cover the case when the agent is running inside GKE with the workload identity.

Thanks !

**Review by prognant — APPROVED** [review]
👍

**Comment by Simwar** [comment]
I added the release note, thanks!

**Pull request merged**
