### PR TITLE
`inv -e tidy-all`

### PR DESCRIPTION
**Pull request by mx-psi**
### What does this PR do?

Run `inv -e tidy-all` to tidy all modules.

### Motivation

the merge of https://github.com/DataDog/datadog-agent/pull/21831 broke main of datadog-agent, as the go.mod files are not up-to-date in the two modules that were created:
```
Errors found:
  - go.mod or go.sum for github.com/DataDog/datadog-agent/comp/logs/agent/config module is out of sync
  - go.mod or go.sum for github.com/DataDog/datadog-agent/pkg/config/utils module is out of sync
Run 'inv tidy-all' to fix 'out of sync' errors.
```
([job log](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/401664929))

### Additional Notes

Reported by @KSerrania (thanks!)

### Describe how to test/QA your changes

n/a

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by pgimalac — APPROVED** [review]

**Review by liustanley — APPROVED** [review]

**Comment by KSerrania** [comment]
I'm going to cancel the mergequeue run to put it back in front, otherwise it will have to wait until all previous PRs fail in the mergequeue to work.

**Review by gh123man — APPROVED** [review]

**Pull request merged**
