### PR TITLE
Backport go bump to 1.21.9

### PR DESCRIPTION
**Pull request by louis-cqrl**
### What does this PR do?

Backport go update to 1.21.9

### CODE REVIEW

**Comment by louis-cqrl** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Review by Kaderinho — APPROVED** [review]

**Review by pgimalac — CHANGES_REQUESTED** [review]
Discussed with @KSerrania, we need to generate specific buildimages for the backport, cherry-picking the following security fixes: https://github.com/DataDog/datadog-agent-buildimages/pull/535 and https://github.com/DataDog/datadog-agent-buildimages/pull/554

**Review by pgimalac — APPROVED** [review]

**Comment by louis-cqrl** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Pull request merged**
