### PR TITLE
tooling: Add invoke vscode devcontainer cmd

### PR DESCRIPTION
**Pull request by clamoriniere**
### What does this PR do?

Add a new "invoke" command to configure "devcontainer" plugin in VS code

the new command is `invoke vscode.setup-devcontainer --image "my-agent-devenv:latest"`
This command will bootstrap the `/devcontainer/devcontainer.json` use by the `devcontainer` plugin to use a container as remote development environment more information in the [devcontainer plugin documentation](https://code.visualstudio.com/docs/remote/containers)

### Motivation

Improve datadog-agent developer experience by simplifying the configuration of its development environment.

### Describe how to test/QA your changes

Run the command `invoke vscode.setup-devcontainer --image "my-agent-devenv:latest"`, it should create the file `.devcontainer/devcontainer.json`

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by amenasria — CHANGES_REQUESTED** [review]
Hey ! Code LGTM !

Could you add some documentation about this task though ?

Since it's related to development environment I'd say the best place to document this would be https://github.com/DataDog/datadog-agent/blob/main/docs/dev/agent_dev_env.md

**Comment by clamoriniere** [comment]
> Hey ! Code LGTM !
> 
> Could you add some documentation about this task though ?
> 
> Since it's related to development environment I'd say the best place to document this would be https://github.com/DataDog/datadog-agent/blob/main/docs/dev/agent_dev_env.md

Hi @amenasria 

I can, but the `Dockerfile` used to build devenv container is not public yet. It requires some extra work which need to be plan by the agent-guild. So the doc that I will provide will not be complete.

**Comment by amenasria** [comment]
Also there's a typo: the new task is not `invoke vscode.devcontainer` but `invoke vscode.setup-devcontainer`.
(typo is in the description and in the QA)

**Comment by amenasria** [comment]
> > Hey ! Code LGTM !
> > Could you add some documentation about this task though ?
> > Since it's related to development environment I'd say the best place to document this would be https://github.com/DataDog/datadog-agent/blob/main/docs/dev/agent_dev_env.md
> 
> Hi @amenasria
> 
> I can, but the `Dockerfile` used to build devenv container is not public yet. It requires some extra work which need to be plan by the agent-guild. So the doc that I will provide will not be complete.

Aaah ok ! I guess it's fine for now then !

**Review by amenasria — APPROVED** [review]
LGTM !

**Comment by clamoriniere** [comment]
@amenasria 
doc updated https://github.com/DataDog/datadog-agent/pull/14031/commits/45d2ac09533ae5c9df231e5e13982483df55fe47

**Pull request merged**
