### PR TITLE
CI: don't rely on a workflow to force DEPLOY_AGENT for conductor runs

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

Attempts to fix the CI configuration when running through conductor

### Motivation

I missed this note in the gitlab doc:
You can use some predefined CI/CD variables in workflow configuration, but not variables that are only defined when jobs start.

This should fix conductor runs systematically failing because no artifacts were deployed, as we should now create the deployment jobs 

### Additional Notes

BARX-263

### CODE REVIEW

**Review by chouetz — APPROVED** [review]

**Comment by chouquette** [comment]
I might have forgotten about the merge freeze :sweat_smile: Sorrn about that

**Review by alopezz — APPROVED** [review]

**Pull request merged**
