### PR TITLE
Provide agent client params with host provisioner

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Allow providing `agentclientparams.Options` as parameter of the host providers.

### Motivation

Being able to easily use agent client parameters.
For now there are very few, but if this is merged I'll add several interesting ones.

### Additional Notes

This shouldn't change any existing behavior.

### CODE REVIEW

**Comment by pgimalac** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Comment by pgimalac** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Comment by pgimalac** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Review by vboulineau — COMMENTED** [review]
Code is legit, though in terms of design, I am not sure about several things:
- The environment needs to be used as a storage for options it does not need to know about, and that are not required at provisioning time.
- That we need to change in the `Provisioner` to add non-provisioning options, although it could be considered part of its job.
- Currently `agentclientparams` are used to inject behaviour that's used at client creation time in `Init()`, which perhaps we should allow to customize.

I think `agentclientparams`, and generally speaking the need to customize creation of clients, also conflicts with the idea of "auto-init" (getting rid of `Init` on environment), because you would then need to have all info available in `Agent` component.

I think this could be solved by providing overriding `Init` when needed, however it does require implementation of interface-bsaed `Provisioner` so that you can re-use `Provisioner` with a custom, but similar enough, environment, which is something that was already discussed but not moved forward with so far.

**Comment by pgimalac** [comment]
@vboulineau I agree the design is not ideal, but I could not see another way to implement something similar without changing any API...

> That we need to change in the Provisioner to add non-provisioning options, although it could be considered part of its job.

`UpdateEnv` only takes `Provisioners`, so the only way to pass parameters to anything is through provisioners...

> Currently agentclientparams are used to inject behaviour that's used at client creation time in Init(), which perhaps we should allow to customize.

That's what I was trying to do with this PR, I'd like to add several new `agentclientparams`, but currently we can't pass those to the `Host`

> I think agentclientparams, and generally speaking the need to customize creation of clients, also conflicts with the idea of "auto-init" (getting rid of Init on environment), because you would then need to have all info available in Agent component.

Well why not just move the agent client in the environment provisioning ? It's not really something that needs to be provisioned, but I'm not sure how much of an issue that is

> I think this could be solved by providing overriding Init when needed, however it does require implementation of interface-bsaed Provisioner so that you can re-use Provisioner with a custom, but similar enough, environment, which is something that was already discussed but not moved forward with so far.

I'm not sure I see what you have in mind, but how complex do you think that would be ?

For context the end goal is to provide some ways to wait for non-core agents (see https://github.com/DataDog/datadog-agent/pull/24345, currently implemented on the `RemoteHost`, but we thought it might make more sense as part of the agent client).
If there is no easy way to use agent client params, then I'll probably just leave that as helpers in the `RemoteHost`.

**Review by vboulineau — APPROVED** [review]
Merge current proposal as-is as the requirement makes sense, but it's an exception and should generally used before we produce a better solution

**Review by KevinFairise2 — APPROVED** [review]

**Pull request merged**
