### PR TITLE
Allow failures in the `kitchen_ubuntu_process_agent-a7` job

### PR DESCRIPTION
**Pull request by FlorentClarret**
### What does this PR do?

Allow failures in the `kitchen_ubuntu_process_agent-a7` job

### Motivation

The image is unavailable, we allow it to fail until we fix the root cause. 

### Additional Notes

https://app.datadoghq.com/incidents/26770

### CODE REVIEW

**Review by chouquette — APPROVED** [review]
:fire_engine:

**Comment by FlorentClarret** [comment]
> Should we rather disable it while we fix it?

That would work too. I'd rather avoid changing the structure of the jobs just in case another one needs it, even if for this particular this is pretty unlikely.

We'll either drop the test or fix it this afternoon once the team is up.

**Pull request merged**
