### PR TITLE
Bump nikos - test

### PR DESCRIPTION
**Pull request by paulcacheux**
### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by paulcacheux** [comment]
@mx-psi @albertvaka as you can see, the workflow is triggered three times (one for each label). But the script part works great ! Maybe you could use something like https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#fetch-metadata-about-a-pull-request to trigger on pull requests from dependabot directly (instead of on label events)

**Comment by mx-psi** [comment]
Where do you see it running three times? I can't find it 🤔 

Also, why did it run here and not in #10680?

**Comment by paulcacheux** [comment]
https://github.com/DataDog/datadog-agent/actions/workflows/dependabot-pr.yml

**Comment by paulcacheux** [comment]
I think it runs on label change so if the PR is only rebased/recreated, the event is not retriggered because the label set did not change

**Comment by mx-psi** [comment]
> I think it runs on label change so if the PR is only rebased/recreated, the event is not retriggered because the label set did not change

That checks out, removing and adding the `dependencies` label made it work. It doesn't run on dependabot PRs though, because Github Actions is not allowed to commit (see [here](https://github.com/DataDog/datadog-agent/runs/5483374903?check_suite_focus=true)).

My proposal is to have an `if` rule that triggers this if (1) the author is dependabot and (2) the milestone is other than triage. That way an engineer can, whenever they are going to review the PR, set the milestone correctly and it will autocommit the fixes for them. What do you think?

**Comment by paulcacheux** [comment]
Seams like a good idea yes

**Pull request closed without merging**
