### PR TITLE
add send_host_metadata option to disable host metadata collection

### PR DESCRIPTION
**Pull request by xvello**
### What does this PR do?

Allow to disable host metadata collection with the `send_host_metadata` option. This is needed if dsd6 is running alongside agent5, and might be needed for agent6 in some edge cases (one agent/pod in openshift, dedicated agent for event collection...), although these cases might be tackled differently.

Please discuss whether the common option for agent is legit or whether that should be a dsd-only option.

Docker image `datadog/dogstatsd:beta` is built with this branch to enable for beta testing.

### CODE REVIEW

**Review by masci — CHANGES_REQUESTED** [review]
Looks good to me, left a couple of nits otherwise 👍 .
Can we add a log INFO or maybe WARNING when the metadata collection is turned off for the agent? For dsd is less important but we can do the same.

**Review by olivielpeau — COMMENTED** [review]
Just a quick comment on the feature itself: we need to make it extra-clear that turning host metadata collection off should not be done unless there is another agent running with host metadata collection on, on the same host. 

Turning host metadata collection off on a "regular" installation can lead to a lot of trouble:
- duplicate hosts on DD
- double-billing (hosts are counted twice and billed twice)

We've had cases (in the past, on agent5) of users turning it off and having very bad surprises afterwards, so let's be careful :)

So, more specifically here, I think we should log a `WARNING` when it's turned off on the agent, and say everywhere that turning it off on an agent can lead to double-billing.

**Review by olivielpeau — APPROVED** [review]
a small comment on the description in the example config file, but other than that LGTM! 👍

**Review by masci — CHANGES_REQUESTED** [review]
I think `enable_metadata_collection` is the right name provided that the option prevents the scheduler to start altogether.

**Review by masci — APPROVED** [review]

**Pull request merged**
