### PR TITLE
ec2 tags collection is broken when kube2iam is used

### PR DESCRIPTION
**Pull request by arminioa**
### What does this PR do?

Fix ec2 tag collection when datadog agent is used in kubernetes with kube2iam.

### Additional Notes

There is no need to add "/" after a IAM role when composing the url used to get AWS security credentials.

Please see these issues:
[DataDog/datadog-agen#3173](https://github.com/DataDog/datadog-agent/issues/3173)
https://github.com/jtblin/kube2iam/issues/204

### CODE REVIEW

**Comment by arminioa** [comment]
@truthbk please review

**Comment by Simwar** [comment]
@clamoriniere @gzussa can you review?

Thanks!

**Review by clamoriniere — APPROVED** [review]

**Review by hush-hush — APPROVED** [review]

**Comment by 2rs2ts** [comment]
This may actually depend on which instance type you are running on. On m5 and c5, you do not want the trailing /, but on other instance types you do. See this issue for more details (particularly this comment) https://github.com/uswitch/kiam/pull/42#issuecomment-371462021

**Comment by 2rs2ts** [comment]
I wonder if you even need to manually fetch credentials at all. Normally, if you provide no credentials the AWS SDK will attempt to use the instance profile, and it does all this work behind the scenes.

**Comment by Simwar** [comment]
Hi @2rs2ts 

The issue linked is, I believe, about the URL:
http://169.254.169.254/latest/meta-data/iam/security-credentials having a trailing '/' or not.
Our issue here is about http://169.254.169.254/latest/meta-data/iam/security-credentials/<iam-role>/ so not the same URL.
I tested on a m5 and on a t2 instance with or without a '/' and it works.
Need to test on kube2iam and we can merge.

**Comment by Simwar** [comment]
Tested on kube2iam. Working without the '/' in the curl.

**Comment by arminioa** [comment]
Thank you guys!

**Comment by xvello** [comment]
While QA-ing this feature, I stumbled upon this [known kube2iam issue about cold caches](https://github.com/jtblin/kube2iam/issues/31). This is an issue for the agent as our cloud provider autodetection algorithm has intentionally short timeouts, to avoid delaying too much the agent startup.

To pre-fill the kube2iam cache, I had to add the following init container to the agent daemonset:

```
      initContainers:
      - image: datadog/agent:latest
        imagePullPolicy: Always
        name: curl-iam
        command: ['curl', 'http://169.254.169.254/latest/meta-data/iam/security-credentials/<ASSUMED_IAM_ROLE_NAME>']
```

**Comment by 2rs2ts** [comment]
That intentionally short timeout causes a lot of issues for us and many others... perhaps it should be reconsidered. One really really common problem is that the metadata endpoint isn't available (often due to setups like kube2iam or kiam) and so the agent boots up with the ec2 hostname as the agent hostname, which of course causes all sorts of problems in the backend because hostnames are not unique so you get tons of no data alerts and other confusion. If the user knows they're deploying the agent to a cloud provider, autodetection only makes things harder for them.

**Comment by hkaj** [comment]
Thanks for the feedback @2rs2ts 

I'll add something to the backlog to make it configurable. I think it requires a different config for each hostname provider, as otherwise we'll wait for X seconds * Y hostname provider, Y being the amount of providers preceding the one that will succeed in the user's environment, and [the EC2 provider is the second last one](https://github.com/DataDog/datadog-agent/blob/d7712d570b91f4f97af9f155ad1c676921d8325d/pkg/util/hostname.go#L198) which would significantly slow down the hostname detection. Do you agree, or did you have another solution in mind?

**Comment by 2rs2ts** [comment]
I think you probably just want to provide a config value for the cloud provider in general. If I say to the agent "you are in EC2" then it should do only EC2 things, not GCE things or anything else.Hopefully that makes sense!

**Pull request merged**
