### PR TITLE
Ignore RemoteSamplingClient when marshaling agent config

### PR DESCRIPTION
**Pull request by martpier**
### What does this PR do?

When remote config is enabled, fixes the output of `trace-agent -info`.

Before:
image

After:
image

### Describe how to test/QA your changes

Run an agent and a trace-agent with remote config enabled.

Run `trace-agent -info`.

There should be no error message `Error: json: cannot unmarshal object into Go struct field AgentConfig.config.RemoteSamplingClient of type config.RemoteClient`.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by dumontg — COMMENTED** [review]
Does it mean "don't read/write `RemoteSamplingClient` in `datadog.yaml`"? If so I assume this needs to be released in `7.41` and `7.42`?

**Comment by martpier** [comment]
> Does it mean "don't read/write `RemoteSamplingClient` in `datadog.yaml`"? If so I assume this needs to be released in `7.41` and `7.42`?

~Yes, but most importantly it means we don't serialise this field when writing the JSON that is used to create the result of `trace-agent-info`.

IIUC, when the trace agent was refactored to have an independent `pkg/trace` module, they added this `RemoteClient` field in the `AgentConfig` struct because it was convenient at the time, even though it is not an actual configuration field (it's a remote client object).

So I think it makes sense to completely ignore this field when we want to print the config in use.

**Review by dumontg — APPROVED** [review]

**Review by knusbaum — APPROVED** [review]

**Comment by knusbaum** [comment]
I think we should add a small fix changelog since this is user-facing.

**Comment by martpier** [comment]
> I think we should add a small fix changelog since this is user-facing.

Done :) And thank you for adjusting the milestone, I was not sure what was appropriate for a fix

**Review by kayayarai — APPROVED** [review]

**Pull request merged**
