### PR TITLE
Fix Cluster Agent triggering error logs in APIServer about external metrics OpenAPI spec

### PR DESCRIPTION
**Pull request by vboulineau**
### What does this PR do?

Fix Cluster Agent triggering error logs in APIServer about external metrics OpenAPI spec.

### Motivation

Remove useless logging triggered in APIServer.

### Additional Notes

Change our code to use upstream defaults instead of relying on copy-pasted version from some years ago.

### Describe how to test/QA your changes

Deploy the Cluster Agent with external metrics server activated in a Kubernetes environment in which you can access APIServer logs. Verify that there's no repetitive logs about `v1beta1.external.metrics.k8s.io`

### CODE REVIEW

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by buraizu — APPROVED** [review]

**Review by KSerrania — APPROVED** [review]
LGTM for `tasks/cluster_agent.py`.

**Review by amenasria — APPROVED** [review]
LGTM for Agent DevX Infra owned files

**Review by FlorentClarret — APPROVED** [review]

**Review by sblumenthal — APPROVED** [review]

**Pull request merged**
