### PR TITLE
Loosen system clang version requirement

### PR DESCRIPTION
**Pull request by YoannGh**
### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by paulcacheux — APPROVED** [review]

**Comment by brycekahle** [comment]
@YoannGh What version do you have locally?

**Comment by paulcacheux** [comment]
He has 12.0.0

**Comment by YoannGh** [comment]
Yeah, and @safchain and @spikat also have the 12.0.0 version locally installed

**Comment by YoannGh** [comment]
`clang 12.0.1` isn't available on ubuntu 20.04.5 unfortunately. I agree that we should try to use the same version in both dev environment and CI but version `12.0.1` makes it quite restrictive on the dev environment. Is there any reason why we require this version specifically?

**Comment by brycekahle** [comment]
There isn't a strong reason for `12.0.1` over `12.0.0` specifically, but it could come up in the future where we need the patch release because it fixes some issue. We can move forward with this change for now.

**Review by brycekahle — APPROVED** [review]

**Review by spikat — APPROVED** [review]

**Pull request merged**
