### PR TITLE
Add tagger-list cmd to process-agent cli

### PR DESCRIPTION
**Pull request by clamoriniere**
### What does this PR do?

* Add `tagger-list` command to the `process-agent`. It allows to display the tags for each entities present in the "tagger" component.
* Add the output of `process-agent tagger-list` to the flare

### Motivation

Ease missing tags investigation in the `process-agent`

### Describe how to test/QA your changes

1. Deploy the `agent` and `process-agent` and run the command `process-agent tagger-list`. 
   The output should be equal to what you get with the `agent tagger-list` command

2. Run the `agent flare` command, the flare should contains a new file call `process-agent_tagger-list.json`

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by juliogreff — APPROVED** [review]

**Review by xornivore — APPROVED** [review]
Thank you so much 🙌 Sounds like it is also added in the flare - may want to update QA instructions with that.

**Review by just-chillin — APPROVED** [review]

**Comment by xornivore** [comment]
> I wanted to add to the flare in a separated PR. but maybe it will not be ready for this milestone. 😢
That's ok, no worries, a separate PR makes sense, this is a big help still! 🙇

**Comment by clamoriniere** [comment]
@xornivore 
finally I was able to easily add the tagger-list to the flare for the process-agent too
https://github.com/DataDog/datadog-agent/pull/12942/commits/2f4057bb4818ba3534a87c0bc6cee108b82beccd

**Review by jtappa — APPROVED** [review]
👍🏻 from docs for release note

**Review by hush-hush — APPROVED** [review]

**Pull request merged**
