### PR TITLE
[system-probe] Allow specifying eBPF compiler

### PR DESCRIPTION
**Pull request by lebauce**
### What does this PR do?

Allow only using the downloaded compiler instead of the local one.

### Motivation

Using newest versions of clang make the compilation fail because of incompatibility with the LLVM 12 and LLVM15 compiled artefacts.

### CODE REVIEW

**Comment by brycekahle** [comment]
What is using LLVM15? Everything should still be on 12

**Comment by lebauce** [comment]
@brycekahle It seems we use that local clang of the system. If this one is clang 15, compilation fails with an error saying that we mix LLVM12 and LLVM15 artifacts. This PR allows using the /opt/datadog-agent/embedded/bin/clang-bpf one (not relying on the local one)

**Comment by brycekahle** [comment]
You should get an error much earlier to complain about the system `clang` version not starting with `12.0`.

**Review by brycekahle — APPROVED** [review]

**Comment by lebauce** [comment]
@brycekahle I indeed get the message but using DD_SYSPROBE_SKIP_CLANG_CHECK allows not relying on the system compiler

**Review by paulcacheux — APPROVED** [review]

**Pull request merged**
