### PR TITLE
[EBPF] Fix kmt.prepare task on macOS

### PR DESCRIPTION
**Pull request by gjulianm**
### What does this PR do?

Minor fixes for the kmt.prepare task in macOS.

### CODE REVIEW

**Review by usamasaqib — APPROVED** [review]

**Comment by gjulianm** [comment]
/

**Comment by gjulianm** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by gjulianm** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
