### PR TITLE
Add dependobot config file

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Add a [Dependabot config file](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates).

### Motivation

Get notified when a new version of a GO module is available.

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Check dependabot alerts.

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
One ugly thing that would happen if we enable this is that all forks would be affected by dependabot/dependabot-core#2198, for which there is no good workaround. I personally think the benefits outweigh the costs but I wanted to bring it up just in case since we have been affected by this in the past on the OpenTelemetry Collector Datadog fork repo.

Another thing that we need to take into account is that we will need to keep this updated with the nested Go modules list (that's on me, I will make a note to update it when we add the first module)

**Comment by olivielpeau** [comment]
Also if I understand correctly, this will make dependabot update all dependencies as soon as they have new versions, regardless of whether they're affected by security advisories or not. Enabling this now would likely create tons of dependabot PRs (or one PR with a huge list of updates) immediately, which we're unlikely to be able to merge.
We should probably start with a more selective approach (example: use dependabot only for select deps we want to always keep on the latest version)

**Comment by mx-psi** [comment]
> We should probably start with a more selective approach (example: use dependabot only for select deps we want to always keep on the latest version)

Agreed, for now all of tooling can be excluded for example (not a priority).

We should also add the [labels](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#labels) option (probably `changelog/no-changelog`, `qa/skip-qa` and `team/agent-platform` would work) and the [milestone](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#milestone) one (which we will need to keep updated)

**Comment by albertvaka** [comment]
> Enabling this now would likely create tons of dependabot PRs 
What's the alternative? Being stuck with old versions is creating technical debt, and the longer we wait the worse it becomes. Updating everything will be a bit of effort initially and lots of changes but over time it will become a smaller effort as we only do incremental changes. 

> the milestone one (which we will need to keep updated)
We have a `Triage` milestone that we can use.

**Pull request closed without merging**
