### PR TITLE
Add container filter by annotation and label

### PR DESCRIPTION
**Pull request by keisku**
### What does this PR do?

Add container filter by annotation and label to [Container Discovery Management](https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagen)

### Motivation

https://github.com/DataDog/datadog-agent/issues/13181

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by hestonhoffman — APPROVED** [review]

**Review by remeh — COMMENTED** [review]
Change looks good from AML perspective. I would like to know what @DataDog/container-integrations think about such a new capacity though.
Also, please make sure to properly fill the todolist and to add a QA section (explaining how to QA/test your change).

**Review by robertjli — APPROVED** [review]

**Comment by AliDatadog** [comment]
I think we do not store container annotations: https://github.com/DataDog/datadog-agent/blob/3ff39e219d3bf5cbe0ce691ef02382a64d2c732a/pkg/workloadmeta/collectors/internal/containerd/container_builder.go#L72

Hence, we can not filter by container annotations. It is because we have to deserialize the `Spec` which can be very costly. Also, it is very rarely used because annotations cannot be added in containers and are usually not used by orchestrators. 

Internally we are working on filtering based on pods annotations.

**Comment by clamoriniere** [comment]
Hi @keisku 

sorry for the late review and feedback. 
We are taking a different approach to allow users to filter specific containers or pods thanks to annotations. 
The problem that we see with the implementation in this PR, is that it is to permissive, and can lead to bad configuration for users, because:
* the filter logic can't do operation such as `kube_namespace:foo && kube_labels_team:bar`
* it requires an agent update to add a new label or annotation in the configuration.
* if a team configures something to permissive, it can impact a team in another namespace.

So, instead of allowing users to define which labels or annotations can be used to filter pods/containers, we prefer to define specific annotations to configure it. Here is the implementation PR: https://github.com/DataDog/datadog-agent/pull/16489

Please let us know what you think.

**Comment by keisku** [comment]
@clamoriniere Thank you for updates! I will close this PR.

**Pull request closed without merging**
