### PR TITLE
auto-instrumentation: increase default memory request to 100Mi

### PR DESCRIPTION
**Pull request by brettlangdon**
### What does this PR do?

Increases the default memory request for the auto instrumentation container from 20Mi to 100Mi.

100Mi is closer to the recommended [minimum memory requirements](https://wiki.alpinelinux.org/wiki/Requirements) for Alpine.

### Motivation

https://datadoghq.atlassian.net/browse/APMON-1472

Right now the containers may get OOM Killed when copying lib injection files from the lib injection container to the application container. This memory usage comes from the `cp` command's usage of `sendfile` and is correlated to the total number of files being copied.

From @levan-m:

> From my perspective, making this change in Agent is cleaner. Memory increase will be tied to a specific Agent version upgrade. On the other hand, Operator config may change while Agent version is pinned (or vice versa). This could create a situation where Operator overrides default value in future Agent versions, or sets higher limit on older installations which work fine with 20mb.

### Describe how to test/QA your changes

Testing limits manually.

Before:

```bash
$ docker run -it --rm  --memory=20Mib --memory-swap=20Mib -v "$(pwd):/out" gcr.io/datadoghq/dd-lib-python-init:2.12 /datadog-init/copy-lib.sh /out/
Killed
```

After:

```bash
$ docker run -it --rm  --memory=100Mib --memory-swap=100Mib -v "$(pwd):/out" gcr.io/datadoghq/dd-lib-python-init:2.12 /datadog-init/copy-lib.sh /out/
```

This change can also be validated by manually updating the cluster agent configuation:

Manually setting the resource request:

```yaml
datadog:
 apiKey: <API-KEY>
 site: datadoghq.com
 tags:
      - env:<ENV>
 apm:
   instrumentation:
      enabled: true
      libVersions:
         java: "1"
         dotnet: "3"
         python: "2"
         js: "5"
         ruby: "2"
clusterAgent:
  env:
    - name: DD_ADMISSION_CONTROLLER_AUTO_INSTRUMENTATION_INIT_RESOURCES_MEMORY
      value: 100Mi
```

Using a custom built image with the changes:

```yaml
datadog:
 apiKey: <API-KEY>
 site: datadoghq.com
 tags:
      - env:<ENV>
 apm:
   instrumentation:
      enabled: true
      libVersions:
         java: "1"
         dotnet: "3"
         python: "2"
         js: "5"
         ruby: "2"
clusterAgent:
   image:
     name: <user>/cluster_agent
     tag: master
     repository: docker.io/<user>/cluster_agent
     doNotCheckTag: true
```

```bash
helm upgrade datadog-agent -f datadog-values.yml datadog/datadog
```

Sample app configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyle-django-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: app
        image: ddkverhoog/django-helloworld:v1.0.1
        env:
          - name: DD_TRACE_DEBUG
            value: "true"
        readinessProbe:
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 18080
          initialDelaySeconds: 30
          periodSeconds: 1
        ports:
          - containerPort: 18080
            protocol: TCP
```

### CODE REVIEW

**Review by alexbryukhanova — COMMENTED** [review]
Changes lgtm. Could you add the note from @levan-m [comment](https://dd.slack.com/archives/C07L8PAGMPZ/p1726520329731839?thread_ts=1726244479.434819&cid=C07L8PAGMPZ) that we're adding this limit here as a cleaner solution. Also, are we adding the limits to Helm & Operator _as well_? If so, could you please link the PRs here.

**Review by clamoriniere — APPROVED** [review]
The change looks good.
However the test description doesn't match how the change can be tested with the APM SSI admission controller.
Can the PR description be updated according to it?

**Review by estherk15 — APPROVED** [review]

**Comment by clamoriniere** [comment]
> Changes lgtm. Could you add the note from @levan-m [comment](https://dd.slack.com/archives/C07L8PAGMPZ/p1726520329731839?thread_ts=1726244479.434819&cid=C07L8PAGMPZ) that we're adding this limit here as a cleaner solution. Also, are we adding the limits to Helm & Operator _as well_? If so, could you please link the PRs here.

@alexbryukhanova, if we cherry-pick this change on `7.57.x` branch, we could include it in 7.57.1 and remove the need to implement the workaround in the helm-chart and Operator.

**Pull request merged**
