### PR TITLE
Migrate the Deployments and Daemonset manifests to apps/v1

### PR DESCRIPTION
**Pull request by aerostitch**
### What does this PR do?

extensions/v1beta1 is deprecated for daemonsets and will be removed in 1.16.
This PR moves the Deamonset and Deployment manifests to apps/v1 and add the required selector when necessary.

That includes mostly the doc but also the e2e tests.

From: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md
> DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

### Motivation

Have an example up-to-date of the deployment.

### Additional Notes

This is available since k8s 1.9 and I doubt a lot of people are still running k8s < 1.9, so it's quite backward compatible.

### CODE REVIEW

**Comment by aerostitch** [comment]
Note: there are many commits in here to make it easier to revert things if you want the PR broken down (for example moving the tests changes around).
But if you're all good and ready to merge, feel free to use the squash merge button! ;)

**Review by hkaj — CHANGES_REQUESTED** [review]
Excellent! Thanks a bunch @aerostitch 
For end-to-end tests there's one more occurence [here](https://github.com/DataDog/datadog-agent/blob/f2984f7074880bdf7dc248eaa444f8e1980613e5/test/e2e/scripts/run-instance/22-argo-submit.sh#L20) (used in our internal CI to run the job in a spot instance iirc).
Could you please update it as well so we can run your PR through our end-to-end k8s tests?

Thanks again

**Comment by aerostitch** [comment]
Hey @hkaj!
Thanks for the review and good catch!
I updated the Daemonset you pointed out. Let me know if you want me to do other changes.

**Review by hkaj — APPROVED** [review]

**Comment by hkaj** [comment]
thanks again @aerostitch :)

**Pull request merged**
