### PR TITLE
Windows: Add HOSTNAME_FQDN install flag

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?

This PR adds `HOSTNAME_FQDN_ENABLED` install flags for Windows.

Usage:
`start /wait msiexec  /i datadog-agent-XXX.msi APIKEY="<YOUR_DATADOG_API_KEY>" HOSTNAME_FQDN="true"`

### Motivation

As the Agent on Windows starts after the installation, we need a way to set `hostname_fqdn` when starting the installation of the Agent.

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details you may have to test your PR.

Check the flag `HOSTNAME_FQDN_ENABLED` for the Agent and DogstatsD stand alone.

Documentation pull request: https://github.com/DataDog/datadog-agent/pull/5427

### CODE REVIEW

**Comment by albertvaka** [comment]
Can you update the docs [1] with the new installer argument and link the PRs?

[1] https://github.com/DataDog/documentation/blob/master/content/en/agent/basic_agent_usage/windows.md

**Comment by ogaca-dd** [comment]
@albertvaka: Updated

**Comment by albertvaka** [comment]
https://github.com/DataDog/documentation/pull/7332

**Review by albertvaka — APPROVED** [review]

**Review by prognant — APPROVED** [review]
The go lines feel a little bit like duplicated code, but at least we are sure it works well 👍

**Pull request merged**
