### PR TITLE
Remove docker build tag for darwin builds

### PR DESCRIPTION
**Pull request by mbotarro**
### What does this PR do?

This PR removes the `docker` build tag for `darwin` builds. When instantiating the process-agent, it performs a containers check in order to auto-enable containers collection on the host. Currently, there's no [ContainerImplementation](https://github.com/DataDog/datadog-agent/pull/4885) for darwin which makes the process-agent crash on macOS when running alongside docker. 

### Motivation

The process-agent crashes on macOS when Docker is also running on the host
```
panic: Trying to get nil ContainerInterface
goroutine 1 [running]:
github.com/DataDog/datadog-agent/pkg/util/containers/providers.ContainerImpl(...)
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/containers/providers/provider.go:20
github.com/DataDog/datadog-agent/pkg/util/docker.(*DockerUtil).ListContainers(0xc00014c000, 0xc0001d3010, 0xc0007ca600, 0x17, 0x1, 0xc0007ca600, 0x17)
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/docker/containers.go:40 +0x121b
github.com/DataDog/datadog-agent/pkg/util/containers/collectors.(*DockerCollector).List(0xc00070d640, 0xc0007ca600, 0x17, 0x0, 0x0, 0x0)
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/util/containers/collectors/docker.go:43 +0x37
github.com/DataDog/datadog-agent/pkg/process/util.GetContainers(0xc0007a1d28, 0x400e816, 0xc0007028e0, 0x20, 0x20)
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/process/util/containers.go:62 +0x5fa
github.com/DataDog/datadog-agent/pkg/process/config.NewAgentConfig(0x6158797, 0x7, 0x618a402, 0x1f, 0x6196b39, 0x24, 0xd0, 0xd0, 0x5f17500)
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/process/config/config.go:302 +0x34
main.runAgent(0xc0003d60c0)
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/process-agent/main_common.go:95 +0x9f
main.main()
	/private/var/cache/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/process-agent/main.go:24 +0x3b8
```

### Additional Notes

Anything else we should know when reviewing?

### Describe your test plan

Write there any instructions and details you may have to test your PR.

### CODE REVIEW

**Review by vboulineau — APPROVED** [review]

**Review by mx-psi — DISMISSED** [review]
The tag exclusion logic makes sense to me; IoT Agent (which is the one my team owns) should be okay if the core Agent is.

**Review by remeh — APPROVED** [review]
Looks good to me.

**Comment by clamoriniere** [comment]
@mbotarro 
the osx_test linter is failing with this error

```
golangci-lint run --timeout 10m0s -c .golangci.yml --build-tags 'fargateprocess etcd jmx apm zk python kubeapiserver gce ec2 kubelet orchestrator consul process clusterchecks secrets zlib dovet' ./pkg/...
pkg/tagger/collectors/common.go:24:6: `retrieveMappingFromConfig` is unused (deadcode)
func retrieveMappingFromConfig(configKey string) map[string]string {
     ^
pkg/tagger/collectors/const.go:30:2: `dockerLabelEnv` is unused (deadcode)
	dockerLabelEnv     = "com.datadoghq.tags.env"
	^
pkg/tagger/collectors/const.go:31:2: `dockerLabelVersion` is unused (deadcode)
	dockerLabelVersion = "com.datadoghq.tags.version"
	^
pkg/tagger/collectors/const.go:32:2: `dockerLabelService` is unused (deadcode)
	dockerLabelService = "com.datadoghq.tags.service"
	^
pkg/tagger/collectors/common_test.go:17:6: `requireMatchInfo` is unused (deadcode)
func requireMatchInfo(t *testing.T, expected []*TagInfo, item *TagInfo) bool {
     ^
pkg/autodiscovery/listeners/common.go:69:6: `getCheckNamesFromLabels` is unused (deadcode)
func getCheckNamesFromLabels(labels map[string]string) ([]string, error) {
     ^
```

**Comment by mbotarro** [comment]
Instead of removing the `docker` build tag from `darwin` builds, we can prevent the docker collector from registering itself in the default catalog. This won't make Mac OS linter tests fail.

https://github.com/DataDog/datadog-agent/pull/7085

**Pull request closed without merging**
