### PR TITLE
{Dockerfiles/agent,trace-agent/config}: disable apm `max_memory` and `max_cpu_percent` by default

### PR DESCRIPTION
**Pull request by ahmed-mez**
### What does this PR do?

Set `apm_config.max_memory: 0` and `apm_config.max_cpu_percent: 0` by default in containerized environments

### Motivation

See https://github.com/DataDog/datadog-agent/pull/4891 
This PR aligns the config in all containerized environments.

### Additional Notes

`apm_config.max_memory` and `apm_config.max_cpu_percent` have been disabled by default in Kubernetes environments since Agent `7.18.0`.

### Describe how to test/QA your changes

- Run the agent container in different environments with debug logs enabled
  - [CI](https://docs.datadoghq.com/continuous_integration/tests/python/?tab=azurepipelines#using-a-cloud-ci-provider) `DD_INSIDE_CI=true`
  - [ECS](https://docs.datadoghq.com/containers/amazon_ecs/apm) `ECS_FARGATE=true`
  - [Docker](https://docs.datadoghq.com/containers/docker)
  - [k8s](https://docs.datadoghq.com/containers/kubernetes/installation?tab=helm) (for regression testing)

Make sure these logs appear 

```
Running in a container and apm_config.max_cpu_percent is not set, setting it to 0
Running in a container and apm_config.max_memory is not set, setting it to 0
```

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by apigirl — APPROVED** [review]
release note looks fine from an editorial review

**Review by vboulineau — CHANGES_REQUESTED** [review]
These files are meant to disappear. The only reliable way is to default this in code using the facilities in `pkg/config` to detect running in a container.

**Comment by ahmed-mez** [comment]
Good point @vboulineau ! PR updated

**Review by vboulineau — APPROVED** [review]

**Review by knusbaum — APPROVED** [review]
Looks great, thanks.

**Pull request merged**
