### PR TITLE
add snyk for python & go

### PR DESCRIPTION
**Pull request by JulesDT**
### What does this PR do?

This PRs adds Snyk tests for both Golang and Python

### Motivation

The adding of Python requirements would make `snyk monitor` only monitor Python dependencies

### CODE REVIEW

**Review by arbll — APPROVED** [review]
🔒

**Comment by irabinovitch** [comment]
@JulesDT any next steps needed here?

**Comment by JulesDT** [comment]
I'd need it to be merged and that should be enough.

**Comment by arbll** [comment]
I'll merge it after the freeze if this is ready

**Pull request merged**
