### PR TITLE
bump github.com/shirou/gopsutil to v4

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

github.com/shirou/gopsutil/v3 is [deprecated](https://github.com/shirou/gopsutil/releases/tag/v4.24.5), this PR bumps the dependency to v4 in all internal usages.

The dependency is still brought by:
- nikos
- datadog-operator
- in a cycle through some otel collector dependencies

This first PR should allow to start breaking some of those cycles as well.

### CODE REVIEW

**Review by pgimalac — APPROVED** [review]

**Review by lebauce — APPROVED** [review]

**Review by spikat — APPROVED** [review]

**Review by vickenty — APPROVED** [review]

**Review by remeh — APPROVED** [review]

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by vitkyrka — APPROVED** [review]

**Review by kkhor-datadog — APPROVED** [review]

**Review by jennchenn — APPROVED** [review]
lgtm for container integrations files

**Review by moth-a — APPROVED** [review]

**Review by derekwbrown — APPROVED** [review]
approved for (1) wkit file (of 157)

**Review by songy23 — APPROVED** [review]

**Review by ichinaski — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]

**Review by BaptisteFoy — APPROVED** [review]

**Pull request merged**
