### PR TITLE
Constructor for bundle params

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?

This PR introduces constructors for `core.BundleParams`.  It makes it easier to set fields to a default value which is not the Go default value.

### Motivation

Be able to have a default value for `DefaultConfPath`.

### Describe how to test/QA your changes

Nothing to QA as the code is already unit tested.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by paulcacheux — APPROVED** [review]

**Review by djmitche — APPROVED** [review]
This is great!

I wonder if the `LogForXxx` should be changed to options, as well, in a followup?

**Review by jtappa — APPROVED** [review]
👍🏻 no review needed from docs

**Review by AlexandreYang — APPROVED** [review]

**Review by clamoriniere — APPROVED** [review]

**Review by alopezz — APPROVED** [review]
FWIW As someone unfamiliar with the code I do find the original code with the explicit struct easier to read (like named arguments).

**Review by cedricvanrompay-datadog — APPROVED** [review]

**Review by remeh — APPROVED** [review]
LGTM from @DataDog/agent-metrics-logs perspective (only checked owned files).

**Review by coignetp — APPROVED** [review]

**Pull request merged**
