### PR TITLE
omnibus: use a new dedicated git cache bucket

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

Switch to a dedicated omnibus git cache bucket

### Motivation

We don't need versioning to be enabled for this purpose

BARX-401

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by KSerrania** [comment]
Seems like the CI does not have write access to the bucket:
```
upload failed: ../../../../../tmp/omnibus-git-cache-bundle to s3://dd-ci-datadog-agent-omnibus-git-cache-build-stable/builds/38ec0a61e52a40ed7f94715c2df0e82418a72d3c/agent-heroku-deb-x64-a6 An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```

from https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/573737045

**Comment by chouquette** [comment]
> Seems like the CI does not have write access to the bucket:
> 
> ```
> upload failed: ../../../../../tmp/omnibus-git-cache-bundle to s3://dd-ci-datadog-agent-omnibus-git-cache-build-stable/builds/38ec0a61e52a40ed7f94715c2df0e82418a72d3c/agent-heroku-deb-x64-a6 An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
> ```
> 
> from https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/573737045

Oh indeed, it misses some permissions, which are still in cloudops. I'll look into migrating those before allowing access to the new bucket

**Review by amenasria — APPROVED** [review]
LGTM

**Review by clarkb7 — APPROVED** [review]

**Pull request merged**
