### PR TITLE
Disable repo GPG check for yum

### PR DESCRIPTION
**Pull request by albertvaka**
We provide signatures for our packages, but not for our repo metadata.

### CODE REVIEW

**Comment by olivielpeau** [comment]
can you confirm this works well on the RHEL versions we support? (6, 7, and ideally 8 as well)

**Comment by albertvaka** [comment]
I've tried in CentOS 6, which as far as I know is the distro with the oldest yum we support, and CentOS 7, which has a recent yum, and both work. RHEL should be very close to CentOS, so I don't see much value in testing that. 

I haven't tested on SUSE, though, so let me do that now.

Of course, if you think it's still worth testing RHEL let me know and I'll do it.

**Comment by olivielpeau** [comment]
SUSE is a different code path in this script, so no need to test it :)

I agree that for our purposes CentOS and RHEL can be regarded as the same distro, so only testing on one of them is OK 👍

**Comment by albertvaka** [comment]
That's true 😅Got confused with both using RPM packages.

**Comment by albertvaka** [comment]
This was already done (better) here: https://github.com/DataDog/datadog-agent/pull/3535

**Pull request closed without merging**
