### PR TITLE
[GUI] Stop looking for configuration files in the dist/conf.d directory

### PR DESCRIPTION
**Pull request by ISauve**
### What does this PR do?

The GUI used to check for configuration files in the `dist/conf.d` directory, but it shouldn't because those files shouldn't be packaged with the agent.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by olivielpeau** [comment]
IIRC the main reason we still want the agent to pull check configs from `dist/conf.d` is to ease development: in a development environment, you can have your configs in the `dev/dist` directory of your local repo and they get copied to the correct `dist/` subfolder by the invoke build task, and then the dev agent picks these configs first.

What I think would be a desirable behavior would be to:
- in the dev env, make the agent pull all of its configs (main `datadog.yaml` + checks' `conf.d`) from the `dist` directory
- in a packaged install, make the agent pull all of its configs from the regular conf directory (typically `/etc/datadog-agent` on Linux)
- in all cases, make the agent pull all of its configs from one single directory at a time.

I also think we should use the existing `-c` CLI flag (https://github.com/DataDog/datadog-agent/blob/6.0.0-beta.5/cmd/agent/app/app.go#L32) to allow specifying which directory to use to pull ALL configs. The default could be the `dist` directory (to make developers' lives easier), but only if we make all packaged agents run with the correct `-c` flag.

@ISauve @masci any thoughts? :)

**Comment by masci** [comment]
@olivielpeau totally makes sense
+1 for using the `-c` option even if having to pass it all the times when interacting with the agent might be annoying (e.g. for `status`, `flare`, etc). So we might actually default to the packaging paths, making devs specify `-c` or populate `/etc/datadog-agent` (this should be the current behaviour of the command line I believe).

**Comment by olivielpeau** [comment]
You're right about the other commands (`status`, `flare`, etc), I hadn't considered those. So yes completely agree with having `/etc/datadog-agent` as the default 👍

**Comment by ISauve** [comment]
Closing this PR because the agent is going to continue using the `dist/conf.d` directory, so the GUI should mimic this behaviour.

**Pull request closed without merging**
