### PR TITLE
add readwrite volumes to agent Dockerfile

### PR DESCRIPTION
**Pull request by stonith**
### What does this PR do?

Declares readwrite directories as volumes.

### Motivation

Allows use of kubernetes `readonlyrootfs` flag

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by xvello — COMMENTED** [review]
Hi @stonith,

Good addition to the image! I have two points to discuss:

- I'd like to reduce the number of volumes, as that will impact all users, even the ones that don't run with a read-only root. The s6 overlay we are using [has a read-only-root option](https://github.com/just-containers/s6-overlay#read-only-root-filesystem), that should allow us to remove the four `/etc/*.d` folders. I think it's fair to enable it by default, so we don't have two run cases to test

- We support running [with a random UID on OpenShift](https://docs.okd.io/3.10/creating_images/guidelines.html#openshift-specific-guidelines), do we have guarantees the permissions we set on `/var/run/s6` and `/var/log/datadog` are persisted when a volume replaces them? A quick test seems to prove OK, but you might have more experience with that than me

**Comment by xvello** [comment]
Also, this change will require a release note item. [We use reno to manage them](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/contributing.md#reno).
I would suggest an `feature` item with the following wording: `Docker image: running with a read-only root filesystem is now supported`

**Comment by stonith** [comment]
@xvello updated per your points. However, I'm not sure Openshift, I don't have a way to test.

**Review by xvello — DISMISSED** [review]
LGTM, thanks for the changes!

I tested successfully on OpenShift 3.7, and permissions are retained.

You'll need to rebase on `master`, as we recently made changes to the CI process.

**Comment by stonith** [comment]
@xvello rebased but still failing CI

**Pull request closed without merging**
