### PR TITLE
[CI] Add `arm64` macOS Gitlab runners to the CI

### PR DESCRIPTION
**Pull request by amenasria**
### What does this PR do?

This PR adds `arm64` macOS Gitlab runners to the CI

### Motivation

More resilient macOS CI.

### CODE REVIEW

**Review by CelianR — APPROVED** [review]
Great ! One question: Would it be better to use `matrix` for that ?

**Comment by amenasria** [comment]
@CelianR that's a good point but for now I'm leaving it like that as I might modify it in later PRs (until the build is not added).
I will address this in later PRs if it stays like this, thanks !

**Pull request merged**
