### PR TITLE
fix installer amd build

### PR DESCRIPTION
**Pull request by raphaelgavache**
### What does this PR do?

A typo in https://github.com/DataDog/datadog-agent/pull/24471/files made the amd build unavailable, this was caught later by https://github.com/DataDog/datadog-agent/pull/24455

updater-e2e are failing on the main branch, this PR fixes the fails

### CODE REVIEW

**Review by arbll — APPROVED** [review]

**Review by chouquette — APPROVED** [review]
LGTM, but I'm curious if it fixes an actual issue since we usually copy files with patterns such as `datadog-installer*`

**Comment by raphaelgavache** [comment]
yes it might have been a red herring and the broken part only due to: https://github.com/DataDog/test-infra-definitions/pull/747
I'm still merging to have the same pattern between different builds, this one for sanity to have the same pattern on each builds

**Pull request merged**
