### PR TITLE
scrub credentials from flare and agent commands output

### PR DESCRIPTION
**Pull request by ahmed-mez**
### What does this PR do?

hide sensitive data in flare and agent `configcheck` and `clusterchecks` commands output

### Motivation

https://github.com/DataDog/datadog-agent/issues/3397

### CODE REVIEW

**Review by hkaj — COMMENTED** [review]
Do we need it to do something here as well? https://github.com/DataDog/datadog-agent/blob/007662ed841843fd2478e8947b40eeac413ffe06/cmd/agent/api/agent/agent.go#L244

**Comment by mfpierre** [comment]
I don't think this would affect the `clusterchecks` command or am I missing something?

**Comment by hkaj** [comment]
it won't, i'm thinking of `configcheck` that has the same issue.

**Comment by ahmed-mez** [comment]
`configcheck` command is calls the same `PrintConfig` function

https://github.com/DataDog/datadog-agent/blob/master/cmd/agent/app/config_check.go#L38

https://github.com/DataDog/datadog-agent/pull/3407/files#diff-dc234dee606607a8600e269aa23f833cR100

**Review by mfpierre — APPROVED** [review]
LGTM, we might want to double check the `flare` because it would be cleaned twice

**Comment by olivielpeau** [comment]
Although we never formalized it, I think the "rule" up to now was that Agent commands can output sensitive information since they're all authenticated (and basically require the caller to run under the same execution context as the Agent itself). The flare however should never contain credentials (which is why the `flare` package uses all this credential scrubbing logic).

We may want to re-evaluate this "rule" if we think Agent commands should never output credentials, but I think it's worth discussing. If we do want to strip all credentials, then let's review all Agent commands more systematically. For example, the `config` command outputs the main Agent config without scrubbing credentials (and there may be others, we should systematically audit all commands)

**Pull request closed without merging**
