### PR TITLE
[ASCII-2621] Update Scrubber package

### PR DESCRIPTION
**Pull request by louis-cqrl**
### What does this PR do?

This PR aims to bump the package yaml.v2 to yaml.v3 in the scrubber package, This PR also moves tests from `default_test.go` to their right place depending of the function tested

### Motivation

yaml.v3 offers a better formatting than yaml.v2

### Describe how you validated your changes

Covered by unit tests

### CODE REVIEW

**Review by JLineaweaver — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]

**Review by ajgajg1134 — APPROVED** [review]
approved for agent-apm!

**Review by mackjmr — APPROVED** [review]

**Review by rayz — APPROVED** [review]

**Review by jennchenn — APPROVED** [review]
lgtm for container integrations files

**Review by dustmop — APPROVED** [review]
LGTM

**Pull request merged**
