### PR TITLE
feat(cws): Sync cws test from main

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
Sync cws test from main. The `new-e2e-cws: [--run TestECSFargate]` is [failing](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/710906415) on `6.53.x` branch

### Motivation
https://datadoghq.atlassian.net/browse/ACIX-455

### CODE REVIEW

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by spikat — APPROVED** [review]

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request closed without merging**
