### PR TITLE
Init tagger module

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

Init `tagger` module.
Moved from JSON to C array since the tagger is heavily used.

### CODE REVIEW

**Comment by xvello** [comment]
FYI the tagger module evolved to support cardinality as an enum, see https://github.com/DataDog/datadog-agent/blob/master/pkg/collector/py/tagger.go#L23

Might be a good time to sync with `master`

**Review by masci — CHANGES_REQUESTED** [review]
Let's port the latest changes on `master` introducing the new cardinality type before merging

**Comment by hush-hush** [comment]
@masci @xvello: I cherry-picked the new tagger commit from master and updated the python bindings.
Tell me what you think.

**Review by masci — APPROVED** [review]
:shipit:

**Comment by hush-hush** [comment]
Cherry-picked onto branch `agent-multi-python` (aka agent-py2-py3 rebased on 6.11).

**Pull request closed without merging**
