### PR TITLE
Preserve metrics on autodetect

### PR DESCRIPTION
**Pull request by dplepage-dd**
### What does this PR do?

This fixes a bug (NDM-2292) where the experimental automatic detection of SNMP metrics will overwrite any metrics explicitly requested in the configuration file.

### Describe how to test/QA your changes

TODO: How to QA this beyond the unit tests? It would require setting up a situation where we provide global metrics that wouldn't have otherwise been picked up by metric detection.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by AlexandreYang — COMMENTED** [review]
Looks good overall to me 👍

**Comment by dplepage-dd** [comment]
@AlexandreYang I'm not sure if there's a good way to QA this - we'd need to set up a situation where there's a custom metric that isn't included in any of our profiles (so that it wouldn't be picked up by metric detection), but our profiles cover most things we'd care about. Or is it enough QA just to verify that this doesn't break existing behavior?

**Comment by AlexandreYang** [comment]
@dplepage-dd You can maybe test by setting the global_metrics, then use the `experimental_detect_metrics_enabled`, then check if the global metrics are being used?

**Review by AlexandreYang — APPROVED** [review]

**Review by hestonhoffman — APPROVED** [review]

**Pull request merged**
