### PR TITLE
Add back trace logs for dsd packets

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?

Trace every dsd packets

### Motivation

#3310 removed a log that could be useful to troubleshoot some agent issues.

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by olivielpeau** [comment]
I don't expect this change to really affect performance (unless the log level is actually set to `trace`), but do you have a small benchmark on `parsePacket` to prove this? 😄

**Comment by mfpierre** [comment]
I was not expecting this kind of difference (first line with log) 😅 

```
BenchmarkParsePacket-4   	 5000000	       365 ns/op	     141 B/op	       3 allocs/op
BenchmarkParsePacket-4   	200000000	        11.1 ns/op	       0 B/op	       0 allocs/op
```

Although the benchmark is pretty lightweight, wondering what actually happens as the log/config package is not properly setup 🤔 

Adding the bench file as it might be reused.

**Review by fanny-jiang — DISMISSED** [review]
Looks good, thanks for adding this back!

**Comment by olivielpeau** [comment]
Interesting @mfpierre, thanks for the benchmark!

Indeed, actually you'll want to try with the `log` package fully initialized before you start the bench, as the `log` package has a mechanism to buffer log entries if the package is used before its full initialization (see https://github.com/DataDog/datadog-agent/blob/8973a3ea96be667bb0e213d2b7818ee91ba2b607/pkg/util/log/log.go#L454-L456)

**Comment by mfpierre** [comment]
@olivielpeau it's still looking pretty bad

```
BenchmarkParsePacketWithoutLogs-4     	10000000	       143 ns/op	      48 B/op	       2 allocs/op
BenchmarkParsePacketWithTraceLogs-4.    50000	     38468 ns/op	    6069 B/op	      39 allocs/op
```

when the log line is commented out:

```
BenchmarkParsePacketWithoutLogs-4     	100000000	        12.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkParsePacketWithTraceLogs-4     100000000	        11.8 ns/op	       0 B/op	       0 allocs/op
```

I guess I did a pretty good dsd optimization removing this log 😅

**Comment by olivielpeau** [comment]
Surprising results! Might be related to the lock we lock/unlock in the function that checks whether we should actually log the entry given the current log level? https://github.com/DataDog/datadog-agent/blob/8973a3ea96be667bb0e213d2b7818ee91ba2b607/pkg/util/log/log.go#L104-L105 We'd have to look at a profile to understand more I guess...

In any case, I think the benchmark is a clear indication that we shouldn't merge the change as-is. As you said, we should revisit our logging strategy around perf critical code and understand what's making the logger add so much overhead even when the log entry should be ignored. Happy to add this to our backlog if you don't have the time to look into it now.

If this log entry is important enough that we should re-add it before we answer these questions, we could put it behind a non-documented config flag for now? What do you think?

**Comment by mfpierre** [comment]
I removed the lock & fixed the benchmark because actually the dsd sender is modifying the original packet content with `nextMessage` so I have to send a new packet everytime

here are the adjusted results:

```
BenchmarkParsePacketWithoutLogs-4     	 2000000	       667 ns/op	     344 B/op	      11 allocs/op
BenchmarkParsePacketWithTraceLogs-4   	   30000	     76310 ns/op	    7855 B/op	      59 allocs/op
```

with the logs commented out:

```
BenchmarkParsePacketWithoutLogs-4     	 2000000	       562 ns/op	     296 B/op	       9 allocs/op
BenchmarkParsePacketWithTraceLogs-4   	 3000000	       549 ns/op	     296 B/op	       9 allocs/op
```

looks way better 👍

**Comment by mfpierre** [comment]
Also benchmarked the lock overhead on the `shouldLog` function:

```
BenchmarkShouldLog-4   	2000000000	         0.39 ns/op	       0 B/op	       0 allocs/op
BenchmarkShouldLog-4   	30000000	        44.4 ns/op	       0 B/op	       0 allocs/op
```

**Comment by arbll** [comment]
We should probably use a `RWLock`. Not sure if it will remove the 40ns overhead but it will certainly lower contention.

**Comment by mfpierre** [comment]
@arbll do we actually need a lock on `shouldLog`? Worst case we log something at the wrong level if it's being changed in the meanwhile but is it really an issue? 🤔

**Comment by olivielpeau** [comment]
Also, is the overhead in `shouldLog` primarily from the lock itself, or from the `defer` call? (I know `defer` has an overhead that's not negligible in hot paths, don't know if it's at play here though)

**Comment by mfpierre** [comment]
The defer has a ~30ns overhead
```
BenchmarkShouldLog-4   	100000000	        15.4 ns/op	       0 B/op	       0 allocs/op
```

**Comment by arbll** [comment]
Well logLevel is a uint8 so it probably won't crash the app in case of race but I don't think it would be a very good practice to purposefully let it happen.
Unit tests with the race detector might also start failing

**Comment by mfpierre** [comment]
State with a RLock without defer:

```
BenchmarkParsePacketWithoutLogs-4     	 2000000	       690 ns/op	     344 B/op	      11 allocs/op
BenchmarkParsePacketWithTraceLogs-4   	   30000	     63540 ns/op	    7864 B/op	      59 allocs/op
```

**Review by olivielpeau — DISMISSED** [review]
So if I understand the benchmarks correctly, this change makes the `parsePacket` function about 20% slower when the log level is set strictly above `trace`, correct?

If that's indeed the case then I'd say the impact is acceptable, since the `parsePacket` function is not AFAIK the bottleneck in the dogstatsd pipeline.

**Review by arbll — DISMISSED** [review]
Looks good to me. Let's just keep an eye on the CPU when this reaches one of our envs.

Nit: I am not sure if we should merge the benchmarks, they might be a bit too tailored to this particular PR context to be re-usable easily

**Review by arbll — APPROVED** [review]

**Pull request merged**
