### PR TITLE
Add basic telemetry about the python version being used

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

Add basic telemetry about the python version being used

### CODE REVIEW

**Review by masci — APPROVED** [review]
very clever, 👍

**Review by olivielpeau — COMMENTED** [review]
Thanks for adding this!

A few comments:
* this metric doesn't make sense on the cluster agent / puppy agent / any build that doesn't include python, I think we should not send it in these cases.
* in terms of naming, I think `datadog.agent.python.version` would be more consistent with the other internal "default" metrics that are sent
* sending the `python_version` as a tag and a constant a value of `1` would make aggregations/counts easier in Datadog, but if you have reasons to send it this way I'm happy to hear them :)

**Comment by hush-hush** [comment]
@olivielpeau thanks for the review, updated the PR following your input.

**Review by olivielpeau — APPROVED** [review]
💯

**Pull request merged**
