### PR TITLE
[cli][integration] freeze isnt appropriate anymore.

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

The new pip upgrade has modified the pip freeze output. We should rely on `pip list`.

Update: using `pip list --format=freeze` allows us to get the same behavior as the old `pip freeze`. Let's use it.

### Motivation

New `pip freeze` output:
```
...
contextlib2==0.6.0
cryptography==2.9.2
cx-Oracle==7.2.0
datadog-activemq @ file:///.omnibus/src/datadog-agent-integrations-py2/integrations-core/activemq
datadog-activemq-xml @ file:///.omnibus/src/datadog-agent-integrations-py2/integrations-core/activemq_xml
...
```

previous `pip freeze` output:
```
...
clickhouse-cityhash==1.0.2.3
clickhouse-driver==0.1.2
cryptography==2.9.2
cx-Oracle==7.2.0
datadog-activemq==1.5.1
datadog-activemq-xml==1.8.0
datadog-aerospike==1.8.0
...
```

alternative `pip list`:
```
...
clickhouse-driver                0.1.2
cryptography                     2.8
cx-Oracle                        7.2.0
datadog-activemq                 1.5.2
datadog-activemq-xml             1.8.0
datadog-aerospike                1.8.3
datadog-airflow                  1.4.0
...
```

Update: alternative `pip list --format=freeze`:
```
...
clickhouse-driver==0.1.2
cryptography==2.9.2
cx-Oracle==7.2.0
datadog-activemq==1.5.1
datadog-activemq-xml==1.8.0
datadog-aerospike==1.8.3
...
```

### Additional Notes

~Kitchen tests are broken, fixed in #6180.~ Update: using `pip list --format=freeze` should fix the kitchen tests without any change.

Reason for breakage in pip `>20.1`: https://github.com/pypa/pip/pull/7612

### Describe your test plan

~Addressed in kitchen tests. Thank @KSerrania~ Update: kitchen tests update not needed anymore. Kitchen tests are green with `pip list --format=freeze`.

### CODE REVIEW

**Review by KSerrania — COMMENTED** [review]
This may be a breaking change for people that were using `datadog-agent integration freeze` to export / list their datadog integrations state, as the output format is different. Should we add a release note mentioning the change?

**Comment by truthbk** [comment]
Yes, we need a release note. We still need to have some discussion over this change.

**Review by albertvaka — APPROVED** [review]
In the end there are no user-facing changes, so we could remove the release note.

**Review by bmikaili — APPROVED** [review]
LGTM, I agree with Albert that we probably don't need a reno for this.

**Review by olivielpeau — APPROVED** [review]
Removed the release note since there are no user-facing changes, will merge once CI is green

**Pull request merged**
