### PR TITLE
fix Error collecting connection stats

### PR DESCRIPTION
**Pull request by cyplenochek**
### What does this PR do?

Currently  network  check  with "collect_connection_state: true" does not work for datadog agent.
iproute2 package missing.

### Motivation

I want to see network connections stats for each of the worker nodes
### Additional Notes

Network check for cluster-agent works fine, but it collects metrics only from one node. We need to have metrics from all worker nodes. 

```
Config: (helm values)
datadog:
  confd:
    network.yaml: |-
      init_config:
      instances:
        - collect_connection_state: true
```
Agent version: Agent 7.16.1 - Commit: 02e0969 - Serialization version: 4.15.0 - Go version: go1.12.9

### CODE REVIEW

**Comment by vboulineau** [comment]
Hi cyplenochek,

Thanks for taking some time to contribute to Datadog Agent.

This issue is a known issue. In our docker image we ship all packages required by the default configuration, to avoid putting all possible packages that may be required by all possible combinations.

In your case adding the `collect_connection_state` option will indeed require iproute2. In this case we recommend to build a image derived from datadog/agent with the required dependencies.

**Comment by cyplenochek** [comment]
Thank you for your response, Vincent.
I believe that packages for custom metrics and application specific metrics
can be derived into custom images.
collect_connection_state is a basic host level metric. Why dont include
support of this metric into upstream?

**Comment by cyplenochek** [comment]
Hi guys! Any updates?

**Comment by deadok22** [comment]
This was fixed in https://github.com/DataDog/datadog-agent/pull/6390. Please close the pull request

**Pull request closed without merging**
