### PR TITLE
[e2e][refactoring] 🚚 move provisioners to dedicated package 

### PR DESCRIPTION
**Pull request by pducolin**
### What does this PR do?

* Rename environments `docs.go` to `environments.go`
* Move provisioners to dedicated package

### Motivation

Part 1 of a refactoring to allow environments to have a `Diagnosable` interface, so that we can dump agent logs and config at test failure time. Currently having provisioners in `e2e` and in `environments` causes circular dependencies.

### CODE REVIEW

**Review by hmahmood — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]

**Comment by pducolin** [comment]
Forced push a rebase on main to fix conflicts

**Review by YoannGh — APPROVED** [review]

**Review by paulcacheux — APPROVED** [review]

**Review by BaptisteFoy — APPROVED** [review]

**Review by jedupau — APPROVED** [review]

**Review by vitkyrka — APPROVED** [review]

**Review by fanny-jiang — APPROVED** [review]

**Review by AlexandreYang — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
approval for OTel

**Review by clarkb7 — APPROVED** [review]

**Review by carlosroman — APPROVED** [review]

**Review by aboitreaud — APPROVED** [review]

**Review by jeremy-hanna — APPROVED** [review]
👍 for ASC owned files

**Review by kkhor-datadog — APPROVED** [review]

**Review by ajgajg1134 — APPROVED** [review]
looks good for the apm related changes!

**Review by louis-cqrl — APPROVED** [review]

**Review by chouquette — APPROVED** [review]

**Review by gjulianm — APPROVED** [review]

**Pull request merged**
