### PR TITLE
add support for components implementing the actor pattern

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

This adds a small supporting library for actor-shaped components.  This isn't used yet, but is likely to be useful in several components and it's easier to just get it in place first, rather than having those components "race" to see who introduces this support.

### Additional Notes

This PR is against a base branch containing #13699 and #13662.  Once those are merged, I'll change the base of this PR to `main` and rebase, but it can be reviewed in the interim.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by maycmlee — APPROVED** [review]
👍 for docs

**Review by hush-hush — APPROVED** [review]

**Review by truthbk — COMMENTED** [review]
Do we have specific use-cases in mind for this? Do we need to open PRs on stuff we aren't quite sure we have specific use for at this time, even if it's good code like this?

**Review by mx-psi — APPROVED** [review]
Same as in the other PRs, no files are actually owned by Agent Platform

**Comment by djmitche** [comment]
> Do we have specific use-cases in mind for this? Do we need to open PRs on stuff we aren't quite sure we have specific use for at this time, even if it's good code like this?

At least lots of things in the logs-agent are structured as actors.  I'd like to have this functionality ready to roll before it's needed, so that whoever needs it first does not need to re-invent it.

**Comment by djmitche** [comment]
Collective response to @ogaca-dd's coments:

[Here](https://github.com/DataDog/dd-agent-comp-experiments/blob/b6917802823099be8687067639a880473ab0c2a9/comp/logs/launchers/file/launcher.go#L67-L78) is an example of the use of the actor pattern.

Note that the `select { .. }` contains the `alive` and `Done` arms, but also application-specific arms (`sourceChangeRx.Chan` in this case, but could be more than one, or timers, or even different `select{ .. }` statements in different conditions).  Because this select needs to encode the set of polled channels in the source code, it's not possible to abstract the loop into the Actor type.  (Well, it is probably _possible_ with `reflect.Select()` but at a cost in performance without simplifying implementations)

Regarding Start and Stop being exported: my intent had been to allow a component to _either_ use `HookLifecycle` _or_ call `Start` and `Stop` directly.  But that may be too much flexibility.  And, you're correct that Start/Stop must not be called concurrently!

Thinking further about @truthbk's question: this PR will probably make more sense when there's a health component, as it the becomes an easy and effective way to get health monitoring for active components.

So I'll make Start/Stop unexported and then mark this as a draft until ASC-191 is done.

**Comment by djmitche** [comment]
```
=== FAIL: . TestPreGeneratedIntegrityChecks (re-run 2) (0.07s)
    repository_test.go:494: 
        	Error Trace:	repository_test.go:494
        	Error:      	Received unexpected error:
        	            	expired at 2022-11-03 18:01:32 +0000 UTC
        	Test:       	TestPreGeneratedIntegrityChecks
```
these are because of an expired cert in the tests for remote-config.

**Comment by ogaca-dd** [comment]
I am closing this PR for now and reopen it if there will be a concrete usage of the actor pattern.

**Pull request closed without merging**
