### PR TITLE
remove batch/v1beta1 and policy/v1beta1 apis for k8s 1.25

### PR DESCRIPTION
**Pull request by a7i**
### What does this PR do?
Remove references to `batch/v1beta1` and `policy/v1beta1` in preparation for k8s 1.25 upgrade

### Motivation
Blocks upgrade to k8s 1.25

### Possible Drawbacks / Trade-offs
Will not work on k8s 1.20 or earlier

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the `k8s/1.21` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by vboulineau** [comment]
Hey @a7i,

Thanks for your contribution. Unfortunately we cannot drop support for older Kubernetes as-is, what we usually do is to implement support for both older and newer objects until we can't (because lib upgrade is necessary and it removes support for older objects), in which case we need to send a communication to customer to warn them early about upcoming breaking change.

**Comment by a7i** [comment]
> Hey @a7i,
> 
> Thanks for your contribution. Unfortunately we cannot drop support for older Kubernetes as-is, what we usually do is to implement support for both older and newer objects until we can't (because lib upgrade is necessary and it removes support for older objects), in which case we need to send a communication to customer to warn them early about upcoming breaking change.

@vboulineau What do customers that need to upgrade to 1.25 do? Given that 1.27 is around the corner, it makes sense to drop APIs that are no longer supported on 1.25 and replace them with those that were added in 1.21 (which came out almost two years ago).

What should be the proper changes then? Happy to apply changes based on your feedback.

**Comment by vboulineau** [comment]
So we already have the logic to use the newer resources if available, but we fallback to previous version if not available, it allows us to support a wide range of versions (currently it's handled automatically in KSM, but through configuration in `orchestrator` check)

The code you're removing is handling the older versions and only used if newer versions is not available.
For 1.25+ users there's nothing to do, it should just work OOTB.

**Comment by a7i** [comment]
I see, thanks for the explanation. Going to close this PR then

**Pull request closed without merging**
