### PR TITLE
Disable publication of Agent 6 docker images

### PR DESCRIPTION
**Pull request by alopezz**
### What does this PR do?

Stops automatic publication of Agent 6 Docker images.

### Motivation

[BARX-375](https://datadoghq.atlassian.net/browse/BARX-375)

### Describe how to test/QA your changes

[BARX-375]: https://datadoghq.atlassian.net/browse/BARX-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by kacper-murzyn** [comment]
Will we be able to manually publish v6 images if required? Use case - we want to release 6.53.0 based bugfix releases with security patches to meet business requirements

**Comment by alopezz** [comment]
> Will we be able to manually publish v6 images if required? Use case - we want to release 6.53.0 based bugfix releases with security patches to meet business requirements

As far as I understand, since this file still exists in the 7.53.x branch, releases triggered from there should still be able to publish Agent 6 images.

**Comment by vboulineau** [comment]
> > Will we be able to manually publish v6 images if required? Use case - we want to release 6.53.0 based bugfix releases with security patches to meet business requirements
> 
> As far as I understand, since this file still exists in the 7.53.x branch, releases triggered from there should still be able to publish Agent 6 images.

As it only removes publication we could trigger publications manually in any case.

**Comment by alopezz** [comment]
> On the PR itself you need to remove the reference to this from includes in .gitlab/deploy_containers/deploy_containers.yml

@vboulineau Good catch, thanks! Next time please 🙏 hit "Request Changes" as I nearly missed it; I've updated the PR, I think I've removed all references now.

**Review by vboulineau — APPROVED** [review]

**Pull request merged**
