### PR TITLE
[RC] Add package version tag

### PR DESCRIPTION
**Pull request by coignetp**
### What does this PR do?

Add a new tag to `datadog.agent.running` metric when the agent is managed by the updater
`PackageVersion` is different from the `AgentVersion`, as it refers to an internal version catalog with more detailed informations that the AgentVersion.

See the install_dir override for the updater https://github.com/DataDog/datadog-agent/blob/main/.gitlab/package_build/remote_updater.yml#L5

### CODE REVIEW

**Review by CelianR — COMMENTED** [review]
Lgtm, I don't approve to have extra reviews

**Review by louis-cqrl — APPROVED** [review]
LGTM for file ASC owns

**Review by vickenty — APPROVED** [review]

**Review by chouetz — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]

**Pull request merged**
