### PR TITLE
[ASCII-1353] Deepcopy objects returned by the config

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Clone objects returned in the config.

### Motivation

Avoid data races.
We shouldn't write to objects returned by the config but it looks like we do because we've seen an instance of a race (but couldn't pinpoint where the write was).

### Additional Notes

`github.com/mohae/deepcopy` is a very simple library (provides a single function, no dependencies) and is already used all agents.

### Possible Drawbacks / Trade-offs

Could also clone directly in our `viper` fork to only do it when necessary.

### Describe how to test/QA your changes

Check whether the memory and CPU usage increased significantly.
Functional bugs should be caught by the CI.

### CODE REVIEW

**Review by vickenty — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]

**Review by liustanley — APPROVED** [review]

**Review by davidor — APPROVED** [review]
👍 for container-integrations files

**Review by louis-cqrl — APPROVED** [review]
LGTM for file ASC owns

**Review by ogaca-dd — APPROVED** [review]
LGTM 🚀

**Review by coignetp — APPROVED** [review]

**Review by mellon85 — APPROVED** [review]

**Review by mfpierre — APPROVED** [review]

**Pull request merged**
