### PR TITLE
clean exit test all services

### PR DESCRIPTION
**Pull request by jack0x2**
### What does this PR do?
Adds tests to test what happens when you manually start services that are configured to be disabled. Updates security-agent to output an informational event on clean exit on start.

### Motivation
https://datadoghq.atlassian.net/browse/WINA-1192
Remove unnecessary errors from event logs and better tests on service behaviors.

### Describe how to test/QA your changes
Adds tests to service-tests to test everything

### Additional Notes

Changelog covered by: https://github.com/DataDog/datadog-agent/pull/31248

### CODE REVIEW

**Review by paulcacheux — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]
lgtm

suggestion: Could split up the three suites run in `TestServiceBehaviorWhenDisabled*` using `parallel.matrix`, too

**Pull request merged**
