### PR TITLE
Update python version used in workflows to the one of the repo

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?
Set the python version used in workflows to the one of the repo.

### Motivation
It's safer to use the same version as the one we build the agent with, and have every workflow use the same version.
I initially wanted to update the version for some workflows owned by my team and thought I could update them all.

### Additional Notes

If you don't want one of these changes let me know and I'll remove it.

### CODE REVIEW

**Review by chouetz — APPROVED** [review]

**Review by ogaca-dd — APPROVED** [review]

**Review by safchain — APPROVED** [review]

**Review by spikat — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by Pythyu — APPROVED** [review]

**Comment by pgimalac** [comment]
Having issues with the MQ, trying to close and re-open...

**Review by IbraheemA — APPROVED** [review]

**Pull request merged**
