### PR TITLE
Fix memory allocation/free & memtrack on windows

### PR DESCRIPTION
**Pull request by derekwbrown**
### What does this PR do?

Modifies the supplied `free()` to track all the way through to the two/three implementation

### Motivation

Memory tracking wasn't working properly on Windows
Memory allocations/frees weren't being handled in same module, which could be a problem

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by ogaca-dd — COMMENTED** [review]
It looks to do the same as before. Allocating and freeing in different modules is not a problem as we use the same compiler. In `two.h` we use `vector<string>` which require to use the same compiler (or at least need a careful review of this part).

Did I misunderstood something?

**Comment by truthbk** [comment]
I believe what is trying to be addressed here is the fact that `two` and `three` are compiled separately, generating shared objects. 

These shared objects have their own copies to the `rtloader_mem` routines, and so they're never properly initialized in `two` and `three` the `common` part however was properly tracked. I believe the problem might actually exist on all platforms the way we currently build. 

I'm not sure if this approach or passing in the memory allocating/free routines to the `two`, `three` constructors is better. To me it feels like a bit of a more natural pattern.

Also, a known issue that should be tackled in the future is overriding the actual `new` and `delete` allocators/free in C++ which is not currently done.

**Comment by derekwbrown** [comment]
> It looks to do the same as before. Allocating and freeing in different modules is not a problem as we use the same compiler. In `two.h` we use `vector<string>` which require to use the same compiler (or at least need a careful review of this part).
> 
> Did I misunderstood something?

There are two issues here.  One is what Jaime mentioned. The other is a windows problem.  Each module (each .exe or .dll) gets it's own heap.  You can't allocate from one and free in another.

_however_, since we're using GCC and not the microsoft compiler, I don't know if we're insulated from that particular problem or not.  But, we should take care here anyway (among other things, I'd love to move off of GCC when `go` supports using MSC for `cgo`.

**Comment by ogaca-dd** [comment]
> There are two issues here. One is what Jaime mentioned. The other is a windows problem. Each module (each .exe or .dll) gets it's own heap. You can't allocate from one and free in another.

Indeed, as `two.dll` and `three.dll` are linked statically with C runtime, we cannot allocate something from `two.dll` and release it from `three.dll`. (If `two.dll` and `three.dll` were linked dynamically with C runtime we do not have this issue).
 
From what I saw on my windows box, `two` and `three` are linked statically with `rtloader` and these 3 projects are linked statically with C runtime. 
So if you define a function in `rtloader` project or in `two`, as these 2 projects are linked statically the result should be the same.  
My question is why moving `free` from `rtloader` to `two` and `three` with the exact same implementation?
Maybe I misunderstood how the project are linked together and used :).

> however, since we're using GCC and not the microsoft compiler, I don't know if we're insulated from that particular problem or not. But, we should take care here anyway (among other things, I'd love to move off of GCC when go supports using MSC for cgo.

Indeed it is not a good idea to allocate something from `two` or `three` and release it from `cgo` as they probably not use the same C runtime. This is an issue only if we call `malloc` or `free` from a go file (I am not use we do it or it is something we want).

**Comment by derekwbrown** [comment]
superceded by https://github.com/DataDog/datadog-agent/pull/4082

**Pull request closed without merging**
