### PR TITLE
pkg/trace/api: ensure service.name & co. resource attrs get properly set

### PR DESCRIPTION
**Pull request by gbbr**
This change ensure that resource attributes such as "operation.name",
"service.name", "resource.name", "span.type" and "analytics.event" get
translated correctly to Datadog span properties.

### CODE REVIEW

**Review by mackjmr — APPROVED** [review]
LGTM, thanks 🙂 

Although it may be good to add a couple small changes to the tests to prevent a regression in precedence:
- Making sure that if both resource attributes `peer.service` and `service.name` are set that `service.name` takes precedence and `peer.service` get's added as a tag.
- Making sure that if `service.name` is set both as a span attribute and resource attribute that the span attribute takes precedence.

?

**Comment by gbbr** [comment]
Thanks for reviewing! Makes sense. Those might already be covered by current tests but I will double check.

**Review by urseberry — APPROVED** [review]

**Comment by gbbr** [comment]
@mackjmr it's done. I changed the current tests to accommodate both of your scenarios. Let me know if you think it's better now.

Lastly, what should we do in the case where the `service.name` resource attribute is set, and then we encounter a span having the `peer.service` attribute? As we are now, the latter gets ignored. Should it?

**Review by mackjmr — APPROVED** [review]
Looks good, Thanks!

**Pull request merged**
