### PR TITLE
Fix usage binary name to use the real one

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?
Fix usage binary name to use the real one

### CODE REVIEW

**Comment by olivielpeau** [comment]
There's actually a good reason for the current usage string: the binary that's built is called `agent`, not `datadog-agent`. It's only in the deb/rpm package that we create a symlink called `datadog-agent`. In the dockerized agent the command is still `agent` as well.

Anyway, ideally we'd be able to determine which command was actually run by the user (`agent` or `datadog-agent`) and display it here accordingly. Not sure if `cobra` allows doing that easily

**Comment by hush-hush** [comment]
@olivielpeau we could use `os.Args[0]` to get the binary used. Any reason not to have the `datadog-agent` link in or containers ? It would help align documentation.

**Review by olivielpeau — APPROVED** [review]
➕  for `os.Args[0]` if it works well across platforms (windows?) and in all circumstances.

Not sure about the reasons behind the different binary/link name in the containerized Agent, tagging Containers on this.

**Comment by xvello** [comment]
We just rolled with the file name from the deb package, and actually liked it being short.
We could add a `datadog-agent` -> `agent` symlink for consistency if needed

**Comment by hush-hush** [comment]
@xvello a link in our containers would be nice. In any case this will work no matter what users use.

**Pull request merged**
