### PR TITLE
feat(apm): implement external data resolution

### PR DESCRIPTION
**Pull request by wdhif**
### What does this PR do?

Implement External Data resolution for APM and the Trace Agent.

### Motivation

This is needed to support the latest Origin Detection spec.

### Describe how you validated your changes

With the following patch to `dd-trace-py`:
```
diff --git a/ddtrace/internal/runtime/container.py b/ddtrace/internal/runtime/container.py
index c12a091fe..5667b70be 100644
--- a/ddtrace/internal/runtime/container.py
+++ b/ddtrace/internal/runtime/container.py
@@ -163,6 +163,7 @@ def get_container_info(pid="self"):
 
 def update_headers_with_container_info(headers: Dict, container_info: Optional[CGroupInfo]) -> None:
     """Get the container info (either the container ID or the cgroup inode) and add it to the headers."""
+    return # skip
     if container_info is None:
         return
     if container_info.container_id:
@@ -189,3 +190,4 @@ def update_header_with_external_info(headers: Dict) -> None:
                 EXTERNAL_ENV_HEADER_NAME: external_info,
             }
         )
+    log.error("external_info: %s", external_info)
\ No newline at end of file
```
And the following application code:
```
#!/usr/bin/env python3

import time

from ddtrace import tracer

while(1):
  increment = tracer.trace("increment", "dummy_trace_python")
  decrement = tracer.trace("decrement", "dummy_trace_python")
  time.sleep(2)
  increment.finish()
  time.sleep(2)
  decrement.finish()
```
Deployed using:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-trace-py
  labels:
    app: dd-trace-py
spec:
  selector:
    matchLabels:
      app: dd-trace-py
  replicas: 1
  template:
    metadata:
      labels:
        app: dd-trace-py
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: dd-trace-py
          image: wdhifdatadog/dd-trace-py
          imagePullPolicy: Always
          env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_AGENT_URL
            value: "http://$(DD_AGENT_HOST):8126"
          - name: DD_TRACE_DEBUG
            value: "true"
```

We are able to see the following traces being tagged correctly:
image

### Possible Drawbacks / Trade-offs

Caching has not yet been implemented in the Remote Tagger and will be addressed in a subsequent PR.

### CODE REVIEW

**Review by jhgilbert — APPROVED** [review]

**Review by ichinaski — APPROVED** [review]
LGTM

**Review by songy23 — APPROVED** [review]
Approval for OTel

**Review by dustmop — APPROVED** [review]
LGTM for ASC-owned files

**Pull request merged**
