### PR TITLE
Include windows unit tests into concurrency group

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

We run a lot of windows tests everyday, this PR would allow us to auto-cancel jobs on branches where new commits have been pushed (and thus a new job is running). 🌍 

```
${{ github.workflow }}-${{ github.head_ref || github.run_id }}
```
- the workflow part allows us to scope the group to this specific workflow
- head_ref or run_id allows us to scope the group to a specific branch (in case of a pull request event) or a unique run_id (will be used on the main branch mostly)

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by mx-psi** [comment]
Let's move this to 7.42, I don't feel comfortable merging this right before the freeze

**Comment by paulcacheux** [comment]
@mx-psi should we move this to 7.43 or maybe close it altogether

**Review by mx-psi — APPROVED** [review]
Sorry forgot about this. I think if we merge this today and keep a close eye on it it should be fine, otherwise yes, I would postpone it to 7.43.0

**Comment by paulcacheux** [comment]
I will merge it and keep a close eye on it

**Comment by paulcacheux** [comment]
If I see something strange I will not hesitate to revert it

**Pull request merged**
