### PR TITLE
rpmsigning: Gracefully interrupt RPM operations

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

This PR attempts to interrupt RPM operations in a more gracefull way, by using SIGINT instead of the SIGKILL defaults.
It also increase the timeout before interrupting the RPM commands, as 2s might be a bit too short in some high load conditions.

### Motivation

Let RPM cleanup behind it and leave its database in an uncorrupted state

### CODE REVIEW

**Review by alopezz — APPROVED** [review]
I'm guessing this is not very testable (at least not as-is)?

**Review by chouetz — APPROVED** [review]
lgtm

**Comment by chouquette** [comment]
> I'm guessing this is not very testable (at least not as-is)?

It would require non negligible changes in the test code, and possibly to the code itself, but I'm not fluent enough in go to assess more precisely

**Pull request merged**
