### PR TITLE
Rework logs pipeline utilization metrics to improve performance. 

### PR DESCRIPTION
**Pull request by gh123man**
### What does this PR do?

The previous implementation reused the tracker shared with measuring check worker utilization. However that code does not perform well in a hot path like the logs pipeline. 

This PR falls back to an older approach I tried that only computes the utilization every tick as triggered by the start/stop method. 
This has some minor drawbacks:
- if the pipeline is blocked, the utilization metric will appear to be stuck. 

However removing the channel operations from the hot path significantly improve performance of this code. 
### Describe how to test/QA your changes

Done (Via SMP and AML benchmark cluster)

### CODE REVIEW

**Review by ankitpatel96 — APPROVED** [review]
otel piece looks good

**Review by vickenty — APPROVED** [review]

**Review by jcstorms1 — APPROVED** [review]

**Review by dustmop — APPROVED** [review]
LGTM for ASC files

**Review by remeh — CHANGES_REQUESTED** [review]
We discussed offline how you can get rid of the ticker here since it's not really necessary, however if you want to stick with it, you'll have to `Stop()` somewhere.

Otherwise, LGTM!

**Review by ogaca-dd — APPROVED** [review]

**Review by remeh — APPROVED** [review]

**Pull request merged**
