### PR TITLE
Bump `k8s.io/kube-state-metrics/v2`

### PR DESCRIPTION
**Pull request by keisku**
### What does this PR do?

Address two breaking changes in `k8s.io/kube-state-metrics/v2` to update from v2.8.2 to v2.12.0

https://github.com/kubernetes/kube-state-metrics/pull/1851

`pkg/customresource/registry_factory.go`

```diff
type RegistryFactory interface {
	// ...
-	MetricFamilyGenerators(allowAnnotationsList, allowLabelsList []string) []generator.FamilyGenerator
+	MetricFamilyGenerators() []generator.FamilyGenerator
	// ...
}
```

https://github.com/kubernetes/kube-state-metrics/pull/2017

`pkg/builder/types/interfaces.go`

```diff
type BuilderInterface interface {
	// ...
-	WithVPAClient(c vpaclientset.Interface)
	// ...
}
```

### Motivation

- Bump `k8s.io/kube-state-metrics/v2`.
- https://github.com/DataDog/datadog-agent/pull/25103/files#r1586257750

### Additional Notes

Currently, we don't filter by `MetricFamilyGenerators(allowAnnotationsList, allowLabelsList)` since any annotations/labels can be used for label joins, which is hardcode.

- https://github.com/DataDog/datadog-agent/blob/95cd819f4add36ad4104ecf35d543b4b3db9af50/pkg/collector/corechecks/cluster/ksm/kubernetes_state.go#L266-L274
- https://github.com/DataDog/datadog-agent/blob/95cd819f4add36ad4104ecf35d543b4b3db9af50/pkg/collector/corechecks/cluster/ksm/kubernetes_state.go#L320-L330

### CODE REVIEW

**Comment by AliDatadog** [comment]
This PR requires an upstream contribution as a bug was introduced in 2.9.x.

**Comment by AliDatadog** [comment]
> @AliDatadog can you share related issue URLs of the bug?

https://github.com/kubernetes/kube-state-metrics/issues/2202

It should be fixed by https://github.com/kubernetes/kube-state-metrics/compare/main...AliDatadog:kube-state-metrics:ali/fix-interface but I didn't propose the change yet

**Comment by keisku** [comment]
Thanks for sharing. I will keep an eye on the issue and hope your changes get merged soon!

**Comment by L3n41c** [comment]
Superseded by #30061.

**Pull request closed without merging**
