### PR TITLE
Maxime/dogstatsd system tests

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

The goal is to have system tests for dogstatsd. For that I added cobra command to allow custom path for the configuration file.

We only test start, receive and forward for now.

### Motivation

We unit test every package but not the final binary.

### Additional Notes

In the futur we could have the default flush time of the forwarder configurable. This would allow a shorter test time (15s right now).

For now the system tests aren't included in the CI, this will come if when we agree on a way to write system tests.

### CODE REVIEW

**Review by olivielpeau — APPROVED** [review]
Nice stuff!

Should we really put these in a `hacks` folder though? :)

**Review by hush-hush — COMMENTED** [review]
@olivielpeau I followed K8s ways, but really if you have a better idea than "hacks" I'm listening. "ci" ? "tools" ?

**Review by xvello — COMMENTED** [review]
LGTM, a sane base on which we will be able to iterate

**Review by masci — CHANGES_REQUESTED** [review]
only few nits, otherwise 👍 
Regarding the repo layout, let's put these modules in `datadog-agent/test/system/dogstatsd` or `datadog-agent/test/integration/dogstatsd`.

**Review by gmmeyer — APPROVED** [review]
these look like good additions! I don't have anything to add to what's already been said. 😄

Once you address the other comments, feel free to merge.

**Review by masci — APPROVED** [review]

**Pull request merged**
