### PR TITLE
[py] terminate python subprocesses if shutdown in process

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

Keeps track of running subprocesses, send a `SIGINT` signal (should maybe be `SIGTERM`) during shutdown to live processes.

`SIGINT` is the interrupt signal. The terminal sends it to the foreground process when the user presses ctrl-c. The default behavior is to terminate the process, but it can be caught or ignored. The intention is to provide a mechanism for an orderly, graceful shutdown.

`SIGTERM` is the termination signal. The default behavior is to terminate the process, but it also can be caught or ignored. The intention is to kill the process, gracefully or not, but to first allow it a chance to cleanup.

### Motivation

Issues during `launchctl` shutdown on mac, could make shutdown a little more graceful, but really debatable if this should be merged.

### CODE REVIEW

**Comment by olivielpeau** [comment]
I just tried reproducing the `launchctl` issue on mac, and it's not present on `6.5.0` anymore: the `netstat` subprocess of the `network` check doesn't prevent the Agent from stopping. 

https://github.com/DataDog/datadog-agent/pull/2240 actually solved the issue. On a local dev builds:
1. agent built from `master` exits quickly when it receives SIGTERM while `network` check is running
2. agent built from `master` + revert of #2240 waits until the `netstat` subprocess terminates while network check is running

Digging a bit deeper (by dumping the goroutines of an agent waiting to stop in `2.`), it appears the call that was actually blocking is here: https://github.com/DataDog/datadog-agent/blob/6.5.2/pkg/collector/embed.go#L36. So this was all caused by the goroutine shutting down the Agent that was blocked on the GIL held by `GetSubprocessOutput` (until the subprocess exited). I really should've investigated this before I created the card 😬 

So we'll want to include what the behavior of the present PR only if we want subprocesses launched by python checks to be cleanly terminated before we exit the Agent. Which is surely a desirable behavior, but not as important as before.

About this PR specifically: have you looked into passing a shared context when creating the subprocess (https://golang.org/pkg/os/exec/#CommandContext) and canceling the context when we want to kill all existing subprocesses?

**Comment by truthbk** [comment]
It had been so long since I wrote the code in the PR's branch I had kind of lost perspective. The code here is actually older than #2240 🤦‍♂️  

Regardless we should try to gracefully terminate the subprocesses, so I'll implement that. I hadn't seen this: https://golang.org/pkg/os/exec/#CommandContext - which is definitely a lot cleaner and idiomatic, so I'll use that instead - I'll rewrite the PR.

**Comment by olivielpeau** [comment]
sorry, didn't get to review this and we're very close to the 6.8 freeze... Postponing to 6.9

**Review by remeh — APPROVED** [review]
I was not able to reproduce the issue, even by using a launchd service.

Other than that, the code of the PR looks great, adding a context.Context can't hurt while using exec.Cmd 👍

**Pull request merged**
