### PR TITLE
pkg/trace/traceutil: Add fast-path for NormalizeTags to reduce cpu usage

### PR DESCRIPTION
**Pull request by ajgajg1134**
### What does this PR do?
This PR ports a fast-path improvement for Tag Normalization thanks in large part to @felixge 

### Motivation
We've seen a large portion of tags are already ascii and normalized, by introducing a fast path here we can reduce the amount of CPU spent on normalizing tags.

### Additional Notes
According to the already included benchmark `BenchmarkNormalizeTag` when a tag is already normalized this fast path provides a significant improvement over the current implementation (61ns / op -> 7ns / op)

### Describe how to test/QA your changes
I believe the numerous unit tests here are sufficient to ensure backwards compatibility. 

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by felixge** [comment]
Awesome, thanks @ajgajg1134 🙇. Q: I've also optimized the slow path for NormalizeTag internally, are you planning to also port those optimizations?

**Review by knusbaum — APPROVED** [review]
One suggestion, but not blocking.

**Comment by ajgajg1134** [comment]
> Awesome, thanks @ajgajg1134 🙇. Q: I've also optimized the slow path for NormalizeTag internally, are you planning to also port those optimizations?

I hadn't looked at those changes just yet, and had a few free minutes yesterday and saw this as an "easy-pickings" so decided to pull it over real fast since it seemed like a quick and easy win. I think we plan to pull the slow path improvements as well (Likely in a separate PR since this change was so easy to pull over / review and verify)

**Review by apigirl — COMMENTED** [review]
no docs review needed

**Review by apigirl — APPROVED** [review]

**Pull request merged**
