### PR TITLE
[percentile] Additional sketches for testing algorithms

### PR DESCRIPTION
**Pull request by jeerim**
### What does this PR do?

Add additional sketches KLL and CompleteDS (holds all the data) for comparison with GKArray. Also update agent-payload version to include the additional sketches.

### Motivation

Need to be able to compare and evaluate the sketch algorithms GKArray and KLL before making a final choice. 

### Additional Notes

Ultimately, either GKArray or KLL will be chosen, so this is a temporary state while we evaluate the different sketch algorithms.

### CODE REVIEW

**Review by olivielpeau — DISMISSED** [review]
Only looked at the bits outside the `percentile` package: LGTM!

**Review by GeorgeErickson — DISMISSED** [review]
LGTM

**Comment by GeorgeErickson** [comment]
Added a few `s = s.Add(...).(GKArray)` lines to make tests pass. 

@jeerim you might wanna review again

**Review by GeorgeErickson — COMMENTED** [review]
@jeerim - could you also run a quick perf test of the normal `statsd.Distribution` call to make sure these changes don't slow things down too much.

I'm ok with the `complete` and `kll` versions being slow.

**Review by olivielpeau — APPROVED** [review]

**Pull request merged**
