### PR TITLE
[EBPF] Use uint64 instead of uintptr in CGo types

### PR DESCRIPTION
**Pull request by gjulianm**
### What does this PR do?

This PR is a followup to https://github.com/DataDog/datadog-agent/pull/29221, changing the uintptr to uint64 as Go still considers uintptr a variable-size type.

### Motivation

Avoid problems when generated types are structs with pointers inside, as the calls to `binary.Read/Write` used in some APIs (batch map APIs mainly) cannot deal with them correctly.

### CODE REVIEW

**Review by akarpz — APPROVED** [review]

**Comment by usamasaqib** [comment]
Is there a test we can add for this?

**Comment by gjulianm** [comment]
> Is there a test we can add for this?

Adam validated it on his branch. Or you mean a test for the correct generation of the code?

**Comment by usamasaqib** [comment]
> Adam validated it on his branch. Or you mean a test for the correct generation of the code?

A test to validate that we are iterating maps with pointers as keys correctly.

**Comment by gjulianm** [comment]
> > Adam validated it on his branch. Or you mean a test for the correct generation of the code?
> 
> A test to validate that we are iterating maps with pointers as keys correctly.

There is one, I added it on the previous PR: https://github.com/DataDog/datadog-agent/pull/29220/files.

**Review by usamasaqib — APPROVED** [review]

**Pull request merged**
