### PR TITLE
AMLII-1233: Adds basic py check in regression detector env

### PR DESCRIPTION
**Pull request by scottopell**
### What does this PR do?
Adds a regression detector experiment that runs a python check. 

### Motivation
No current scenarios are running python checks, this adds _something_ even if its the simplest possible check.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by scottopell** [comment]
Another candidate for a python check that could be useful, the one from https://github.com/DataDog/datadog-agent/pull/21424

**Review by GeorgeHahn — APPROVED** [review]
Could you PR this to single-machine-performance too? This looks like a compelling experiment for a memory optimization goal.

**Comment by scottopell** [comment]
Deferring this until Agent CI uses a version of `lading` with this change https://github.com/DataDog/lading/pull/774 (bug is: when no generators are specified, lading exits too early)

**Comment by scottopell** [comment]
lading 0.20.4 is now the version used in this repo, once mergefreeze is lifted I'll merge this.

**Review by KSerrania — APPROVED** [review]

**Pull request merged**
