### PR TITLE
Add patches for python2

### PR DESCRIPTION
**Pull request by masci**
### What does this PR do?

Not sure how the build could succeed before. ~Still unclear if the patches are needed with `2.7.16`~

### CODE REVIEW

**Comment by olivielpeau** [comment]
I believe we still need these patches. Their naming (with `2.7.11`) is misleading, but overall as long as the patches can be applied successfully on the python 2 version we're building, we should keep them around

**Comment by masci** [comment]
re-added patches

**Comment by ofek** [comment]
Ha, it's been a long time since I've seen the word thunk, thanks

**Comment by masci** [comment]
superseded by https://github.com/DataDog/datadog-agent/pull/3328

**Pull request closed without merging**
