### PR TITLE
Check go version in CI

### PR DESCRIPTION
**Pull request by djmitche**
### Motivation

It's easy to use the wrong rev of a docker image and end up building with the wrong version of Go, and not catch that soon enough.

### Additional Notes

I'll add a similar check to the macos repo.

### Describe how to test/QA your changes

No need - test only.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by brycekahle — APPROVED** [review]

**Review by clarkb7 — APPROVED** [review]
One question, but LGTM as is.

Does it make sense for this task to also be called in the `source_test` gitlab tasks?
* https://github.com/DataDog/datadog-agent/blob/main/tasks/winbuildscripts/unittests.ps1#L45
* https://github.com/DataDog/datadog-agent/blob/main/tasks/winbuildscripts/sysprobe.ps1#L17

**Comment by djmitche** [comment]
Looks like just normal kitchen failures here, unrelated to this check.

**Comment by djmitche** [comment]
> Does it make sense for this task to also be called in the source_test gitlab tasks?

I think the critical thing is that we're shipping binaries made with the right Go version.  The version we use to run tests is less critical, and anyway uses the same docker images, etc. so is probably the same.

**Review by bkabrda — APPROVED** [review]
Great idea, LGTM.

**Review by sgnn7 — APPROVED** [review]
:shipit: 🚀

**Pull request merged**
