### PR TITLE
pkg/trace: use go.uber.com/atomic (again)

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Uses go.uber.com/atomic to ensure alignment of atomic access in pkg/trace (second landing, after #12120 was reverted in #12568).

### Motivation

Alignment issues with atomic access.  See #11716, https://pkg.go.dev/sync/atomic#pkg-note-BUG and https://go101.org/article/memory-layout.html

### Additional Notes

This package uses a lot of atomics!  For structs that are basically just a list of atomics, I chose to use them inline instead of via pointers.  Some of these structs are unmarshaled from JSON, and using a pointer means that the zero value is `nil` instead of `NewUint64(0)`, which leads to a lot of fiddly nonsense.  So it was just easier to use them embedded in the struct.

In addition to the changes in #12120, this adds tests for, and fixes the serialization of stats by expvar.  These values were cast to `interface{}`, so the change in type from `int64` to `atomic.Int64` did not raise any issues for the compiler.

Reviewers more familiar with the trace agent should consider if there are other areas where this sort of serialization takes place, that I have not yet spotted.

### Describe how to test/QA your changes

In #12120, the thing that broke was `agent status`, so verify that `agent status` still produces useful output when trace-agent is running.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by alai97 — APPROVED** [review]
Looks good, one copy nit!

**Review by mx-psi — APPROVED** [review]
The docs update LGTM

**Review by katiehockman — APPROVED** [review]
Reviewed the changes in commits 1, 2, and 4 (since the other big commit was already reviewed and merged previously) and they look good. Only small thing is that the new files use a copyright of 2016. Should that be 2022?

Thanks!

**Comment by djmitche** [comment]
I'll update the copyright dates and merge.  Thanks!

**Pull request merged**
