### PR TITLE
Add journalctl output on trace-agent bound port error

### PR DESCRIPTION
**Pull request by KevinFairise2**
### What does this PR do?

Add some more information to what prevented the trace-agent from starting.

For example"
```
        	Test:       	TestInstallScript/test_install_script_on_debian-9_x86_64_datadog-agent_agent_7/TestInstallAgent/port_bound_apm_enabled
        	Messages:   	port 8126 of trace-agent should be bound when APM is enabled:
        	            	 Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]: WARNING: `--pid` argument is deprecated and will be removed in a future version. Please use `--pidfile` instead.
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]: Usage:
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   trace-agent [command] [flags]
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   trace-agent [command]
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]: Available Commands:
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   completion  Generate the autocompletion script for the specified shell
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   help        Help about any command
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   info        Gather Datadog trace-agent information.
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   run         Start datadog trace-agent.
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   version     Print the version info
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]: Flags:
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   -c, --config string        path to directory containing datadog.yaml (default "/opt/datadog-agent/etc/datadog.yaml")
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   -l, --cpu-profile string   enables CPU profiling and specifies profile path.
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   -h, --help                 help for trace-agent
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   -m, --mem-profile string   enables memory profiling and specifies profile.
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]:   -p, --pidfile string       path for the PID file to be created
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]: Use "trace-agent [command] --help" for more information about a command.
        	            	Jan 11 12:55:47 ip-10-1-60-59 trace-agent[1080]: Error: unknown flag: --pidfilefile
        	            	Jan 11 12:55:47 ip-10-1-60-59 systemd[1]: datadog-agent-trace.service: Main process exited, code=exited, status=255/n/a
        	            	Jan 11 12:55:47 ip-10-1-60-59 systemd[1]: datadog-agent-trace.service: Unit entered failed state.
        	            	Jan 11 12:55:47 ip-10-1-60-59 systemd[1]: datadog-agent-trace.service: Failed with result 'exit-code'.
```

### Motivation

When we have an issue with the trace-agent, the only error that is visible is that the trace-agent port was not correctly bound. With this we now display the content of journalctl to give more info about the error.

System that do not have the journalctl command will not display more information.

### Additional Notes

I use `journalctl | grep 'trace-agent\|datadog-agent-trace` to get the journalctl logs related to `trace-agent`. I first tried with `journalctl -u datadog-agent-trace` but it looks not reliable as sometimes some (meaningful) logs are missing

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided. Except if the `qa/skip-qa` label, with required either `qa/done` or `qa/no-code-change` labels, are applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Looks straightforward, it'd be nice to use the native options of `journalctl` rather than grepping. But I feel like that's more of an opinion than actual improvement.

**Comment by KevinFairise2** [comment]
> Looks straightforward, it'd be nice to use the native options of `journalctl` rather than grepping. But I feel like that's more of an opinion than actual improvement.

I put some note about it in the description. I actually tried to use `journalctl -u datadog-agent-trace` but it lead to imcomplete logs. I cannot really understand why but it is like if some logs in `journalctl` are not linked properly with the `datadog-agent-trace` unit and not displayed when filtered 🤷‍♂️

**Comment by spencergilbert** [comment]
Yeah, not sure why that would be happening - and realistically it doesn't change much of the outcome, nor does it save us installing an additional tool. It just _feels_ like the right way 😅

**Pull request merged**
