### PR TITLE
Improve logs in api security

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Improve logs around api security.

### Motivation

https://github.com/DataDog/datadog-agent/pull/21025#discussion_r1412494689

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by sgnn7** [comment]
> @sgnn7 would you like more logging somewhere ? What do you think of using `log.InfoStackDepth`, it might not be super clear when looking at the code but that way you know when reading the logs what called the initialization functions

Seems reasonable - primary purpose is mainly to audit creation and usage of these when debugging/running. I don't think I'm a fan of `log.InfoStackDepth` mainly because we've had various problems with that functionality in the past but I'll leave it up to you if you want to keep or not.

**Review by sgnn7 — APPROVED** [review]

**Comment by pgimalac** [comment]
Replaced `log.InfoStackDepth` with explicit calls to `runtime.Caller` and `log.Infof`.

**Pull request merged**
