### PR TITLE
Update debian-11 to use our private AMI

### PR DESCRIPTION
**Pull request by KevinFairise2**
### What does this PR do?

Revert a temporary fix introduced by https://github.com/DataDog/datadog-agent/pull/22767
to use our private AMI

### CODE REVIEW

**Comment by KevinFairise2** [comment]
/trigger-ci --variable RUN_E2E_TESTS=auto --variable RUN_KITCHEN_TESTS=true

**Review by amenasria — APPROVED** [review]
LGTM !

**Pull request merged**
