### PR TITLE
Do not commit changes to runtime integrity hashes to repo

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

Ignores changes to the runtime integrity hashes in git. This still leaves a skeleton file in the repo with an empty hash, for linting and build purposes. The builds will still generate the complete hashes and be included in released binaries.

### Motivation

The hashes are not consistently checked-in when the source content is changed. This results in hash files being part of PRs where nothing relevant actually changed, and the owning teams requested for review.

### Additional Notes

New files will need to be manually added, but this is a relatively rare operation.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by hmahmood** [comment]
Can we just add these files to `.gitignore`?

**Comment by paulcacheux** [comment]
Do you think https://github.com/DataDog/datadog-agent/pull/12114 will not work ?

**Comment by brycekahle** [comment]
> Can we just add these files to `.gitignore`?

Nope. I tried this first. Once a file is part of the index, `.gitignore` doesn't do anything.

**Comment by brycekahle** [comment]
> Do you think #12114 will not work ?

They do different things. Your PR ensures the CWS hashes are always generated during a build. This is preventing hash updates from being committed to git at all. Since we are re-generating the hashes during build, we aren't concerned with validating the exact hashes being committed. The files are kept to prevent basic build error dues to missing variables.

**Review by lebauce — APPROVED** [review]

**Review by nplanel — APPROVED** [review]

**Pull request merged**
