### PR TITLE
Bump go extended libraries

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Bump all `golang.org/x/...` dependencies in all modules.

### Motivation

Stay up to date, clean up a dozen dependabot PRs.

### Additional Notes

PR created by running
```
inv modules.for-each "go get golang.org/x/arch golang.org/x/crypto golang.org/x/lint golang.org/x/mod golang.org/x/net golang.org/x/sync golang.org/x/sys golang.org/x/term golang.org/x/text golang.org/x/time golang.org/x/xerrors golang.org/x/tools golang.org/x/exp"
inv tidy-all
```

### CODE REVIEW

**Review by amenasria — APPROVED** [review]
LGTM for Agent DevX Infra owned files !

**Review by vickenty — APPROVED** [review]

**Review by iglendd — APPROVED** [review]
LGTM for Windows files

**Review by ichinaski — APPROVED** [review]

**Review by clamoriniere — APPROVED** [review]
/lgtm for @DataDog/container-platform team

**Review by L3n41c — APPROVED** [review]

**Review by remeh — APPROVED** [review]

**Review by liustanley — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Review by Gui774ume — APPROVED** [review]

**Review by robertjli — APPROVED** [review]

**Review by moth-a — APPROVED** [review]

**Review by misteriaud — APPROVED** [review]

**Pull request merged**
