### PR TITLE
[all] Update OpenTelemetry Collector dependencies to v0.103.0

### PR DESCRIPTION
**Pull request by mx-psi**
### What does this PR do?

Updates OpenTelemetry Collector modules to v0.103.0/v1.10.0

### Motivation

open-telemetry/opentelemetry-collector/issues/10447

### Describe how to test/QA your changes

No QA needed, only renames

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Does this need QA? If so please update with instructions

**Review by alai97 — APPROVED** [review]
Looks good for docs

**Comment by mx-psi** [comment]
> Does this need QA? If so please update with instructions

No relevant changes upstream that would require QA here IMO, so I added `skip-qa`

**Review by pgimalac — APPROVED** [review]

**Review by remeh — APPROVED** [review]
LGTM for @DataDog/agent-processing-and-routing owned files.

**Review by ichinaski — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Pull request merged**
