### PR TITLE
[gitlab] Use two GitHub Apps for macOS jobs

### PR DESCRIPTION
**Pull request by KSerrania**
### What does this PR do?

Updates macOS jobs to use two different GitHub Apps to trigger macOS builds, allowing us to double the number of uses before getting rate-limited.

[ACIX-247
](https://datadoghq.atlassian.net/browse/ACIX-247)
### Motivation

Reduce rate-limiting errors.

### Additional Notes

For this first implementation, the use of each app is evenly spread among the jobs. In a future iteration, we could try to assign the app with the most remaining requests to the job.

### Possible Drawbacks / Trade-offs

n/a

### Describe how to test/QA your changes

Run a full pipeline, check that all macOS jobs run and succeed, and that they use different GitHub Apps.

### CODE REVIEW

**Comment by KSerrania** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Review by Pythyu — APPROVED** [review]
🚀

**Review by KevinFairise2 — APPROVED** [review]

**Review by FlorentClarret — APPROVED** [review]

**Review by pducolin — APPROVED** [review]

**Review by CelianR — APPROVED** [review]
LGTM !

**Pull request merged**
