### PR TITLE
Transfer installation methods ownership to container-ecosystems

### PR DESCRIPTION
**Pull request by Pythyu**
### What does this PR do?

Transfer code related to installation methods to container-ecosystems, agent-delivery stays as shadow / 2nd reviewer for now

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
I wonder if all of these should be handed off, if some of the tests are testing the packages being installable/containing the right bits we may still own those?

**Review by FlorentClarret — CHANGES_REQUESTED** [review]
Left one comment, otherwise LGTM

**Review by FlorentClarret — APPROVED** [review]

**Review by CelianR — APPROVED** [review]

**Pull request merged**
