### PR TITLE
Use go.uber.org/atomic in pkg/security

### PR DESCRIPTION
**Pull request by djmitche**
### What does this PR do?

Uses go.uber.com/atomic to ensure alignment of atomic access in cmd/system-probe.

### Motivation

Alignment issues with atomic access, and enforcing atomic access to atomic variables.  See #11716.

### Additional Notes

At several points, especially in perf_buffer_monitor.go, atomic values were accessed non-atomically.  All accesses are now atomic.

There were a few places where alignment wasn't guaranteed, but since most struct fields are 32-bit-aligned, the chances are 50/50 that a given 64-bit atomic variable was properly aligned.  Adding another field to any of these structs might have introduced alignment issues.

### Possible Drawbacks / Trade-offs

Many of the `uint64` and `int64` struct fields that were treated atomically are now a pointer.  I believe, based on a guess from the type name, that these structs are few in number and not allocated frequently, so additional pointer allocations should not create memory- or cpu-performance issues.  But, please look over the patches with this in mind and verify my assumption.

### Describe how to test/QA your changes

Any basic security-agent QA should detect issues here.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by paulcacheux** [comment]
Hello ! Thanks for this PR. On the other hand I'm a bit afraid that this will not scale if we do not enforce this policy of not using the default atomics.

**Comment by djmitche** [comment]
Once all uses of `sync/atomic` are gone, we'll enforce that.

**Review by paulcacheux — APPROVED** [review]

**Comment by paulcacheux** [comment]
The CI is failing for real reasons around `pkg/security/tests/module_tester.go`. Otherwise LGTM :+1:

**Comment by djmitche** [comment]
Looksl ike GitLab didn't update some checks here -- the pipeline is green in GitLab.

**Comment by djmitche** [comment]
Yellow jobs are due to problems syncing from GitLab -- the pipeline is green.

**Comment by paulcacheux** [comment]
Yes this PR is great, we'll merge it when main is unfrozen

**Comment by djmitche** [comment]
Whoops, I didn't mean to repeat myself there!  I was just checking through my PRs to make sure CI had succeeded :)

**Pull request merged**
