### PR TITLE
[DCA][Admission] Fix admission controller not starting

### PR DESCRIPTION
**Pull request by ahmed-mez**
### What does this PR do?

- Make the admission controller the last component to start in the cluster agent
- Instead of querying api groups and resources from the api server, try to list objects using the v1 and v1beta1 apis and decide which one to use.

### Motivation

Fix this:
```
XXXX-XX-XX XX:XX:XX UTC | CLUSTER | ERROR | (app/app.go:290 in start) | Could not start admission controller: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

Bug explanation:
When the cluster agent is registered as external metrics provider, it can fail at startup to answer the api server query on `external.metrics.k8s.io/v1beta1` because it takes about 30s to become ready. This makes the admission controller discovery call fail.

### Additional Notes

- The delay caused by the retries does not impact any other cluster agent component because the admission controller is the last component to start

### Describe how to test/QA your changes

Should be tested on 3 different k8s versions:
- k8s < 1.16 for v1beta1 only -> use v1beta1
- 1.16 < k8s < 1.22 where both versions are available -> use v1
- k8s >= 1.22 where only the v1 is available -> use v1

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [x] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [x] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by ruthnaebeck — APPROVED** [review]
👍  for docs

**Review by djmitche — APPROVED** [review]
pkg/config changes look good

**Comment by vboulineau** [comment]
Could we get around that by just performing a `ctx.Client.AdmissionregistrationV1().MutatingWebhookConfigurations().List()` and check the error returned?

**Comment by ahmed-mez** [comment]
@vboulineau good idea 👌  It's implemented in the latest commit (could have been prettier if we had generics)

**Review by vboulineau — APPROVED** [review]

**Pull request merged**
