### PR TITLE
Move builds to docker-machine

### PR DESCRIPTION
**Pull request by adrienkohlbecker**
We recently introduced docker-machine as a way to get an ephemeral docker box for a build, and are deprecating the dind runners.

More info: https://github.com/DataDog/devops/wiki/Gitlab#doing-a-docker-build

### CODE REVIEW

**Review by xvello — DISMISSED** [review]
LGTM

**Review by xvello — APPROVED** [review]
LGTM!

**Comment by olivielpeau** [comment]
discussed this IRL: let's wait for the final artifacts of rc.1 to be built before merging this, will let you know

**Review by olivielpeau — APPROVED** [review]
Let's do this :)

**Pull request merged**
