### PR TITLE
creates pkg/util/containers/image go module

### PR DESCRIPTION
**Pull request by jackgopack4**
### What does this PR do?

creates a go module for pkg/util/containers/image functionality.

### Motivation

[OTEL-1995](https://datadoghq.atlassian.net/browse/OTEL-1995); infraattributesprocessor has a dependency on this functionality

### Describe how to test/QA your changes

run integrated unit/integration tests

[OTEL-1995]: https://datadoghq.atlassian.net/browse/OTEL-1995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by purple4reina — APPROVED** [review]

**Comment by clamoriniere** [comment]
Hi @jackgopack4 

could you provide more details about this logic needs to be in a dedicated go module? 
why `infraattributesprocessor` need to be a go module?

**Comment by jackgopack4** [comment]
> could you provide more details about this logic needs to be in a dedicated go module? why `infraattributesprocessor` need to be a go module?

yes of course. This is something we plan to use via opentelemetry collector builder (ocb) to build the Converged Agent; the version of the agent that customer can use as a drop-in replacement for OpenTelemetry collector.

**Comment by songy23** [comment]
Yes `infraattributesprocessor` and its dependencies need to be Go modules so that they can be included built with OCB

**Review by dustmop — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]

**Review by amenasria — APPROVED** [review]
LGTM for Agent Infra owned files !

**Comment by clamoriniere** [comment]
> Yes `infraattributesprocessor` and its dependencies need to be Go modules so that they can be included built with OCB

Hi @songy23 and @jackgopack4  but the OCB is implemented in the `datadog-agent` repo? if it the case, do we need a go module? if not where it is located?

my worry is that we are creating hundred of `go.mod` in this repo, and we split exiting package. At the end some of these packages contains only 2 functions. So instead of splitting already small package in 2. can we define maybe a larger `go.mod` that contains low level code base that can be used by different binary?

**Comment by clamoriniere** [comment]
Thanks for the link.

my comments about creating too many go module is still valid. I feel like we are adding technical debts to this repository to allow the import of go packages in another project.

Does the function is directly used in `infraattributesprocessor`  ?
Overall it is not a big deal to expose `SplitImageName()` in a go module despite the fact to have a module only for a function... however what is the expectation after for the evolution of the function, can we do breaking change? change the function signature with the risk of breaking external project?

**Review by clamoriniere — APPROVED** [review]
Approved, But still think that we can do a better job to define organise packages and function in go modules.

**Comment by jackgopack4** [comment]
I agree with your concerns and think there are definitely downsides to adding go modules to our agent code.

We do have a disclaimer on our datadog agent repository that go modules from DD-agent are intended for "internal consumption only" and are not guaranteed to be stable, at least

**Pull request merged**
