### PR TITLE
Fix kernel header downloading on COS

### PR DESCRIPTION
**Pull request by ISauve**
### What does this PR do?

Fixes a kernel header downloading bug where system-probe containers running on COS hosts are unable to find downloaded kernel headers.

This was occurring because the system-probe was detecting the running platform to be `ubuntu` instead of `COS`, causing it to look in the wrong location for kernel headers. The solution is simply to always check all possible places where kernel headers might be downloaded.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe how to test your changes

Write here in detail how you have tested your changes
and instructions on how this should be tested in QA.

Describe or link instructions to set up environment 
for testing, if the process requires more than just
running the agent on one of the supported platforms.

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

### CODE REVIEW

**Comment by brycekahle** [comment]
Why was it being detected as `ubuntu` and not `cos`?

**Comment by ISauve** [comment]
@brycekahle honestly, I'm not sure. The system-probe calls `host.GetStatusInformation()` to detect the current platform, and that checks `/etc/os-release`, which (in the system-probe container) is mounted from the host & states that the OS is `cos`. So it's very strange that it's returning the container's OS instead of the host's.

I took a quick look at some internal deployments and it looks to me like this is only happening on COS. I'll keep looking into it, but either way, I think that there isn't a good reason for us to not just check all the possible paths where kernel headers might be found.

**Comment by celenechang** [comment]
If I'm reading this correctly, it looks like if `/etc/debian_version` exists (which it does in my case) it reads the Platform from `/etc/lsb-release` https://github.com/shirou/gopsutil/blob/5268453c1e25853698065e9e5cb14afc175610c3/host/host_linux.go#L202-L205

**Comment by ISauve** [comment]
@celenechang very interesting, on my cluster `/etc/debian_version` doesn't exist, only `/etc/os-release` and `/etc/lsb-release` (which, for what it's worth, does contain information identifying the platform as `ubuntu`, however it should only be getting read if `/etc/os-release` isn't found)

**Review by brycekahle — APPROVED** [review]

**Pull request merged**
