### PR TITLE
pkg/trace/config: move env. var registrations to shared config pkg

### PR DESCRIPTION
**Pull request by gbbr**
This change moves the loading of environment variables into the main agent config package.

Whenever a file was loaded with the `pkg/config` package outside the `trace-agent` (e.g. agent CLI, flares, etc), it would lack environment variables. The reason for this was partly lack of functionality in the Viper dependency and also support for Agent 5 (and the way the `pkg/config/legacy` package was working).

Support for Agent 5 is no longer needed in this repository so it is safe to do it right now.

### CODE REVIEW

**Review by olivielpeau — APPROVED** [review]
LGTM at a high level, I think this approach will work well 👍 
(haven't reviewed in details that every config option is handled exactly the same though)

Notes/questions:

1. I have a preference for not calling `config.SetKnown` on config keys for which the code is setting defaults or env vars, that's the convention we use for core and logs agent
2. I think it'd make sense to allow env vars for all config options (that's what we're aiming for in other agent components). Would be a for a future PR of course.
3. should we start at some point using `DD_APM_CONFIG_` as an allowed prefix for apm env vars? Would be longer, but consistent with logs (`DD_LOGS_CONFIG_`)

**Comment by gbbr** [comment]
Thanks @olivielpeau!

> (haven't reviewed in details that every config option is handled exactly the same though)

That's ok, there are plenty of tests to cover for that, and I will test this well during release week too.

> I have a preference for not calling config.SetKnown on config keys for which the code is setting defaults or env vars, that's the convention we use for core and logs agent

Fixed!

> I think it'd make sense to allow env vars for all config options (that's what we're aiming for in other agent components). Would be a for a future PR of course.

I have added support via env. var. for all configuration options I considered that a user might want to work with. Some of them are either outdated or we want to discourage their use (such as `apm_config.extra_sample_rate`).

> should we start at some point using DD_APM_CONFIG_ as an allowed prefix for apm env vars? Would be longer, but consistent with logs (DD_LOGS_CONFIG_)

I don't think this is a bad idea, but I'd like to bring it up with the team before making this change on my own. I hope that's ok.

**Review by hush-hush — APPROVED** [review]
This is neat !

**Review by olivielpeau — APPROVED** [review]
LGTM!

> I don't think this is a bad idea, but I'd like to bring it up with the team before making this change on my own. I hope that's ok.

Sounds good 👍

**Review by knusbaum — APPROVED** [review]
LGTM

**Comment by lattwood** [comment]
@gbbr, @olivielpeau and others, it looks like this broke things for us: https://github.com/DataDog/datadog-agent/commit/b7467cc7b50bcad34b64268b25d3ba1dfeef4079#r43487574

We worked around it, but it was very concerning to see analyzed spans work one minute, then disappear the next.

**Pull request merged**
