### PR TITLE
add stakeholders to review `datadog-agent integration`

### PR DESCRIPTION
**Pull request by trishankatdatadog**
### Motivation

Add agent-core, agent-integrations, and prodsec as `datadog-agent integration` command reviewers.

### Additional Notes

N/A

### CODE REVIEW

**Review by olivielpeau — APPROVED** [review]
LGTM! Let's wait for the 6.6 freeze to end before merging

**Comment by trishankatdatadog** [comment]
No problemo, thanks boss 🙇

**Comment by trishankatdatadog** [comment]
Hi, can I get a ping, please? 🙇

**Comment by olivielpeau** [comment]
Thanks for the ping, merging 👍

**Pull request merged**
