### PR TITLE
(pkg/trace) Pre-grow the trace receiver buffers to the "Content-Length" header, or 8KiB

### PR DESCRIPTION
**Pull request by paullegranddc**
### What does this PR do?

Pre-allocate the buffers before copying request body's, in the trace-agent http receivers.

### Motivation

A non negligible portion of the time of the trace-agent is spent growing these buffers. Pre-allocating them to the request body, or a reasonable default if missing should reduce the cost of this operation

Screenshot 2024-04-25 at 14 53 26

### CODE REVIEW

**Comment by ajgajg1134** [comment]
Thanks! Do you have any benchmark data showing improvement here or any QA needed?

**Comment by paullegranddc** [comment]
> Thanks! Do you have any benchmark data showing improvement here or any QA needed?

I discussed with @knusbaum and @ahmed-mez and we decided that it can't really hurt anything, so we'd just merge it and look at if makes a significative change on the nightly releases

**Review by ajgajg1134 — APPROVED** [review]

**Comment by ajgajg1134** [comment]
Marking as approved but please either provide a QA testing plan or mark the PR as skip-qa/done if you already performed the QA

**Pull request merged**
