### PR TITLE
Add "Tolerate Unready" Annotation

### PR DESCRIPTION
**Pull request by psycotica0-shopify**
### What does this PR do?

Adds a new pod annotation to the kubernetes auto-discovery that allows metrics to be collected from unready pods.

### Motivation

Some of our pods go unready when they are struggling, which is a bad time for metrics to stop being collected.

### Additional Notes

This will bypass the normal logic that skips pods that aren't ready.
It's a bit of a divergence from the normal way of doing annotations, which is that they're based on the container.

This status is global to the pod, though, so I had to come up with something.
If you were to have a container named `tolerate-unready` this would be confusing, but still wouldn't collide because it'd still be looking for things suffixed off that (`.checks` or whatever)

I had a lot of trouble with the testing framework, so I simply adapted one of the tests I could convince to run on my system to require these changes by making one of the fixture pods unready, but adding the annotation so the tests still pass.

I _expect_ this PR will not be suitable for merging, but I figure it's a good place to start a dialog so I can massage it into a shape people like.

### CODE REVIEW

**Comment by psycotica0-shopify** [comment]
Also, I don't _appear_ to have auth to apply labels or milestones... so hopefully that's not a problem.

As for the release notes, my plan was to not write the release notes until people have had their say on approach, because it's not a sure thing yet.

**Comment by hkaj** [comment]
Hi @psycotica0-shopify
Thanks for the PR! That's definitely a feature we want to add. There are several things to consider about it, which I would like your (and anyone else reading this) opinion about, to make sure we're moving in the right direction:

- should this be the default behavior? I.e. should we just remove that setting, and consider the pod for autodiscovery as long as the phase is `Running`? I would argue that this is not a good idea, as sometimes, if a pod is not ready, it won't even be ready to serve metrics.
- should this setting be global? I.e. do we want the setting to apply to every pod, or to specific pods (as you do right now). For the aforementioned reasons I think a granular setting, per pod, is ideal. I could be convinced that both are needed, with the per-pod version overriding the global setting. But if no one wants that, per-pod is good.
- are annotations the right medium to configure this? Here I think annotations are a good start, there might be a use case for a category-based setting (say, whitelisting all pods where a container running some image exists), but we'll wait for user demand before thinking about adding that.

If everyone is fine with this, I'm happy to merge this as is, as soon as you add a release note for this change. Unless you want to add something else to this PR?

**Comment by psycotica0-shopify** [comment]
I don't know enough about why the decision was made to ignore pods to know if it should be the default.
That being said, since we setup autodiscover like this, it seemed like a useful place to say "This configuration supports unready pods too"

But! If people want to make it global, that would _also_ solve my problem.

In terms of merging this, my primary concerns are that I've hard-coded a string, but I don't know the right place to put it, if that is a problem.
And I had a hard time getting some kind of integration test going, so this one test passes, and it doesn't if I undo my code, but I don't _know_ that I've made enough changes that a real datadog-agent would really detect and (most importantly) process this pod.

If someone has a working env set up that could test *that* that'd be great!

**Comment by hkaj** [comment]
Hey @psycotica0-shopify, sorry for the delay, I was out.

> I don't know enough about why the decision was made to ignore pods to know if it should be the default.

We made that call because usually when a pod is seen in the kubelet but is not ready, it will not respond to requests coming from a check, meaning we're scheduling a check for no reason. However the use case you raise is something we've seen coming up recently and it's worth addressing.

> That being said, since we setup autodiscover like this, it seemed like a useful place to say "This configuration supports unready pods too"

Agreed.

> In terms of merging this, my primary concerns are that I've hard-coded a string, but I don't know the right place to put it, if that is a problem.

Right, if you could make it [a const in that file](https://github.com/DataDog/datadog-agent/blob/b3cb6353c55bcc00b98def09e06fed0ca89ebc5b/pkg/util/kubernetes/kubelet/kubelet.go#L31) that would be great. Then we'll call out this annotation in the docs, and that should be enough.

> And I had a hard time getting some kind of integration test going

Your unit test is a good start, here is an end-to-end test to go with it. You can run it with `invoke -e e2e-tests -t local --image datadog/agent-dev:psycotica0-shopify-cv-tolerate-unready` if you set up the end-to-end test suite as detailed [here](https://github.com/DataDog/datadog-agent/tree/master/test/e2e).

The image I reference is a build of your branch. We don't expose the end-to-end test results in github yet unfortunately, so you'll need to run it locally or I can check our tests results once it's committed. Let me know if you hit any issue there.

```diff
diff --git a/test/e2e/argo-workflows/agent.yaml b/test/e2e/argo-workflows/agent.yaml
index 1ac9698a..8a9dd54a 100644
--- a/test/e2e/argo-workflows/agent.yaml
+++ b/test/e2e/argo-workflows/agent.yaml
@@ -68,6 +68,41 @@ spec:
                     memory: "128Mi"
                     cpu: "100m"

+    - name: redis-deployment-unready
+      value: |
+        apiVersion: extensions/v1beta1
+        kind: Deployment
+        metadata:
+          name: redis-unready
+          namespace: default
+        spec:
+          replicas: 1
+          template:
+            metadata:
+              labels:
+                app: redis
+              annotations:
+                ad.datadoghq.com/tolerate-unready: "true"
+            spec:
+              containers:
+              - name: redis-unready
+                image: redis
+                ports:
+                - name: redis
+                  containerPort: 6379
+                resources:
+                  requests:
+                    memory: "64Mi"
+                    cpu: "50m"
+                  limits:
+                    memory: "128Mi"
+                    cpu: "100m"
+                readinessProbe:
+                  tcpSocket:
+                    port: 8080
+                  initialDelaySeconds: 1
+                  periodSeconds: 1
+
     - name: cpu-stress
       value: |
         apiVersion: extensions/v1beta1
@@ -520,6 +555,7 @@ spec:
       - name: dsd-hostname
       - name: redis-service
       - name: redis-deployment
+      - name: redis-deployment-unready
       - name: agent-configmap
       - name: agent-service-account
       - name: agent-cluster-role
@@ -554,6 +590,17 @@ spec:
         withItems:
         - "{{inputs.parameters.redis-deployment}}"

+      - name: redis-deployment-unready-setup
+        template: manifest
+        arguments:
+          parameters:
+          - name: action
+            value: "apply"
+          - name: manifest
+            value: "{{item}}"
+        withItems:
+        - "{{inputs.parameters.redis-deployment-unready}}"
+
       - name: kube-state-metrics-setup
         template: manifest
         arguments:
@@ -625,6 +672,9 @@ spec:
       - name: find-metrics-redis
         template: find-metrics-redis

+      - name: find-metrics-redis-unready
+        template: find-metrics-redis-unready
+
       - name: find-metrics-cpu-docker
         template: find-metrics-cpu-docker

@@ -685,6 +735,7 @@ spec:
       parameters:
       - name: redis-service
       - name: redis-deployment
+      - name: redis-deployment-unready
       - name: cpu-stress
       - name: dsd-hostname
       - name: agent-configmap
@@ -709,6 +760,7 @@ spec:
         withItems:
         - "{{inputs.parameters.redis-service}}"
         - "{{inputs.parameters.redis-deployment}}"
+        - "{{inputs.parameters.redis-deployment-unready}}"
         - "{{inputs.parameters.cpu-stress}}"
         - "{{inputs.parameters.dsd-hostname}}"
         - "{{inputs.parameters.agent-configmap}}"
@@ -1176,3 +1228,22 @@ spec:
           }
           sleep(2000);
         }
+
+  - name: find-metrics-redis-unready
+    activeDeadlineSeconds: 200
+    script:
+      image: mongo:3.6.3
+      command: [mongo, "fake-datadog.default.svc.cluster.local/datadog"]
+      source: |
+        while (1) {
+          var nb = db.series.find({
+            metric: {$regex: "redis*"},
+            tags: {$all: ["kube_deployment:redis-unready", "kube_container_name:redis-unready"]}
+          }).count();
+
+          print("find: " + nb)
+          if (nb != 0) {
+            break;
+          }
+          sleep(2000);
+        }
```

**Comment by hkaj** [comment]
Thanks again for the PR @psycotica0-shopify !

**Pull request merged**
