### PR TITLE
Support dark mode for status bar menu on macOS

### PR DESCRIPTION
**Pull request by adhumi**
### What does this PR do?

This PR fix the color of the bone icon of the status bar menu on macOS.

Before:
Capture d’écran 2019-09-05 à 22 10 24

After:
Capture d’écran 2019-09-05 à 22 10 58

### Motivation

Will help users see the icon, as it was barely invisible in dark mode before

### CODE REVIEW

**Comment by KSerrania** [comment]
Hi @adhumi,

Thanks for the PR! Could you add a release note for this fix? [Here](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/contributing.md#reno) are the docs on how to install and use the release note tool `reno`.

**Comment by adhumi** [comment]
@KSerrania Thanks for the review! Just added the release notes.

**Review by KSerrania — APPROVED** [review]

**Review by remeh — APPROVED** [review]
Thanks for your contribution!

**Comment by adhumi** [comment]
Thanks!

**Pull request merged**
