### PR TITLE
[otel-agent] config: adding missing testdata

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

Follow up to #28743 where we forgot to add the test YAML (and the tests still passed somehow).

### Motivation

Missing testdata was not commited in prior PR #28743 

### Describe how to test/QA your changes

Not necessary. Unit test should take care of it.

### CODE REVIEW

**Review by mackjmr — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Comment by mackjmr** [comment]
@truthbk I just ran the test locally without the "fix" in this PR, and it passes. Perhaps we need to figure out why it's not currently failing before merging this ?

**Comment by mackjmr** [comment]
Ah, it's passing because there is an error `open testdata/datadog_bad_log_level.yaml: no such file or directory` but it's not the error we would expect for the test. Can we be more specific in asserting the error ?

**Review by jackgopack4 — APPROVED** [review]

**Review by mackjmr — APPROVED** [review]
LGTM 👍

**Pull request merged**
