### PR TITLE
[otlp] Bump go.opentelemetry.io/collector to v0.64.1

### PR DESCRIPTION
**Pull request by songy23**
### What does this PR do?

Bumps the go.opentelemetry.io/collector dependencies to v0.64.1.

### Motivation

Keep OTel deps up-to-date.

### Describe how to test/QA your changes

Check that the OTel ingest in the Agent works.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [x] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by urseberry — APPROVED** [review]

**Review by knusbaum — APPROVED** [review]

**Review by mx-psi — COMMENTED** [review]
The current code LGTM, but we should also address a couple of changes upstream from this release. 
 
First, there are a couple of places where we are using parts of the API that were deprecated on v0.64.0:  the `config.Exporter` symbol was deprecated in favor of `component.ExporterConfig` and is used here: https://github.com/DataDog/datadog-agent/blob/3056b44bfa024558fa4df12540afbc7e2c3eb785/pkg/otlp/internal/serializerexporter/exporter.go#L25-L27 and also here: https://github.com/DataDog/datadog-agent/blob/3056b44bfa024558fa4df12540afbc7e2c3eb785/pkg/otlp/internal/serializerexporter/factory.go#L40. Could you rename those to `component.ExporterConfig` and fix the imports?

Lastly, the v0.64.0 release split some packages into their own modules. While Go makes this magically work, I think we should use the paths explicitly on our `go.mod`, so that in the future we can use Dependabot for these. The new modules on this release that we use are: the batch processor and the OTLP receiver. To require the Go modules explicitly we should modify the main `go.mod` to add a `require` for `go.opentelemetry.io/collector/processor/batchprocessor v0.64.1` and `go.opentelemetry.io/collector/receiver/otlpreceiver v0.64.1`. You should do an `invoke -e tidy-all` after adding those.

**Comment by songy23** [comment]
Thank you @mx-psi , I have replaced the deprecated `config.Exporter` interfaces with `component.ExporterConfig`, and updated the main `go.mod` with new modules.

**Review by mx-psi — APPROVED** [review]
:rocket:

**Comment by mx-psi** [comment]
LGTM, you will need to fix some merge conflicts before merging though :)

**Comment by songy23** [comment]
Thank you for the review!

**Pull request merged**
