### PR TITLE
[pkg/otlp] Remove usage of deprecated function WithPreviewHostnameFromAttributes.

### PR DESCRIPTION
**Pull request by mackjmr**
### What does this PR do?

This PR is a follow up to the following [PR](https://github.com/DataDog/opentelemetry-mapping-go/pull/48). It removes usage of deprecated function `WithPreviewHostnameFromAttributes`.

### Motivation

https://datadoghq.atlassian.net/browse/OTEL-231

### Additional Notes
In order to take advantage of this [PR](https://github.com/DataDog/opentelemetry-mapping-go/pull/48), it updates `github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics` to v0.1.5. This also brings in the following [change](https://github.com/DataDog/opentelemetry-mapping-go/pull/26) which has been added to the release notes.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Can you also bump https://github.com/DataDog/datadog-agent/blob/7c2957480fb02eaa02af25fdb20714a857ff8738/pkg/trace/go.mod#L20 ?

**Review by mx-psi — APPROVED** [review]

**Review by ahmed-mez — APPROVED** [review]

**Review by rtrieu — APPROVED** [review]
Looks good!

**Comment by mx-psi** [comment]
I caused a merge conflict here after merging #16546, sorry! Should be easy to fix

**Comment by mackjmr** [comment]
Accepted the incoming changes @mx-psi 👍

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
> The `kernel_matrix_testing_upload_deps` test shows up as pending -- even though when I check in gitlab it shows up as skipped: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/254043846.
> 
> @mx-psi am I good to ignore the check showing up as pending and merge this in ?

The check is not required so I think that should be fine. If I recall correctly, I don't think Github CI check API allows you to mark something as skipped if not coming from a Github app

**Pull request merged**
