### PR TITLE
remove ebpf clang pre-commit

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

remove ebpf clang pre-commit

### Motivation

No eBPF developers are checking this, largely because we don't have a style that we all agree on. `clang-format` and `clang-tidy` are also not as flexible as we would like.

### Additional Notes

- removed `clang-format` and `clang-tidy` tasks in system-probe tasks

### CODE REVIEW

**Review by KevinFairise2 — APPROVED** [review]
LGTM. 
I just see that we also have a pre-commit `check-winclang-format` do you know if this requires the `.clang-format` files you just deleted?

**Review by gjulianm — APPROVED** [review]

**Review by CelianR — APPROVED** [review]

**Comment by brycekahle** [comment]
> I just see that we also have a pre-commit `check-winclang-format` do you know if this requires the `.clang-format` files you just deleted?

@KevinFairise2 I checked with WKIT and they don't use this check. I'm checking with the other windows agent teams.

**Comment by brycekahle** [comment]
@KevinFairise2 @julien-lebot is using the `.clang-format` file, so I re-added it.

**Pull request merged**
