### PR TITLE
Upgrade windows config from agent5 on service start

### PR DESCRIPTION
**Pull request by derekwbrown**
Upon service start, check to see if there's a valid agent5 config AND an invalid agent6 config.  If so, automatically run the upgrade code.

Refactored the upgrade code to `common` so it could be shared between the command line upgrader and here.

### CODE REVIEW

**Review by gmmeyer — DISMISSED** [review]
I read through this and it all seems pretty reasonable to me. I'll approve

**Review by masci — CHANGES_REQUESTED** [review]
why the huge code duplication in cmd/agent/common/import.go?

**Comment by derekwbrown** [comment]
@masci code duplication was from a bad merge.  Should be fixed.  All implementation of import should be in `cmd/agent/common`, not `cmd/agent/app`

**Review by masci — APPROVED** [review]
👍

**Pull request merged**
