### PR TITLE
Remove dependency on github.com/iovisor/gobpf for single function

### PR DESCRIPTION
**Pull request by brycekahle**
### What does this PR do?

Remove dependency on github.com/iovisor/gobpf

### Motivation

We were only using a single function `cpupossible.Get()` that didn't even return the data in the form we wanted.

### Additional Notes

Reused code from `cilium/ebpf` with appropriate license included.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by guyarb — APPROVED** [review]
good for USM

**Review by clamoriniere — COMMENTED** [review]
The change looks good, but since this PR contains some code changes, I think it make sens to not have the "skip/qa" label. 
and provide a description about how to test it. Even if it is: test that the tcpqueue length check is still working.

**Comment by brycekahle** [comment]
@clamoriniere There are automated tests for the TCPQ check. Is that sufficient?

**Comment by clamoriniere** [comment]
> @clamoriniere There are automated tests for the TCPQ check. Is that sufficient?

I didn't know about the automated tests. In that case all good.

**Review by clamoriniere — APPROVED** [review]

**Review by lebauce — APPROVED** [review]

**Review by val06 — APPROVED** [review]

**Review by pgimalac — APPROVED** [review]
LGTM.
Adding some unit tests for `parseCPUs` might be useful, but the format is so simple I'd understand if you think it's not necessary.

**Pull request merged**
