### PR TITLE
[docs] Clarify A6 service commands depending on Linux distribution

### PR DESCRIPTION
**Pull request by olivielpeau**
### What does this PR do?

Clarifies which exact service command to use depending on the default init system, and in particular depending on the Linux distribution.

### Motivation

Help users understand which service command they should use, depending on their Linux distro.

[skip ci]

### CODE REVIEW

**Review by l0k0ms — DISMISSED** [review]
Duly noted, doc will be updated soon.

**Comment by olivielpeau** [comment]
Just realized I missed Amazon Linux, adding it...

**Review by masci — COMMENTED** [review]
📄 LGTM

**Review by masci — APPROVED** [review]
2nd take

**Pull request merged**
