### PR TITLE
agent: compress OCI layer with gzip

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

Switch OCI layer compression from the default (XZ) to GZip

### Motivation

There are 3 reasons for this change:
* for main
    *  we just want to enable a change in omnibus-ruby and avoid compressing an already compressed file, in order to save a bit of resources
    * the compression algorithm can now be chosen between `zstd`, `xz` and `gzip`. As per the remote updater team request, we now use gzip
- for 7.52.x, omnibus-ruby was bumped by mistake as part of the release process, which causes omnibus to produce an artifact with an unexpected name for the agent CI, and the builds to fail. This change fixes it

### CODE REVIEW

**Review by richl-dd — APPROVED** [review]

**Review by bkabrda — APPROVED** [review]

**Comment by chouetz** [comment]
> ### What does this PR do?
> Switch OCI layer compression from the default (XZ) to GZip
> 
> ### Motivation
> ### Additional Notes
> ### Possible Drawbacks / Trade-offs
> ### Describe how to test/QA your changes

@chouquette could you please say `why` you are doing this change in the PR description please?
Thanks in advance

**Pull request merged**
