### PR TITLE
[circleci] split reno and team assignment linters

### PR DESCRIPTION
**Pull request by arbll**
### What does this PR do?

Split reno and team assignment linters to avoid confusion.

Also using this opportunity to rename `reno_linting` to `release_note_linting` to make it clearer for external contributors.

### Note

Not sure if I need to edit something on github side - testing it with this PR

### CODE REVIEW

**Comment by remicalixte** [comment]
I think we'll need to change the required checks there: https://github.com/DataDog/datadog-agent/settings/branch_protection_rules/1441780, but apart from that, lgtm.

**Comment by arbll** [comment]
Thanks for the link, I wasn't able to find it. Seems like it picks them up automatically : `Status checks found in the last week for this repository`. Merging this and disabling `reno_linting` requirement should be enough then

**Comment by remicalixte** [comment]
And enabling both new checks as required too

**Review by truthbk — APPROVED** [review]
Go for it 👍

**Pull request merged**
