### PR TITLE
[ASCII-2259] Add mandatory Params to orchestrator

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?
This PR adds a mandatory parameter to the orchestrator `Module()` in order to replace
```go		
orchestratorForwarderImpl.Module(),
fx.Supply(orchestratorForwarderImpl.NewDefaultParams()),
```
by
```go
orchestratorForwarderImpl.Module(orchestratorForwarderImpl.NewDefaultParams()),
```

### Motivation
By adding the parameter to the `Module` function, a user of orchestrator doesn't have to guess that `orchestrator.Params` is mandatory

### Describe how to test/QA your changes
QA done by running unit tests and E2E tests.

### CODE REVIEW

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by hush-hush — APPROVED** [review]

**Review by vickenty — APPROVED** [review]

**Review by TCheruy — APPROVED** [review]

**Review by remeh — APPROVED** [review]

**Review by NouemanKHAL — APPROVED** [review]

**Comment by ogaca-dd** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Comment by ogaca-dd** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Pull request merged**
