### PR TITLE
[CSPM] upgrade rego dependency

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

This PR upgrades the dependency `github.com/open-policy-agent/opa` from `v0.31.0` to `v0.33.1`.
This upgrade implies an upgrade of `github.com/dgraph-io/ristretto` from `v0.0.3` to `v0.1.0`.

This upgrade is problematic as the dependency on `github.com/golang/glog v1.0.0` is added, which is crashing on Windows nanoserver container images because of a missing DLL (`netapi32.dll`).

See the following PR/issues as other examples of the underlying problem :
- https://github.com/docker-library/golang/issues/348
- https://github.com/microsoft/Windows-Containers/issues/72

The solution implemented in this PR is to fork `github.com/golang/glog` and recover on a potential panic of the `user.Current()` function call. We then use a `replace` in the `go.mod` to replace use of the original repo with the fork.

Using this fork should not pose major problems as the original repo is not actively developed (it's mainly a mirror of an internal project inside Google that is sync infrequently).

Here is the branch with the fix: https://github.com/paulcacheux/glog/tree/recover-panic-current-user

If this potential solution is agreed upon, we can move this fork under the Datadog Github Org.

### Motivation

Keep dependencies up to date.

### Describe how to test your changes

This update _should_ be a no-op. The main thing to test is that a windows container based on a nanoserver image can actually start.

### Checklist

- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] The `need-change/operator` and `need-change/helm` labels has been applied if applicable.
- [x] The appropriate `team/..` label has been applied, if known.
- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] The [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated if applicable.

Note: Adding GitHub labels is only possible for contributors with write access.

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Thanks for doing this! I have a small question to understand this better: do you understand what are the implications of returning an empty user? To put it another way, where is the username value used in glog?

**Review by mx-psi — APPROVED** [review]
Makes sense, looks good to me then :)

**Comment by paulcacheux** [comment]
Do you want me to move the fork under Datadog org then ? Or should I just let the fork where it is currently ?

**Comment by mx-psi** [comment]
> Do you want me to move the fork under Datadog org then ? Or should I just let the fork where it is currently ?

No strong opinion on it, I will let the Agent security team decide that

**Review by safchain — APPROVED** [review]

**Pull request merged**
