### PR TITLE
Avoid unnecessary allocations in `BuildAgentKey`

### PR DESCRIPTION
**Pull request by blt**
### What does this PR do?

In the regression detector experiment `tcp_syslog_to_blackhole` we see that `BuildAgentKey` accounts for ~20% of Agent allocations, see [this notebook](https://app.datadoghq.com/notebook/6376068/agent-performance-investigation-gethostname?view=view-mode) for reference to the profiles. Most of _those_ allocations are in `path.Join` and as the Agent never has a '..' et al present in its keys and the prefix is guaranteed non-empty we can simplify to just the use of a `strings.Builder`.

### Motivation

Reduce allocation load in the Agent. 

### Possible Drawbacks / Trade-offs

We don't document that `BuildAgentKey` has the same semantics in joining as `path.Join` but this is a change to how this function operates in practice, not just a simple internals swap. Examining the project I don't believe any of the more elaborate nature of `path.Join` is relied on, but I suppose tests will tell. 

### Describe how to test/QA your changes

I expect most of the result to come in the regression detector results and in profiles. I'll link here when those are ready.

### Related Issues 

REF SMP-673

### CODE REVIEW

**Comment by GeorgeHahn** [comment]
I added the new profile to [Agent Performance Investigation: GetHostName](https://app.datadoghq.com/notebook/6376068/agent-performance-investigation-gethostname). There's a significant reduction in the number of allocations, but the string sizes here are small enough that the performance impact is small.

**Comment by blt** [comment]
@GeorgeHahn indeed. I'm content with a performance neutral change but less allocator traffic. I do want to look at the capture data but I suspect a neutral result. If so, I'll move this forward to review, see what the shared components folks think.

**Comment by blt** [comment]
Neat, according to [the profiler](https://app.datadoghq.com/profiling/comparison?query=account%3Asingle-machine-performance%20client_team%3Aagent%20runtime%3Ago%20experiment%3Atcp_syslog_to_blackhole%20version%3A%28_7_48_0_rc.2_git.78.fdafe66_fdafe66_%20OR%20_7_48_0_rc.2_git.80.1f1f31e_1f1f31e_%29%20&compare_end_A=1693501012452&compare_end_B=1693501008491&compare_query_A=account%3Asingle-machine-performance%20client_team%3Aagent%20runtime%3Ago%20experiment%3Atcp_syslog_to_blackhole%20version%3A_7_48_0_rc.2_git.78.fdafe66_fdafe66_&compare_query_B=account%3Asingle-machine-performance%20client_team%3Aagent%20runtime%3Ago%20experiment%3Atcp_syslog_to_blackhole%20version%3A_7_48_0_rc.2_git.80.1f1f31e_1f1f31e_&compare_start_A=1693430766298&compare_start_B=1693430572361&compareValuesMode=absolute&my_code=disabled&viz=flame_graph&start=1693328133662&end=1693500933662&paused=false) we have:

* roughly the same CPU time in our experiment duration
* baseline allocates 30Gb memory total, comparison 29Gb 
* CPU time in the hotspot that leads to `path.Join` drops by 2s 
* the allocation centers are now in the prefixer and delimiter, see [this profile](https://app.datadoghq.com/profiling/search?query=account%3Asingle-machine-performance%20client_team%3Aagent%20runtime%3Ago%20experiment%3Atcp_syslog_to_blackhole%20version%3A_7_48_0_rc.2_git.80.1f1f31e_1f1f31e_%20&compareValuesMode=absolute&my_code=disabled&profile_type=alloc-size&viz=flame_graph&start=1693328133662&end=1693500933662&paused=false)

Capture data also looks neutral on throughput, CPU: [here](https://app.datadoghq.com/dashboard/t3q-y5d-i7u/smp-regression-detector-capture-data?tpl_var_experiment%5B0%5D=tcp_syslog_to_blackhole&tpl_var_run-id%5B0%5D=096d13f2-70fa-4b49-a003-a699a0ccfe52&from_ts=1693439842417&to_ts=1693440318905&live=false)

Neutral change on throughput,

**Review by hush-hush — APPROVED** [review]

**Review by pgimalac — COMMENTED** [review]
You might want to add a comment to explicitly say that we want to minimize allocations in this function

**Pull request merged**
