### PR TITLE
Handle configuration secrets in system-probe

### PR DESCRIPTION
**Pull request by mftoure**
### What does this PR do?
This PR aims to make system-probe handle configuration secrets. It makes system-probe use the core-agent api so that we can get the secrets decrypted by the core-agent

### Motivation
In an effort, to use CWS with system-probe only, we are migrating some of the security-agent functionalities to system-probe

### Describe how to test/QA your changes 
- Define api_key in datadog.yaml as a secret: [Instructions](https://docs.datadoghq.com/agent/configuration/secrets-management/?tab=linux)
- Enabled the sync server in the core-agent by setting:
```
agent_ipc:
  port: XXXX
  config_refresh_interval: 30
```
- Print out the api_key somewhere in system-probe and check if we get the actual decrypted key
```
coreconfig.Datadog().GetString("api_key")
```

### CODE REVIEW

**Comment by brycekahle** [comment]
Won't this allow a non-privileged user to provide a program that would be executed by root? That seems like a privilege escalation?

**Comment by brycekahle** [comment]
This was previously intentionally disabled in #18222 so what has changed?

**Comment by hush-hush** [comment]
Same question than @brycekahle: Not enabling secrets on system-probe was required by the security-team.

It also raise more issue as we require the the binary being executed to be own by the same user than the agent process. On a host install we can't have the same binary own by `dd-agent` for the core-agent and `root` for system-probe.

We have a feature, disable right now, that allow different Datadog processes to fetch the API key from the core-agent which already uses secrets. We could work on enabling it by default and updating our HELM chart. This would give system-probe access to the API key through secrets without directly executing anything.

**Comment by mftoure** [comment]
Yep, that makes sense, thanks for raising this issue. I'll explore another approach using the [feature](https://github.com/DataDog/datadog-agent/pull/23211) that syncs the secrets resolved by the core-agent with other agents.

**Comment by brycekahle** [comment]
Can you explain why the system-probe needs the API key (or other secrets)?

**Comment by mftoure** [comment]
In an effort, to use CWS with system-probe only, we are migrating some of the security-agent functionalities to system-probe.

**Review by brycekahle — CHANGES_REQUESTED** [review]
Please do not merge until a policy decision can be made regarding system-probe having the API key and talking to the backend directly. This is a significant shift in the security posture.

**Pull request closed without merging**
