### PR TITLE
[compliance-agent] generate multiple reports per run and add framework id

### PR DESCRIPTION
**Pull request by safchain**
### What does this PR do?

This PR changes the way check reports are generated. Previously on check fail only one report was generated using the first fail. With this patch, multiple reports are generated within a limit defined in the configuration file. The behavior is now the following: 

Succeed : the last success check is used to generate the report
Failed: multiple reports generated within the limit.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Describe how to test your changes

Unit test have been added. We should see possibly  multiple reports generated for one check fails.

### CODE REVIEW

**Review by vboulineau — COMMENTED** [review]
PR is LGTM, however it does not implement multiple reports for iterable objects handled here: https://github.com/DataDog/datadog-agent/blob/6af9b254b2b6a1ecd59990796c93e70cb79c3728/pkg/compliance/eval/eval.go#L147

It can be verified with this check for instance:
https://github.com/DataDog/security-agent-policies/blob/master/compliance/containers/cis-kubernetes-1.5.1.yaml#L809-L828

**Comment by safchain** [comment]
@vboulineau, thanks for the review. Not sure to understand the comment for the `iterate` thing, here the modification I made https://github.com/DataDog/datadog-agent/pull/8123/files#diff-763fabe40d7473354fdf47615205cf68d5cef9cbdbfd6bfbef4b60d0798a62c0R155

is it not correct ?

**Review by cswatt — COMMENTED** [review]
no docs review required :)

**Comment by vboulineau** [comment]
> @vboulineau, thanks for the review. Not sure to understand the comment for the `iterate` thing, here the modification I made https://github.com/DataDog/datadog-agent/pull/8123/files#diff-763fabe40d7473354fdf47615205cf68d5cef9cbdbfd6bfbef4b60d0798a62c0R155
> 
> is it not correct ?

So I checked with your latest changes, it looks okay BUT it does not fully work due to the way the evaluation works.
Consider this condition (from K8S 5.7.4): `condition: count(_) == 0`

In this case the `_` evaluation of each object (POD in this case) is always true, thus in `iterate()` we'll return first instance only. However, later on, the `count()` fails and we only report the first failed POD instead of all of them.

So it's more linked to the expression/function evaluation, but it requires extra change to report correctly all failed objects in these situations.

**Comment by safchain** [comment]
@vboulineau thanks for your advices. I fixed the issue you pointed and added a unit test for that.

**Review by vboulineau — APPROVED** [review]

**Review by lebauce — APPROVED** [review]

**Pull request merged**
