### PR TITLE
fix(ci): RUN_E2E_TESTS is not false, but on, auto or true

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
Rule on RUN_E2E_TESTS is checking a `true` status whereas it should be only `on`, `auto` or `off`

### Motivation
Fix rules condition that prevent gitlab to [generate pipelines correctly](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/29368527) with this setup:
```
Creating child pipeline with params: {'RELEASE_VERSION_6': 'nightly', 'RELEASE_VERSION_7': 'nightly-a7', 'BUCKET_BRANCH': 'dev', 'DEPLOY_AGENT': 'false', 'INTEGRATIONS_CORE_VERSION': 'bot/update-dependencies-1709518593', 'RUN_KITCHEN_TESTS': 'false', 'RUN_E2E_TESTS': 'off'} off branch: main
```

### CODE REVIEW

**Review by amenasria — APPROVED** [review]
LGTM !

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable DEPLOY_AGENT=true --variable RUN_UNIT_TESTS=on

**Pull request merged**
