### PR TITLE
Fix inconsistent indentation on oracle-dbm yaml template

### PR DESCRIPTION
**Pull request by gabriel-ndc**
### What does this PR do?

Fix inconsistent indentation so that it's easier to apply the oracle-dbm configuration without mistakes.

### Motivation

When adding tags, I've noticed that it required one indentation less. Seeing the rest of the
file, I've noticed more inconsistencies. This aims to keep every indentation with 2 spaces.

### Additional Notes

As it's only a change in a template, I had added the option to skip the CI. But had to turn it back because it got stuck.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by nenadnoveljic — APPROVED** [review]

**Comment by gabriel-ndc** [comment]
Hello, @nenadnoveljic!

Would you be able to merge? I don't have the permission. Or are more approvals needed?

Thanks!

**Comment by nenadnoveljic** [comment]
> Would you be able to merge? I don't have the permission. Or are more approvals needed?

The CI checks are stuck. Merge isn't possible, unless they complete. Also tags are missing, which will cause the checks to fail.

**Comment by gabriel-ndc** [comment]
I see. I added [skip-ci] because it's only a template change, not sure why CI is stuck. Is there anything I can do to help?

**Comment by nenadnoveljic** [comment]
> I see. I added [skip-ci] because it's only a template change, not sure why CI is stuck. Is there anything I can do to help?

Can you remove [skip-ci]?

**Comment by nenadnoveljic** [comment]
> I removed the skip ci tag and all the circleci checks passed, but the gitlab ones are still to be expected. Can't be sure if they are running, though. Anything else I can do?

I don't know how to unblock the pending tests. Could you try to push the empty commit which should trigger all the tests again?

**Comment by gabriel-ndc** [comment]
Still nothing. I saw that there were a few commits on .gitlab/, I'll try rebasing on main

**Pull request closed without merging**
