### PR TITLE
[Serverless] Remove serverless dependency on agent-payload/v5/process.

### PR DESCRIPTION
**Pull request by purple4reina**
### What does this PR do?

Use build tag to initialize some of the expvars in `pkg/forwarder`.

### Motivation
This change removes several dependences from the serverless extension, most importantly `github.com/DataDog/agent-payload/v5/process`. This reduces the binary size from 42.5MB to 40.6MB, saving roughly 1.96MB equivalent to about 19.6ms of cold start time.

Dependency graph:

Screen Shot 2023-02-28 at 10 43 21 AM

### CODE REVIEW

**Comment by purple4reina** [comment]
@vickenty, to address your comment in my previous closed pull request (https://github.com/DataDog/datadog-agent/pull/15803#discussion_r1119858310), adding the `github.com/DataDog/agent-payload/v5/process` dependency increases our binary size by about 2MB to 42.5MB. I can only assume it increases the sizes of other agent flavors as well.

One solution as you mentioned in your comment is to revert https://github.com/DataDog/datadog-agent/pull/15136. We could also put just the `model.K8SResource` type behind a build tag and use an interface instead. I'll see what that change would look like and share it with you when I'm done.

**Comment by purple4reina** [comment]
@vickenty, I've updated the pull request to just special case the `K8SResource` type. Please let me know your thoughts.

**Comment by vickenty** [comment]
@purple4reina Thank you for giving it a go, but this looks we're adding complexity to solve a problem that shouldn't (and didn't!) exist in the first place. So I opened https://github.com/DataDog/datadog-agent/pull/15883 to revert that PR.

**Comment by purple4reina** [comment]
> @purple4reina Thank you for giving it a go, but this looks we're adding complexity to solve a problem that shouldn't (and didn't!) exist in the first place. So I opened #15883 to revert that PR.

Fantastic. I completely agree. I will close this PR and require https://github.com/DataDog/datadog-agent/pull/15883 to be merged before our next release of the lambda extension.

**Pull request closed without merging**
