### PR TITLE
[CI] Avoids concurrent writes to staging repos

### PR DESCRIPTION
**Pull request by mx-psi**
### What does this PR do?

Sets [resource groups](https://docs.gitlab.com/ee/ci/yaml/#resource_group) to prevent two jobs from modifying the same staging repo at the same time.

### Additional Notes

Unsure if `.kitchen_cleanup_s3_common` needs to be handled too (it would potentially need several resource groups).

### CODE REVIEW

**Review by albertvaka — COMMENTED** [review]
There are two kinds of deploy jobs in the pipeline:
- `deploy_deb_testing-a6` (and similarly-named for rpm and a7) create a repo per-pipeline, so concurrent writes shouldn't ever happen there (or are very unlikely). These repos are not the staging repos, though, they are short lived repos that are only used for kitchen tests in the same pipeline.
- `deploy_deb-6` (and the like) deploy to staging, and these are the ones more likely to have race conditions if there are two pipelines running at the same time.

This PR should target the second group of jobs.

Edit: naming is not great. We should rename the second group of jobs to `deploy_staging_*`.

**Comment by mx-psi** [comment]
> Edit: naming is not great. We should rename the second group of jobs to deploy_staging_*.

Should I rename them in this PR?

**Comment by kbogtob** [comment]
I think we could do it in the same PR :).

**Review by albertvaka — COMMENTED** [review]
For the repos where we only add files (ie: we do `S3_CP_CMD` and that's it: dogstatsd, process...) we don't need this mutex mechanism because adding files will always be safe.

In contrast with that, the DEB bucket has a single index/metadata file that lists all the files, which could be susceptible to racey edits. (Eg:
pipelineA pulls the file, pipelineB pulls the file, pipelineA pushes the file, pipelineB pushes the file).

I'm not sure about RPM repos, but since we use a tool to push to the repo and not a simple s3 push, I would also use the mutex there.

On Windows we do have a json file that lists all releases, but I think we only have this file for prod and not staging. We can also keep the mutex for the staging bucket to keep it in line with the prod bucket, though, but it would be correct without it also.

**Comment by mx-psi** [comment]
Thank you for the comments, hopefully it makes sense now. I kept the mutex on the DEB and RPM buckets and removed it from everything else (that is Windows, processes and dogstatsd). As far as I can see, the Windows staging deployment does not have the json file so they should be safe.

**Review by albertvaka — APPROVED** [review]

**Review by kbogtob — APPROVED** [review]

**Pull request merged**
