### PR TITLE
Match the sources directory for eBPF object files inside build container and on host

### PR DESCRIPTION
**Pull request by usamasaqib**
### What does this PR do?
KMT builds eBPF object files inside a container by bind mounting the host working directory into the container. This causes the DWARF debug info to record the sources path to the mount point inside the container. As a result, `llvm-objdump` when invoked on the eBPF object files inside `./pkg/ebpf/bytecode/build` will be unable to perform source code annotation.
This PR change the mountpoint inside the container to a location where a matching symlink to the working directory is also present on host. This resolves this issue.

### CODE REVIEW

**Review by gjulianm — APPROVED** [review]
LGTM. This is for running `llvm-objdump` from the host machine, right?

**Comment by usamasaqib** [comment]
> LGTM. This is for running `llvm-objdump` from the host machine, right?

Yes correct. On microvms it won't have source code annotations anyway since the source files are not present at all.

**Pull request merged**
