### PR TITLE
Rename helper_test to test_helper to please gopls

### PR DESCRIPTION
**Pull request by pgimalac**
### What does this PR do?

Rename `test/new-e2e/tests/npm/helper_test.go` to `test_helpers.go`.

### Motivation

`gopls` (the Go language server) considers that Go files ending with `_test.go` are test files, and you can't import from a test file, so it is complaining about it in my IDE.
Not sure why `go` doesn't seem bothered by that, but in any case the easiest fix is to rename the file. 

### Additional Notes

I can definitely close if you don't want that change, the goal is purely to stop having errors in my IDE.

### Describe how to test/QA your changes

There is no change done to the code in any way.
The file is renamed but stays in the same package so no import path to change either.

### CODE REVIEW

**Comment by hmahmood** [comment]
What is the error you're seeing in your IDE?

**Comment by pgimalac** [comment]
@hmahmood here are the errors:
image
Basically it can't find the two symbols because they are declared in `helper_test.go` (which is considered a test file, although it doesn't really contain any test) but used in `common_1host.go`

**Review by hmahmood — APPROVED** [review]

**Review by KevinFairise2 — APPROVED** [review]

**Comment by pgimalac** [comment]
Had to override the 3rd party copyright to please CircleCI (which couldn't find it in the CI weirdly, likely a cache issue), cc @KevinFairise2

**Pull request merged**
