### PR TITLE
Secrets Management feature is now GA

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

Remove the `Beta` tag for the Secrets Management feature as it's now GA.

### CODE REVIEW

**Review by ruthnaebeck — DISMISSED** [review]
👍 for docs

**Review by derekwbrown — DISMISSED** [review]

**Comment by olivielpeau** [comment]
do we need to update https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/secrets-helper/README.md as well?

**Comment by hush-hush** [comment]
> do we need to update https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/secrets-helper/README.md as well?

Yes, good catch !

**Review by xlucas — DISMISSED** [review]

**Review by mtremsal — DISMISSED** [review]
LGTM

**Review by albertvaka — DISMISSED** [review]

**Pull request merged**
