### PR TITLE
(fleet) fix remote updates permissions

### PR DESCRIPTION
**Pull request by arbll**
Couple fixes to allow the deamon to write runtime files.

### CODE REVIEW

**Review by raphaelgavache — APPROVED** [review]

**Review by BaptisteFoy — APPROVED** [review]
LGTM. Maybe a line on the E2E test?

**Comment by raphaelgavache** [comment]
yes, add your dir here to test ownership https://github.com/DataDog/datadog-agent/blob/main/test/new-e2e/tests/installer/linux_test.go#L124-L125

**Pull request merged**
