### PR TITLE
Implement GetHosts, GetPorts, add tests and revamp

### PR DESCRIPTION
**Pull request by hkaj**
This reverts commit f1c6daecea6e5b2393c5f6bfbb2672683bf62b28.

### What does this PR do?

revert the revert

### Motivation

Same as #675 

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by hkaj** [comment]
@mfpierre 👍 ?

**Review by mfpierre — CHANGES_REQUESTED** [review]
Unit tests are failing

**Comment by hkaj** [comment]
yeah, ping too soon sorry. I'm on it

**Review by mfpierre — APPROVED** [review]
Looking good :shipit:

**Pull request merged**
