### PR TITLE
omnibus: stop building pkg-config

### PR DESCRIPTION
**Pull request by chouquette**
### What does this PR do?

This PR removes pkg-config from our dependencies as it's already available in the build image

### Motivation

Removing unneeded package

### Additional Notes

This also removes pkg-config from the shipped software sources, which might need a legal approval

Associated omnibus-software PR: https://github.com/DataDog/omnibus-software/pull/485

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Review by amenasria — APPROVED** [review]
**👏 praise:** LGTM ! Nice one !‏


**💬 suggestion:** Two things to test before merging IMO:
- Since it changes the omnibus build I think we should run a full pipeline for this one !
- It would be safe to download the post build artifact and install it / check that the Agent runs as well !‏

**Comment by chouquette** [comment]
> * Since it changes the omnibus build I think we should run a full pipeline for this one !
> * It would be safe to download the post build artifact and install it / check that the Agent runs as well !‏

That seems like a good idea :)
Full pipeline: https://gitlab.ddbuild.io/DataDog/datadog-agent/pipelines/22270764

Regarding downloading & running the binary, isn't that handled by the kitchen tests?

**Comment by amenasria** [comment]
True, I was a bit overzealous on this one, kitchen tests should be enough indeed !

**Review by pgimalac — APPROVED** [review]
Can you merge main so that the gitlab job `do-not-merge` fails, so that you don't risk merging with a different value of `OMNIBUS_SOFTWARE_VERSION` ?

**Review by vickenty — APPROVED** [review]

**Pull request merged**
