### PR TITLE
[ASCII-2071] Workloadmeta module `Params`

### PR DESCRIPTION
**Pull request by ogaca-dd**
### What does this PR do?
This PR adds a mandatory parameter to the workload meta `Module()` in order to replace
```go		
fx.Supply(workloadmeta.NewParams()),
workloadmetafx.Module(),
```
by
```
workloadmetafxmock.MockModule(workloadmeta.NewParams()),
```

### Motivation
By adding the parameter to the `Module` function, a user of workloadmeta doesn't have to guess that `workloadmeta.Params` is mandatory

### Describe how to test/QA your changes
QA done by running unit tests and E2E tests.

### CODE REVIEW

**Review by vickenty — APPROVED** [review]

**Review by L3n41c — APPROVED** [review]
LGTM for files owned by @DataDog/container-integrations.

**Review by NouemanKHAL — APPROVED** [review]

**Review by davidor — APPROVED** [review]
:+1: for container-platform files

**Review by YoannGh — APPROVED** [review]

**Review by liustanley — APPROVED** [review]

**Review by daniel-taf — APPROVED** [review]

**Review by stanistan — APPROVED** [review]
LGTM for @DataDog/apm-onboarding

**Review by knusbaum — APPROVED** [review]

**Review by paulcacheux — APPROVED** [review]

**Review by hush-hush — APPROVED** [review]

**Review by kangyili — APPROVED** [review]

**Review by purple4reina — APPROVED** [review]

**Comment by ogaca-dd** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on --variable RUN_KMT_TESTS=on

**Review by mfpierre — APPROVED** [review]

**Pull request merged**
