### PR TITLE
Revert "[CONTINT-3909] Add tests for dogstatsd origin detection on ECS"

### PR DESCRIPTION
**Pull request by AliDatadog**
#incident-25908

### What does this PR do?
This PR reverts https://github.com/DataDog/datadog-agent/pull/23532 which breaks dogstatsd tests, due to the fact that we can't filter metrics by regexp.

### CODE REVIEW

**Review by clamoriniere — COMMENTED** [review]
could you add the link to the PR that you revert?

**Comment by AliDatadog** [comment]
> could you add the link to the PR that you revert?

Updated the PR description

**Review by L3n41c — APPROVED** [review]

**Pull request merged**
