### PR TITLE
[SVLS] Update list of known env vars for AWS Lambda Extension and AAS Windows Extensions

### PR DESCRIPTION
**Pull request by duncanpharvey**
### What does this PR do?

Updates the list of known environment variables for Serverless to suppress warnings.

| Environment Variable | AWS Lambda | AAS Windows .NET | AAS Windows Java | AAS Windows Node |
| :------------------: | :--------: | :--------------: | :--------------: | :--------------: |
| DD_AAS_DOTNET_EXTENSION_VERSION | | &#9989; | | |
| DD_AAS_EXTENSION_VERSION | | | | &#9989; |
| DD_AAS_JAVA_EXTENSION_VERSION | | | &#9989; | |
| DD_AGENT_PIPE_NAME | | &#9989; | &#9989; | &#9989; |
| DD_APPSEC_ENABLED | | &#9989; | &#9989; | &#9989; |
| DD_AZURE_APP_SERVICES | | &#9989; | &#9989; | &#9989; |
| DD_DOGSTATSD_ARGS | | &#9989; | &#9989; | &#9989; |
| DD_DOGSTATSD_PATH | | &#9989; | &#9989; | &#9989; |
| DD_DOGSTATSD_WINDOWS_PIPE_NAME | | &#9989; | &#9989; | &#9989; |
| DD_EXTENSION_PATH | | | | &#9989; |
| DD_INTEGRATIONS | | &#9989; | | |
| DD_INTERNAL_NATIVE_LOADER_PATH | | &#9989; | | |
| DD_INTERNAL_PROFILING_NATIVE_ENGINE_PATH | | &#9989; | | |
| DD_PROFILER_EXCLUDE_PROCESSES | | &#9989; | | |
| DD_PROFILING_LOG_DIR | | &#9989; | | |
| DD_RUNTIME_METRICS_ENABLED | | &#9989; | &#9989; | &#9989; |
| DD_SERVERLESS_FLUSH_STRATEGY | &#9989; | | | |
| DD_TRACE_AGENT_ARGS | | &#9989; | &#9989; | &#9989; |
| DD_TRACE_AGENT_PATH | | &#9989; | &#9989; | &#9989; |
| DD_TRACE_AGENT_URL | | | | &#9989; |
| DD_TRACE_LOG_DIRECTORY | | &#9989; | | |
| DD_TRACE_LOG_PATH | | | &#9989; | |
| DD_TRACE_METRICS_ENABLED | | &#9989; | | |
| DD_TRACE_PIPE_NAME | | &#9989; | &#9989; | &#9989; |
| DD_TRACE_TRANSPORT | | &#9989; | &#9989; | |

### Motivation

* Customer reported issue with AWS Lambda Extension: https://github.com/DataDog/datadog-lambda-extension/issues/196
* Upcoming GA for AAS Node Windows Extension: https://github.com/DataDog/datadog-aas-extension/pull/229

### Additional Notes

Example warnings in AAS:

```
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_AAS_EXTENSION_VERSION
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_AGENT_PIPE_NAME
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_AZURE_APP_SERVICES
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_DOGSTATSD_ARGS
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_DOGSTATSD_PATH
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_DOGSTATSD_WINDOWS_PIPE_NAME
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_EXTENSION_PATH
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_TRACE_AGENT_ARGS
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_TRACE_AGENT_PATH
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_TRACE_AGENT_URL
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_TRACE_PIPE_NAME
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_APPSEC_ENABLED
2024-03-06 21:18:05 UTC | DSD | WARN | (pkg/util/log/log.go:666 in func1) | Unknown environment variable: DD_RUNTIME_METRICS_ENABLED
```

### Describe how to test/QA your changes

**AWS Lambda**
* Run the Lambda Extension locally using files provided here: https://github.com/DataDog/datadog-lambda-extension/tree/main/local_tests
  * Create a `datadog.yaml` file and add it to `Dockerfile-Python` -> `COPY func.py datadog.yaml /var/task/`
  * `RUNTIME=python ./local_tests/build-docker-runtime.sh`
  * `./local_tests/invoke.sh`

**AAS Node Windows Extension**
* Create a Node Windows app in Azure App Service and install the Datadog Extension
* Download the Agent artifacts from this GitLab job
  * https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/453266883
* Replace the dogstatsd agent and trace agent executables in the Kudu site

### CODE REVIEW

**Review by purple4reina — CHANGES_REQUESTED** [review]
I’m pretty sure that vars like `DD_SERVICE` are already handled by the config struct, and thus don’t need to be listed. Let's make sure that all of the env vars in the list are _not_ on the config struct. Let me know if you need a hand with that, I've got some ideas.

**Review by pgimalac — APPROVED** [review]
LGTM as long as existing comments are fixed, we might as well minimize the list

**Comment by pgimalac** [comment]
@purple4reina I actually don't think there is a specific "service" config in the agent

**Review by purple4reina — APPROVED** [review]

**Comment by purple4reina** [comment]
> @purple4reina I actually don't think there is a specific "service" config in the agent

@pgimalac Yes, you are correct. I met with @duncanpharvey and we worked through this together. Thanks for confirming that for us.

**Pull request merged**
