### PR TITLE
Revert "Revert "[pkg/collector] Add worker utilization stats to expvars""

### PR DESCRIPTION
**Pull request by olivielpeau**
Reverts DataDog/datadog-agent#9022 to re-introduce https://github.com/DataDog/datadog-agent/pull/8925 for 7.32. See that PR for description, details, and QA plan.

### CODE REVIEW

**Review by olivielpeau — COMMENTED** [review]
@sgnn7 Would it be complex to log the utilization warning only when the average utilization ratio of _all_ workers is above 99%?

I'm concerned that logging a warning per-worker could lead to spammy/misleading warnings in scenarios where one check takes a long time to run on a single worker (for example, >5min) but other workers can run checks fine. WDYT?

**Comment by sgnn7** [comment]
> @sgnn7 Would it be complex to log the utilization warning only when the average utilization ratio of all workers is above 99%? I'm concerned that logging a warning per-worker could lead to spammy/misleading warnings in scenarios where one check takes a long time to run on a single worker (for example, >5min) but other workers can run checks fine. WDYT?

@olivielpeau Since the warning is only shown when a worker is not running a `duration=0` task and is >99% utilized over the collection window, I would think it has a pretty high confidence threshold excluding the startup sequence (first 5min) and the edge case of a 5m+ check run but you are right that when it does reach that threshold that it would probably be spammy. I think your suggestion would be a good follow-up to this PR so I'll open a task for it in the backlog.

The implementation wouldn't be too complex to do this. The aggregation point for the overall util number should probably not be expvars module though so it would require some code movement and the unit testing may be tricky but overall doable.

**Comment by olivielpeau** [comment]
We discussed in a meeting: there are some checks such as the SNMP or kube_state_metrics check that can in some known (and non-problematic) scenarios run for >1min, and logging the warning in this case would be spammy and misleading. So we'll remove the warning altogether for now, and plan follow-up work to implement a warning based on the global worker utilization

**Review by djmitche — APPROVED** [review]
e375d6b27dc70710c8e5b70956afae4d2753d1e1 looks good atop the revert

**Pull request merged**
