### PR TITLE
ebpf: CPU and memory improvements to `HostProc`

### PR DESCRIPTION
**Pull request by paulcacheux**
### What does this PR do?

In some of our (CWS) code, [HostProc can be called in the hot path ](https://app.datadoghq.com/profiling/explorer?query=service%3Asystem-probe%20datacenter%3Aus1.ddbuild.io%20&agg_m=count&agg_m_source=base&agg_t=count&cols=timestamp%2Cservice%2C%40metrics.core_cpu_cores%2C%40metrics.core_alloc_bytes_per_sec%2Cversion%2Chost&event=AgAAAZHHHOvhSXaKiwAAAAAAAAAYAAAAAEFaSEhIT3Z0QUFCbVY4TFFyNEh0cHdBQQAAACQAAAAAMDE5MWM3MjEtNDQwNC00NTA0LWI0ODgtNTM1ZDM1NjY0NDRm&group_by=line&my_code=disabled&profile_type=alloc-size&profileId=AZHHHOvtAABmV8LQr4HtpwAA&refresh_mode=paused&stream_sort=%40metrics.core_alloc_bytes_per_sec%2Cdesc&viz=stream&from_ts=1725621377600&to_ts=1725624977600&live=false), as such this PR tries to improve a bit the performance characteristics of this function. To do that:
- it extracts the core algorithm in a testable function (one that does not call `ProcFsRoot` since it's a cached function with no way to override, clear it)
- adds some benchmarks
- adds some tests

Benchmarks:
```
Before:
BenchmarkHostProc-4   	 9296641	       128.1 ns/op	      24 B/op	       2 allocs/op
After:
BenchmarkHostProc-4   	15349244	        77.94 ns/op	      16 B/op	       1 allocs/op
```

Note: the panic for int overflow are there to match the `strings.Join` behavior

### CODE REVIEW

**Comment by brycekahle** [comment]
This kind of seems like you are trying to optimize `filepath.Join`? I wonder if you would get equivalent improvements, by replacing `kernel.HostProc(a, b)` with `filepath.Join(kernel.ProcFSRoot(), a, b)` so there is only one `filepath.Join` call instead of two.

**Comment by paulcacheux** [comment]
The main issue is that you cannot really do that because of the `combineWith...`. AFAIK as I know it's not possible to do
```
filepath.Join(ProcFSRoot(), combineWith...)
```
but yeah this is exactly what I would like to do if possible

**Comment by brycekahle** [comment]
> The main issue is that you cannot really do that because of the `combineWith...`

Yeah, I was suggesting changing the call sites of `kernel.HostProc` to avoid that issue.

**Comment by paulcacheux** [comment]
I could do this change in specifically the hot code path I'm looking at yes, that would work. Especially as a first step

**Pull request closed without merging**
