### PR TITLE
Update snowflake-connector-python version in omnibus

### PR DESCRIPTION
**Pull request by yzhan289**
### What does this PR do?
This PR increments the current version of the `snowflake-connector-python` dependency in the omnibus to 2.7.3 (which requires pyopenssl < 22.0). 

I will also update the cryptography library in integrations-core after this PR, and then submit another PR to datadog-agent to match the actual version [currently used in the Snowflake check](https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/data/agent_requirements.in#L107).

### Motivation
The Snowflake check no longer uses the 2.6.0 version of the check, and that version restricted `cryptography` library versions to <4.0.0, but `cryptography` changed how it increments release numbers (the current version is 38.0.1). 

This is currently blocking updating the the version of the [`securesystemslib`](https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/data/agent_requirements.in#L99) library from 0.20.1 to 0.24.0, because `securesystemslib` now requires [a minimum `cryptography` version of 37.0.0](https://github.com/secure-systems-lab/securesystemslib/blob/v0.24.0/requirements.txt#L34)

### Additional Notes
~~I wasn't too sure if I needed to also change the `sha256` value on line 7.~~ Nevermind, I needed to change it otherwise it fails the CI.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature. 
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by hithwen** [comment]
is it a no changelog label?

**Review by hithwen — APPROVED** [review]

**Comment by yzhan289** [comment]
> is it a no changelog label?

I didn't think this needed a changelog, since the [previous PR](https://github.com/DataDog/datadog-agent/pull/9089) that updated the version didn't have one. Should we add one to this PR?

**Comment by alopezz** [comment]
It looks like I got this to build successfully, updating `snowflake-connector` all the way up to 2.7.12 (matching [what we have in integrations-core](https://github.com/DataDog/integrations-core/blob/4fb3b5f07c99b044081e16cc5c174016095d25f2/datadog_checks_base/datadog_checks/base/data/agent_requirements.in#L107)).

The trick was to force `pyopenssl==21.0.0`, [which is compatible with lower versions of `cryptography`](https://github.com/pyca/pyopenssl/blob/51717970261d6283b681f5fa8347808409f0991d/setup.py#L99) (like the one currently set in integrations-core). Otherwise, installing `snowflake-connector==2.7.12` would install `pyopenssl==22.0.0` which requires a more recent version of `cryptography`.

Once we update `cryptography` we can remove this workaround. Maybe we should pin `pyopenssl` on integrations-core anyway, though, to make things more manageable.

**Comment by mx-psi** [comment]
Related issue: snowflakedb/snowflake-connector-python/issues/1259

**Comment by alopezz** [comment]
> Related issue: [snowflakedb/snowflake-connector-python/issues/1259](https://github.com/snowflakedb/snowflake-connector-python/issues/1259)

Luckily this seems to affect 2.8.0. But yeah, this library seems to have a history of problematic dependency requirements...

**Comment by KSerrania** [comment]
> Luckily this seems to affect 2.8.0. But yeah, this library seems to have a history of problematic dependency requirements...

It also affects 2.7.12 (it's the same issue which forced you to pin `pyOpenSSL` to `21.0.0`).

**Comment by alopezz** [comment]
True, I see how it could also affect 2.7.12 the same way, but I'm not sure that was the [problem I was running into](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/184055148#L1811):

```
The following shell command exited with status 1:
    $ /opt/datadog-agent/embedded/bin/pip3 check
Output:
    pyopenssl 22.0.0 has requirement cryptography>=35.0, but you have cryptography 3.4.8.
```

cryptography==3.4.8 comes from [here](https://github.com/DataDog/integrations-core/blob/4fb3b5f07c99b044081e16cc5c174016095d25f2/datadog_checks_base/datadog_checks/base/data/agent_requirements.in#L20) if I understand correctly.

In fact, even though I don't want to go too deep into this rabbit hole, the fact that it picked up pyopenssl 22.0.0 (and not 22.1.0) when trying to install snowflake-connector makes me think that the dependency resolver normally does the right thing and finds a compatible set of dependency versions (which exists).

More importantly, is it normal that all those checks are failing? They don't seem related to this PR.

**Comment by mx-psi** [comment]
> More importantly, is it normal that all those checks are failing? They don't seem related to this PR.

They should pass if you rebase/merge main :)

**Review by KSerrania — APPROVED** [review]

**Pull request merged**
