### PR TITLE
feat(repo): clean branches without activity in more than 6 months

### PR DESCRIPTION
**Pull request by chouetz**
### What does this PR do?
Activate the [devflow cleanup](https://datadoghq.atlassian.net/wiki/spaces/DEVX/pages/3176367142/Cleanup+Stale+Branches) of stale branch.

### Motivation
Sanitize the repository activity

### Additional Notes
This will not delete the external contributors' PR as they don't have branches in the repo

### CODE REVIEW

**Review by CelianR — APPROVED** [review]

**Review by mx-psi — COMMENTED** [review]
I have a couple branches that end in `-DO-NOT-DELETE` that I don't want to delete. There's also a third branch from @KSerrania and me (https://github.com/DataDog/datadog-agent/tree/kserrania/pkg-trace-split) that I would like to keep.

**Comment by chouetz** [comment]
> I have a couple branches that end in `-DO-NOT-DELETE` that I don't want to delete. There's also a third branch from @KSerrania and me ([`kserrania`/pkg-trace-split](https://github.com/DataDog/datadog-agent/tree/kserrania/pkg-trace-split?rgh-link-date=2024-04-08T16%3A07%3A11Z)) that I would like to keep.

I've added an exclusion pattern on `*DO-NOT-DELETE` to prevent such branches from deletion, and I [duplicated](https://github.com/DataDog/datadog-agent/compare/kserrania/pkg-trace-split...pkg-trace-split/DO-NOT-DELETE?expand=1) the branch you mentioned that wasn't following this pattern.
Please tell me if this is fine for you.
Thanks in advance

**Review by mx-psi — APPROVED** [review]
Awesome, thank you!!

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Comment by chouetz** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable RUN_UNIT_TESTS=on

**Pull request merged**
