### PR TITLE
Do not specify -compat when running go mod tidy

### PR DESCRIPTION
**Pull request by albertvaka**
### What does this PR do?

Do not specify `-compat=1.17` when running `go mod tidy` and re-run the command.

### Motivation

Dependabot doesn't pass `-compat`, so the CI would fail on PRs open by Dependabot because of go.sum differences.

This seems an easier solution that trying to fix go.sum automatically on dependabot PRs, see #11264

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by vickenty** [comment]
Will this mean that we're potentially stuck with older versions of modules, since the default for `go mod tidy` keeps modules compatible with the version one behind what we declare in `go.mod`?

**Comment by djmitche** [comment]
I'll be honest, I don't remember why I had to add this flag, but something went wrong when I didn't and the error message suggested this flag.

So, let's try it and see what happens!

**Comment by albertvaka** [comment]
Alternative to this PR: https://github.com/DataDog/datadog-agent/pull/11334

**Comment by djmitche** [comment]
Looks like that alternative was selected :)

**Pull request closed without merging**
