### PR TITLE
Add documentation about the Python's API for checks.

### PR DESCRIPTION
**Pull request by hush-hush**
### What does this PR do?

We only document what we support in Agent 6 instead of the differences
from Agent 5.

### CODE REVIEW

**Review by masci — CHANGES_REQUESTED** [review]
Since this is a "Developer Guide", can we move the entire `checks` folder under `dev`?

**Review by masci — DISMISSED** [review]

**Review by kmshultz — CHANGES_REQUESTED** [review]
I've left some comments. :) Thanks

**Review by jeremy-lq — DISMISSED** [review]
Single comment inline, but other than that looks great!

**Review by masci — APPROVED** [review]
Let's 🚢  this!

**Pull request merged**
