### PR TITLE
Add kube_cluster_name as a global tag

### PR DESCRIPTION
**Pull request by sblumenthal**
### What does this PR do?

This PR adds kube_cluster_name as a global static tag if it is available, regardless of environment.

### Motivation

In EKS Fargate, we are unable to get the cluster name from the environment. The official documentation recommends that the cluster name be set on the cluster agent deployment. The problem here is that the cluster name is only added as a global tag if the eks_fargate feature is enabled on the deployment, via `DD_EKS_FARGATE=true`, which is not in the documentation. Without this setting, the kube cluster name is not checked even though it is present.

This tag is needed for the `datadog.cluster_agent.running` metric in order for the Kubernetes Orchestrator page to correctly display the running version on the given cluster.

[Ticket](https://datadoghq.atlassian.net/browse/CONT-3975)

### Additional Notes

- Based on my testing, I had to remove the hostname check from the `aggregator.tags` function, as the detected hostname is not empty when running on EKS Fargate without the `DD_EKS_FARGATE` set. 
- As best as I can tell, the current implementation for the global tagger only has global tags being added from parsing ECS tasks or from calling the static tags function, which short circuits if the agent is not running in Fargate. So, the change to the `aggregator.tags` function should not meaningfully affect the cardinality of these metrics. Obviously, this can change as more features are added to the agent.
- Another implementation was attempted without adding the kube_cluster_name tag as a global tag everywhere. You can see that attempt [here](https://github.com/DataDog/datadog-agent/compare/sblumenthal/cont-3975-eks-fargate-dca-cluster-name?expand=1). If we would rather do something like that (it needs to be cleaned up a bit) vs this change to the `GetStaticTagsSlice` function due to concerns about the increase in payload size this would result in, I am happy to make that change. It just felt more hacky to me, which is why I opted for this approach.

### Possible Drawbacks / Trade-offs

- Most (all?) data being sent from the agent will have the `kube_cluster_name` tag included if it is available, meaning that each payload will be slightly larger

### Describe how to test/QA your changes

Deploy the cluster agent to EKS Fargate using the configuration detailed in our official docs [here](https://docs.datadoghq.com/integrations/eks_fargate/#running-the-cluster-agent-or-the-cluster-checks-runner)

Validate that the version shows up correctly in the cluster list on the Kubernetes Orchestration cluster view.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [ ] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [ ] Changed code has automated tests for its functionality.
- [ ] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [ ] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by vickenty** [comment]
If the hostname is not empty, can we add the tag to the host instead?

I am a bit worried about adding global tags unconditionally, since it will lead to possibility of duplicated tags in some new corner cases when tags are modified. Would it be possible to scope this tagging change to the cluster agent only?

**Comment by sblumenthal** [comment]
> If the hostname is not empty, can we add the tag to the host instead?
> 
> I am a bit worried about adding global tags unconditionally, since it will lead to possibility of duplicated tags in some new corner cases when tags are modified. Would it be possible to scope this tagging change to the cluster agent only?

Even though the hostname is not empty, the EKS Fargate host does not have any host tags attached to it.

And I agree with your concern regarding duplicated tags. I can scope the change down to just the cluster agent on the `aggregator` side, but I am not sure if I can conditionally add the kube_cluster_name to the global tag store if the DCA is running.

But that comes back to the issue that lead to this PR; if the DCA is misconfigured, then this tag is missing on metrics even though we have the ability to resolve it. The same could apply to the agent. At least on the agent side, the documentation is correct, so it would be user error. But the end result is the same, the tag would be missing from the `datadog.agent.running` metric.

So, if the concern is regarding adding global variables, then SOMETHING like [this](https://github.com/DataDog/datadog-agent/compare/sblumenthal/cont-3975-eks-fargate-dca-cluster-name?expand=1) might make more sense. But even that would run the risk of duplicating kube_cluster_name on the metric itself, or having the kube_cluster_name be sent as a host tag and inline with the metrics in question

**Review by clamoriniere — APPROVED** [review]

**Review by clamoriniere — COMMENTED** [review]
Could you please add a release note

**Review by vickenty — APPROVED** [review]

**Review by clamoriniere — APPROVED** [review]

**Review by rtrieu — APPROVED** [review]
Looks good!

**Pull request merged**
