### PR TITLE
Store and display the config file used for each check

### PR DESCRIPTION
**Pull request by albertvaka**
### Motivation

We want to be able to display the source of the config for each check in status/web-gui.

I added this to the Check interface, so it required a ton of changes. If anyone has a better solution for this, it's welcome.

### CODE REVIEW

**Comment by mfpierre** [comment]
How does `Source` differs from `Provider` which is displayed in the `configcheck` command?

**Comment by albertvaka** [comment]
> How does `Source` differs from `Provider` which is displayed in the `configcheck` command?

It differs in that I didn't know about `Provider` 😅

That aside, `Provider` just displays "file" for plugins loaded from a config file, instead of the actual filename and path, so it's not the same.

In any case, it totally looks like I could re-use a lot more code if I base my patch on the already implemented `Provider` field :)

I will give it a try and update my patch.

**Comment by albertvaka** [comment]
Unfortunately, the info from `agent configcheck` and `agent status` comes from very different places: the first comes from `GetLoadedConfigs()`, while the second from the `Status` structs tied to each `Check`. Even if we pass the filename information to the `Config` struct (that's easy), we wouldn't have it in `Check` nor in `Status`, where we need it for the command `agent status`.

I've tried to make `agent status` get both sources of information and match them together before rendering the status template, but unfortunately there is no common unique identifier in both places to do the match.

The other alternative is to get the filename in `Status`, and for that we need to pass it from `Check`, and to have it in `Check` we need to provide it either when the `Check` is created or in `Configure()`, like this patch does.

I don't really like this patch myself, but I can't find a better way of matching `Check`s and `Config`s. Any ideas?

**Comment by albertvaka** [comment]
Superseded by https://github.com/DataDog/datadog-agent/pull/3916

**Pull request closed without merging**
