### PR TITLE
[NPM] Only count evicts on adding to process cache

### PR DESCRIPTION
**Pull request by hmahmood**
### What does this PR do?

Only counts evicts that happen when adding an entry to the process cache in the network_tracer module. Previously, we were incrementing the counter in the evict callback, which is also be called during a remove operation on the cache.

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Use the `major_change` label if your change either has a major impact on the code base, is impacting multiple teams or is changing important well-established internals of the Agent. This label will be use during QA to make sure each team pay extra attention to the changed behavior. For any customer facing change use a releasenote.
- [x] A [release note](https://github.com/DataDog/datadog-agent/blob/main/docs/dev/contributing.md#reno) has been added or the `changelog/no-changelog` label has been applied.
- [x] Changed code has automated tests for its functionality.
- [x] Adequate QA/testing plan information is provided if the `qa/skip-qa` label is not applied.
- [x] At least one `team/..` label has been applied, indicating the team(s) that should QA this change.
- [ ] If applicable, docs team has been notified or [an issue has been opened on the documentation repo](https://github.com/DataDog/documentation/issues/new).
- [ ] If applicable, the `need-change/operator` and `need-change/helm` labels have been applied.
- [ ] If applicable, the `k8s/<min-version>` label, indicating the lowest Kubernetes version compatible with this feature.
- [ ] If applicable, the [config template](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) has been updated.

### CODE REVIEW

**Comment by paulcacheux** [comment]
I think this might change again in the upstream library.. 
- https://github.com/hashicorp/golang-lru/releases/tag/v2.0.6
- https://github.com/hashicorp/golang-lru/pull/154

**Comment by hmahmood** [comment]
> I think this might change again in the upstream library..
> 
> * https://github.com/hashicorp/golang-lru/releases/tag/v2.0.6
> * [Revert #135 and add tests for eviction callback hashicorp/golang-lru#154](https://github.com/hashicorp/golang-lru/pull/154)

We are already using 2.0.6 I believe (although this appears to be a recent change #19020). So we should have the right behavior for evicts.

**Comment by hmahmood** [comment]
Oh great @paulcacheux you're the one who bumped it :-)

**Comment by hmahmood** [comment]
The `Remove` behavior is still the same in 2.0.6, which is what this PR is trying to avoid.

**Review by akarpz — APPROVED** [review]

**Pull request merged**
