### PR TITLE
Use gitlab module instead of raw requests (3)

### PR DESCRIPTION
**Pull request by CelianR**
### What does this PR do?

Reverts my [2nd revert](https://github.com/DataDog/datadog-agent/pull/24735) to use the gitlab module instead of a custom api.

[Initial PR](https://github.com/DataDog/datadog-agent/pull/24666)

### CODE REVIEW

**Comment by CelianR** [comment]
/trigger-ci --variable RUN_ALL_BUILDS=true --variable RUN_KITCHEN_TESTS=true --variable RUN_E2E_TESTS=on --variable DEPLOY_AGENT=true --variable RUN_UNIT_TESTS=on

**Review by pducolin — APPROVED** [review]

**Review by chouquette — APPROVED** [review]
LGTM for BaRX files

**Review by gjulianm — APPROVED** [review]
LGTM for eBPF platform files, thx!

**Review by chouetz — APPROVED** [review]

**Pull request merged**
